decaporg/decap-cms

- src/components/Cards/ImageCard.js
- src/components/EntryEditor.js
- src/components/Widgets/ImageControl.js
- src/containers/FindBar.css
- src/index.css
Just some basic colours, mostly for the header and main content areas.  Need to fix up the editor still, but having a bit of trouble with it. Not sure it's the latest version on this branch, anyhow.
> Apply theme

- LICENSE
- README.md
Add the MIT License to the root of the repository and link to it in the README.
It also links to a great explanation of the license.
> Add LICENSE for the react version.

- .travis.yml
- package.json
> Add support for Travis CI

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Inspired by Docker and Yarn. We can add more things later if we need
them, but I think this is a good start.
> Add OSS management files.

- src/components/Widgets/MarkdownControlElements/RawEditor/Toolbar.css
- src/components/Widgets/MarkdownControlElements/RawEditor/Toolbar.js
- src/components/Widgets/MarkdownControlElements/RawEditor/index.js
This adds options for h1/h2 headers and styles the toolbar a little
> Editor fixes

- src/backends/github/API.js
- src/backends/github/implementation.js
- src/containers/editorialWorkflow/EntryPageHOC.js
**- Summary**
The single file collection branch introduced a few changes on slug signature - but there were a few cases where where code wasn't updated accordingly.
> Bugfixes due to new slug signature

- src/components/Cards.js
- src/components/Cards/ImageCard.css
- src/components/Cards/ImageCard.js
- src/components/EntryListing.js
- src/components/UnpublishedListing.css
- src/components/UnpublishedListing.js
- src/components/Widgets.js
- src/containers/CollectionPage.js
**- Summary**
This PR fixes typography and layout inconsistencies over the card's design.
Visual.
Consistent typography in the card's lists.
> Cards typography

- yarn.lock
The yarn.lock file has missing dependencies.
> Fix Yarn dependencies.

- src/actions/editorialWorkflow.js
- src/containers/editorialWorkflow/EntryPageHOC.js
- src/reducers/editorialWorkflow.js
**- Summary**
This change makes all persistence actions go through editorial workflow actions & reducers.
This gives the opportunity to add optimistic updates for new drafts
> [WIP] Persistence editorial workflow through own actions & reducer

- src/components/ControlPanel/ControlPane.js
- src/components/EntryListing/EntryListing.js
- src/containers/CollectionPage.js
- src/reducers/index.js
- src/reducers/medias.js
**- Summary**
Collection fields should allow for default values (hidden or not) like layout and styleoverrides, for example.
> Config default values

- src/components/Widgets/ListControl.js
- src/components/Widgets/ObjectControl.js
**- Summary**
Enables List widget to accept a single field, and persist the value as a simple list (instead of a key-value pair).
List Widget: Option for single field (persisting the value as a simple list instead of a key-value pair).
```
/)_/)
( .  .)
C(") (")
```
> List single field

- src/actions/entries.js
- src/backends/backend.js
- src/components/ControlPanel/ControlPane.js
**- Summary**
Entry Draft Refactor. Closes #177
Refactor in entry draft generation (Closes #177)
```
_______\\__
(_. _ ._  _/ 
'-' \__. /
/  / 
/  /    .--.  .--.
(  (    / '' \/ '' \   "
\  \_.'            \   )
||               _  './
|\   \     ___.'\  /
'-./   .'    \ |/ 
\| /       )|\
|/       // \\ 
|\    __//   \\__
//\\  /__/  mrf\__|
.--_/  \_--.
/__/      \__\
```
> Entry Draft Refactor. Closes #177

- README.md
**- Summary**
The English language, no longer butchered.
This is not code, ergo it cannot break anything.
Fixed some typos
https://i.redd.it/5xjcwnn7gx2y.jpg
> Fixed 3 typos in README

- package.json
- src/components/EntryEditor/EntryEditor.css
- src/components/EntryEditor/EntryEditor.js
- src/components/PreviewPane/PreviewPane.js
- src/index.css
- yarn.lock
**- Summary**
Resizable split pane on the content editor. Start implementing #183 (but without responsive breakpoints yet).
Resizable split pane for editor
```
(\____/)
/ @__@ \
(  (oo)  )
`-.~~.-'
/    \
@/      \_
(/ /    \ \)
WW`----'WW
```
> Resizable split pane

- package.json
- src/actions/config.js
- src/backends/backend.js
- src/backends/github/API.js
- src/backends/github/implementation.js
- src/backends/netlify-auth/API.js
- src/backends/netlify-auth/AuthenticationPage.css
- src/backends/netlify-auth/AuthenticationPage.js
- src/backends/netlify-auth/implementation.js
- src/backends/netlify-auth/netlify_logo.svg
- src/components/AppHeader/AppHeader.js
- src/components/EntryEditor/__tests__/__snapshots__/EntryEditorToolbar.spec.js.snap
- src/lib/textHelper.js
- yarn.lock
Includes a new Backend that authenticates via Netlify Auth and uses GitHub API via proxy with signed requests.
> Netlify auth

- src/backends/test-repo/AuthenticationPage.js
**- Summary**
The current example login screen looks broken. This makes it look OK.
**- Before:**
**- After:**
Make the example login page look decent.
> Make sure the example login page looks decent

- src/backends/netlify-auth/AuthenticationPage.css
- src/backends/test-repo/AuthenticationPage.js
- src/backends/test-repo/implementation.js
Explain what the email in the login is for
Make a guess at the users name
Don't mark uploaded files as persisted (since they're not)
> Improvements to the demo experience

- src/backends/github/API.js
- src/lib/promiseHelper.js
**- Summary**
Don't show posts which have been merged outside of the CMS as unpublished posts in the editorial workflow.
Closes #251.
- **Filter merged PRs from unpublished posts**
> Filter merged PRs from unpublished posts

- src/reducers/entryDraft.js
**- Summary**
Bug fix; closes #287
Manually tested, existing test suite passes.
- **Don't ask for navigation confirmation on save**
> Don't ask for navigation confirmation on save

- src/actions/editorialWorkflow.js
- src/actions/entries.js
- src/reducers/entryDraft.js
**- Summary**
Bugfix; closes #287 (for real this time).
Manually tested on editorial workflow and regular workflow, with both github and test backends.
- **Don't ask for navigation confirmation on save**
> Set correct `hasChanged` and set it on all entry persistence actions

- src/backends/backend.js
**- Summary**
* Closes #294 
* No tests required.
* Make commit messages imperative
> #294 Make commit messages imperative

- README.md
**- Summary**
Changed `she'll` in readme to `they'll`.
> Changed she'll to they'll

- docs/quick-start.md
> fixed typo

- README.md
Mention the public Gitter channel to find members of the community.
> Add section about the community to the README.

- .travis.yml
> Disable email notification for Travis.

- README.md
**- Summary**
Switch 'with' with 'that', because typos detract from project documentation
Read README.md
Fix tiny README typo
> Fix tiny README typo

- src/components/AppHeader/AppHeader.js
The log out menu was nested within a button, which caused
bubbling issues for the log out button event handler. This
was due to a misuse of the React Toolbox AppBar component.
Added a proper IconMenu to trigger the logout dropdown.
Fixes #333
> Fix logout for Firefox

- example/config.yml
Fixes #315 
Fix optional field syntax in example config (outdated).
> fix example optional field

- src/actions/entries.js
> fixes #258 - reverse collection order

- docs/examples.md
**- Summary**
#365
Looking for examples/blog posts of this CMS being used with different Static Site Generators. I am looking to add a section to the docs for new and existing users can reference. But for now just looking for a place to collect this data.
Added a examples section to the repo in preparation to collect examples.
> examples in docs added

- docs/intro.md
> fix editorial workflow docs link

- src/components/Widgets/ListControl.js
**- Summary**
Fixes #381 
List items without metadata could not be deleted, regression from #359.
Attempting to delete list entries without metadata now works. This was tested in the example project locally.
Fix list item deletion
> fix list item deletion

- docs/quick-start.md
> Fix editorial workflow link in documentation

- package.json
- src/backends/backend.js
When added post with title containing unicode localised (e.g. +ěščřžý) chars, it was save in wrong form. THis is fix ...
Cheers
> slug from unicode chars

- src/components/PreviewPane/PreviewPane.js
**- Summary**
Fixes #420 - app was throwing when loading preview pane
fix preview pane not loading
> fix preview pane not loading

- src/backends/backend.js
- src/backends/test-repo/implementation.js
**- Summary**
For example/testing purposes, its helpful to allow users to run the test backend without manually adding test data. This fix creates empty default values wherever needed so that any config can be tested against the test backend.
Allow the test backend to be used without preloading data
> allow test repo to be used without window.testRepo

- docs/quick-start.md
- example/config.yml
- example/index.html
Remove filtering and language handling from the example repo, it's an edge case that can bring confusion. Add documentation.
> Remove example filter

- src/backends/github/AuthenticationPage.js
- src/containers/App.js
Hi, i needed to use netlify-cms just with github OAuth provider. So I made this changes along with OAuth client https://github.com/vencax/netlify-cms-github-oauth-provider.
I hope you find it useful. CHeers
> auth without netlify oauth provider

- webpack.dev.js
Improved support for developing with locally linked dependencies.
> optimize webpack dev config for use w linked pkgs

- CONTRIBUTING.md
**- Summary**
Fixed a typo in CHANGELOG.md (Runing) and improved the link syntax to yarnpkg to use vanilla markdown syntax rather than depending on link detection.
N/A
Fix typo in CHANGELOG.md
> Fix typo and improve markdown link syntax in CONTRIBUTING.md

- docs/intro.md
**- Summary**
There were two `from`s in a sentence. Fixed it.
> Fixes typo

- docs/widgets.md
documents the list widget, see example in #505
> improve documentation of list widget, fixes #505

- src/backends/git-gateway/implementation.js
**- Summary**
Fix missing avatar for `git-gateway` backend.
@erquhart Is it good enough to just do it like this, and if it isn't defined, it should just be at undefined for the `user.get("avatar_url")`, or should I `if`-check if it is defined first?
Closes #583.
Show user avatar for git-gateway backend.
> Show user avatar for git-gateway backend.

- src/backends/github/API.js
Fixes deletion of entries not on the "master" branch. Closes #602.
> Fix entry deletion on non-master branches

- CONTRIBUTING.md
**- Summary**
After discussion on gitter. I discovered that PRs should be rebased. I figured it's a good idea to document it. 
n/a
n/a
> (docs) Document that pull requests should be rebased. 

- src/backends/git-gateway/implementation.js
> add branch selection support for git gateway

- src/actions/editorialWorkflow.js
- src/actions/entries.js
> fix file collection persist

- src/components/Widgets/Markdown/MarkdownControl/RawEditor/index.js
- src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/__snapshots__/parser.spec.js.snap
- src/components/Widgets/Markdown/MarkdownControl/VisualEditor/components.js
- src/components/Widgets/Markdown/MarkdownControl/VisualEditor/index.js
- src/components/Widgets/Markdown/MarkdownControl/VisualEditor/plugins.js
- src/components/Widgets/Markdown/serializers/__tests__/remarkAllowHtmlEntities.spec.js
- src/components/Widgets/Markdown/serializers/__tests__/remarkEscapeMarkdownEntities.spec.js
- src/components/Widgets/Markdown/serializers/__tests__/remarkStripTrailingBreaks.spec.js
- src/components/Widgets/Markdown/serializers/__tests__/slate.spec.js
- src/components/Widgets/Markdown/serializers/index.js
- src/components/Widgets/Markdown/serializers/remarkAllowHtmlEntities.js
- src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js
- src/components/Widgets/Markdown/serializers/remarkImagesToText.js
- src/components/Widgets/Markdown/serializers/remarkSlate.js
- src/components/Widgets/Markdown/serializers/remarkStripTrailingBreaks.js
- src/components/Widgets/Markdown/serializers/slateRemark.js
- src/components/Widgets/ObjectControl.js
- src/lib/regexHelper.js
Fixes a bunch of stuff on the new markdown editor. Related to #575, see issue for a list of bugs resolved.
> editor fast follow

- .github/ISSUE_TEMPLATE.md
**- Summary**
It is often helpful to know the CMS version when a user is reporting an issue, especially not that we are releasing Beta versions.
N/A
Add CMS version question to GitHub issue template.
[![teaksu-kim-226783](https://user-images.githubusercontent.com/20345941/30838510-2220dd80-a229-11e7-981b-6f8e8e627e1e.jpg)](https://unsplash.com/photos/mTkKYzlAAMc)
> Add CMS version question to GitHub issue template.

- src/lib/urlHelper.js
**- Summary**
urlize is not used in the code base, remove to reduce volume of code to maintain.
> Remove unused urlize

- package.json
**- Summary**
This was a bug in `one-click-hugo-cms` (https://github.com/netlify-templates/one-click-hugo-cms/pull/9), not in the CMS itself.
This reverts commit a1c32f5154e7af0242c496776e9f544bc2e9484b.
Please test `one-click-hugo-cms` with CMS 0.5.0.
> Revert "fix bundled code error"

- docs/quick-start.md
**- Summary**
Hugo's a little pickier than GitHub when it comes to interpreting ordered lists in markdown. Added a line so the ordered list on this page displays properly on netlifycms.org.
Before (on netlifycms.org):
After (in [branch deploy](https://quick-start-test--netlify-cms-www.netlify.com/docs/quick-start/)):
Fix ordered list display in Quick Start doc
> Fix ordered list display in Quick Start

- src/containers/editorialWorkflow/EntryPageHOC.js
**- Summary**
I didn't test editorial workflow when I was upgrading to React Router 4, so it became broken.
Tested Editorial Workflow -- working.
> React Router 4 fix

- package.json
- src/actions/editorialWorkflow.js
- src/components/Widgets/RelationControl.js
- src/containers/editorialWorkflow/EntryPageHOC.js
- yarn.lock
**- Summary**
Upgrade the UUID module.
~~@erquhart @Benaiah I really have no idea how to test this?~~
Tested manually -- the affected components (editorial workflow and RelationControl) still work normally.
Upgrade the UUID module.
> Upgrade UUID module.

- src/components/Widgets/ListControl.css
**- Summary**
`ListControl` would not actually hide its `ObjectControl`s when they were collapsed. This was a simple CSS precedence issue.
Tested manually, problem is resolved.
Fix ListControl collapsing bug
> Fix ListControl collapsing bug

- docs/extending.md
**- Summary**
The regex pattern in the example editor component was not actually a regex, so it wasn't working properly.
N/A: Docs.
Docs: Fix editor component regex pattern.
> Docs: Fix editor component regex pattern.

- package.json
- src/formats/formats.js
- src/formats/frontmatter.js
- src/formats/helpers.js
- src/formats/toml.js
- src/formats/yaml.js
- yarn.lock
**- Summary**
This PR adds support for TOML files.
Existing tests pass. Manually tested YAML and TOML data files.
Add support for TOML files.
> Add support for TOML files.

- src/formats/frontmatter.js
**- Summary**
Quick typo fix in an error message.
> Typo fix in FrontMatter error.

- docs/authentication-backends.md
Proposed changes against https://github.com/netlify/netlify-cms/pull/751.
> proposed changes to auth docs update

- src/formats/formats.js
**- Summary**
JSON was only available as an extension-implied format. This adds support as a manually set format.
Fixes #748.
> Add JSON as manually supported format.

- docs/quick-start.md
**- Summary**
This note doesn't seem to be necessary anymore, and seems to be causing way more problems than it's worth.
> Drop outdated Gatsby note from quick start docs.

- README.md
> Make docs links in README point to website.

- src/components/Widgets/Markdown/MarkdownControl/VisualEditor/renderers.js
Missed step from the recent Slate upgrade.
> fix slate mark rendering

- src/components/App/Header.css
- src/components/Collection/CollectionTop.css
- src/components/Collection/Sidebar.css
- src/components/Editor/EditorToggle.css
- src/components/Editor/EditorToolbar.css
- src/components/Editor/EditorToolbar.js
- src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/Toolbar.css
- src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/Toolbar.js
- src/components/UI/Dropdown/Dropdown.css
- src/components/UI/base.css
- src/components/Workflow/Workflow.css
- src/components/Workflow/Workflow.js
Shawn, feel free to merge. 
Still working on Media Library and loading indicators
> WIP - a bunch of fun UI fixes! a BUNCH!

- website/site/content/docs/start-with-a-template.md
**- Summary**
Change Gatsby template link back to original repo. Thanks to @AustinGreen for creating the template and getting the update merged so quickly!
Created new site using updated link.
Change Gatsby template link back to original repo
> Change Gatsby template link back to original repo

- src/components/EditorWidgets/Select/SelectControl.js
**- Summary**
Fix select widgets with object keys causing the entire CMS to crash. The problem was just an improper import from Immutable.js.
Select widgets with object options work now.
Fix select widgets with object type options.
> Fix select widgets with object type options.

- src/backends/git-gateway/AuthenticationPage.js
- src/backends/github/AuthenticationPage.js
- src/components/App/App.js
**- Summary**
The notification component is duplicated across some of the backends, and is missing on others. This PR moves the notif component above the auth components.
Tested GitHub backend: Error notifications show up correctly. 
Abstract notif component for auth pages.
> Refactor: Abstract notif component for auth pages.

- website/src/js/app.js
> fix community meeting time

- .github/ISSUE_TEMPLATE.md
**- Summary**
Add config.yml request to issue template
N/A
Add config.yml request to issue template
> Add config.yml request to issue template

- src/formats/json.js
**- Summary**
Currently we store JSON as a single line in files. We should prettify it
like we do the other formats. This PR adds 2-space indentations.
Format JSON files.
> Format JSON files.

- website/site/content/docs/custom-widgets.md
> Small typo

- website/site/content/docs/architecture.md
Right now the lists are rendered correctly on github thanks to GFM, but not on https://www.netlifycms.org/docs/architecture/
> fix lists markup

- package.json
- yarn.lock
**- Summary**
remove unused `slug` package
originally removed in #640, accidentally added as part of #638
N/A
> remove unneeded package

- website/site/content/docs/examples.md
I have created a blog on Netlify CMS and created a guide for it. Including links for it.
**- Summary**
> Update examples.md to include one more example

- website/gulpfile.babel.js
**- Summary**
Right now we are using full size contributor avatars on the website, which really slows down the loading. This PR allows us to use avatars scaled down to the size that we are using.
> Use scaled avatars for website contributors.

- website/src/css/imports/hero.css
> WIP: Fix CTA overflow.

- website/site/content/docs/contributor-guide.md
**- Summary**
There is no link to the Netlify CMS Gitter community on the contributor guide page. It makes sense telling potential contributors about it via the page.
Added a link to the Gitter community of Netlify CMS
> Adding Gitter community link on this page might be helpful.

- website/site/content/docs/contributor-guide.md
Change order of links in contributing list. Also, don't show already claimed issues in the "Good First Issues" list.
> Cleanup links in contributor-guide.md

- website/site/content/docs/add-to-your-site.md
**- Summary**
This PR removes a superfluous occurrence of the word **the**. It contributes to solving the problem of accidental grammatical errors in documentation.
Ask someone else to read it, and ask them if it is correct. 
Documentation updated for accidental grammatical error.
> Remove extra 'the'

- website/src/css/imports/header.css
> Fix "Get Started" button on small screens.

- website/site/content/docs/add-to-your-site.md
Added Wyam to list of generators to store static files in the input directory
> Update add-to-your-site.md to add Wyam

- website/site/content/docs/examples.md
Seems necessary for an effective CMS implementation example.
@verythorough thoughts?
> add source repo field for docs examples

- src/backends/github/implementation.js
Closes #1188.
**- Summary**
I just found a couple of lines that can be improved while working on another PR:
No idea how to test it (I mean I know, but only by inspecting the values directly, by adding console.log's in the code to see the values for instance), these all seem to be "unseen" changes.
- (Media Library) Adding new media would set the media id as undefined
- (Media Library) Removed redundant filter call during media library startup
> Misc optimizations

- src/components/Editor/EditorToolbar.js
**- Summary**
Hides the "Publish and Create New" button for single-file collections. Uses the code from the "Quick Add" button.
Fix #1183.
Manually tested with both simple and editorial workflows.
> Hide create new button for single files.

- src/backends/github/API.js
**- Summary**
The editorial workflow pulls in all workflow pull requests, regardless of base branch. If multiple CMS instances are used against the same repo, they'll all see each other's entries in the editorial workflow. This change filters the workflow entries to pull requests that are based on the current configured branch for the CMS (default master).
Closes #412.
filter editorial workflow entries by PR base branch
> filter workflow entries by pr base branch

- .babelrc
- package.json
- src/components/App/App.js
- yarn.lock
**- Summary**
RHL was removed before for multiple reasons. Version 4 on WebPack v4 seems to be working now.
> Add React Hot Loader

- website/site/content/docs/configuration-options.md
**- Summary**
Adds documentation for #949. My first open source commit ever, so be gentle. :)
Documented the option to hide preview pane by default for a collection.
>  949 document hide preview by default

- website/site/content/docs/widgets/index.md
**- Summary**
Small documentation change for consistency.
Small documentation change for consistency.
> Use double quotes consistently

- CHANGELOG.md
Nice for quick regression checks, validating new issues, etc.
> add demo links to changelog

- src/actions/editorialWorkflow.js
- src/backends/git-gateway/AuthenticationPage.js
- src/components/App/NotFoundPage.js
- src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec.js
- src/components/UI/Icon/Icon.js
**- Summary**
While working on #952, I noticed that there were a few actual code errors that the linter was picking up. I think they should be fixed sooner, rather than waiting until we can merge the entire linted/prettified code.
> Fix miscellaneous code errors.

- website/site/content/docs/examples.md
**- Summary**
Adding my own site as an example of integrating Netlify CMS into Hugo site.
Not really required for adding an example
Added Hugo example
https://www.flickr.com/photos/forestgardenwales/41036171822/in/photolist-HxDMKN-25we7cQ-249WPo5-22va3Hf-F1HHjh-J9dvFV-22J4U1p-HD67XW-25M1fnT-24FSYj5-HCZqN7
🐕 😄
> Add example

- src/reducers/auth.js
safely convert to string as it throws an error if the action.payload is undefined
possibly fixes #1231 
nope
> Safely convert to string

- website/site/content/docs/examples.md
> Add blog post link to forestgarden.wales example

- website/site/static/widgets.js
**- Summary**
Closes #934.
> Updating browser history when a new widget docs link is clicked so that back/forward buttons work
> Docs: Link widget cloud to browser URL.

- .travis.yml
- yarn.lock
**- Summary**
This adds Node.js 8 and 10 for the tests on Travis CI to make sure that netlify successfully builds and runs on them.
> chore: add Node.js 8 and 10

- website/site/content/docs/architecture.md
- website/site/content/docs/customization.md
As mentioned in https://github.com/netlify/netlify-cms/pull/1366#issuecomment-390075964.
> add architecture and previews guide to docs menu sections

- src/backends/gitlab/AuthenticationPage.js
**- Summary**
Typo in the GitLab implicit OAuth.
> Fix GitLab Implicit OAuth

- src/components/EditorWidgets/Object/ObjectControl.js
**- Summary**
Make the object widget use the editor control passed in as a prop instead of importing it separately.
Tested -- working correctly.
> Make object control pure (no extra imports).

- packages/netlify-cms-backend-bitbucket/src/API.js
- packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js
- packages/netlify-cms-backend-bitbucket/src/implementation.js
- packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
- packages/netlify-cms-backend-git-gateway/src/implementation.js
- packages/netlify-cms-lib-auth/src/netlify-auth.js
- packages/netlify-cms-lib-util/src/index.js
- packages/netlify-cms-ui-default/src/AuthenticationPage.js
Address rebasing errors that broke the Bitbucket backend. Also dropped some console logs that were left in by mistake.
> fix(bitbucket): fix rebasing mistakes in bitbucket backend and deps

- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreview.js
- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
- packages/netlify-cms-core/src/components/EditorWidgets/Unknown/UnknownControl.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
- packages/netlify-cms-core/src/components/UI/ErrorBoundary.js
- packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js
- packages/netlify-cms-core/src/reducers/collections.js
- packages/netlify-cms-core/src/reducers/editorialWorkflow.js
- packages/netlify-cms-core/src/reducers/integrations.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
- packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js
**- Summary**
These are all "code-type" fixes from linters, not "style-type" fixes from Prettier. Those will be in a separate commit.
These deserve a manual review and test, since they are not always "obvious".
> fix: bug fixes from linters

- packages/netlify-cms/src/backends.js
> fix: register bitbucket backend in netlify-cms

- website/content/docs/widgets/index.md
**- Summary**
This PR fixes the invalid href to contain a valid href.
This ensures that users reading our documentation do not get sent to a page that does not exist when learning how to use our product.
I clicked the link and lit no longer goes to a invalid page.
my dog Tank. He was super sleepy from playing outside!
> update href to include a valid URL.

- packages/netlify-cms-backend-git-gateway/src/implementation.js
> Proxied is true (git-gateway)

- packages/netlify-cms-backend-github/src/API.js
- packages/netlify-cms-backend-github/src/implementation.js
- packages/netlify-cms-backend-test/src/implementation.js
- packages/netlify-cms-core/src/backend.js
**- Summary**
Editorial workflow entries were being created without a status due to a bug in how the initial status constant was being passed to backends.
Fixes #1556.
> Fix workflow persist

- packages/netlify-cms-backend-test/src/AuthenticationPage.js
- packages/netlify-cms-core/src/components/Collection/Entries/EntriesCollection.js
- packages/netlify-cms-core/src/components/Collection/Entries/EntriesSearch.js
- packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
- packages/netlify-cms-core/src/components/Editor/Editor.js
- packages/netlify-cms-core/src/components/Editor/EditorScrollSync/ScrollSyncPane.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
- packages/netlify-cms-widget-file/src/withFileControl.js
- packages/netlify-cms-widget-list/src/ListControl.js
- packages/netlify-cms-widget-relation/src/RelationControl.js
> refactor: stop using unsafe or deprecated React methods

- website/content/docs/add-to-your-site.md
**- Summary**
Just added jigsaws source folder path.
Did not test it, but it should work like a charm.
*Edit:* I just reviewed the deploy review build and it looks like it worked. 
Added jigsaws source folder path to a table.
> Add: jigsaw source path

- website/content/docs/start-with-a-template.md
Fixed two links. Hope this helps! Great job on Netlify by the way!
> Fixed two broken links.

- packages/netlify-cms-backend-git-gateway/src/implementation.js
**- Summary**
Followup from #1558 -- there was one case missed.
> Editorial workflow entries were being created without a status due to a bug in how the initial status constant was being passed to backends.
>
> Fixes #1556.
> fix(workflow): workflow entries not appearing

- packages/netlify-cms-core/babel.config.js
**- Summary**
React Hot Loader was removed in the v2.0 transition. This PR simply adds it back.
> dev: add react-hot-loader

- website/content/docs/widgets/index.md
fixes #1613. just scratching an itch...
> docs(fix): #1613 link to demo configuration code for widgets

- packages/netlify-cms-core/src/components/App/Header.js
**Summary**
The media button is not consistent with the other header links in most browsers. This is a v2.0 regression. I'm wondering if we should use `normalize.css` again, any thoughts?
**Test plan**
Tested in BrowserStack.
> fix: Make media button consistent with links.

- website/content/docs/start-with-a-template.md
**- Summary**
Was going through the quick-start and noticed 404 to links
Just simple link changes.
e.g Changed (https://netlifycms.org/docs/hello) to (/docs/hello)
> Fix 404 links

- website/content/docs/add-to-your-site.md
**Summary**
Found and fixed typo on the "Add to Your Site" page.
**Test plan**
Checked preview
> (docs) fixed typo in add-to-your-site.md

- website/content/docs/start-with-a-template.md
Edited for present tense and active voice, as well as some ambiguous wording.
**Summary**
I noticed some future tense and passive voice, which don't read well. I've also noticed some ambiguous phrasing.
**Test plan**
> Editing start-with-a-template.md for style and grammar

- .gitignore
- .prettierignore
**Summary**
The linters were trying to list website `.cache` and `public` folders, since they only read the top-level `.gitignore`, not the nested ones.
**Test plan**
> chore: update ignore files (for linters)

- CONTRIBUTING.md
**Summary**
Re-claimed from #646 with changes made.
> docs: add Git details to CONTRIBUTING.md

- packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js
**Summary**
Typo here: `site_id` should be `siteId`.
**Test plan**
> fix: setting site_id for BitBucket auth

- packages/netlify-cms-backend-git-gateway/src/implementation.js
Revert "improvement: clear error if Git Gateway settings 404"
This reverts commit 424a49e36c92501bad9610fbbe646088d7ab5400.
**Summary**
**Test plan**
> revert accidently pushed commit

- packages/netlify-cms-backend-git-gateway/src/implementation.js
**Summary**
If Git Gateway is disabled, the current error is *very* unclear: `Unexpected token < in JSON at position 0`. This PR changes to Git Gateway initial settings check code to validate that the request is OK (200 code) and is actually JSON. If not, we output a clear error message.
**Test plan**
> improvement: use clear error if Git Gateway off

- README.md
Update '/admin' to match other documentation.
**Summary**
**Test plan**
> change '/admin' to '/admin/'

- website/content/blog/netlify-cms-2-1-0-adds-external-media-support-with-uploadcare.md
- website/package.json
- website/src/components/twitter-meta.js
- website/src/templates/blog-post.js
- website/static/admin/config.yml
So we get proper previews on Twitter. Want this live before tweeting a link to the media libraries blog post.
> docs: add twitter metadata tags

- website/content/docs/intro.md
- website/content/docs/start-with-a-template.md
Let's clear up the difference, because it wasn't immediately obvious to a n00b like me. The [Deploy to Netlify](https://www.netlifycms.org/docs/start-with-a-template/) buttons are great, but don't help that confusion.
Based on the [excellent explanation by @verythorough](https://gitter.im/netlify/NetlifyCMS?at=58d31392fe6a638b1af3ac65).
Thanks for all your great work on two great products!
> Clarify the difference between Netlify.com and Netlify CMS

- website/content/docs/widgets/list.md
> Fix single field list example

- website/content/docs/configuration-options.md
Hey, this is my first open-source PR. Sorry if my PR description is a bit incorrect or incomplete.
**Summary**
Docs typo fix, which provides better understanding of the sentence containing the typo for the reader. 
**Test plan**
No tests needed, just reading the sentence is enough 👓
> Fix typo: it's --> its

- README.md
I felt like this document should be referenced in the README so that new users don't have to go looking for it.
**Summary**
I had to look around for this file, some people might not!
**Test plan**
N/A
Me and my dogs:
> Add a link to CONTRIBUTING.md

- website/gatsby-config.js
**Summary**
Swapped Guides and References on the Side Navigation.  Will comment if to see if Guides should be renamed to something else per issue #1641 
**Test plan**
STR:
1. From local forked repo yarn start
2. Navigate to Top Nav > Docs
3. Inspect Side Navigation
ER:
Reference is the second menu item
Guides is below Reference
All items expand where relative
All links reference correct documentation
AR:
Expected results confirmed - Passed
> fix #1641 swapped Guides and References

- packages/netlify-cms-widget-list/src/ListControl.js
**Summary**
This PR fixes #1810
> fix #1810 delete list item

- packages/netlify-cms-core/src/constants/configSchema.js
**Summary**
Closes #1811 - see issue for details.
**Test plan**
> Allow setting publish_mode to 'simple' in config.yml

- packages/netlify-cms-lib-auth/src/netlify-auth.js
**Summary**
Closes #1765.
This was only a problem in Firefox, since it is the only one that actually accepts `scrollbars=no`.
**Test plan**
Tested desktop browsers:
> fix: scrollbars not appearing in auth window

- packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
**Summary**
Fixes #1616 regression, bad editor component default value processing [introduced by yours truly](https://github.com/netlify/netlify-cms/pull/1616#issuecomment-416750263) 👌🏼.
@tech4him1 next time I can "help" with one of your PRs let me know! 😅
Closes #1823.
> fix(editor-components): fix default value processing

- packages/netlify-cms-backend-bitbucket/src/API.js
- packages/netlify-cms-backend-bitbucket/src/implementation.js
- packages/netlify-cms-backend-github/package.json
- packages/netlify-cms-backend-github/src/implementation.js
- packages/netlify-cms-backend-gitlab/src/implementation.js
- packages/netlify-cms-core/src/actions/auth.js
- packages/netlify-cms-core/src/components/UI/Toast.js
- yarn.lock
**Summary**
Provides a descriptive error message in the UI when a repo is not found during login. Fixes #545.
> improvement(auth): verbose error message when GitHub repo unavailable

- packages/netlify-cms-backend-gitlab/src/API.js
**Summary**
This PR fixes #1798.
The change made will replace every '+' character with a white space inside the URL of the request that fetches a list of files inside a folder.
> Bugfix: GitLab folders with whitespace (fixes #1798)

- packages/netlify-cms-core/src/actions/entries.js
- packages/netlify-cms-widget-boolean/src/BooleanControl.js
- website/content/docs/configuration-options.md
**Summary**
This PR fixes #1653
> fix list object field default values

- website/content/docs/configuration-options.md
**Summary**
This PR adds the missing slug `sanitize_replacement` option in the configuration options documentation.
> [docs] sanitize replacement option

- packages/netlify-cms-core/src/actions/entries.js
- packages/netlify-cms-widget-date/src/DateControl.js
**Summary**
This PR closes issue #1117  and #1276
> fix default value for nested date widget

- website/content/docs/examples.md
**Summary**: Docs improvment by adding a Jekyll Demo to the Examples
**Test plan** : N/A
> Adding Jekyll Demo Site to Examples

- website/content/docs/examples.md
**Summary**
Added a new example built with Eleventy to the Docs > Examples page of the website. This example is also listed over at: templates.netlify.com
**Test plan**
> Docs: add Eleventy Netlify Boilerplate to examples

- packages/netlify-cms-core/src/components/EditorWidgets/Unknown/UnknownPreview.js
**Summary**
This PR fixes the missing widget placeholder for unknown preview translation.
> i18n fix missing widget placeholder

- packages/netlify-cms-core/src/components/App/App.js
We can’t access to props or `this` in a `static` method.
> netlify-cms-core: fix `configError`

- website/content/docs/widgets/list.md
**Summary**
Typo fix: `disapears` => `disappears`
> docs: update list.md

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
**Summary**
A simple typo fix for the validation pattern  error message.
> fix validation pattern error message

- packages/netlify-cms-core/src/components/App/App.js
- packages/netlify-cms-core/src/components/App/Header.js
- packages/netlify-cms-ui-default/src/styles.js
**Summary**
This PR removes some unnecessary wrapper elements. The elements don't do anything and just clutters the markup and makes it harder to get a good overview in the devtools.
**Test plan**
I've tested this manually and they should look identical.
> chore(netlify-cms-core): remove unnecessary wrapper elements

- packages/netlify-cms-widget-select/package.json
- packages/netlify-cms-widget-select/src/SelectControl.js
- yarn.lock
**Summary**
This PR will allow the cms to use the [react select](https://github.com/JedWatson/react-select) for it's select widget. When merged, it will help finish up the multiselect widget #922
> use react select

- packages/netlify-cms-core/src/components/App/Header.js
- packages/netlify-cms-core/src/components/Collection/Sidebar.js
**Summary**
Closes #1488 
This PR only affects the markup, the style should look identical
**Test plan**
N/A
> fix(netlify-cms-core): wrap navigations in lists for better a11y

- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
**Summary**
Removes/fixes these warnings
**Test plan**
No warnings shown in the console
> fix(netlify-cms-core): fix prop-types warnings

- packages/netlify-cms-core/src/backend.js
> commit message use singular label if present

- packages/netlify-cms-core/package.json
- yarn.lock
**Summary**
Upgrade `react-waypoint` to the latest version. No breaking changes
**Test plan**
N/A
> chore(netlify-cms-core):upgrade react-waypoint

- packages/netlify-cms-widget-text/package.json
- yarn.lock
**Summary**
Upgrade `react-textarea-autosize` to the latest version. No breaking changes.
**Test plan**
N/A
> chore(netlify-cms-widget-text): upgrade react-textarea-autosize

- packages/netlify-cms-core/package.json
- yarn.lock
**Summary**
Upgrade `gray-matter` to 4.x.  No breaking changes what affects us https://github.com/jonschlinkert/gray-matter/blob/master/CHANGELOG.md
**Test plan**
N/A
> chore(netlify-cms-core): upgrade gray-matter to 4.x

- website/content/docs/uploadcare.md
**Summary**
Fix typo on Uploadcare docs page
**Test plan**
> Fix typo on Uploadcare docs page

- packages/netlify-cms-core/src/actions/auth.js
- packages/netlify-cms-core/src/constants/defaultPhrases.js
**Summary**
Fixed Auth notification message to support new translation format. Possibly related to #1819 .
**Test plan**
[image](https://i.imgur.com/eSRb1ux.png)
> Fixed notification messages to support new translation format

- packages/netlify-cms-editor-component-image/src/__tests__/index.spec.js
- packages/netlify-cms-editor-component-image/src/index.js
- packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js
Adds a "title" attribute to the built-in image editor component. There might be more robust ways to handle the regex or escaping though?
closes #1775
**Test plan**
Can someone point me to a relevant file to test this? I also noticed the docs are still in progress for this package, but is there somewhere I should add documentation?
> feat(editor-components): add title to image component

- packages/netlify-cms-media-library-cloudinary/src/__tests__/index.spec.js
- packages/netlify-cms-media-library-uploadcare/src/__tests__/index.spec.js
- packages/netlify-cms-media-library-uploadcare/src/index.js
Didn't test some of the deeper Uploadcare file handling integration because I expect much of that will change in #1825.
Also includes superficial improvements for cloudinary tests.
> fix(media-library-uploadcare): fix bugs, add tests

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
> fix(netlify-cms-core): relation widget value swap

- packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js
- packages/netlify-cms-core/src/constants/defaultPhrases.js
**Summary**
move the last modified text from `WorkflowCard` into `defaultPhrases` file.
**Test plan**
manually tested on `dev-test`.
needed to add the fallback to empty string, as the author was undefined on the `test-repo`.
> feat(netlify-cms-core): translate workflow card last modified text

- website/content/blog/netlify-cms-2-1-0-adds-external-media-support-with-uploadcare.md
- website/content/docs/customization.md
- website/content/docs/intro.md
- website/src/components/header.js
Fixes docs links and removes some weird ones.
Closes #2061.
> docs: fix links, remove some weird ones

- website/content/docs/cloudinary.md
**Summary**
Updated documentation for Cloudinary Media Library integration.
**Motivation**
Documentation need updating around syntax and approach to integrating Cloudinary Media Library
> Updated media library configuration info

- packages/netlify-cms-widget-number/src/NumberControl.js
- packages/netlify-cms-widget-number/src/__tests__/number.spec.js
**Summary**
Closes #2067
**Test plan**
See added tests
> Improve handling of empty values for number input

- website/data/updates.yml
- website/src/components/release.js
- website/src/pages/index.js
- website/static/admin/config.yml
- website/yarn.lock
- update website CMS to 2.4.1
- update config with preview paths
- add `url` param so release links can point to custom url (eg. blog post)
> chore: update website for preview links

- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCard.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
**Summary**
This PR is a simple implementation of an MVP for https://github.com/netlify/netlify-cms/issues/1984
**Test plan**
Unable to run `yarn test` at the moment due to WSL-related cypress errors. Once I can get on a real Linux system, I'll update this with the output.
> 1984 non-image "thumbnail" placeholder

- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/PreviewHOC.js
> fix relation widget preview

- website/content/docs/authentication-backends.md
**Summary**
Extremely minor grammatical changes in documentation. Adding three words which were likely omitted by accident.
**Test plan**
Previewed to ensure Markdown and URLs successfully unaffected.
As a completionist I must include https://imgflip.com/i/2tv8h7
> fix: minor grammatical corrections

- packages/netlify-cms-core/src/reducers/collections.js
**Summary**
Uses `identifier_field` as the title in the collection view entry card.
Closes #2016.
**Test plan**
Asking @Undistraction in a really nice way.
(@Undistraction would you mind testing this?)
> enhancement(collections): use identifier field in collections view

- website/content/docs/add-to-your-site.md
**Summary**
This is adding 'Pelican' to the list of generators on the 'add-your-site' page
**Test plan**
Copied the formatting from the other generators.
> Include pelican to list of generators

- packages/netlify-cms-backend-bitbucket/src/implementation.js
- packages/netlify-cms-backend-git-gateway/package.json
- packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
- packages/netlify-cms-backend-git-gateway/src/implementation.js
- packages/netlify-cms-backend-git-gateway/src/netlify-lfs-client.js
- packages/netlify-cms-backend-github/src/implementation.js
- packages/netlify-cms-backend-gitlab/src/implementation.js
- packages/netlify-cms-core/src/actions/mediaLibrary.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCard.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryModal.js
- packages/netlify-cms-core/src/reducers/mediaLibrary.js
- packages/netlify-cms-lib-util/package.json
- packages/netlify-cms-lib-util/src/getBlobSHA.js
- packages/netlify-cms-lib-util/src/index.js
- website/content/docs/netlify-large-media.md
- yarn.lock
**Summary**
Add support for Netlify Large Media in Netlify CMS.
> Netlify Large Media integration

- website/content/docs/netlify-large-media.md
**Summary**
Neltify -> Netlify
**Test plan**
> Fix typo in netlify-large-media.md

- packages/netlify-cms-widget-relation/src/RelationControl.js
- website/content/docs/widgets/relation.md
**Summary**
Update relation widget doc, add multiple options.
> doc: relation widget add multiple options

- packages/netlify-cms-core/src/backend.js
> fix(core): number type slug template

- website/content/docs/cloudinary.md
**Summary**
Added Cloudinary configurations under 'config' (in Global configuration section)
Reason: 'config' was missing
> Added Cloudinary configurations under 'config'

- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCard.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
- packages/netlify-cms-ui-default/src/index.js
- packages/netlify-cms-ui-default/src/styles.js
- packages/netlify-cms-widget-file/src/withFileControl.js
**Summary**
Closes #2126. I was also consistently seeing a horizontal scrollbar on the media upload popup, so I fixed that too.
**Test plan**
Run locally and upload images to the media library. Make sure you can see the whole image you uploaded, including white and gray icons. You shouldn't see a horizontal scrollbar.
> enhancement(media-library): use checkerboard pattern as background

- packages/netlify-cms-lib-auth/package.json
- packages/netlify-cms-widget-file/package.json
- packages/netlify-cms-widget-relation/package.json
**Summary**
UUID is a peer dependency in the packages. Removes unnecessary bundled code.
**Test plan**
As long as bundles build, there is no change in main build.
🙈
> chore: fix uuid peers

- website/content/docs/deploy-preview-links.md
**Summary**
Fix a typo in documentation for Deploy Preview Links
**Test plan**
N/A
> fix a typo in documentation for Deploy Preview Links

- README.md
**Summary**
Suggestion for a minor wording improvement.
Suggestion to remove the assumption that only "non-technical" people will benefit / prefer using CMS functionality. 
My reasoning behind this suggestion is that I'm pretty sure many "technical" folks also prefer using a UI for creating or editing content. Instead the focus should be the convenience that a CMS like this provides, as an option to any user of the system.
**Test plan**
Tested by: Peer Review
🐼
> Update to Readme.md: Remove "non-technical"

- packages/netlify-cms-backend-bitbucket/package.json
- packages/netlify-cms-backend-git-gateway/package.json
- packages/netlify-cms-backend-github/package.json
- packages/netlify-cms-backend-gitlab/package.json
- packages/netlify-cms-backend-test/package.json
- packages/netlify-cms-core/package.json
- packages/netlify-cms-default-exports/package.json
- packages/netlify-cms-editor-component-image/package.json
- packages/netlify-cms-lib-auth/package.json
- packages/netlify-cms-lib-util/package.json
- packages/netlify-cms-media-library-cloudinary/package.json
- packages/netlify-cms-media-library-uploadcare/package.json
- packages/netlify-cms-ui-default/package.json
- packages/netlify-cms-widget-boolean/package.json
- packages/netlify-cms-widget-date/package.json
- packages/netlify-cms-widget-datetime/package.json
- packages/netlify-cms-widget-file/package.json
- packages/netlify-cms-widget-image/package.json
- packages/netlify-cms-widget-list/package.json
- packages/netlify-cms-widget-map/package.json
- packages/netlify-cms-widget-markdown/package.json
- packages/netlify-cms-widget-number/package.json
- packages/netlify-cms-widget-object/package.json
- packages/netlify-cms-widget-relation/package.json
- packages/netlify-cms-widget-select/package.json
- packages/netlify-cms-widget-string/package.json
- packages/netlify-cms-widget-text/package.json
- packages/netlify-cms/src/index.js
**Summary**
- Fix main export bundle `netlify-cms`
- add source maps to esm builds
**Test plan**
Beta released
> fix: export on netlify-cms and maps on esm

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
> fix: broken preview

- packages/netlify-cms-core/src/components/Editor/Editor.js
**Summary**
Fixes a bug where new entry backups weren't being deleted, and the CMS kept offering to restore when creating a new entry.
Closes #2259
> fix(core): correctly delete backups for new entries

- README.md
**Summary**
Small PR to address a few Accessibility & Lingo issues. Adds alt tags and fixes lingo.
Hoping to contribute more. 👍
**Test plan**
Not needed.
> 👌 IMPROVE: Accessibility & Lingo

- packages/netlify-cms-backend-git-gateway/src/implementation.js
**Summary**
Fixes image display in the media library when using Git Gateway with Gitlab, but not using Large Media. Closes #2242.
**Test plan**
> Fix image display for GitLab+Git Gateway without Large Media

- website/content/docs/cloudinary.md
**Summary**
Fixes typo in cloudinary docs
> Typo - templates

- packages/netlify-cms-widget-relation/src/RelationControl.js
> fix(widget-relation): clear button

- website/content/docs/customization.md
Remove duplicate word in sentence "...besides the plain plain textual..."
**Summary**
**Test plan**
> Remove duplicate word in customization.md

- packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
> fix(widget-markdown): ensure correct value on list reorder

- website/content/docs/authentication-backends.md
**Summary**
Added code backticks for Client-Side Implicit Grant (Bitbucket) settings example. The code was not formatted properly.
**Test plan**
No testing, just minor formatting in documentation 
🐺
> docs: code format bitbucket settings example

- website/content/docs/jekyll.md
> docs: update Jekyll tutorial blog screen shot

- website/content/docs/gatsby.md
**Summary**
I'd followed all along with docs and executed all steps but in the end when I was trying to run <code>gatsby develop</code>
I'd got the following error:
This dependency was not found:
⠀
* netlify-cms-app in ./node_modules/gatsby-plugin-netlify-cms/cms.js
⠀
To install it, you can run: npm install --save netlify-cms-app
> Added Missing dependency

- website/content/docs/uploadcare.md
**Summary**
Theyve changed the URLs on the Uploadcare docs and i've updated the link to the widget options
**Test plan**
Not needed, just a change to a docs file
> Updated link to widget options on Uploadcare

- packages/netlify-cms-backend-git-gateway/src/implementation.js
> fix(git-gateway): new entry for gitlab

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
> fix(core): list widget validation

- website/content/pages/community.md
- website/src/components/docsearch.js
- website/src/components/header.js
- website/src/components/video-embed.js
- website/src/css/imports/collab.css
- website/src/css/imports/header.css
- website/src/pages/community.js
- website/src/pages/index.js
- website/static/admin/config.yml
- dropped bi-weekly call info
- added information about available channels for support and development
- fixed build warnings
- added CMS config for community page
> docs: update community info with channel links

- website/content/docs/add-to-your-site.md
**Summary**
This commit adds Elmstatic (the static site generator for Elm sites) and sorts the list of generators. It also links to the specific pull requests section of the docs for filing a pull request, since it's at the bottom of the linked page.
**Test plan**
Only a doc change.
> Add Elmstatic and sort list of generators

- jest.config.js
- package.json
- packages/netlify-cms-backend-gitlab/src/__tests__/gitlab.spec.js
- packages/netlify-cms-core/src/backend.js
- setupTestFramework.js
- yarn.lock
**Summary**
Opening this early for visibility, discussion, and contribution.
This project's greatest weakness is its lack of testing. The lack of testing is, I think, mostly owing to a general awareness that the backends are by far the most needful of testing, but require considerable effort to test well. Being often busy with features and bugfixes, we tended to put this effort off. That's my theory, anyway. We've only avoided massive failure for the thousands of sites using Netlify CMS through diligence in writing and merging code.
This is not a scalable solution.
The project is now at a place where important and exciting contributions are being delayed to avoid the risk of bugs - a risk that is exponentially higher than it should be because of our lack of testing. This PR aims to get …
> cover gitlab backend integration

- packages/netlify-cms-core/src/backend.js
**Summary**
The below error shows up while using the backend `file-system` with the CMS. This PR should address the issue.
```
TypeError: Cannot read property 'includes' of undefined
at netlify-cms-app.js:16
at async j.entryExist (netlify-cms-app.js:16)
at async j.generateUniqueSlug (netlify-cms-app.js:16)
at async j.persistEntry (netlify-cms-app.js:16)
at async Object.onPersist (netlify-cms-app.js:227)
```
> fix(core): create entry for backend file system 

- packages/netlify-cms-widget-list/src/ListControl.js
**Summary**
Closes #2378, closes #2363
> fix(widget-list): default values when adding new items

- website/content/docs/nextjs.md
> Fix bottom "add to your site" link

- packages/netlify-cms-core/src/backend.js
> fix(chore): broken search

- website/content/docs/contributor-guide.md
- website/content/docs/style-guide.md
- website/content/docs/writing-style-guide.md
**Summary**
Collaboration between @mimidumpling and myself at Write The Docs Portland 2019. In response to #1038 and #1632. Inspiration was taken from the Kubernetes Contributing Guidelines and Style Guide as mentioned in the respective issues.
I submit this baby trash panda to the Netlify CMS gods
> WTD19: Improve Contrib Guide and Create Style Guide

- website/content/docs/nextjs.md
> Fix URL Typo

- packages/netlify-cms-ui-default/src/styles.js
**Summary**
Hello, just 2 tiny errors I spotted in the styles file.
**Test plan**
> fix(netlify-cms-ui-default): typos in styles.js

- website/content/docs/contributor-guide.md
> fix: incorrect github repo url

- packages/netlify-cms-backend-github/src/API.js
- packages/netlify-cms-backend-github/src/AuthenticationPage.js
- packages/netlify-cms-backend-github/src/implementation.js
- packages/netlify-cms-backend-gitlab/src/API.js
- packages/netlify-cms-core/src/actions/auth.js
- packages/netlify-cms-core/src/actions/mediaLibrary.js
- packages/netlify-cms-core/src/components/Editor/Editor.js
- packages/netlify-cms-core/src/components/Editor/EditorInterface.js
- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
- packages/netlify-cms-core/src/components/Workflow/Workflow.js
- packages/netlify-cms-core/src/components/Workflow/WorkflowList.js
- packages/netlify-cms-core/src/reducers/globalUI.js
- packages/netlify-cms-lib-util/src/backendUtil.js
- packages/netlify-cms-lib-util/src/index.js
- packages/netlify-cms-lib-util/src/unsentRequest.js
- website/content/docs/open-authoring.md
**Summary**
Fixes bugs introduced by Open Authoring changes, and correctly handles paginated endpoints in the GitHub API. Also renames Fork Workflow to Open Authoring throughout the whole codebase, including renaming `backend.fork_workflow` to `backend.open_authoring`.
**Test plan**
> Open Authoring bugfixes and pagination improvements

- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCard.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
> fix(core): media non viewable files

- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Fixes #2608 
All the details are explained in the issue
> Fix: Pass correct prop type to DropdownItem

- packages/netlify-cms-widget-list/src/ListControl.js
Fixes #2610 
All the details are explained in the issue
> Fix: Pass correct prop type to List widget 

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
> fix(core): list widget pattern validation

- website/content/docs/start-with-a-template.md
The link cannot be accepted (and would be broken) if deployment is not finished.
**Summary**
**Test plan**
> added condition to Access section

- website/content/docs/jekyll.md
The file '_layouts/post.html' has to be updated as well, since 'short_name' was changed to 'name'. I've included the path of the file and the code snippet which needs to be updated to the writeup.
> Add '_layouts/post.html' to Jekyll guide

- packages/netlify-cms-backend-gitlab/src/API.js
> fix(backend-gitlab): 404 collection listing error

- packages/netlify-cms-backend-bitbucket/src/implementation.js
- packages/netlify-cms-core/src/actions/editorialWorkflow.js
- packages/netlify-cms-core/src/actions/entries.js
- packages/netlify-cms-core/src/actions/search.js
- packages/netlify-cms-core/src/backend.js
- packages/netlify-cms-core/src/constants/configSchema.js
- packages/netlify-cms-core/src/lib/__tests__/urlHelper.spec.js
- packages/netlify-cms-core/src/lib/urlHelper.js
- packages/netlify-cms-core/src/reducers/medias.js
- packages/netlify-cms-media-library-cloudinary/src/index.js
- packages/netlify-cms-media-library-uploadcare/src/index.js
- website/content/docs/nextjs.md
- website/src/components/docs-nav.js
**Summary**
I've fixed some typos in comments.
> fix: fix the typos in comments

- website/content/docs/custom-widgets.md
> custom-widget.md: link to starter repo

- packages/netlify-cms-backend-git-gateway/src/GitHubAPI.js
- packages/netlify-cms-backend-github/src/GraphQLAPI.js
- packages/netlify-cms-backend-github/src/implementation.js
Closes #2629
**Summary**
Fixes regression described in the issue above.
**Test plan**
> Fix broken git gateway github integration

- website/content/docs/nuxt.md
@nuxt/markdownit was broken so I updated these references to @nuxtjs/markdownit
**Summary**
**Test plan**
> Update markdownit references

- website/content/docs/authentication-backends.md
**Summary**
That link was broken.
**Test plan**
Go and click it if you dare!
_Picture courtesy of [Jessica Weiller](https://unsplash.com/photos/GAw5wFLVWVo) on Unsplash._
> :bug: fixed broken link

- .eslintrc
> chore: disable eslint react prop-types rule

- website/content/docs/start-with-a-template.md
Just shifted this repo to the official org, updating the link here
> pointing the url to the repo in the preactjs org

- packages/netlify-cms-core/src/routing/history.js
**Summary**
Fix `history` module console warning: 
``
warnAboutDeprecatedCJSRequire.js:17 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.
``
> fix history console warning

- packages/netlify-cms-widget-date/src/DateControl.js
- packages/netlify-cms-widget-datetime/src/DateTimeControl.js
fixes #2697
feel free to squash the two commits
> Fix date widgets with format when user enters empty string

- website/content/docs/add-to-your-site.md
Fixed typo
comfirming => confirming
> [Typo] comfirming

- website/content/docs/deploy-preview-links.md
Fixed typo
continous => continuous
> [Typo] continous

- website/content/docs/hugo.md
Fixed typo
sucessfully => successfully
giti => git
> [Typo] sucessfully, giti

- packages/netlify-cms-core/src/components/Collection/Entries/EntriesCollection.js
- packages/netlify-cms-core/src/components/Editor/Editor.js
- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
**Summary**
I have fixed the lint issues. 
**Test plan**
```
npm run lint
```
> Fix lint issues with propTypes

- website/content/docs/widgets.md
Using double quotes with pattern raises an error (found out the hard way): https://github.com/netlify/netlify-cms/issues/675#issuecomment-444316681
> [docs] Update widgets.md pattern example

- commitlint.config.js
- package.json
- yarn.lock
This enforces conventional commit messages (we're already doing it manually...)
> chore: add commitlint

- website/content/docs/authentication-backends.md
**Summary**
Fixed the code formatting in the authentication-backend.md page (https://www.netlifycms.org/docs/authentication-backends/)
**Test plan**
Check out the [/docs/authentication-backends/](https://deploy-preview-2812--netlify-cms-www.netlify.com/docs/authentication-backends/#specifying-a-status-for-deploy-previews) page.
|Before|After|
|---|---|
|<img width="914" alt="Screen Shot 2019-10-27 at 5 03 43 PM" src="https://user-images.githubusercontent.com/3411183/67644162-1cbaab80-f8dc-11e9-861b-ce2c4782d5f4.png">|<img width="891" alt="Screen Shot 2019-10-27 at 5 06 06 PM" src="https://user-images.githubusercontent.com/3411183/67644168-2217f600-f8dc-11e9-88fa-6a26e685150a.png">|
> Fixed the code formatting in the backends doc

- packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js
- packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
- packages/netlify-cms-backend-github/src/AuthenticationPage.js
- packages/netlify-cms-backend-gitlab/src/AuthenticationPage.js
- packages/netlify-cms-backend-test/src/AuthenticationPage.js
- packages/netlify-cms-ui-default/src/AuthenticationPage.js
- packages/netlify-cms-ui-default/src/GoBackButton.js
- packages/netlify-cms-ui-default/src/index.js
If this is a bug fix, make sure your description includes "fixes #xxxx", or
"closes #xxxx", where #xxxx is the issue number.
Please provide enough information so that others can review your pull request.
The first two fields are mandatory:
-->
**Summary**
Closes #2537. I added link to the '/' page. It might be good to take this link from `site_url` in `config.yml`, but as far as I know this entry is not required.
**Test plan**
> Fix #2537: Add go back to site button

- packages/netlify-cms-backend-github/src/implementation.js
Fixes #2535
Skip the UI part of asking to fork in case the fork exists.
> fix: display UI to fork a repo only when fork doesn't exist

- .github/stale.yml
This will give us some more time to go over stale issues
> chore: change stale bot daysUntilClose to 14

- packages/netlify-cms-ui-default/src/AuthenticationPage.js
**Summary**
Just noticed the `github` backend authentication page is broken. Issue introduced by #2538, probably should affect other backends except `test`. A quick fix here.
> fix: authentication page

- website/content/docs/nuxt.md
> Delete duplicate key-value

- packages/netlify-cms-backend-git-gateway/src/GitHubAPI.js
- packages/netlify-cms-backend-github/src/API.js
> fix(backend-git-gateway): omit /repos/ when no repo

- packages/netlify-cms-backend-github/src/AuthenticationPage.js
- packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
- packages/netlify-cms-core/src/constants/configSchema.js
Fixes #1423.
This is also relevant for open authoring as the default scope should not be `repo` (was raised as a question in the JAMstack community slack).
> fix: change default open authoring scope, make it configurable

- packages/netlify-cms-widget-list/src/ListControl.js
> fix(widget-list):  when single field value is object widget

- packages/netlify-cms-backend-git-gateway/src/implementation.js
- packages/netlify-cms-backend-github/src/API.js
- packages/netlify-cms-backend-github/src/implementation.js
- packages/netlify-cms-core/src/actions/mediaLibrary.js
**Summary**
Fixes #2158 (I think). Added a message to log to the console where 404s are handled. Did not add any logs in places where an error is thrown due to a 404.  
**Test plan**
Currently unsure. Ran tests and formatting and everything looked good. Would love some advice/help on a good way to test that this works as expected, although it's fairly simple and I can't imagine this not working. Hopefully put the loggings in the right places.
> add logs when a 404 error is expected

- website/content/docs/authentication-backends.md
> docs: fix bitbucket implicit grant docs

- packages/netlify-cms-backend-github/src/API.js
- packages/netlify-cms-lib-util/src/__tests__/backendUtil.spec.js
> fix(backend-github): editorial workflow commits

- website/content/docs/add-to-your-site.md
Cherry picked from https://github.com/netlify/netlify-cms/pull/2669 and fixed per @tomrutgers comment
> Docs: add missing Next entry in add-to-your-site.md

- packages/netlify-cms-widget-markdown/src/__tests__/renderer.spec.js
A required prop was missing leading to an error in the log when running unit tests
> test: pass missing prop in test

- packages/netlify-cms-locales/src/de/index.js
> feat: add german translation

- packages/netlify-cms-ui-default/src/styles.js
**Summary**
Currently, the media modal looks like so on dev:
A simple fix for the issue.
> fix: media assets modal

- packages/netlify-cms-ui-default/src/Icon/images/_index.js
- packages/netlify-cms-ui-default/src/Icon/images/h-options.svg
- packages/netlify-cms-ui-default/src/styles.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
- website/content/docs/widgets/markdown.md
**Summary**
I took over the work from @zacharysierakowski and fixed the problem with the switching between Markdown and the visual editor.
**Test plan**
> feat(netlify-cms-widget-markdown): add headings dropdown, new try

- packages/netlify-cms-locales/src/es/index.js
- packages/netlify-cms-locales/src/index.js
**Summary**
* Changes: Add spanish (es) locale to the list of locales
* Motivation: I'm a native spanish speaker and I want my editors to have a CMS in a language they can fully understand
**Test plan**
> feat(lang): add 'es' locale

- netlify.toml
Trying to fix: https://github.com/netlify/netlify-cms/issues/2901
Not sure what the problem is as building and serving locally works.
First attempt is to make sure we're using the same yarn versions and flags.
> fix: demo site is broken

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/nl/index.js
> feat(lang): add 'nl' locale

- website/content/docs/beta-features.md
> docs: add beta docs for folder collections path config

- packages/netlify-cms-backend-test/src/__tests__/implementation.spec.js
- packages/netlify-cms-backend-test/src/implementation.js
**Summary**
Currently, test backend  `deleteFile` for nested file path doesn't work. A simple fix for the issue.
> fix(backend-test): delete nested file path

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/tr/index.js
Fixed the formatting from this PR: https://github.com/netlify/netlify-cms/pull/2933
> feat(lang): add 'tr' locale

- website/content/docs/jekyll.md
**Summary**
Fixes a typo
**Test plan**
view new text
> "Indentity" -> "Identity"

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/pl/index.js
Fixed the formatting from this PR: https://github.com/netlify/netlify-cms/pull/2948
> Feat(docs): add pl locale

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/ja/index.js
> feat(locales): add ja locale

- packages/netlify-cms-backend-bitbucket/src/API.js
**Summary**
Closes #2105 
The fix here is to replace the branch name with the branch commit sha.
> fix(bitbucket): branchname containing slash

- packages/netlify-cms-locales/src/hu/index.js
- packages/netlify-cms-locales/src/index.js
**Summary**
🇭🇺Hungarian language translation 🇭🇺
> feat(lang): add 'hu' locale

- packages/netlify-cms-backend-bitbucket/src/API.js
**Summary**
With the fix for branchname containing slash here #2963, newly created entry returns 404, cause we are checking for the branch sha once. I think it's best to check for the current branch sha on every relevant  API call.
> fix(backend-bitbucket): 404 for new entry

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
> fix: select widget dropdown options

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
- packages/netlify-cms-widget-code/src/CodeControl.js
- packages/netlify-cms-widget-code/src/SettingsPane.js
> fix: allow widget overflow

- packages/netlify-cms-core/src/components/App/App.js
Check for collection existence before attempting to load an entry by URL - this avoids potential crashes, especially for open authoring when accessing an entry direct by URL.
> Safe collection routing

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
- packages/netlify-cms-widget-list/src/ListControl.js
> fix: cleanup nested widget validation

- cypress/utils/steps.js
- packages/netlify-cms-core/src/actions/editorialWorkflow.ts
- packages/netlify-cms-core/src/actions/entries.ts
- packages/netlify-cms-core/src/components/Editor/Editor.js
Currently, the new and duplicate entry operation stopped working(race condition). 
A fix for the issue.
> fix: duplicate and new entry action

- packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js
> fix(widget-markdown): cut/copy selection only in raw mode

- packages/netlify-cms-locales/src/pt/index.js
**Summary**
:brazil: :portugal: Portuguese translation c: :portugal: :brazil:
> feat(lang): add 'pt' locale

- packages/netlify-cms-locales/src/tr/index.js
> fix(locale-tr): fix tr locale

- packages/netlify-cms-backend-bitbucket/src/API.js
Fixes https://github.com/netlify/netlify-cms/issues/3058
> fix(backend-bitbucket): fix media library not loaded on BitBucket

- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
- packages/netlify-cms-core/src/reducers/mediaLibrary.js
- packages/netlify-cms-locales/src/en/index.js
- website/content/docs/beta-features.md
see #1322
seems to work, feedback welcome!
> Add media_library.config.max_file_size option

- packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js
- packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js
**Summary**
Multiline shortcodes aren't detected if they contain empty lines. This is due to an unproven performance guard that only ran editor component patterns from a given line through the next newline.
**Test plan**
Unit tests added. Checked for resulting perf issues in the kitchen sink collection and noticed no difference.
> fix(widget-markdown): allow multiline shortcodes

- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js
- packages/netlify-cms-core/src/reducers/entries.ts
- packages/netlify-cms-core/src/types/redux.ts
Fixes https://github.com/netlify/netlify-cms/issues/3053
@erquhart let me know if this is what you had in mind (I'm not sure I completely understand the scenario in the issue).
We can move forward on the other related issues after this is merged.
> feat: support per collection public_folder

- packages/netlify-cms-lib-util/src/__tests__/backendUtil.spec.js
- packages/netlify-cms-lib-util/src/backendUtil.ts
Fixes https://github.com/netlify/netlify-cms/issues/2518
> fix: use string endsWith to filter by extension

- packages/netlify-cms-backend-github/src/GraphQLAPI.ts
Fixes https://github.com/netlify/netlify-cms/issues/3098
> fix(backend-github-graphql): handle trailing paths in collection folder

- .gitignore
- .storybook/main.js
- package.json
- yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/3102
Basically adjusted the getting started guide to our repo structure.
Feel free to make any configuration changes. 
Not sure if we need a separate storybook setup per package, or we could just use a naming convention based like `Core/Button` vs `UI Default/Button`. We can start with a single setup and change if that doesn't work out.
@danoszz & @timmysmalls, let me know if that works for you.
> chore: add storybook

- packages/netlify-cms-backend-gitlab/src/API.ts
- packages/netlify-cms-backend-gitlab/src/__tests__/API.spec.js
Fixes https://github.com/netlify/netlify-cms/issues/3120
> fix(backend-gitlab): check for shared group permissions

- cypress/integration/editorial_workflow_spec_proxy_backend.js
- cypress/integration/media_library_spec_proxy_backend.js
- cypress/integration/simple_workflow_spec_proxy_backend.js
- cypress/utils/steps.js
- packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
Hopefully this fixes the flaky proxy tests.
> test(backend-proxy-e2e): stabilize backend proxy tests

- packages/netlify-cms-widget-file/src/withFileControl.js
Fixes https://github.com/netlify/netlify-cms/issues/3128
> fix(media-library): pass correct value to Asset component

- packages/netlify-cms-widget-code/src/CodeControl.js
Replaces https://github.com/netlify/netlify-cms/pull/3150
> fix(widget-code): use snake case for default language option

- packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js
- packages/netlify-cms-core/src/reducers/entries.ts
Fixes https://github.com/netlify/netlify-cms/issues/3132
> fix: allow absolute paths for collection media folder

- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Fixes https://github.com/netlify/netlify-cms/issues/3124
> fix: don't show duplicate entry button when create is disabled

- packages/netlify-cms-core/src/backend.ts
A fix for the issue described on slack here https://netlifycms.slack.com/archives/CPRR0PQ9E/p1580284574058800
> fix: media file path

- packages/netlify-cms-locales/src/pt/index.js
> No open issue
**Summary**
Typo fix to return the correct message :memo: :stuck_out_tongue: 
Vira-lata caramelo :brazil:
> fix(locale-pt): typo fix for `backCollection` pt

- packages/netlify-cms-locales/src/en/index.js
- packages/netlify-cms-widget-select/src/SelectControl.js
- packages/netlify-cms-widget-select/src/__tests__/select.spec.js
- website/content/docs/widgets/select.md
**Summary**
Adds **min** and **max** validation options for the select widget.
**Test plan**
Unit tests added.
> feat(select-widget): add min/max validation

- packages/netlify-cms-core/src/actions/editorialWorkflow.ts
- packages/netlify-cms-core/src/backend.ts
- packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
- packages/netlify-cms-core/src/lib/registry.js
- website/content/docs/beta-features.md
Initial work for https://github.com/netlify/netlify-cms/issues/1348
Doesn't allow modifying content yet.
> feat: add prePublish,postPublish events

- packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkSlate.spec.js
- packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js
Fixes https://github.com/netlify/netlify-cms/issues/3163
> fix(slate): merge adjacent text nodes with same marks

- packages/netlify-cms-widget-select/src/SelectControl.js
- packages/netlify-cms-widget-select/src/SelectPreview.js
- packages/netlify-cms-widget-select/src/__tests__/select.spec.js
- fixed initial value handling
- fixed preview
- added tests
- cleaned up a bit
> fix(widget-select): allow optional field to use min/max

- website/content/blog/netlify-cms-gatsby-plugin-4-0-0.md
- website/content/docs/cloudinary.md
- website/content/docs/uploadcare.md
Fixes #2954 
I'm not too sure if I have included the note for `netlify-cms-app` users in the most appropriate place.
> docs: fix media library usage

- .github/workflows/nodejs.yml
Reference https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths
> ci: don't run github actions on docs changes

- packages/netlify-cms-core/src/actions/entries.ts
- packages/netlify-cms-core/src/actions/mediaLibrary.ts
> fix: media library on reload

- packages/netlify-cms-core/src/actions/entries.ts
- packages/netlify-cms-core/src/backend.ts
> fix: load missing assets when retrieving backup

- packages/netlify-cms-core/src/actions/editorialWorkflow.ts
- packages/netlify-cms-core/src/actions/entries.ts
- packages/netlify-cms-core/src/backend.ts
- packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
- packages/netlify-cms-core/src/lib/registry.js
- website/content/docs/beta-features.md
> feat: add preUnpublish, postUnpublish events

- packages/netlify-cms-locales/src/pl/index.js
This should be merged after #3193
**Summary**
Add missing polish translations
**Test plan**
Maybe someone who knows polish could check it?
> feat(polish): add missing polish translations

- packages/netlify-cms-locales/src/nl/index.js
**Summary**
Add missing Dutch translations based on the polish ones by @pniedzwiedzinski
> feat(dutch): add missing dutch translations

- dev-test/backends/proxy/config.yml
- dev-test/backends/proxy/index.html
- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
- packages/netlify-cms-core/src/constants/configSchema.js
- website/content/docs/beta-features.md
Related to #2335 
@erquhart let me know if this is what you had in mind.
> feat: auto detect proxy server on load

- packages/netlify-cms-backend-bitbucket/src/implementation.ts
- packages/netlify-cms-backend-gitlab/src/implementation.ts
- packages/netlify-cms-lib-util/src/Cursor.ts
Fixes https://github.com/netlify/netlify-cms/issues/2246
Specifically the comment here  https://github.com/netlify/netlify-cms/issues/2246#issuecomment-582097086
As the original issue was fixed here https://github.com/netlify/netlify-cms/pull/3097
> fix: filter paginated results

- packages/netlify-cms/webpack.config.js
Fixes https://github.com/netlify/netlify-cms/issues/3220
Not sure about changing the default though
> build: expose local dev server port

- cypress/integration/editorial_workflow_spec_proxy_git_backend.js
- cypress/integration/media_library_spec_proxy_git_backend.js
- cypress/integration/simple_workflow_spec_proxy_fs_backend.js
- cypress/integration/simple_workflow_spec_proxy_git_backend.js
- cypress/plugins/proxy.js
- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-proxy-server/src/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/joi/customValidators.ts
- packages/netlify-cms-proxy-server/src/middlewares/localFs/index.spec.ts
- packages/netlify-cms-proxy-server/src/middlewares/localFs/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/utils/entries.ts
- packages/netlify-cms-proxy-server/src/middlewares/utils/fs.ts
Fixes https://github.com/netlify/netlify-cms/issues/3211
@erquhart The local fs middleware is very similar to the git one, just without editorial workflow methods and all the branch switching logic.
> feat(proxy-server): add local fs middleware and make it the default

- packages/netlify-cms-proxy-server/src/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/utils/entries.ts
Fixes https://github.com/netlify/netlify-cms/issues/3228
Also increased the json request payload size limit to support larger files (specifically images).
> Fix: proxy fs on windows

- packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
- packages/netlify-cms-core/src/lib/formatters.ts
- packages/netlify-cms-core/src/lib/stringTemplate.ts
- packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js
- packages/netlify-cms-core/src/reducers/collections.ts
Fixes https://github.com/netlify/netlify-cms/issues/2417
Replaces https://github.com/netlify/netlify-cms/pull/3121
@erquhart Let me know if this addresses your comment here https://github.com/netlify/netlify-cms/pull/3121#discussion_r369738118
> Feat: Allow using subfields as identifier field

- packages/netlify-cms-proxy-server/src/middlewares/joi/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/localFs/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
- packages/netlify-cms-proxy-server/src/middlewares/utils/entries.ts
Fixes https://github.com/netlify/netlify-cms/issues/3234
> fix(proxy-server): better handle files based collections

- packages/netlify-cms-widget-list/src/ListControl.js
> fix: remove empty list item

- packages/netlify-cms-widget-markdown/src/MarkdownControl/schema.js
Fixes https://github.com/netlify/netlify-cms/issues/3253
See [test PR](https://github.com/erezrokah/axway-open-docs/pull/1)
> fix(widget-markdown): allow shortcodes as list items

- cypress/integration/common/editorial_workflow_migrations.js
- cypress/utils/steps.js
- packages/netlify-cms-backend-github/src/API.ts
- packages/netlify-cms-backend-github/src/__tests__/API.spec.js
- packages/netlify-cms-core/src/backend.ts
**Summary**
- Improves recovery from aborted migration sequences
- Gives ugly but helpful indicators about the migration to the end user
Feel free to improve any code style/implementation issues.
> fix(backend-github): improve workflow migration edge cases/messaging

- packages/netlify-cms-backend-github/src/API.ts
Bail on individual migrations gracefully without failing the entire process.
> fix(backend-github): fail workflow migrations gracefully

- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Eliminates most button overflow in the toolbar for screens smaller than 1200px width.
> fix(core): improve editor buttons for smaller screens

- website/content/docs/authentication-backends.md
> Add PHP oauth backend

- packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js
- packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
- packages/netlify-cms-backend-github/src/AuthenticationPage.js
- packages/netlify-cms-backend-gitlab/src/AuthenticationPage.js
- packages/netlify-cms-backend-proxy/src/AuthenticationPage.js
- packages/netlify-cms-backend-test/src/AuthenticationPage.js
- packages/netlify-cms-locales/src/cs/index.js
- packages/netlify-cms-locales/src/de/index.js
- packages/netlify-cms-locales/src/en/index.js
- packages/netlify-cms-locales/src/es/index.js
- packages/netlify-cms-locales/src/fr/index.js
- packages/netlify-cms-locales/src/gr/index.js
- packages/netlify-cms-locales/src/hu/index.js
- packages/netlify-cms-locales/src/it/index.js
- packages/netlify-cms-locales/src/ja/index.js
- packages/netlify-cms-locales/src/nl/index.js
- packages/netlify-cms-locales/src/pt/index.js
- packages/netlify-cms-locales/src/ru/index.js
- packages/netlify-cms-locales/src/uk/index.js
- packages/netlify-cms-locales/src/zh_Hant/index.js
- packages/netlify-cms-ui-default/src/AuthenticationPage.js
- packages/netlify-cms-ui-default/src/GoBackButton.js
Related to #2959 
Follow up from #3193 
- Remove hard coded strings and added language translations
> fix(locale): Remove hard coded string literals

- packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js
- packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js
- packages/netlify-cms-core/src/reducers/collections.ts
- packages/netlify-cms-core/src/reducers/entries.ts
- packages/netlify-cms-core/src/types/redux.ts
Fixes per field media folders for variable types  https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types
> fix: consider variable types when traversing collection fields

- packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
- packages/netlify-cms-core/src/lib/formatters.ts
- website/content/docs/configuration-options.md
Fixes https://github.com/netlify/netlify-cms/issues/3364
> feat: support filename and extension vars in summary

- package.json
Our CI build was missing types checks
> ci: add missing types check

- packages/netlify-cms-core/src/components/Collection/CollectionTop.js
- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
- packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryActions.js
This looks to begin replacing legacy Buttons with those from the new UI
> Replace Legacy Buttons

- packages/netlify-cms-core/src/components/App/Header.js
- packages/netlify-cms-core/src/components/Collection/CollectionTop.js
- packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
- packages/netlify-cms-core/src/components/Collection/Sidebar.js
- packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js
- packages/netlify-cms-ui-default/src/Card/story.jsx
- packages/netlify-cms-ui-default/src/NavigationMenu/story.jsx
- packages/netlify-cms-ui-default/src/widgets/SelectWidget/story.jsx
Refactor Header from using legacy dropdown to using the new Header
Also fixed multi linting errore
> Refactor(Header) switch to using new menu

- .storybook/preview.js
- packages/netlify-cms-core/src/bootstrap.js
- packages/netlify-cms-ui-default/src/AppBar/AppBar.jsx
- packages/netlify-cms-ui-default/src/AppBar/story.jsx
- packages/netlify-cms-ui-default/src/AppWrap/AppWrap.jsx
- packages/netlify-cms-ui-default/src/HOC/withUIContext.jsx
> fix(ui): fix storybook and unit tests

- packages/netlify-cms-backend-github/src/API.ts
Fixes https://github.com/netlify/netlify-cms/issues/3407
> fix: update repo owner from GitHub API to match casing

- .storybook/preview.js
- packages/netlify-cms-ui-default/src/AppWrap/AppWrap.jsx
- packages/netlify-cms-ui-default/src/Icon/Icon.jsx
- packages/netlify-cms-ui-default/src/Icon/icons/Workflow.jsx
- packages/netlify-cms-ui-default/src/NavigationMenu/NavigationMenu.jsx
- packages/netlify-cms-ui-default/src/NavigationMenu/NavigationMenuItem.jsx
- packages/netlify-cms-ui-default/src/NavigationMenu/story.jsx
This PR adds props to allow the NavigationMenu to render different sections.
> refactor(navigation): rework navigation menu to accept list of sections

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
**Summary**
fixes #3222 
**Test plan**
> fix(core): custom widget validate bug in EditorControlPane

- website/content/docs/widgets/boolean.md
Fixes https://github.com/netlify/netlify-cms/issues/3311
> docs(widgets-boolean): clarify default value usage

- packages/netlify-cms-backend-bitbucket/src/API.ts
- packages/netlify-cms-backend-github/src/API.ts
- packages/netlify-cms-backend-gitlab/src/API.ts
> fix: missing workflow timestamp

- packages/netlify-cms-core/src/bootstrap.js
- packages/netlify-cms-core/src/components/UI/ErrorBoundary.js
An attempt to improve all of those empty issues we've been getting
> chore: populate error boundry issue with relevant values

- cypress/integration/editorial_workflow_spec_test_backend.js
- packages/netlify-cms-backend-test/src/implementation.ts
- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
- packages/netlify-cms-core/src/components/Workflow/Workflow.js
- packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js
- packages/netlify-cms-core/src/components/Workflow/WorkflowList.js
- packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
- packages/netlify-cms-core/src/constants/configSchema.js
- website/content/docs/configuration-options.md
Fixes https://github.com/netlify/netlify-cms/issues/1298
Added a test with `publish: false` to the test backend
> feat: add publish configuration option to collections

- packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
- packages/netlify-cms-core/src/actions/__tests__/editorialWorkflow.spec.js
- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
Cleanup up some prop types warnings and some tests warnings
> chore: cleanup warnings

- packages/netlify-cms-core/src/constants/fieldInference.js
Replaces https://github.com/netlify/netlify-cms/pull/3480 with fixed formatting
> Feat: add logo to inference for thumbnails

- packages/netlify-cms-core/src/actions/entries.ts
> fix: media files when duplicating entry

- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
Fixes https://github.com/netlify/netlify-cms/issues/3487
> fix: don't override empty public folder

- .github/workflows/nodejs.yml
This is required for cross OS support
> ci: fix yarn caching

- functions/publish.js
> chore: improve publish function logs

- packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
- packages/netlify-cms-core/src/lib/formatters.ts
Fixes https://github.com/netlify/netlify-cms/issues/3470
> fix: sanitize dots in path collection config

- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/reducers/collections.ts
Fixes https://github.com/netlify/netlify-cms/issues/3483
> fix: set default public_folder on files and fields

- packages/netlify-cms-backend-proxy/src/implementation.ts
Related to https://github.com/netlify/netlify-cms/issues/3526
> fix(backend-proxy): fix error reporting

- packages/netlify-cms-locales/src/pl/index.js
Replaces https://github.com/netlify/netlify-cms/pull/3528
> Fix(locale): Polish translation update

- website/content/docs/jekyll.md
**Summary**
A few typos fixed.
**Test plan**
N/A
> Update Docs: Guides “jekyll”

- packages/netlify-cms-widget-file/src/withFileControl.js
Fixes https://github.com/netlify/netlify-cms/issues/3537
> fix(widget-image): multiple image support

- website/content/docs/examples.md
**Summary**
Adding new Netlify CMS based JAMStack website built with GatsbyJS
**Test plan**
Demo URL: https://delog-w3layouts.netlify.com/
Source: https://github.com/W3Layouts/gatsby-starter-delog
> Update Docs: Quick Start “examples”

- packages/netlify-cms-backend-github/src/API.ts
Better handle edge cases where we can't infer the entry from the PR diff
> fix(backend-github): add fallback for diff errors/warnings

- packages/netlify-cms-core/src/actions/config.js
Fixes https://github.com/netlify/netlify-cms/issues/3566
> fix: allow unlimited alias count

- packages/netlify-cms-core/src/actions/editorialWorkflow.ts
- packages/netlify-cms-core/src/actions/entries.ts
- packages/netlify-cms-core/src/components/Editor/Editor.js
> fix: duplicate entry

- packages/netlify-cms-core/src/actions/config.js
> fix: enable merge option for yaml parser

- packages/netlify-cms-locales/src/en/index.js
- packages/netlify-cms-ui-default/src/styles.js
- packages/netlify-cms-widget-datetime/src/DateTimeControl.js
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/3399
Added a now button under the datepicker
**Test plan**
> Feat(widget-datetime): add now to datepicker

- packages/netlify-cms-widget-list/src/ListControl.js
> fix: list widget validation after sort

- packages/netlify-cms-locales/src/ja/index.js
**Summary**
- add missing Japanese locale
> fix: locale japanese

- packages/netlify-cms-locales/src/pt/index.js
> Fix PT language

- .github/workflows/nodejs.yml
- setupTestFramework.js
Fixes https://github.com/netlify/netlify-cms/issues/3655
> test: fix unit tests on windows machines

- jest.config.js
- packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js
- packages/netlify-cms-widget-list/src/ListControl.js
- packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
- packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
Context:
https://github.com/netlify/netlify-cms/pull/3607
https://github.com/netlify/netlify-cms/pull/3616
https://github.com/netlify/netlify-cms/pull/3675
Added some tests to the list widget to facilitate recent contributions.
> Test(widgets-list): add tests

- website/content/docs/hugo.md
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/3676
Update docs to so preview sites will use relative links. Changed from .PermaLink to 
.RelPermaLink
**Test plan**
Changed from .PermaLink to  .RelPermaLink in both codeblock and description. 
> Update Docs: Guides “hugo”

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/sv/index.js
**Summary**
Add Swedish locale 🇸🇪 
> feat(locale): add 'sv' locale

- packages/netlify-cms-widget-date/src/DateControl.js
Replaces https://github.com/netlify/netlify-cms/pull/3703 (could not push to that branch)
> fix(date): allow default value to Date field

- packages/netlify-cms-core/src/backend.ts
- packages/netlify-cms-core/src/components/Editor/Editor.js
> fix: delete new entry backup

- packages/netlify-cms-backend-bitbucket/src/git-lfs-client.ts
- packages/netlify-cms-backend-git-gateway/src/__tests__/GitHubAPI.spec.js
- packages/netlify-cms-backend-git-gateway/src/implementation.ts
- packages/netlify-cms-backend-git-gateway/src/netlify-lfs-client.ts
- packages/netlify-cms-backend-github/src/__tests__/API.spec.js
- packages/netlify-cms-backend-github/src/__tests__/implementation.spec.js
- packages/netlify-cms-backend-github/src/implementation.tsx
- packages/netlify-cms-backend-proxy/src/implementation.ts
- packages/netlify-cms-core/src/integrations/providers/algolia/implementation.js
- packages/netlify-cms-core/src/integrations/providers/assetStore/implementation.js
- packages/netlify-cms-lib-util/src/unsentRequest.js
**Summary**
Fixes #3605
**Test plan**
`yarn test` failed 3 tests because the tests now expect different outcomes.
> chore: timeout-requests closes #3605

- packages/netlify-cms-widget-code/src/CodeControl.js
Fixes https://github.com/netlify/netlify-cms/issues/3725
Not sure what had changed (probably a dependency update).
> fix(widget-code): change dynamic import to require

- packages/netlify-cms-locales/src/es/index.js
This may have to be done for all the other languages.
> Add translation for "download" in mediaLibraryModal

- packages/netlify-cms-widget-relation/src/RelationControl.js
- packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Fix a bug introduced by me here https://github.com/netlify/netlify-cms/pull/3754/files/c4b1424b68448f3af3567d3817bf5cd165330ce2#diff-1c6e2a499213935b7c1b04dbb4e1ca1c
> fix(widget-relation): fix displayFields default

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/nb_no/index.js
- packages/netlify-cms-locales/src/nn_no/index.js
**Summary**
Added support for the two offical written forms of Norwegian, [bokmål and nynorsk](https://en.wikipedia.org/wiki/Norwegian_language#Bokm%C3%A5l_and_Nynorsk). :norway: 
**Why two written forms?** 
To make a long story short  "bokmål" (literally meaning "book tongue") is the most widely used written form, and basically a "fork" of Danish :denmark: from when they ruled over Norway (before they got carried away with pastry and beer, as they tend to do, and cut us loose). Although pretty similar (at least in recent years), nynorsk (literally meaning "new norwegian") uses more words and phrases from our many dialects (you can literally hear people's way of speaking change as you _walk_ from place to place). Fun-fact: Some of them are so widely different we can't even understand each …
> feat(lang): add norwegian

- package.json
- yarn.lock
See https://github.com/cypress-io/cypress/pull/7366
> chore(deps): update cypress

- packages/netlify-cms-core/package.json
- packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
- packages/netlify-cms-core/src/constants/configSchema.js
Related to https://github.com/netlify/netlify-cms/issues/3803
> fix(config): validate unique fields names under the same level

- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js
- packages/netlify-cms-core/src/constants/configSchema.js
- website/content/docs/beta-features.md
Fixes https://github.com/netlify/netlify-cms/issues/3782
> feat: add allowed_hosts support in local_backend

- website/content/docs/beta-features.md
Fixes https://github.com/netlify/netlify-cms/issues/3769
> docs: update manual init docs

- packages/netlify-cms-widget-relation/src/RelationControl.js
- packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Fixes https://github.com/netlify/netlify-cms/issues/3709
Replaces https://github.com/netlify/netlify-cms/pull/3834
> fix(widget-relation): keep referenced field type when not using templates

- packages/netlify-cms-widget-markdown/src/MarkdownControl/__tests__/__snapshots__/parser.spec.js.snap
- packages/netlify-cms-widget-markdown/src/serializers/index.js
- packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js
Fixes https://github.com/netlify/netlify-cms/issues/3755
Tagging @erquhart for feedback
> fix(widget-markdown): don't strip new lines from text nodes

- packages/netlify-cms-widget-markdown/package.json
- packages/netlify-cms-widget-markdown/src/serializers/__tests__/index.spec.js
- yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/3727
See https://github.com/rehypejs/rehype-minify/issues/19
> fix: update rehype-remark

- packages/netlify-cms-widget-markdown/package.json
- yarn.lock
Related https://github.com/netlify/netlify-cms/issues/3840
> chore(deps): remove monaco editor unused deps

- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
- packages/netlify-cms-app/package.json
- packages/netlify-cms-core/package.json
- packages/netlify-cms/package.json
Testing to see if this speeds up the build
> build: increase webpack memory

- packages/netlify-cms-backend-bitbucket/src/API.ts
- packages/netlify-cms-backend-git-gateway/src/implementation.ts
- packages/netlify-cms-backend-github/src/API.ts
- packages/netlify-cms-backend-gitlab/src/API.ts
Fixes https://github.com/netlify/netlify-cms/issues/3881
> feat(backend-gitgateway): improve deploy preview visibility

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/th/index.js
**Summary**
Add Thai (th) locale to the list of locales
**Test plan**
Not sure if this is necessary to test?
A cat in front of my house.
> feat(lang): add 'th' locale

- packages/netlify-cms-core/src/constants/configSchema.js
Fixes https://github.com/netlify/netlify-cms/issues/1035
> fix(schema): enforce files and collections names uniqueness

- packages/netlify-cms-core/src/reducers/collections.ts
Fixes https://github.com/netlify/netlify-cms/issues/3920
> fix(editor-media-lib): handle duplicate media folders

- packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
Replaces https://github.com/netlify/netlify-cms/pull/3808 (thanks @BA1RY, @magomimmo and @barthc!)
Fixes https://github.com/netlify/netlify-cms/issues/3744
> feat: pattern validation on blur event

- packages/netlify-cms-widget-number/src/schema.js
Fixes https://github.com/netlify/netlify-cms/issues/3924
> fix(widget-number): use number instead of integer in schema

- .github/workflows/create-release.yml
**Summary**
Create GitHub release after each new version tag to properly support GitHub _watch releases only_ feature.
**Test plan**
N/A
> CI/ Simple workflow to create GitHub release

- packages/netlify-cms-core/src/__tests__/backend.spec.js
- packages/netlify-cms-core/src/backend.ts
Fixes https://github.com/netlify/netlify-cms/issues/3907
> fix: search file collections using top level file fields

- dev-test/backends/test/index.html
- dev-test/index.html
Pad creation of date days to match ISO format
> fix(cms-demo): pad days when creating test-repo date field

- packages/netlify-cms-ui-default/src/MediaDialog/MediaDialog.jsx
- packages/netlify-cms-ui-default/src/MediaDialog/index.js
- packages/netlify-cms-ui-default/src/MediaDialog/story.jsx
**Summary**
This PR adds the `MediaDialog` component. This PR is not to be approved as it still has bugs.
**Test plan**
Hey @austincondiff, I'm having trouble understanding how the sizing is working for `ThumbnailGrid`. Take a look and see. When I reload the component, the size of children elements changes on the same view screen. Any ideas?
> feat: added-media-dialog-component

- website/content/docs/widgets/relation.md
Adds an example for referencing a file collection and lists via wildcards.
> docs(widget-relation): improve docs

- dev-test/backends/test/index.html
- dev-test/index.html
> chore: fix demo site

- packages/netlify-cms-core/src/components/Editor/Editor.js
- packages/netlify-cms-core/src/components/Editor/EditorInterface.js
- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Fixes https://github.com/netlify/netlify-cms/issues/3994
> fix(editor): pass back link to editor toolbar

- packages/netlify-cms-locales/src/fr/index.js
**Summary**
French translation of the interface was a bit behind, so I updated it!
> feat: update locale (fr)

- packages/netlify-cms-backend-github/src/API.ts
Fixes https://github.com/netlify/netlify-cms/issues/4018
> fix(backend-github): use workflow branch when listing files to move

- packages/netlify-cms-core/package.json
- packages/netlify-cms-core/src/components/Collection/Entries/Entries.js
- packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
- yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/2132
Fixes https://github.com/netlify/netlify-cms/issues/3950
Fixes https://github.com/netlify/netlify-cms/issues/3696
> fix(entries-pagination): keep loading pages until entries are available

- website/content/docs/beta-features.md
- website/static/admin/config.yml
**Summary**
Updates CMS so entries show in the admin after recent re-org.
> chore: update CMS config

- packages/netlify-cms-widget-relation/src/RelationControl.js
Fixes https://github.com/netlify/netlify-cms/issues/4024
Prepend the existing value search to the other options instead of just showing a single option when there is an existing value.
Problem also visible here https://cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things
> fix(widget-relation): prepend initial value search to options

- .github/workflows/publish.yml
- package.json
Follow up on https://github.com/netlify/netlify-cms/pull/4029
> ci: fix publish script

- website/content/docs/nextjs.md
**Summary**
Fix spelling inside the NextJS example setup
> Spelling Fix

- packages/netlify-cms-widget-relation/src/RelationControl.js
Fixes https://github.com/netlify/netlify-cms/issues/4061
> fix(widget-relation): handle initialization when multiple=true

- packages/netlify-cms-locales/src/ja/index.js
**Summary**
update Japanese locale file.
> feat: update locale (ja)

- .github/workflows/create-release.yml
**Summary**
By some reason push event is not being triggered on version tags (Lerna implementation? :thinking: ), so I'm trying with `on.create` event now, then checking tag name on job level condition.
Related to https://github.com/netlify/netlify-cms/pull/3930
**Test plan**
N/A
> CI: fix create release workflow

- cypress/integration/markdown_widget_link_spec.js
- cypress/support/commands.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/Link.js
Fixes https://github.com/netlify/netlify-cms/issues/4074
> fix(widget-markdown): properly check for selection when inserting links

- website/content/docs/nextjs.md
**Summary**
Typo error. 
I modified the sentence to make it more readable.
**Test plan**
> Update Docs: Guides “nextjs”

- website/.markdownlint.json
- website/content/docs/git-gateway-backend.md
- website/content/docs/github-backend.md
- website/netlify.toml
- website/package.json
- website/yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/3268
> docs: fix indentation of code blocks in lists

- packages/netlify-cms-core/index.d.ts
> Add allow_add field (which is valid for list widgets)

- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
**Summary**
Added ID-attribute to the Preview Pane Frame to better target the iFrame in React.
**Test plan**
no idea how to test or if necessary
> Added ID-attribute to the Preview Pane Frame

- packages/netlify-cms-locales/src/ca/index.js
Changed literal translations into more realistic/used words. Also detected a typo error.
**Summary**
**Test plan**
> Update catalan translation

- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
- website/content/docs/customization.md
Fixes https://github.com/netlify/netlify-cms/issues/4142
> feat(preview-pane): pass iframe window and document instances as props

- packages/netlify-cms-widget-relation/src/RelationControl.js
- packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
> fix(widget-relation): set initial metadata value

- .github/workflows/publish.yml
Increase timeout to 40 minutes
> ci(publish): increase timeout

- packages/netlify-cms-widget-relation/src/RelationControl.js
**Summary**
This PR fixes #4185. See the issue for further details.
**Test plan**
> fix(widget-relation): handle optional configuration

- .github/workflows/publish.yml
- scripts/revert_publish.sh
> chore: add revert failed publish command

- packages/netlify-cms-locales/src/de/index.js
Added missing German translations for newly added locale strings
added in #2959
**Test plan**
Compiled and checked that the site still works and shows the new translations
> Added missing German translations

- packages/netlify-cms-locales/src/zh_Hant/index.js
**Summary**
Update the translation with newly translated strings and edit zh_hans (Chinese Simplified) strings to zh_hant.
**Test plan**
> fix(locale): update zh_Hant translation

- packages/netlify-cms-locales/src/th/index.js
Summary
Update Thai (th) locale to the list of locales
Test plan
Not sure if this is necessary to test?
A picture of a cute animal (not mandatory but encouraged)
My cat
> Update 'th' locale

- dev-test/config.yml
- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/constants/configSchema.js
- website/content/docs/configuration-options.md
**Summary**
Closes #1289 
**Test plan**
> #1289: allow to disable editor preview for all collections

- website/content/docs/configuration-options.md
Follow up on https://github.com/netlify/netlify-cms/pull/4414
> fix(docs): add missing docs about file preview config

- packages/netlify-cms-locales/src/th/index.js
**Summary**
Fix 'th' translation for #4421
> Fix 'th' locale translation

- packages/netlify-cms-locales/src/en/index.js
- packages/netlify-cms-locales/src/zh_Hant/index.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
- packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/visual.js
relates to #2959 and #3193
**Summary**
Remove remaining hard coded strings in the markdown widget and add corresponding zh_Hant translation.
Includes:
Titles of the toolbar buttons
The prompt after clicking link button
**Test plan**
Tested in test backend
> fix(locale): remove hard coded strings

- packages/netlify-cms-lib-widgets/src/index.ts
- packages/netlify-cms-lib-widgets/src/validations.ts
- packages/netlify-cms-widget-list/src/ListControl.js
- packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js
- packages/netlify-cms-widget-list/src/schema.js
- packages/netlify-cms-widget-select/package.json
- packages/netlify-cms-widget-select/src/SelectControl.js
- website/content/docs/widgets/list.md
**Summary**
Fixes #1480 
I revived the PR #1527 by @Dammmien ,  that had been marked abandoned. Instead of prepopulating the list with empty elements I added a validation for min/max, because adding entries would not be feasible with variable types.
**Test plan**
ran yarn test
Unclear if additional tests should be written
> 1480 min max

- packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js
- packages/netlify-cms-lib-widgets/src/stringTemplate.ts
- website/content/docs/beta-features.md
**Summary**
Support filters for template strings 
fixes #3677
template string can now contain additional filters like {{title | upper}}-{{publishDate | date('YYYY-MM')}}
- supports upper, lower and date filter
- registering custom functions is not yet implemented
**Test plan**
- added unit tests
> Support filters for template strings #3677

- website/content/docs/nuxt.md
**Summary**
According to https://content.nuxtjs.org/displaying the <nuxt-content> component will only work on Markdown files. Having json files will result in no output. Defaulting to Markdown files will result in correct rendered output.
> Documentation Update

- website/content/docs/configuration-options.md
Follow up on https://github.com/netlify/netlify-cms/pull/4486
> fix(docs-view-groups): add missing docs

- website/static/_redirects
Update the slack link. Related to https://github.com/netlify/netlify-cms/issues/3203#issuecomment-722745285
> fix(website): update slack link

- packages/netlify-cms-widget-list/src/ListControl.js
- packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap
> fix: list markdown widgets

- packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
- packages/netlify-cms-core/src/lib/registry.js
**Summary**
Fixes #4602 
Removed the automatic return after the first handler
Return data is progressively saved after each handler executes
**Test plan**
`yarn test:unit` - all tests pass
Obligatory cute red panda
> fix(events): allow multiple event handlers to execute

- packages/netlify-cms-core/index.d.ts
**Summary**
Types for boolean and color widget were missing
**Test plan**
I tested it locally in my project
> fix(typings): add types for boolean and color widgets

- packages/netlify-cms-core/src/actions/status.ts
- packages/netlify-cms-core/src/backend.ts
- packages/netlify-cms-core/src/reducers/auth.ts
- packages/netlify-cms-core/src/reducers/status.ts
- packages/netlify-cms-core/src/types/immutable.ts
- packages/netlify-cms-core/src/types/redux.ts
**Summary**
Make 'status' state slice more typesafe by providing proper StatusAction type
**Test plan**
Tests are not needed
> fix(typings): make 'status' state slice more typesafe

- packages/netlify-cms-locales/src/index.js
- packages/netlify-cms-locales/src/lt/index.js
Replaces https://github.com/netlify/netlify-cms/pull/4758 with fixed formatting
> feat(locales): add Lithuanian translation

- packages/netlify-cms-locales/src/hr/index.js
- packages/netlify-cms-locales/src/index.js
> feat(locales): add Croatian translation

- packages/netlify-cms-core/index.d.ts
fixes #4782
this is my first contribution, would love to get some review on it. i can open a code review on the specific points
**Summary**
adds `registerEventListener` to CMS interface in netlify-cms-core
**Test plan**
`yarn test` output (truncated):
```
Test Suites: 2 skipped, 73 passed, 73 of 75 total
Tests:       650 skipped, 922 passed, 1572 total
Snapshots:   89 passed, 89 total
Time:        27.788 s
Ran all test suites.
✨  Done in 56.91s.
```
my cat, winston :)
> fix(typing): add `registerEventListener` to CMS interface

- packages/netlify-cms-locales/src/es/index.js
Fixes some typos in the Spanish locales.
> fix(locale): fix typos in es locales

- packages/netlify-cms-core/src/actions/config.js
- packages/netlify-cms-core/src/bootstrap.js
**Summary**
Decouple config actions from auth actions by moving authenticateUser action call to bootstrap
**Test plan**
No testing needed
> refactor: decouple config actions from auth actions

- website/content/docs/gitlab-backend.md
**Summary**
Hello team! I work at GitLab and a user [opened an issue](https://gitlab.com/gitlab-org/gitlab/-/issues/299240) following some integration trouble with netlify-cms so I'm opening this PR to update the documentation.
The OAuth implicit flow doesn't work anymore when the OAuth application is configured as "confidential". I've also updated some terms that have changed in the documentation (web application flow -> authorization code flow)
**Test plan**
Documentation change only
> Update GitLab OAuth documentation

- packages/netlify-cms-lib-util/src/API.ts
Fixes https://github.com/netlify/netlify-cms/issues/4521 (the fix is to report a proper error).
We're calling `.json` when the status code is 403 which prevents the caller to read the response again.
> fix(backend): allow calling 'json' again on 403 failure

- packages/netlify-cms-widget-markdown/package.json
- packages/netlify-cms-widget-markdown/src/MarkdownPreview.js
- packages/netlify-cms-widget-markdown/src/__tests__/__snapshots__/renderer.spec.js.snap
- packages/netlify-cms-widget-markdown/src/__tests__/renderer.spec.js
- website/content/docs/widgets/markdown.md
- yarn.lock
Replaces https://github.com/netlify/netlify-cms/pull/4873 as I can't push to that branch
Fixes #4099
> fix(security-markdown-widget): allow sanitization of preview content

- packages/netlify-cms-widget-file/package.json
- packages/netlify-cms-widget-file/src/withFileControl.js
- yarn.lock
closes [#2701](https://github.com/netlify/netlify-cms/issues/2701)
**Summary**
Hello! First of all, big thanks to the maintainers and contributors for this massive achievement !
To the best of my knowledge, there is currently no way to re-order images when using the widget-image (when combined with the Cloudinary media extension for instance to enable multiple selection). I see this issue has already been raised [here](https://github.com/netlify/netlify-cms/issues/2701), and I'm surprised it didn't get a lot of votes, as it seems to me that it's quite an important feature for all websites that display some sorts of photo galleries. Personnally, this is unfortunately kind of a showstopper for some projects, typically when building static websites for artists or photographers: these folks …
> feat(widget-image): enable images ordering

- packages/netlify-cms-backend-gitlab/src/API.ts
Attempted fix for https://github.com/netlify/netlify-cms/issues/4890
> fix(backend-gitlab): increase rebase timeout

- renovate.json
**- Summary**
Renovate bot no longer uses the term `masterIssue` in their docs, it's now called `dependencyDashboard`.
If you want to make changes to your dashboard and search for `masterIssue` you're not going to find any references to that term in the Renovate docs.
This PR ensures you're using a current term.
The functionality does not change, you'll keep your Dependency Dashboard just the way it is now.
If you don't want this PR, you can just close it, as the Renovate bot already "massages" any old config terms to newer terms behind your back anyways. 😄 
Reference: https://docs.renovatebot.com/configuration-options/#dependencydashboard
I've done this migration for other repositories, and they had no problems with their dashboard. 😄  …
> chore: migrate masterIssue to dependencyDashboard

- website/static/_redirects
> chore: update slack link

- packages/netlify-cms-locales/src/ru/index.js
Synced Russian locale with current state of https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-locales/src/en/index.js
> chore(locale): update ru locale

- packages/netlify-cms-core/src/formats/__tests__/frontmatter.spec.js
- packages/netlify-cms-core/src/formats/frontmatter.js
details in issue
https://github.com/netlify/netlify-cms/issues/4908#issue-798404748
> fix: json FM ending with object parse error

- packages/netlify-cms-locales/src/fr/index.js
**Summary**
Better translation for multilingual editor + missing question dot.
**Test plan**
/
> ref(locale-fr): change translation + missing '?'

- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.js
**Summary**
Another atomic PR to make merging of https://github.com/netlify/netlify-cms/pull/4776 easier
**Test plan**
> refactor: remove ImmutableJS from applyDefaults function

- cypress/run.js
- packages/netlify-cms-core/src/actions/config.js
Follow up on https://github.com/netlify/netlify-cms/pull/4940 and https://github.com/netlify/netlify-cms/pull/4924
> fix: convert config before passing to resolveBackend

- .eslintrc.js
- packages/netlify-cms-core/index.d.ts
- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.ts
- packages/netlify-cms-core/src/types/global.d.ts
- packages/netlify-cms-core/src/types/redux.ts
**Summary**
Convert config actions to TypeScript
**Test plan**
> refactor: convert config actions to TypeScript

- website/content/docs/hugo.md
**Summary**
Update Hugo docs to address https://github.com/netlify/netlify-cms/issues/4976
**Test plan**
No testing needed
> fix(docs): update Hugo docs

- renovate.json
> chore: disable renovate rollbackPrs

- packages/netlify-cms-core/src/actions/entries.ts
Fixes https://github.com/netlify/netlify-cms/issues/4529
Fixes https://github.com/netlify/netlify-cms/issues/5091
> fix: field based media_folder

- packages/netlify-cms-core/package.json
- packages/netlify-cms-core/src/bootstrap.js
- packages/netlify-cms-core/src/reducers/combinedReducer.ts
- packages/netlify-cms-core/src/redux/index.ts
- yarn.lock
Summary
Remove connected-react-router as it's not being used anywhere [fixes #4756]
Test plan
Just run current tests
> chore: remove connected-react-router

- packages/netlify-cms-core/src/actions/mediaLibrary.ts
- packages/netlify-cms-core/src/reducers/mediaLibrary.ts
- packages/netlify-cms-core/src/types/redux.ts
**Summary**
Proper type for media library action
**Test plan**
> fix: proper type for media library action

- cypress/plugins/proxy.js
- dev-test/backends/proxy/config.yml
- package.json
- yarn.lock
Our tests have [started failing](https://github.com/netlify/netlify-cms/actions/runs/653680382) since https://github.com/netlify/netlify-cms/pull/5121 was merged. 
This is a PR to fix the tests.
> test(e2e): use predictable branch name in proxy backend tests

- packages/netlify-cms-locales/src/nl/index.js
I added some missing locales. I ran `yarn:format` and tested the locales locally.
> feat: update locale (nl)

- packages/netlify-cms-core/src/actions/__tests__/entries.spec.js
- packages/netlify-cms-core/src/actions/entries.ts
- packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js
- packages/netlify-cms-widget-list/src/ListControl.js
- website/content/docs/widgets/list.md
**Summary**
Fixes #5016 
Allows setting any array as a default value for list widgets
* Updated list widget docs
**Test plan**
Run `npm run test`
Run `npm run build`
> fix: allow any default list as default value for list widgets

- packages/netlify-cms-locales/src/ca/index.js
Mainly added missing translations but also fixed a typo and some incongruences between verb tenses.
> fix(locale-ca): update Catalan translation

- packages/netlify-cms-core/src/components/App/App.js
- packages/netlify-cms-core/src/components/Editor/Editor.js
- packages/netlify-cms-core/src/components/Workflow/Workflow.js
- packages/netlify-cms-core/src/reducers/__tests__/globalUI.js
- packages/netlify-cms-core/src/reducers/globalUI.ts
- packages/netlify-cms-core/src/types/redux.ts
Alright, this is a small one :)
**Summary**
GlobalUI refactoring:
1. Convert to TS
2. Replace immutable with immer
**Test plan**
Current tests
> chore: refactor globalUI

- website/content/docs/external-oauth-clients.md
> Update Docs: Account “external-oauth-clients”

- packages/netlify-cms-app/package.json
Follow up on https://github.com/netlify/netlify-cms/pull/5265
Related to https://github.com/netlify/netlify-cms/issues/5221
> fix: add missing code codemirror deps

- babel.config.js
- packages/netlify-cms-app/package.json
#5087 broke some stuff, see https://github.com/netlify/netlify-cms/issues/5266 and https://github.com/netlify/netlify-cms/issues/5221.
Going to revert until I figure this out.
Fixes https://github.com/netlify/netlify-cms/issues/5266
> fix: Revert "fix: generate esm correctly (#5087)"

- packages/netlify-cms-core/src/formats/frontmatter.ts
See https://github.com/netlify/netlify-cms/pull/5273#discussion_r616545323
> refactor: use plain object instead of enum

- packages/netlify-cms-locales/src/sv/index.js
**Summary**
Updates the Swedish locale with missing keys.
```
__
(___()'`;
/,    /`
\\"--\\
```
> fix(locale): add missing keys to 'sv' locale

- website/content/docs/git-gateway-backend.md
Just a broken link fix
Cute animal:
> Fix broken link

- packages/netlify-cms-core/index.d.ts
**Summary**
Fixes an issue from #4782 where the `handler` type should be a function, not an object. This was pointed out in [this comment](https://github.com/netlify/netlify-cms/issues/4782#issuecomment-835721211). 
**Test plan**
> fix(typing): type for CmsEventListener handler property

- packages/netlify-cms-core/src/actions/__tests__/config.spec.js
- packages/netlify-cms-core/src/actions/config.ts
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/5386
**Test plan**
Add a new test
🐶
> fix(config): allow empty public folder for collection,file,field

- packages/netlify-cms-widget-code/package.json
- packages/netlify-cms-widget-markdown/package.json
- packages/netlify-cms-widget-relation/package.json
- packages/netlify-cms-widget-relation/src/RelationControl.js
- packages/netlify-cms-widget-select/package.json
- packages/netlify-cms-widget-select/src/SelectControl.js
- yarn.lock
Replaces https://github.com/netlify/netlify-cms/pull/5392
> fix(deps): update react-select to v3

- packages/netlify-cms-core/index.d.ts
**Summary**
Adds `hide` option to `CmsCollection` type.
**Test plan**
none
> chore: add hide option to CmsCollection type

- renovate.json
Disable some major version updates we need to perform manually
> chore(deps): ignore some packages

- packages/netlify-cms-core/src/components/Collection/Collection.js
- packages/netlify-cms-core/src/components/Collection/CollectionControls.js
- packages/netlify-cms-core/src/components/Collection/Sidebar.js
- packages/netlify-cms-core/src/components/Collection/__tests__/Sidebar.spec.js
- packages/netlify-cms-core/src/components/Collection/__tests__/__snapshots__/Sidebar.spec.js.snap
- website/content/docs/configuration-options.md
**Summary**
issue #5501 
Adding `search: false` to config.yml will disable the search and filters which can sometimes cause the CMS to make too many API calls and hit the limit
**Test plan**
`yarn test` succeeded
> 5501 make search optional

- packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
- packages/netlify-cms-core/src/components/Editor/__tests__/Editor.spec.js
- packages/netlify-cms-core/src/components/Editor/__tests__/EditorToolbar.spec.js
- packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
**Summary**
fixes #5554 
This button doesn't work if you are an open authoring user, I have hid it. It will still work for normal users.
**Test plan**
**Figure: Hidden delete button**
> Feat: hide delete entry if open authoring

- .github/PULL_REQUEST_TEMPLATE.md
Add a checklist to the PR template
> docs(pr-template): add checklist

- cypress/fixtures/BitBucket Backend Editorial Workflow__can change status on and publish multiple entries.json
- cypress/fixtures/BitBucket Backend Editorial Workflow__can change workflow status.json
- cypress/fixtures/BitBucket Backend Editorial Workflow__can create an entry.json
- cypress/fixtures/BitBucket Backend Editorial Workflow__can delete an entry.json
- cypress/fixtures/BitBucket Backend Editorial Workflow__can publish an editorial workflow entry.json
- cypress/fixtures/BitBucket Backend Editorial Workflow__can update an entry.json
- cypress/fixtures/BitBucket Backend Editorial Workflow__can update workflow status from within the editor.json
- cypress/fixtures/BitBucket Backend Media Library - Large Media__can publish entry with image.json
- cypress/fixtures/BitBucket Backend Media Library - Large Media__can save entry with image.json
- cypress/fixtures/BitBucket Backend Media Library - Large Media__should not show draft entry image in global media library.json
- cypress/fixtures/BitBucket Backend Media Library - Large Media__should show published entry image in global media library.json
- cypress/fixtures/BitBucket Backend Media Library - Large Media__should show published entry image in grid view.json
- cypress/fixtures/BitBucket Backend Media Library - REST API__can publish entry with image.json
- cypress/fixtures/BitBucket Backend Media Library - REST API__can save entry with image.json
- cypress/fixtures/BitBucket Backend Media Library - REST API__should not show draft entry image in global media library.json
- cypress/fixtures/BitBucket Backend Media Library - REST API__should show published entry image in global media library.json
- cypress/fixtures/BitBucket Backend Media Library - REST API__should show published entry image in grid view.json
- cypress/integration/common/spec_utils.js
- cypress/integration/editorial_workflow_spec_gitlab_backend.js
- cypress/integration/simple_workflow_spec_proxy_git_backend.js
Related to https://github.com/netlify/netlify-cms/pull/5611
Apparently if you stop the runner on the first retry the test suite succeeds.
> test(e2e): only stop Cypress runner on last retry

- website/content/docs/collection-types.md
**Summary**
I spent too much time moving around folders/files in my project before realizing that the Nested Collections feature existed. I could have use the search function to find it listed under Beta Features, but I don't think that this should be a requirement. I add a section at the bottom of the "Folder Collections" section that discusses this important beta feature.
As a larger question, when do features move out of beta?
**Test plan**
N/A
**Checklist**
> Link to nested collections feature

- .github/workflows/fossa.yml
**Summary**
Fixes fossa scanning
**Test plan**
See status checks
**Checklist**
🐩
> chore: fix fossa

- packages/netlify-cms-locales/src/fr/index.js
**Summary**
List buttons are now translatable (https://github.com/netlify/netlify-cms/pull/5679), I add the translation in French.
> ref(locale-fr): Add FR translation for list buttons

- packages/netlify-cms-locales/src/ja/index.js
**Summary**
update locale ja
**Test plan**
nothing
**Checklist**
> feat: update locale ja

- packages/netlify-cms-locales/src/pl/index.js
**Summary**
Since the admin panel in Polish were written in a mix of Polish an English,
folowing the index.js file for en locale I provided the translations missing from the locales > pl > index.js file.
**Test plan**
**Checklist**
> update index.js pl

- packages/netlify-cms-widget-date/package.json
- packages/netlify-cms-widget-datetime/package.json
- yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/5800
> fix(deps): update react-datetime

- packages/netlify-cms-core/src/lib/__tests__/registry.spec.js
- packages/netlify-cms-core/src/lib/registry.js
**Summary**
fix for https://github.com/netlify/netlify-cms/issues/5753
**Test plan**
registry test
**Checklist**
> feat: change invoke CMS Events to throw Error

- packages/netlify-cms-locales/src/pt/index.js
**Summary**
A update to missing translations from pt locale. 
**Test plan**
None needed.
**Checklist**
I still don't have a pet, so I will owe one for now.
> feat: add missing pt locale translations

- packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js
- website/yarn.lock
- yarn.lock
This reverts commit 8c5531dd4fbf3a3fcf4b509779fa6f3b18a41945.
Which broke our tests in https://github.com/netlify/netlify-cms/pull/5987
> Revert "chore(deps): lock file maintenance (#5987)"

- packages/netlify-cms-core/index.d.ts
**Summary**
Fix #6017
**Test plan**
**Checklist**
> feat: add generic type support for CmsWidget and CmsWidgetParam

- yarn.lock
The yarn file is out of sync due to a renovate PR, this updates it
> chore: sync yarn

- website/content/docs/beta-features.md
Follow up on https://github.com/netlify/netlify-cms/pull/6059
> fix(docs-beta-features): fix Typo in comment

- packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js
Closes #5794 
**Summary**
Handles '*' + space or '-' + space to add bullet points
**Test plan**
**Checklist**
> feat: use keyboard shortcuts to insert bullet points

- packages/netlify-cms-locales/src/hu/index.js
I would to have the button text translated to hungarian in the list widget also.
"Add" -> "Új"
"Add type" -> "Új típus"
I did not tested it, sorry. I just edited the file in github, so i had no opportunity to test it.
I made the changes based on this thread: https://github.com/netlify/netlify-cms/pull/5686/commits/94ff57e45acb1d57caf6925a4d9dfd128ef51a8f
**Checklist**
> ref(locale-hu): Add HU translation for list buttons

- cypress/utils/steps.js
Draft PR to try and make the tests stable in CI
> chore: fix ci tests

- yarn.lock
**Summary**
Syncs the lock file
**Test plan**
Existing tests
**Checklist**
🐱
> chore: sync lock file

- CONTRIBUTING.md
**Summary**
Add tips for fine tuning Jest tests using the Jest command line runner. Tips include:
- running tests from a specific file
- running tests for a file whose path matches a given regexp
- running individual tests that match a given regexp in a file
Please refer to #6298 
**Test plan**
N/A
**Checklist**
> feat(docs): add tips for running Jest CLI

- renovate.json
**Summary**
Enables lock file maintenance for renovate
**Test plan**
Existing tests
**Checklist**
🐶
> chore: enable lock file maintenance

- website/content/docs/add-to-your-site.md
**Summary**
**Test plan**
**Checklist**
> "add sveltekit to add-to-your-site"

- README.md
**Summary**
**Test plan**
**Checklist**
> chore: fix the broken repo links

- CONTRIBUTING.md
- packages/netlify-cms-backend-git-gateway/README.md
- website/content/docs/start-with-a-template.md
> docs: replace template urls

- website/content/docs/custom-widgets.md
**Summary**
**Test plan**
**Checklist**
> Fix broken screenshot url

- packages/netlify-cms-locales/src/da/index.js
**Summary**
Updates to danish translations. Fix some typos and add translations missing
**Checklist**
- [x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
> fix(locales): Add missing translations, fix typos

- website/src/components/docs-template.js
- website/src/components/sidebar-layout.js
Closes #5921
Makes the container wider and the sidebar responsive.
> docs: make container wider

- website/content/docs/releases.md
Updated versions to reflect current DecapCMS version numbers
> Update Docs: Intro “releases”

- website/gatsby-config.js
- website/package.json
- website/yarn.lock
Add Google Tag Manager to website
> feat: add GTM

- website/content/blog/decap-3-1-0-beta-0.md
- website/content/blog/decap-3.md
- website/content/blog/git-based-cms-definition-features-best-practices.md
- website/content/blog/github-discussions.md
- website/content/blog/introducing-decap.md
- website/content/blog/march-23-status-update.md
- website/content/blog/moving-to-discord.md
- website/content/blog/software-reviews-gold-medal-2023.md
- website/src/components/layout.js
- website/src/html.js
- website/src/templates/blog-post.js
- website/static/admin/config.yml
- set post image as og:image
- remove image on posts where it is not needed
> feat(website): replace twiter image with image

- packages/decap-cms-locales/src/zh_Hans/index.js
- packages/decap-cms-locales/src/zh_Hant/index.js
**Summary**
**Test plan**
**Checklist**
> fix(i18n): translate editor.editorWidgets.list.add in Simplified Chinese and Traditional Chinese

- website/content/docs/beta-features.md
- website/content/docs/configuration-options.md
> Update Docs: migrate Beta Features - Commit Message Templates

- packages/decap-cms-locales/src/zh_Hans/index.js
- packages/decap-cms-locales/src/zh_Hant/index.js
**Summary**
**Test plan**
**Checklist**
> fix(i18n): translate copyFromLocale and copyFromLocaleConfirm in Chinese

- packages/decap-cms-backend-aws-cognito-github-proxy/src/AuthenticationPage.js
- packages/decap-cms-backend-gitea/src/AuthenticationPage.js
- packages/decap-cms-backend-gitlab/src/AuthenticationPage.js
- packages/decap-cms-lib-auth/src/pkce-oauth.js
FIX: #7093 #7100 
**Summary**
**Test plan**
**Checklist**
> fix: gitlab pkce auth error

- package-lock.json
- packages/decap-cms-ui-next/package.json
- packages/decap-cms-ui-next/src/GlobalStyles/GlobalStyles.jsx
- packages/decap-cms-ui-next/src/GlobalStyles/index.js
- packages/decap-cms-ui-next/src/UIContext/UIContext.jsx
- packages/decap-cms-ui-next/src/UIContext/index.js
- packages/decap-cms-ui-next/src/hooks/index.js
- packages/decap-cms-ui-next/src/hooks/useLocalStorageState.js
- packages/decap-cms-ui-next/src/hooks/useUIContext.js
- packages/decap-cms-ui-next/src/index.js
- packages/decap-cms-ui-next/src/styles.js
- packages/decap-cms-ui-next/src/theme.js
- packages/decap-cms-ui-next/src/utils/color.js
- packages/decap-cms-ui-next/src/utils/responsive.js
- packages/decap-cms-ui-next/src/utils/shadow.js
- scripts/webpack.js
**Summary**
Add base theming for decap-cms-ui-next with [@emotion/react](https://emotion.sh/).
> (next-ui) feat: add theming

- packages/decap-cms-backend-azure/src/implementation.ts
**Summary**
fix some comments
**Test plan**
**Checklist**
> chore: fix some comments

- packages/decap-cms-lib-util/README.md
**Summary**
At least this is what I think was meant.
**Test plan**
**Checklist**
🐴
> Update README.md, fix spelling error

- package-lock.json
- packages/decap-cms-widget-code/package.json
- packages/decap-cms-widget-relation/package.json
- packages/decap-cms-widget-select/package.json
Update react-select from 4 to 5 to get rid of some console warnings.
I closed #7496 because this is much simpler and tests also pass (locally)
> chore(deps): update react-select from 4 to 5

- package-lock.json
- packages/decap-cms-app/package.json
Fixed the error with missing ajv dependencies as explained here https://github.com/decaporg/decap-cms/issues/7375#issuecomment-3008477431
> fix: could not resolve "ajv"

- packages/decap-cms-widget-relation/src/RelationControl.js
**Summary**
Seems like async function does not play nice with debounce after the caching update we did in 3.8. This is a patch that fixes this by using promise chaining again.
**Test plan**
**Checklist**
> Fix relation control loading values

- package-lock.json
- package.json
- packages/decap-cms-core/src/components/Collection/Entries/EntriesSearch.js
- packages/decap-cms-core/src/components/Collection/Entries/EntryListing.js
Closes #7550
This PR adds `getWorkflowStatus` function to `EntriesSeach` component.
> Fix: add workflow status to Search Entries
