src/components/Widgets/MarkdownControl.js
```
ERROR in ./src/components/Widgets/MarkdownControl.js
Module build failed: SyntaxError: Only one default export allowed per module.
80 | };
81 | 
> 82 | export default connect(
| ^
83 |   state => ({ editor: state.editor }),
84 |   { switchVisualMode }
85 | )(MarkdownControl);
@ ./src/components/Widgets.js 23:23-59
```
=> Removed second default export that caused an error in the bundle compilation

.eslintrc, package.json, src/backends/github/AuthenticationPage.js, src/backends/netlify-git/AuthenticationPage.js, src/backends/test-repo/AuthenticationPage.js, src/components/AppHeader/AppHeader.js, src/components/EntryEditor.js, src/components/FindBar/FindBar.js, src/components/PreviewPane.js, src/components/UI/loader/Loader.js, src/components/UI/toast/Toast.js, src/components/UnpublishedListing.js, src/components/Widgets/DateTimeControl.js, src/components/Widgets/ImageControl.js, src/components/Widgets/MarkdownControl.js, src/components/Widgets/MarkdownControlElements/RawEditor/index.js, src/components/Widgets/MarkdownControlElements/VisualEditor/BlockTypesMenu.js, src/components/Widgets/MarkdownControlElements/VisualEditor/StylesMenu.js, src/components/Widgets/MarkdownControlElements/VisualEditor/index.js, src/components/Widgets/MarkdownControlElements/plugins.js, src/components/Widgets/StringControl.js, src/components/Widgets/TextControl.js, src/containers/App.js, src/containers/CollectionPage.js, src/containers/EntryPage.js, src/containers/editorialWorkflow/CollectionPageHOC.js
This is a quick refactoring to ES7 class properties initializers done using JSCodeshift.
It lacks some `propTypes` in as class properties due a bug in https://github.com/zertosh/class-props-codemod that I used to move some of them. I'd say this isn't important ATM and can be done later as well.
=> Class properties initializers

src/index.js, src/utils.css, webpack.base.js
In case if we define try to render a local `className` that is not defined in `*.css` file this PR will display an red overlay saying that it is not defined.
Note: It seems that React 15.3.x doesn't render `undefined` classNames anymore so probably we won't need this.
=> CSS-modules `undefined` overlay

package.json
Until #96 and #99 are merged. This way we can at least see if tests are failing.
=> Temporarily disabled linting in `test` script

example/example.css, package.json, src/components/ControlPanel/ControlPane.css, src/components/Widgets/MarkdownControl.js, src/components/Widgets/MarkdownControlElements/RawEditor/BlockMenu.css, src/components/Widgets/MarkdownControlElements/RawEditor/BlockMenu.js, src/components/Widgets/MarkdownControlElements/RawEditor/Toolbar.css, src/components/Widgets/MarkdownControlElements/RawEditor/Toolbar.js, src/components/Widgets/MarkdownControlElements/RawEditor/index.css, src/components/Widgets/MarkdownControlElements/RawEditor/index.js, src/components/Widgets/MarkdownControlElements/plugins.js
**- Summary**
The current slate based editor is not performant enough to handle real life articles, content, etc. This seems to be a problem with Slate itself, and it will quite possibly be a lot of work to fix. Meanwhile we should have a robust solution for markdown editing. This PR replaces Slate with a much simpler textarea based markdown editor without an intermediary content model, but with menu bar and custom block support.
This is still work in progress and the menus are very roughly styled, but it's already workable for long posts, dragging images and files work, bold and italics works and there's an option to add link, although this one relies on a prompt.
=> Simple markdown editor

package.json, src/reducers/__tests__/collections.spec.js, wallaby.config.js, webpack.base.js, yarn.lock
- Upgraded Jest to 17.0 🚀
- Removed unused deps
- Removed redundant `NODE_ENV` from test task
- Fixed CSS mocking for tests
=> Updated Jest to 17.0.0

package.json, src/components/ControlPanel/ControlPane.js, src/components/PreviewPane/PreviewPane.js, src/components/Widgets.js, src/components/Widgets/DateControl.js, src/components/Widgets/DatePreview.js, src/components/Widgets/ListControl.js, src/components/Widgets/MarkdownControlElements/RawEditor/index.js, src/components/Widgets/SelectControl.js, src/components/Widgets/SelectPreview.js, src/index.js, yarn.lock
**- Summary**
This ads a `date` widget for when date + time selection is not needed and also makes `string` the default widget when no widget is specified for a field in the config.yml
Add Date widget and make `widget` optional in field declarations
=> Widget fixes

src/components/EntryListing/EntryListing.js, src/containers/CollectionPage.js, src/reducers/index.js, src/reducers/medias.js
**- Summary**
When integrating with Netlify, which already has existent content, only file names are persisted as image fields. 
The CMS should look for this images on the defined public_folder in this case.
=> Use public_folder to display images persisted with no path reference

webpack.base.js
- react-toolbox requires its own setup with sass-loader for now
- redux-notifications doen's need to use css-modules
- exclude `node_modules` from our own CSS pipeline
Realted to bcca98b1951d03e0850b353e9c16fd8b1db2291f
=> Use proper loaders for external module's CSS

src/components/EntryListing/EntryListing.css, src/components/EntryListing/EntryListing.js, src/components/PreviewPane/Preview.js, src/components/PreviewPane/PreviewPane.js, src/components/UI/card/Card.css, src/components/UnpublishedListing/UnpublishedListing.js, src/components/Widgets/DatePreview.js, src/components/Widgets/DateTimePreview.js, src/components/Widgets/ImagePreview.js, src/components/Widgets/ListPreview.js, src/components/Widgets/MarkdownPreview.js, src/components/Widgets/NumberPreview.js, src/components/Widgets/ObjectPreview.js, src/components/Widgets/SelectPreview.js, src/components/Widgets/StringPreview.js, src/components/Widgets/TextPreview.js, src/components/Widgets/UnknownPreview.js, src/components/Widgets/defaultPreviewStyle.js, src/constants/fieldInference.js, src/containers/DashboardPage.js, src/containers/editorialWorkflow/UnpublishedEntriesPanel.js, src/reducers/collections.js
**- Summary**
This PR implements a default preview styling for editing as well as a few general improvements to user experience and UI:
- Automatic redirect from Dashboard to first collection (when publish mode is "simple")
- More collection inference synonyms
Refinements & Preview Defaults
```
_,-""`""-~`)
(`~_,=========\
|---,___.-.__,\
|        o     \ ___  _,,,,_     _.--.
\      `^`    /`_.-"~      `~-;`     \
\_      _  .'                 `,     |
|`-                           \'__/ 
/                      ,_       \  `'-. 
/    .-""~~--.            `"-,   ;_    /
|              \               \  | `""`
\__.--'`"-.   /_               |'
`"`  `~~~---..,     |
\ _.-'`-.
\       \
'. …
```
=> Refinements & Preview Defaults

src/actions/entries.js, src/actions/search.js, src/components/ControlPanel/ControlPane.js, src/components/EntryEditor/EntryEditor.js, src/components/PreviewPane/PreviewPane.js, src/components/Widgets/ListControl.js, src/components/Widgets/ObjectControl.js, src/components/Widgets/RelationControl.js, src/containers/EntryPage.js, src/reducers/__tests__/entryDraft.spec.js, src/reducers/entryDraft.js, src/reducers/search.js
This PR adds metadata support for widgets, (Allowing control widgets to send more than just the plain textual `value` to preview widgets).
**- Summary**
This is implemented in the Redux store though a new `fieldsMetaData` immutable map in the Draft Entry state tree.
Each field already had a "value" key - the main objective of fieldsMetaData is providing additional information for aiding in the preview. For example, the Relation widget passes the whole selected relation data as fieldsMetaData.
Closes #191 
Redux test cases were updated accordingly
Added metadata support for widgets
```
(>\---/<)
,'     `.
/  q   p  \
(  >(_Y_)<  )
>-' `-' `-<-.
/  _.== ==.,- \
/,    )`  '( …
```
=> Add metadata to draft entry fields

.gitignore, package.json, scripts/autoconfigure.collection.js, src/formats/formats.js, yarn.lock
Eventually this could turn into a bin/netlict-cms commandline tool
Right now this PR will let you build a small cli tool by running:
```
npm run build:cli
```
You can then use `bin/autoconfigure.collection.js <path-to-my-collection-folder>` to
autogenerate a configuration for a collection that you can paste into your `config.yml`.
=> Add a script for auto configurating a collection

src/actions/editorialWorkflow.js, src/actions/entries.js, src/components/ControlPanel/ControlPane.css, src/components/ControlPanel/ControlPane.js, src/components/EntryEditor/EntryEditor.js, src/components/Widgets/ControlHOC.js, src/components/Widgets/FileControl.js, src/components/Widgets/ImageControl.js, src/containers/EntryPage.js, src/containers/editorialWorkflow/EntryPageHOC.js, src/reducers/__tests__/entryDraft.spec.js, src/reducers/entryDraft.js
**- Summary**
- Presence: By default all widgets are required, unless specified in the config. Example:
`- {label: "Subtitle", name: "subtitle", widget: "string", required: false}`
- Pattern: Field configuration can specify a regex pattern with the appropriate error message. Example:
`- {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 10 characters"] }`
The widget control can optionally implement an `isValid` method to perform custom validations, in addition to presence and pattern. The `isValid` method will be automatically called, and it can return either a boolean value, an object with an error message or a promise. Examples:
**Boolean**
No errors:
```javascript
isValid = () => {
// Do internal validation
return true;
};
```
Existing error: …
=> Validation

README.md
**- Summary**
Added instructions to README on how to authorize GitHub as a provider.
Added instructions to add GitHub as an auth provider
=> Added instructions to add GitHub as an auth provider

src/backends/github/API.js
**- Summary**
Closes #222 
* Steps/workflow mentioned in #222 were tested manually. 
* Basic tests passed (`npm run test`) but I don't think there are any test for the backends.
* Pre-commit hook was skipped because `eslint` complains of code that is already in master.
**- Additional info**
* `encodeURIComponent` was already being used [here](https://github.com/marzeelabs/netlify-cms/blob/471b26a9d553ca5c92bdf53fd60b3b0512ec520c/src/backends/github/API.js#L49) but it only encodes parameters like the branch name when they're passed in the `options.params` object, not when strings such as the branch name are passed on the URL for the request directly (such as in the lines that change in this diff). For now this will fix it but a refactoring should be considered to pass all …
=> #222 - Encode branch name on requests to avoid errors with special chars

src/index.css
**- Summary**
Discovered that large images inserted in the markdown editor expand beyond the borders of the editor, making them a hassle to scroll past.
I added the common global default `img { max-width: 100%; }` to prevent this and other similar layout bugs that may come up in the future.
Quick-and-dirty testing with the web inspector showed the problem solved and no other layout bugs as a result.
Prevent images from overflowing their containers
(my pups, Monty and Petunia) 😄
=> Prevent giant images in editor

src/backends/backend.js
**- Summary**
Persisting an entry in a collection based on files rather than a folder failed when trying to determine the order of the fields and the format of the entry.
This changes the handling of the `entryToRaw` method in the backend to handle files based collections correctly.
=> Fix persistence for collections stored in different files

docs/quick-start.md
**- Summary**
Updated docs - Added the file path location for the `/admin` folder when using Netlify CMS with Spike.
n/a
Update Quick Start doc with `/admin` location when using Spike
=> Add Spike to list in App File Structure

docs/extending.md, example/index.html, src/components/PreviewPane/PreviewPane.js
**- Summary**
Fixes #236 
Preview templates did not have access to individual nested fields for object and list entries, which limited customization of related preview panes.
An `AuthorPreview` template has been added to the example project, and demonstrates this fix in action for a list entry. The existing `GeneralPreview` template has also been updated to utilize the new fix as an example of use with an object entry.
Add widgetsFor helper for nested widget access in preview templates
=> Add widgetsFor helper - fixes #236

example/config.yml, src/actions/editorialWorkflow.js, src/backends/backend.js, src/backends/github/API.js, src/backends/github/implementation.js, src/components/UnpublishedListing/UnpublishedListing.js, src/containers/editorialWorkflow/UnpublishedEntriesPanel.js
**- Summary**
Added the basic functionality (via a button) to delete a card from the editorial workflow. It also closes the related PR via GitHub API. It mirrors the request publish functionality. This was created to address issue #252.
Added cms to an existing statically generated site. Deleted(which closed related PRs) cards using the new button in all columns of the editorial workflow. (Note this could not be tested in the local example as discussed in issue #264.) Also checked that the cards remained deletable without error if the corresponding PR had been closed independently on github prior to use of the delete button. Attached gifs below: 
First gif demonstrates deleting cards from all rows and resulting PRs closed: 
Second gif demonstrates a previously closed PR in …
=> delete button working

src/backends/backend.js
**- Summary**
Full stops in slugs were preventing branch creation for unpublished
entries when using the editorial workflow, as `.` is not an allowed
character in branch names. This commit changes slug generation so
periods are replaced with `-` the same way other "non-sluggable"
characters are.
Closes #275.
Tested manually (no current automated test setup exists for the editorial workflow, due to its dependence on the GitHub API)
- **Disallow full stops in entry slugs**
=> Disallow full stops in entry slugs

src/backends/github/API.js
Firefox 52 gives an error:
```
Failed to load entry: 'cache' member of RequestInit 'false' is not a valid value for enumeration RequestCache.
```
When calling fetch with `cache: false` as an option.
Change this to `cache: no-store`
=> Fix firefox fetch issue in GitHub API

src/containers/EntryPage.js, src/reducers/__tests__/entryDraft.spec.js, src/reducers/entryDraft.js
**- Summary**
- New state field: `state.entryDraft.hasChanged`, initialized to `false`.
- `state.entryDraft.hasChanged` set to `true` in `entryDraft` reducer for `DRAFT_CHANGE_FIELD`.
- `EntryPage` adds a `listenBefore` listener to `history` on `componentDidMount` that checks `this.props.entryDraft.hasChanged` and, if that is true, asks the user to confirm the navigation.
- `EntryPage` removes its listener on `componentWillUnmount`.
Closes #249.
Tested manually and added `hasChanged` attribute to relevant tests in `src/reducers/__tests__/entryDraft.spec.js`
- **Confirm navigation when it would discard unsaved changes**
=> Confirm navigation when it would discard unsaved changes

src/components/ControlPanel/ControlPane.css, src/components/EntryEditor/EntryEditor.css, src/components/UI/theme.css, src/components/Widgets/ListControl.css, src/components/Widgets/ListControl.js, src/components/Widgets/MarkdownControlElements/VisualEditor/index.css, src/components/Widgets/ObjectControl.css, src/components/Widgets/ObjectControl.js
Fixes #257, improves various rough bits in the entry editor UI. Tested with Smashing's setup.
* Improved contrast (no more white against very light gray)
* Replaced text based icons with icon font
* Increased label sizes
* Form controls have white background for clarity
* Provided a visual "drag bar" - even though entire list objects are draggable, this helps make that discoverable and should reduce confusion
* Other basic finishing
=> improve entry editor UI

src/components/EntryEditor/EntryEditor.css
=> fix preview pane height in Safari

src/backends/backend.js, src/backends/github/API.js, src/backends/github/implementation.js, src/components/UI/theme.css, src/components/UnpublishedListing/UnpublishedListing.js, src/components/UnpublishedListing/UnpublishedListingCardMeta.css, src/components/UnpublishedListing/UnpublishedListingCardMeta.js, src/lib/promiseHelper.js, src/valueObjects/Entry.js
Fixes #270 
**- Summary**
Adds meta information to the cards in the editorial workflow. Currently this includes the following:
- Which collection an entry is part of
- Whether an entry is new or an update to an already published entry
In order to retrieve the new/update info, it adds the field `state.editorialWorkflow.entities[i].isModification`, which is retrieved using the GitHub API whenever unpublished entries are loaded.
Tested manually (no automated tests exist for the editorial workflow).
- **Add meta info to cards in editorial workflow**
=> Add meta info to cards in editorial workflow

docs/quick-start.md
Skipping all the code-related bits in your contrib template. The "Step-by-Step Guide to Hugo on Netlify" is broken. (That said, slick 404 page design. I'm all Zen'ed out.) Cheers.
=> docs: Updating URL for Victor Hugo on Netlify

package.json
**- Summary**
It'd be nice to have sourcemaps switched on by default for development
- turned on `-d` debug mode for webpack-dev-server cli client
=> Enable sourcemaps

src/components/EntryEditor/EntryEditor.css, src/components/EntryEditor/EntryEditor.js
**- Summary**
Added the basic functionality (via a button) to hide/show the preview panel in the Entry Editor.  It mirrors the request publish functionality. This was created to address issue #113. (*Note that it deals with the second level of integration @calavera mentioned in his most recent comment on the issue.*)
Tested code using the local "example" page. Added button(s) which call a function which toggles the state (*added to code as 'previewOpen'*). Added a showOnlyEditor, which displays the editor fullscreen without the preview. Depending on the status of this.state.previewOpen (*boolean*) the main render function displays either the original JSX or calls the showOnlyEditor. Attached gif below demonstrates its functionality: 
(*Note: Different styling maybe needed …
=> Adding close preview feature

src/containers/CollectionPage.css, src/containers/CollectionPage.js, src/reducers/entries.js
**- Summary**
Stop showing the loading spinner on the collection page when there are no entries. Closes https://github.com/netlify/netlify-cms/issues/269.
Existing test suite passes. Changes are mostly cosmetic.
Stop showing the loading spinner on the collection page when there are no entries.
=> Stop showing loader forever when there are no entries

package.json, yarn.lock
Current markup-it dep is based on @cassiozen's fork - moving to upstream (his changes were merged in https://github.com/GitbookIO/markup-it/pull/26). Using the latest release in the currently used major release line 2.x.
=> switch to markup-it upstream repo

src/lib/promiseHelper.js
**- Summary**
There were a couple issues with the original version of
`resolvePromiseProperties`:
- The wrapper promise was unnecessary, since we can just return the
`Promise.all`. Fixing this allows us to remove a wrapping function,
reduce indentation, remove the `resolve` and `reject` calls, and
remove the now unnecessary `.catch` line.
- There was inadvertent mutation in the `Object.assign` call - the
first parameter to `Object.assign` is mutated, so to call it without
mutating existing objects the first parameter should be a literal
`{}`. This is now fixed.
All existing tests pass and the functionality works as expected.
- Cleanup `resolvePromiseProperties`
=> Cleanup `resolvePromiseProperties`

package.json
**- Summary**
With a fresh clone of master `npm run build` gives me the error:
```
ERROR in ./routing/history.js
Module not found: Error: Cannot resolve module 'history' in /Users/Joseph/Workspace/netlify-cms/src/routing
@ ./routing/history.js 8:15-33
```
Before: builds with error.
After: no error when building.
Added missing [history](https://www.npmjs.com/package/history) package for `createHashHistory` in `history.js`.
=> Add missing history package

docs/customization.md, docs/extending.md
I notice I created two new doc pages using h2 markdown headers and they should of been h1
This 
should look like this:
=> make doc page a h1

src/actions/config.js
**- Summary**
Fixes #357 - shows an error when there is an issue parsing the config file.
Changed the `test-repo/config.yml` to:
```yaml
backend:
name test-repo
delay: 0.1
``` 
Execute `npm start`:
Change the promise structure so all happens in a single pipeline and all errors are caught by the catch.
=> Show error if config fails to parse

example/config.yml, src/components/EntryEditor/EntryEditor.js
**- Summary**
Fixes #113. Adds ability to disable the editor preview for a collection.
Added setting to example `config.yml` for settings collection. Tested with `npm start`.
Adds `editor.disable_preview` option to collection. If set to `true`, the editor preview will not be displayed and the button to show the preview will not be displayed.
Not sure it was the best option name so let me know if there's a better one.
=> Disable editor preview

src/components/Widgets/ListControl.js
**- Summary**
* Closes #359 
* I know, no excuses for not writing any tests but I ended up having to test it all manually anyway in my use case. Adding, removing and updating any child of the `list` works, there are no incompatibilities with the current version, nothing needs to be changed in the docs (they don't go very deep into the `relation` widget anyway - room for improvement in another contribution), now works as expected. If you did the setup to confirm the bug exists (see #359), just adding, editing and removing entries in the list field should be enough to confirm that the metadata now comes as expected.
* Handle metadata for all children of a list field
=> #359 - Handle metadata for all children of a list field

package.json, yarn.lock
Fixes #356 by removing pre-commit hook.
If you have already cloned the repository, you may need to manually remove the hook in `.git` with `rm .git/hooks/pre-commit` after merging this commit.
**- Summary**
Makes contributing easier - now committing does not fail because of lint issues in existing code.
Removed pre-commit hook. Made a commit. Nothing was executed.
Removes the pre-commit hook package and settings.
=> Fixes #356 Remove pre-commit hook

src/components/EntryEditor/EntryEditor.css, src/components/EntryEditor/EntryEditor.js
**- Summary**
Fixes #358 - Save bar stuck in middle of screen.
Feedback welcome on class names or if there's an existing style I should be using, or if I should make a component.
Tested by toggling off the preview editor using test backend, using Safari.
Put the editor inside an absolutely positioned div container, to match the `ScrollSync` container when editor is visible).
=> Fixes 358 Save bar stuck

docs/quick-start.md, src/backends/github/AuthenticationPage.js, src/containers/App.js
**- Summary**
We have our main site served by nginx and load the netlify site via proxy_pass for specified paths. Attempting to load the admin CMS page breaks since the host is different than our Netlify custom domain. Making the `site_id` configurable addresses this. 
https://github.com/netlify/netlify-cms/issues/37
To test this I ran the server locally with `npm run start`, updated my Netlify site config to include the new `site_id:` and pointed the CMS CSS /JS my local copy of my middleman site to the local CMS server.
```haml
= stylesheet_link_tag "http://localhost:8080/cms.css"
= javascript_include_tag "http://localhost:8080/cms.js"
```
I added the following to `src/backends/github/AuthenticationPage.js`
```js
console.log('siteId is 'this.props.siteId);
auth = new …
```
=> Add backend config for site ID

src/index.js, webpack.dev.js, webpack.prod.js
**- Summary**
Show the version number in the "settings" dropdown - fixes #292. I also combined the settings menu and user avatar together, which haves the benefit of leaving more space for the search bar on mobile. "-dev" is appending to the version when developing.
* Inject the version number from `package.json` with Webpack and display it in the settings menu (this could lead to an about page)
* Combine the settings icon and user avatar together
=> Fixes #292 Display version number

example/index.html, src/backends/backend.js, src/backends/github/API.js, src/backends/github/implementation.js, src/backends/test-repo/implementation.js, src/lib/__tests__/pathHelper.spec.js, src/lib/pathHelper.js, src/reducers/collections.js
**- Summary**
Fixes #278 and also #313. 
For folder type collections, the listing files now **only** returns files and only returns files matching the collection extension (which is the `extension` property if defined, or the default extension for the collection format if one exists, or 'md').
Tested with Test and GitHub repos.
For the GitHub and Test Repo APIs:
* Only files matching matching a folder collection's extension are listed
For the GitHub API:
* Only files are now considered (and fetched)
* An error is thrown if the path points to something that is not a directory (a file, a symlink or a submodule)
=> Fixes #278 Filter folder collection files by extension

src/backends/github/implementation.js
**- Summary**
The extension filter was not running properly since `file` was not passed in.
Run server locally and watch posts not load and then load with the change
Fix extension filter filtering out all files
=> Fix filtering by file extension

example/config.yml, src/formats/__tests__/frontmatter.spec.js, src/formats/frontmatter.js
Switches back to custom frontmatter stringification
until support lands in the preliminaries lib. This is necessary
because we use custom schemas for certain data types,
such as dates and times.
(This is a copy of #384 with history rewritten to use @josephearl's alternate implementation).
**- Summary**
Date fields can no longer be changed through the CMS. Regression from #348.
Moved the Published Date field in the example project out of metadata and into standard fields, so persisting dates can be observed in deploy previews. Tested locally. Existing automated tests pass.
Fix date/datetime field persisting
=> Fix date field persist

src/actions/__tests__/config.spec.js, src/actions/config.js, src/reducers/collections.js
**- Summary**
Fixes #298 - adds some basic validation for the config.
Added some unit tests for config validations.
Add a `validateConfig` to provide basic validation of configuration.
=> Fixes #298 Basic validation for config

src/components/Widgets/MarkdownControlElements/VisualEditor/index.css
**- Summary**
Previously, long lines of preformatted text would cause the lines to run off the side of the ProseMirror edit box and give the entire entry editor a horizontal scrollbar. This commit makes the edit box itself scroll, which looks and feels much less broken.
Tested manually (no visual diff testing exists on this project at the moment).
Prevent long code lines from breaking visual entry editor.
=> Prevent long code lines from breaking visual entry editor

src/components/Widgets/MarkdownControlElements/RawEditor/index.css, src/components/Widgets/MarkdownControlElements/RawEditor/index.js, src/components/Widgets/MarkdownControlElements/VisualEditor/index.css
**- Summary**
The rich text editor is now sized by an autosizing library, and should never have scroll bars. When it does have scroll bars, the scroll events break sticky toolbar positioning. This fix prevents scrollbars from showing within the rich text editor, and also improves code, ordered list, and paragraph display styling (within the rte).
Prevent rich text editor scroll and improve code/code block display
=> prevent rte scroll, improve code display

docs/quick-start.md
The `site_domain` key is for a rare case and should not be used by the vast majority of projects. It breaks auth if used incorrectly. Proper documentation will be handled under #405.
=> remove site_domain key from example

package.json, src/components/PreviewPane/PreviewPane.js, yarn.lock
Fixes #307
**- Summary**
Uses `react-frame-component` for preview pane instead of custom iframe code. Fixes #307.
Existing tests pass; manually tested that previewing and scrolling work correctly in both Firefox and Chrome.
Use react-frame-component for preview pane
=> Use react-frame-component for preview pane

example/config.yml
**- Summary**
The `card` setting in the example config.yml was used in the first iteration of the card UI.
The code was later changed to infer the fields that appear in the card, instead of having to configure them (see [commit 2a2497072dd2c538735a92a1f6e93de6af7c796d](https://github.com/netlify/netlify-cms/commit/2a2497072dd2c538735a92a1f6e93de6af7c796d)).
The old card settings, however, were left in the example configuration file, which leads to confusion.
Run the CMS locally and note the UI is not affected by this setting.
Remove deprecated setting from example config.yml
_this should be animated!_
=> Remove deprecated card setting from example config.yml

example/config.yml, example/index.html, src/components/EntryListing/EntryListing.js
**- Summary**
In the current behavior, the CMS encounters a problem, while displaying "remaining fields" in a card, as it encounters a field with a value of "null" explicitly set in the front matter... blank works, but not null. The console errors with "Cannot read property 'toString' of null at EntryListing.js:60" and the CMS app will no longer respond until refreshed.
A null value occurs whenever a non-required field is skipped during post entry. This might not be intended behavior for persisting a post, but regardless, it should be handled.
The offending line originally read:
```
{ entry.getIn(['data', f.get('name')], '').toString() }
```
but now is changed to:
```
{ entry.getIn(['data', f.get('name')], '')?entry.getIn(['data', f.get('name')], '').toString():'' }
```
A …
=> Tests remaing field value in card view for null

docs/widgets.md, src/components/Widgets.js, src/components/Widgets/BooleanControl.js, yarn.lock
**- Summary**
While working on the file-system backend, I was working with `hugo`. `hugo` uses a draft attribute to let you mark content as draft so it's not included in the output. I found there was no `boolean` widget, so here it is.
The MR passes `npm run lint:staged` but I have issues the the pre-commit hooks:
```
.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory
```
There's no test for the other widget, so I did not really know where to start here. Let me know if you want one.
Widget for `boolean` fields
=> boolean widget & some documentation

example/config.yml, example/index.html, src/backends/backend.js
**- Summary**
Closes #407 
A new field was added to the sample repo and filtering is done on it via the changes made to the sample config.yml. Probably could use some more hands-on testing to make sure everything is ok but the code is very straightforward and the only new post that should be excluded is excluded as specified in the filter. Changing filtering values also yields the expected results.
Add collection entries filtering by `field: value` through the `filter` property in the collections.
=> #407 Add collection filtering by field and value

src/components/ControlPanel/ControlPane.js, src/components/PreviewPane/PreviewPane.js, src/components/Widgets/BooleanControl.js, src/components/Widgets/ControlHOC.js, src/components/Widgets/DateTimeControl.js, src/components/Widgets/ListControl.js, src/components/Widgets/NumberControl.js, src/components/Widgets/ObjectControl.js, src/components/Widgets/StringControl.js, src/components/Widgets/TextControl.js, webpack.dev.js
**- Summary**
First, thanks for your app, it is really usefull !
I wanted to remove warnings that I saw while browsing the example and building my `config.yml`.
Here are the results:
- remove `localforage.js` warning (This seems to be a pre-built javascript file)
- warnings/proptypes: use oneOfType to support object and string
- warnings/widgets: forID is not required (can be undefined) + typo
- warnings/map>key related warnings + typo
To test this PR, you can browse the example and look at the console, this PR removes most of warnings
fix development warnings (proptypes, keys in map, prebuild javascript + typos
=> Fix development warnings

src/backends/github/API.js
This should solve issues like #308 and the issues with cached
API responses after deleting an entry
**- Summary**
GitHub's API does fairly aggressive caching for GET requests, at this causes problems in several cases. Especially when creating commit trees where a stale response from the GitHub API can make us try to base the changes on a wrong SHA and lead to issues like #308 
This also caused problem for the work on deleting entries, since we would get a stale folder list right after entry deletion.
This PR takes the brute force approach of adding a cache buster timestamp as a query parameter to all GitHub API requests.
Warning - I haven't tested this yet. The old Ember prototype had a similar cache buster approach (though only on some requests) so I'm fairly confident in …
=> Add cache buster to all GitHub API calls

src/backends/backend.js
**- Summary**
`identifier` is used to build slug when slug field is `{{slug}}` and was retrieved using nested `.get()` methods on `entryData` which did not fail gracefully and was sensitive to the case of the field name declaration in `config.yml` This change makes the assignment of `identifier` more robust by making it effectively case-insensitive, by throwing a meaningful error when no usable entry identifier can be found, and by moving the   assignment of `identifier` inside the `case "slug"` so that it is only assigned when required.
Tested using steps to repro in #458 on Chromium using test-repo backend. 
All jest tests passing.
Names of entry fields used in slug construction as entry identifiers are no longer case-sensitive
**- A …
=> Fix #458 by ending case sensitivity of names of fields used in slug construction

docs/customization.md, docs/extending.md, docs/intro.md, docs/quick-start.md
**- Summary**
html snippets in the docs demonstrate loading the CMS via an unpkg.com link that's pinned at v0.3 (or 0.x in a few places). This changes the link to point to the latest release instead.
None
Docs: update links to unpkg.com to pull the latest release of Netlify CMS.
http://i.imgur.com/rDiVe2z.gifv (technically not an image, but too cute)
=> Docs: change unpkg links to pull latest release

example/config.yml, src/components/Widgets/ObjectControl.js
Fixes hidden widgets not being hidden when nested (instead outputs something like "No control widget for 'hidden'").
Change only needed to be applied to object control since the list control uses the object control.
=> hide hidden widget in object and list controls

src/components/Widgets/ListControl.css, src/components/Widgets/ListControl.js
> Fixes Issue #300 
**- Summary**
This PR adds the list label to the new button which provides users better context (especially with nested lists).
All tests continue to pass. I created nested lists 20 levels deep to test & ensure scalability. I ran `npm build test` & `npm run line` in compliance with contributing.md guidelines.
<br/>
<br/>
- Adds the specific content type to the list control widget's "new" button.
<br/>
> ![Basketball Dog :)](https://media.giphy.com/media/HWamJO1FK5dNm/giphy.gif)
=> adds context to new list item button

src/components/EntryListing/EntryListing.js, src/lib/pathHelper.js
**- Summary**
PR #415 fixed the image path problem, but too deep. The fix created a problem where all images with a space in the image name ended up with "%20" in the actual persisted image name. This was because resolvePath() was obviously used in both display and persist cases (unknown to the author of the fix (me) at the time).
Instead, the image name is now encoded in EntryListing.js right before displaying.
Images display in cards. Uploaded images should no longer have "%20" in their names.
Posts and page types display normally.
Image name is now encoded in EntryListing.js rather than pathHelper.js.
=> Reverse change in #415; Image paths encoded before displaying instead

src/actions/entries.js, src/backends/backend.js, src/backends/github/API.js, src/backends/github/implementation.js, src/backends/test-repo/implementation.js, src/components/EntryEditor/EntryEditor.js, src/components/EntryEditor/EntryEditorToolbar.js, src/components/EntryEditor/__tests__/EntryEditorToolbar.spec.js, src/containers/EntryPage.js, src/containers/editorialWorkflow/EntryPageHOC.js, src/reducers/entries.js, src/reducers/entryDraft.js
**- Summary**
This PR adds a "Delete" button to the entry page in the simple workflow which deletes the current entry from the backend. This does not close https://github.com/netlify/netlify-cms/issues/291 completely, but it is most of the way there (the remaining work to close that ticket is to implement deletion in the editorial workflow, which is in progress in the `delete-entries-in-editorial-workflow` branch.
Existing tests pass, relevant spec tests were updated, and the PR was manually tested with editorial workflow both enabled and disabled.
Entry deletion for the simple workflow
=> Entry deletion for the simple workflow

src/components/Widgets/MarkdownControlElements/VisualEditor/index.js
**- Summary**
Fix list item reordering. As explain in the issue #437.
In the example project:
- Open the authors entry in the settings collection
- Update the author descriptions to be distinct
( editor have to be on visual mode, markdown disabled )
- Reorder the authors
- Check the descriptions
- Before, the descriptions wasn't correctly updated, now it should be correct.
After component did update, check the editor content is the same that the state value.
If it isn't the same, reset the state using a mutualized `createState` method.
I think it isn't the cleanest way to fix this bug.
It's better than nothing but if you have any other idea ...
=> Fix list item reordering #437

docs/architecture.md, docs/custom-authentication.md, docs/customization.md, docs/editorial-workflow.md, docs/extending.md, docs/intro.md, docs/quick-start.md, docs/test-drive.md, docs/validation.md, docs/widgets.md
**- Summary**
Read through all the .md files under /docs/ and copy edited. Primarily made changes to sentences to clean up structure and usage. Some minor grammar and general typo edits.
Editing for style, usage, consistency, etc. is how I can best contribute (not a coder; professional writer/editor) to this repo.
Cleaned up and (hopefully) help make docs more readable and usable by the end user.
No tests since changes were strictly to copy; no code changes.
Copy edits to /docs/ to improve consistency & readability
My dog & co-editor Psycho!
=> misc edits in /docs; mostly style, grammar, consistency

package.json, src/components/AppHeader/AppHeader.js, src/components/UnpublishedListing/UnpublishedListing.js, src/containers/App.js
**- Summary**
Removed pluralization of collection names in the CMS.
As suggested, this is the minimalist fix for #422
Pass all current tests and no additional tests required.
Stopped the pluralization of collection name
=> Stopped the pluralization of collection name

src/backends/github/API.js
**- Summary**
Makes comparison of repo names from the config and the GitHub API case-insensitive since GitHub's user and repo names are case-insensitive. Fixes #510.
Make GitHub repo name comparison case-insensitive
=> Make GitHub repo name comparison case-insensitive (fixes #510)

src/actions/editorialWorkflow.js
**- Summary**
Fixes an error that was showing up in the console when saving a post in the editorial workflow.
The removed `dispatch(closeEntry)` is handled in the code that's been erroring out (in `EntryPage.js`). User-visible functionality is identical.
Tested manually. The error only ocurred in one scenario, and is no longer reproducible.
Fixes an error that was showing up in the console when saving a post in the editorial workflow.
=> Fix runtime error on saving post in editorial workflow

package.json, yarn.lock
**- Summary**
Just adds the development package `eslint-import-resolver-webpack`,
which is [already configured][0], but not previously installed. This
removes a _lot_ of incorrect eslint errors.
[0]: https://github.com/netlify/netlify-cms/blob/2d344ef4caa5e21866a61c077b19ee7f64120d9b/.eslintrc#L6-L10
Manually tested eslint; incorrect errors are no longer present.
Fix incorrect eslint import errors
=> Fix incorrect eslint import errors

src/formats/formats.js
**- Summary**
Makes "yml" and "yaml" synonyms for both file extensions and format
settings. Makes YAML work as the output format for `format: yml` and
`extension: yaml` settings on collections.
Fix confusing "yaml/yml" distinction in formats.js
=> Fix confusing "yaml/yml" distinction in formats.js

docs/quick-start.md
**- Summary**
I was recently trying to integrate NetlifyCMS with Netlify service and Gatsby.js. I found an open [issue](https://github.com/gatsbyjs/gatsby/issues/623) on Gatsby's repo on possible GUI for the app. I'm still in the process of making both work well, though since I also found an article [on your blog](https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify/) and given the increasing interest in the JAM stack, I decided this suggestion might be useful :)
Simple updates in documentation :)
Notes for integrating with Gatsby statis site generator.
=> Suggestion for adding Gatsby JS

src/backends/test-repo/implementation.js
**- Summary**
Fixes #537.
Deletion was added in #485, but the function for the `test-repo` backend was `deleteEntry` instead of `deleteFile` like it was supposed to be. Therefore, files could not be deleted.
Also, setting the key for a deleted file to `undefined` did not really remove that file from the object, so there were then errors stating `file.content` is not defined. `delete`ing the "file" from the object fixes this bug.
Manually tested with `npm run start`, then adding and deleting posts. Also deleted some default posts.
Fix broken entry deletion for the `test-repo` backend.
=> Fix deletion for the `test-repo` backend.

src/backends/github/API.js, src/backends/github/implementation.js
**- Summary**
`isCollaborator` was created in #491 to block login if a user did not have write (push) permissions to a repo, by going through the list of a users repos until it found the right one. It did not institute pagination, however, so if a user had enough repos that the one in question was on another page, the CMS would assume that they did not have permission and block the login. Since there are only about 30 repos per page, this is a fairly significant bug.
This commit fixes the problem by calling the API for the specific repo instead of getting the whole list.
Tested manually before and after:
- repo w/permissions.
Tested errors after:
- repo w/o permissions (no permission error).
- non-existing repo ("Not Found" error).
Fix …
=> Fix denied login for users with many repos.

src/actions/entries.js
**- Summary**
Fixes #555:
> Currently, if the user tries to save an entry, but the backend has an error, the page still tries to redirect back to the dashboard. However, since the page is not saved yet, the user is presented with a popup: "Are you sure you want to leave this page?". If they click "OK", their content is lost. After the popup is closed (OK or Cancel), the red error notification show up: "Failed to persist entry: API_ERROR: ...".
Manually tested with the `test-repo` backend by returning a rejected promise from `persistEntry` and `deleteFile`.
Do not close entry page if the entry failed to save or delete.
=> Do not close entry page if it failed to save or delete.

src/components/Widgets/NumberControl.js
**- Summary**
Number editor creates strings not numbers. Use parseInt to ensure a number is created.
Tested manually, issue noticed because Jekyll's sort complained. (Couldn't find the widget tests? But didn't look too hard :-s It's a pretty trivial change...)
Ensure Number widget saves values as numbers not strings.
=> Number editor return number.

src/components/Widgets/Markdown/serializers/__tests__/remarkEscapeMarkdownEntities.spec.js, src/components/Widgets/Markdown/serializers/index.js, src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js
**- Summary**
When markdown entities are entered in the visual editor, they are not escaped in the underlying markdown, which results in the entities being unintentionally parsed as raw markdown.
Closes #558.
Tested in the editor, provided unit tests.
- escape markdown entities entered as literal text
=> escape markdown entities entered as literal text

package.json, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/__snapshots__/parser.spec.js.snap, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/plugins.js, src/components/Widgets/Markdown/serializers/index.js, src/components/Widgets/Markdown/serializers/remarkSlate.js, src/components/Widgets/Markdown/serializers/slateRemark.js, yarn.lock
Allows soft breaks to be read/entered in raw markdown via double trailing spaces or trailing backslash. Soft breaks are always rewritten as trailing backslashes on stringify per the Commonmark spec.
Soft breaks can now also be entered in the visual editor via <kbd>Shift</kbd> + <kbd>Enter</kbd>.
=> add markdown editor soft break support

src/actions/editorialWorkflow.js, src/components/Widgets/Markdown/MarkdownControl/RawEditor/index.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/parser.spec.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/index.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/plugins.js, src/components/Widgets/Markdown/MarkdownControl/index.js, src/components/Widgets/Markdown/MarkdownPreview/__tests__/renderer.spec.js, src/components/Widgets/Markdown/MarkdownPreview/index.js, src/components/Widgets/Markdown/serializers/index.js, src/components/Widgets/Markdown/serializers/remarkSlate.js
- remove JIT serialization of markdown widget values
- debounce markdown widget change handler to improve performance
- fix broken editorial workflow (regression from #254, missing import)
- close heading blocks on <kbd>Enter</kbd>
=> Markdown editor improvements

docs/test-drive.md
**- Summary**
The docs for adding an authentication provider to your Netlify site still had instructions for the old Netlify interface.
Update docs for new Netlify auth provider interface.
=> Docs: Update the authentication provider docs for the new Netlify interface.

src/components/EntryEditor/EntryEditor.js, src/components/EntryEditor/EntryEditorToolbar.js, src/components/EntryEditor/__tests__/EntryEditorToolbar.spec.js, src/components/EntryEditor/__tests__/__snapshots__/EntryEditorToolbar.spec.js.snap, src/containers/EntryPage.js
**- Summary**
Fixes #573.
This disables the "Save" button until a user has changed an entry. This also applies to new entries -- the user must modify a field before the "Save" button works.
@erquhart Do you think it is worth naming the prop that is passed to the component something other than `hasChanged`, kind of like was done for `showDelete`?
Manually tested using example config.
Disable "Save" button when entry has no changes.
=> Disable "Save" button when entry has not been changed.

src/reducers/collections.js
**- Summary**
If the `folder` for a collection has a trailing slash in the config, this breaks the collection when another slash is added. This PR fixes this by trimming a trailing slash from the folder value if it exists.
Fixes #615.
Manually tested with config from #615 and example config.
Fix collections breaking if folder has trailing slash.
=> Fix collections breaking if folder has trailing slash.

.gitignore, package.json, src/components/Widgets/Markdown/serializers/remarkPaddedLinks.js
**- Summary**
This is a first step towards adding support for a 3rd party code coverage service. It adds code coverage output to the npm test command.
on your command line run 
```
npm test
```
verify you see the code coverage output as a result of the test.
verify the coverage folder is generated with the lconv output. 
verify the coverage folder is ignored by git. 
Add code coverage to ```npm test```
=> Add code coverage output generation to npm test

.travis.yml, codecov.yml
**- Summary**
depends on: https://github.com/netlify/netlify-cms/pull/610
closes: https://github.com/netlify/netlify-cms/pull/609
This PR will add codecov reporting to the build process.
For this to properly work someone will need to 
1. goto https://codecov.io/gh/netlify/netlify-cms/settings and authorize codecov
2.  copy the repository upload token.
3. goto https://travis-ci.org/netlify/netlify-cms/settings
4. add an environment variable named CODECOV_TOKEN with the value of the repository upload token.
Do the above and then merge. The following master build should update the baseline info in codecov. In my experience it takes a few PRs and builds for codecov to start reporting properly.
Add codecov reporting to the build process.
=> Add codecov reporting  to build process.

package.json, src/formats/frontmatter.js, webpack.base.js, yarn.lock
**- Summary**
This PR contains multiple commits that focus on making the bundled YAML and TOML parsers have a smaller bundle size.
- Remove Esprima from the `js-yaml` bundle.
According to the `js-yaml` docs, it is only needed if you are trying
to parse JS functions in/out of JSON, which we are not doing.
- Switch to a smaller/faster TOML parser.
@erquhart and I had previously looked at a new(er) TOML parser, `toml-j0.4`, that is much smaller and *way* faster than the one we are using now. It is also fully spec-compliant.
~ https://github.com/jakwings/toml-j0.4/issues/3
Tested input/output of each parser to make sure it was still valid. Use kitchen sink and some other tests.
Make YAML and TOML parsers' bundle smaller.
**- A picture of a …
=> Make YAML and TOML parsers' bundle smaller

docs/quick-start.md
**- Summary**
The Gatsby instructions that were added in #527 didn't actually need to be that complex. I tested the template that the author had, and the problem with it not showing up at `/admin/index.html` was that the script was in the `head` instead of in `body`. There is still a small difference with `gatsby develop` -- you must go to `/admin/index.html` instead of `/admin`, so I left that as a note.
N/A -- docs update
Make Gatsby setup docs simpler.
=> Make Gatsby setup docs simpler.

package.json, src/components/Widgets/Markdown/MarkdownControl/RawEditor/index.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/__snapshots__/parser.spec.js.snap, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/index.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/keys.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/plugins.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/rules.js, src/components/Widgets/Markdown/serializers/remarkSlate.js, src/components/Widgets/Markdown/serializers/slateRemark.js, yarn.lock
Migrate from Slate 0.21 to 0.25 - related changelog [here](https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md).
=> Migrate to Slate 0.25

src/components/Widgets/Markdown/MarkdownControl/VisualEditor/__tests__/__snapshots__/parser.spec.js.snap, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/keys.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/plugins.js, src/components/Widgets/Markdown/MarkdownControl/VisualEditor/rules.js, src/components/Widgets/Markdown/serializers/__tests__/slate.spec.js, src/components/Widgets/Markdown/serializers/index.js, src/components/Widgets/Markdown/serializers/remarkEscapeMarkdownEntities.js, src/components/Widgets/Markdown/serializers/remarkSlate.js, src/components/Widgets/Markdown/serializers/remarkSquashReferences.js
Bugfixes and improvements for the new Slate editor. Continuation of #629. Closes #575.
**NOTE: merge after #638**
=> Editor fast follow

src/backends/backend.js, src/backends/git-gateway/implementation.js, src/backends/github/implementation.js, src/backends/test-repo/implementation.js
**- Summary**
Fixes #556.
Before, if the CMS was loading user OAuth credentials from `localStorage`, then user write access would not be checked again. However, the `config.yml` repo could be changed, which would cause the user to be still logged in even if they did not have write permissions. Also, if the user had updated their metadata (avatar, etc.), the CMS would not update that either.
The main change that this PR makes is that it expects `setUser` to return a rehydrated user object, instead of just taking the user object that it was fed and using it.
Check user permissions and metadata *every* CMS load.
=> Check user permissions and metadata every CMS load.

package.json
This was breaking some sites that depended on the CMS because they were
accidentally using storybook's deps instead of adding them as their own
(particularly the babel presets). We are going to hold off on this until
the next version so that we can add a release warning.
This reverts commit 4634918001e474ec2f195fbdddae18591d3207ab.
=> Move storybook back to dev deps.

src/backends/git-gateway/API.js
**- Summary**
Adds a cachebuster to GitHub API calls made by the `git-gateway` backend. This closes the last reported instance of #308.
Tested manually and added to @neutyp's user testing site. Neither test was able to reproduce the recurrence of the fast-forward error.
Add cachebuster to `git-gateway` API calls.
=> Add cachebuster to git-gateway API calls

docs/quick-start.md
Addresses part of #600
**- Summary**
Updates the Quick Start doc to use Netlify Identity and Git Gateway.
You can check the GitHub rendering at
https://github.com/netlify/netlify-cms/blob/quick-start-identity/docs/quick-start.md
(Note that the links to Intro and Quick Start at the end of the doc will not work in this view, due to issues discussed in #511)
I'm also pushing a temporary branch to netlify-cms-www to test rendering on netlifycms.org:
https://quick-start-test--netlify-cms-www.netlify.com/docs/quick-start/
Update the Quick Start doc to use Netlify Identity and Git Gateway.
OK, maybe not cute, but kind of funny? 😜
=> Re-write Quick Start with Identity/Git Gateway

src/index.js
**- Summary**
This causes the index.html from /example to be included in the `dist` and published to the npm package.
Deploy should show no side affects, since this is a build issue.
Development `yarn start` runs with no side affects.
Run a build command to make sure the `index.html` file is excluded from the build.
Remove the distribution of the index.html example file into the package `dist` folder.
=> Removes the index.html from the dist folder on build

src/containers/App.js, src/lib/urlHelper.js
**- Summary**
Right now we use `/collections/:name/entries/new` to create a new entry, but this prevents any entry that has a slug of `new` from being edited. This PR changes the path to be `/collections/:name/new` instead.
Closes #692.
Manually tested creating new entries with example site (simple and editorial workflow). Also tested with filename slug set to `new`.
Fix CMS path to create new entries.
=> Fix CMS path to create new entries.

.babelrc, package.json, yarn.lock
**- Summary**
This allows only the transpilation needed for the supported browsers to be done. It also allows us to use the upgrades from ES2016 and ES2017 without needing to add a separate preset.
Manual testing showed no regressions.
Use babel-preset-env instead of the yearly presets.
=> Use babel-preset-env instead of the yearly presets.

package.json, webpack.base.js, yarn.lock
**- Summary**
Remove any pollyfill shims for IE11 and stop targeting in babel env
Closes #695 
Replaces and Closes #699 
Replaces and Closes #698 
Test known browsers.
There was a full discussion on including polyfills for IE11 alone and it was agreed to drop support for IE11 in the CMS.
Benifits will include a smaller code base and not having to manage the polyfills.
=> Remove ie11 support

src/components/AppHeader/AppHeader.js, src/components/Widgets/Markdown/MarkdownControl/Toolbar/ToolbarComponentsMenu.js
**- Summary**
Maps are actually invalid, and lists make more sense than sequences. This removes the React warning, and should make us compatible with React 16.
These two menus still work normally.
BUGFIX: Use Lists for menu items, instead of maps or sequences.
=> Use Lists for menu items, instead of maps or sequences.

docs/quick-start.md
**- Summary**
The Editorial Workflow link is set up to work within GitHub but redirects to a 404 page on the actual Docs site.
Editorial Workflow link will navigate to `/docs/editorial-workflow/` (correct URL) instead of `/docs/quick-start/editorial-workflow.md` (does not exist).
Fix broken Editorial Workflow link
=> Fix broken Editorial Workflow link

src/containers/EntryPage.js
**- Summary**
There is a small regression as of React 16: If someone edits an entry, then without saving, they exit the entry editor, they are presented with two confirm dialogs, instead of just one.
The normal flow:
1. User clicks Home button to go to Dashboard.
2. User is prompted to save changes. **If changes Rejected:**
1. Location changed to `/`.
2. `DRAFT_DISCARD` runs.
3. Location redirects to default entry listing (e.g. `/collections/posts`)
The current (broken) flow:
1. User clicks Home button to go to Dashboard.
2. User is prompted to save changes. **If changes Rejected:**
1. Location changed to `/`.
2. Location redirects to default entry listing (e.g. `/collections/posts`)
3. `DRAFT_DISCARD` runs.
The change comes where 2.ii. and 2.iii. are switched.
This may be related to …
=> Fix EntryPage showing double confirmations if changes not saved.

package.json, src/components/Widgets/ListControl.css, src/components/Widgets/ListControl.js, yarn.lock
**- Summary**
Migrates ListControl from `react-sortable` to `react-sortable-hoc` and enables drag handles. Closes #431.
(this may be closed in favor of a PR using https://github.com/atlassian/react-beautiful-dnd)
Manually tested, including nested lists.
Migrate ListControl from react-sortable to react-sortable-hoc
=> Migrate ListControl from react-sortable to react-sortable-hoc

src/components/EntryListing/EntryListing.js
**- Summary**
When clicking on a entry in the listing, a console error would be logged
by `history` (react-router): "Hash history cannot push state; it is
ignored". This was caused because using `bind` in the click handler
caused the return value to be passed to the `history.push` as the second
param. This was ignored in react-router v2, but gives a warning in v4.
Opening an entry works fine, with no console error.
Fix `history` warning when opening entry.
=> Fix history warning when opening entry.

src/actions/editorialWorkflow.js
Related to #555, extends #566 fix to also cover editorial workflow.
=> stop navigation on failed entry save in editorial workflow

package.json
**- Summary**
Move React Storybook and React Hot Loader to development dependencies. More detail in #671.
Closes #671.
PLEASE DO NOT MERGE into a patch release, wait for 0.6.0.
=> (WIP: 0.6.0) Move storybook and react-hot-loader to dev deps.

src/components/EntryEditor/EntryEditor.css, src/components/EntryEditor/EntryEditor.js, src/components/ScrollSync/ScrollSync.js
Closes #532 
**- Summary**
- A new button allows the user to toggle preview auto-scroll behaviour.
- This button is only rendered when preview is enabled
- Button state is stored and read via localStorage (same as preview button)
- Uses `sync` and `sync-disabled` icon
Manually tested UI (see screen capture). If I should be adding formal tests, please let me know.
Added button to toggle preview scroll-sync.
=> Add ScrollSync Button to Preview UI

src/reducers/collections.js
**- Summary**
If a collection has `format: toml`, the files will still be saved with the `.undefined` file extension unless the extensions is explicitly specified.
Create a collection with `format: toml` set.
Fix TOML files not being saved with correct file extension.
=> Fix TOML files not being saved with correct file extension.

src/formats/__tests__/frontmatter.spec.js, src/formats/formats.js, src/formats/frontmatter.js, src/formats/json.js, src/formats/toml.js, src/formats/yaml.js, src/reducers/collections.js
**- Summary**
This PR aims to clean up the `/src/formats` code.
@erquhart @Benaiah What do you think on "Use same parsers for files and frontmatter."? I think this will be better to retain consistency in the future -- so things like AssetProxy and Moment.js can be interpreted correctly in frontmatter as well (instead of just in the data-file formatters).
FOR REVIEW: The easiest way to review this PR will probably be to review each commit separately, the history should be clean.
Tested manually with example site to ensure files are still being saved with correct format/extension.
Cleanup file formatters.
=> Cleanup file formatters.

example/config.yml, src/backends/backend.js, src/containers/editorialWorkflow/EntryPageHOC.js, src/reducers/collections.js
**- Summary**
Fixes #593. Adds a `delete` flag to collections in `config.yml`. Defaults to false. This is mostly for use with files to restrict users from deleting settings files etc that are available via the CMS but can also be used to restrict the ability to delete within any collection.
I'm currently not 100% sure about the how it should handle `delete` not being set for a collection. Ideally I'd have it like I've implemented where if `delete` is not set then it counts as `false`. This is how the `create` flag works. My only worry is that when this feature is implemented and users upgrade they will suddenly find that unless they add the flag that they can't delete documents they could previously? 
**EDIT — This now defaults to `true`**
Manually tested using example …
=> Add delete flag in configuration

src/actions/auth.js, src/backends/git-gateway/AuthenticationPage.js, src/backends/github/AuthenticationPage.js, src/backends/test-repo/AuthenticationPage.js, src/containers/App.js, src/reducers/auth.js
**- Summary**
Since the authentication can occur in another window, or it can occur behind the scenes when restoring locally saved credentials, the login button should be disabled while the login is running. This makes it clearer for the user.
Login works normally. The login button is disabled while logging in (or restoring login).
Disable login button while login is in progress.
=> Disable login button while login is in progress.

src/components/Widgets/Markdown/MarkdownControl/VisualEditor/index.js
**- Summary**
Fixes #700 using the [`activeMarks` property](https://github.com/ianstormtaylor/slate/blob/master/docs/reference/slate/value.md#activemarks)
Turn off style toggle on pressing Enter
=> Turn off style toggle on Enter

src/components/Widgets/ListControl.css
**- Summary**
Fixes #755  
Screencap:
Add background-color to list widget
=> Add background-color to list widget

package.json, webpack.prod.js, yarn.lock
Adds a js sourcemap to the build output for debugging purposes. Uses `uglify-js-webpack-plugin` directly to ensure latest version (as opposed to `webpack.optimize.UglifyJsPlugin`).
=> Upgrade uglify-js-webpack-plugin, enable sourcemaps

src/components/Widgets/SelectControl.js
**- Summary**
Add a "not selected" option to the select widget when there is no default set. Closes #562.
Add unselected option to select widget when no default is set.
=> Add unselected option to select widget when no default is set

src/backends/github/implementation.js
**- Summary**
Closes #788.
Images weren't visible until refresh after uploading in Git Gateway. Fixes image url construction by pulling the username/repo from the response url if no repo is set in the CMS config (as is the case in Git Gateway installations).
=> fix image not shown after upload for git gateway

src/reducers/mediaLibrary.js
Fixes error from default `files` value not being provided when loading an empty media folder.
=> fix empty media folder loading error

src/actions/editorialWorkflow.js, src/backends/backend.js, src/containers/editorialWorkflow/UnpublishedEntriesPanel.js, src/formats/formats.js
**- Summary**
When entries were loaded for the editorial workflow dashboard, they were
all assumed to be FrontMatter/MarkDown files. This PR allows them to be
any supported format.
Fixes #743.
Tested use case in #743.
Also tested simple workflow -- no regressions found.
Fix other than markdown editorial workflow entries on dashboard.
=> Fix other than markdown editorial workflow entries on dashboard.

src/backends/git-gateway/implementation.js
**- Summary**
The actual code was invalid here. I haven't done much work with `git-gateway` yet, so I don't completely understand the code, but this looks like the right place to put it. Fixes #792.
Logging into `git-gateway`, both with and without `accept_roles`, seems to work normally.
Fix no users being allowed to login when `accept_roles` set.
=> Fix no users being allowed to login when `accept_roles` set.

src/components/PreviewPane/PreviewPane.js, src/components/UI/ErrorBoundary/ErrorBoundary.css, src/components/UI/ErrorBoundary/ErrorBoundary.js, src/index.css
Related to #778, doesn't quite close.
=> add generic error boundary, apply to preview iframe

src/actions/editorialWorkflow.js, src/backends/backend.js, src/backends/github/API.js
Editorial workflow pull requests are rebased if the base has
changed to ensure that asset changes on the base branch are
reflected in the PR branch, but if an asset store is in use,
no rebasing is necessary because assets are stored outside
of the content repo.
=> only rebase EW PR if no asset store

src/actions/auth.js, src/reducers/auth.js
**- Summary**
This was causing users to not be able to sign up with Netlify Identity.
=> Stop using `logout` when no locally stored user was found.

src/formats/__tests__/frontmatter.spec.js, src/formats/frontmatter.js
**- Summary**
Trying to save a page that does not have a value for body results in an error. This is a regression from #759, which removed the default value for `body`.
If you try to save the Kitchen Sink entry you'll end up with the following error:
```
Uncaught TypeError: Cannot read property 'content' of undefined
at module.exports (stringify.js?2ea5:23)
at Function.matter.stringify (index.js?1c62:131)
at Object.toFile (frontmatter.js?cfa9:57)
at Backend.entryToRaw (backend.js?bb12:303)
at Backend.persistEntry (backend.js?bb12:239)
at eval (entries.js?c1a9:300)
at eval (index.js?8bff:9)
at eval (bindActionCreators.js?45eb:3)
at eval (EntryPage.js?2e7b:109)
```
Or run new `should stringify YAML with missing body` test in `frontmatter.spec.js`.
**- Description for the …
=> Fix persist with missing body from file (regression from #759)

src/components/Widgets/ControlHOC.js, src/components/Widgets/RelationControl.js
If a widget uses `connect` to receive state updates from the store, `ControlHOC` can no longer get the control instance ref. This fix checks for this case and uses a connect option to obtain the wrapped control ref.
=> fix ControlHOC ref for redux container widgets

src/backends/backend.js
#804 checked the `integrations` state object with the assumption that a truthy default state (like `Map()`) was provided - this fix checks for existence first. Not switching default to `Map()` to ensure against unexpected breaks.
=> update integrations check to account for null default state

package.json, setupTests.js, yarn.lock
**- Summary**
React 16 needs `requestAnimationFrame` in it's environment, and this does not exist in the test environment. This PR adds a polyfill to the test environment only,
Tests pass.
Fix requestAnimationFrame warnings in tests.
=> Fix requestAnimationFrame warnings in tests.

src/backends/github/API.js
In some cases we're calling the dir listing with a trailing slash, which causes extra redirects from GitHub's API (and breaks the git-gateway backend). This should make sure we always trip trailing slashes.
=> Make sure we strip trailing slashes for dir listing

src/components/MediaLibrary/MediaLibrary.js
There are a few places where we filter assets down to just images using an array of lowercase extensions, but we weren't converting the file extensions to lowercase prior to comparison. This fixes that.
=> fix image filtering case sensitivity

src/containers/EntryPage.js
**- Summary**
Prompts before closing the entry page if there are unsaved changes present. Closes https://github.com/netlify/netlify-cms/issues/286.
Prompt before exiting tab with unsaved changes
=> Prompt before exiting tab with unsaved changes

src/actions/mediaLibrary.js, src/components/MediaLibrary/MediaLibrary.css, src/components/MediaLibrary/MediaLibrary.js, src/components/Widgets/FileControl.js, src/components/Widgets/ImageControl.js, src/integrations/providers/assetStore/implementation.js, src/reducers/mediaLibrary.js
For users of custom asset store integrations, "private" assets requiring authentication for read access can be uploaded through the CMS. This PR adds media library support for private asset handling:
* Switches to a "private" mode when launched from an image or file widget configured as private
* Resets media library state to default when switching in and out of private mode
* Ignores async media library state changes from that did not originate from the current mode
* Visually distinct so the user knows they're viewing private assets
There is a possibility that a user could experience non-destructive bugs by initiating a long async request, like an upload, and then switching modes twice to arrive back in the same mode before the request finishes. Documented in #835.
=> add private media library for integrations

src/index.js
**- Summary**
Closes #828.
Does anyone think we need a more through fix, i.e. returning an empty string instead of `null` or `undefined`?
=> Fix empty image fields saving null or undefined.

webpack.prod.js
**- Summary**
WebPack 3 now has scope hoisting, which optimizes bundle speed at runtime. It also decreases bundle size, though the change is small. This is basically the main benefit that Rollup was designed with, except failsafe (more info here: https://medium.com/webpack/webpack-freelancing-log-book-week-5-7-4764be3266f5).
For now, this is only enabled for the production build, as it would break Hot Module Reloading.
CMS deploy preview seems to work fine for me (but that probably isn't much good as a test 😁).
Enable WebPack scope hoisting.
=> Enable WebPack scope hoisting.

package.json, yarn.lock
Making sure we use the same gotrue in the CMS as in identity-widget
=> Update bundled version of gotrue-js to latest

src/index.js
**- Summary**
This adds an error boundary around the entire app, so that a crash does
not just show up as an empty white screen.
Manually threw in UI code, made sure entire app was dismounted and replaced with error message.
Add global error boundary.
=> Add global error boundary.

docs/widgets.md, src/components/Widgets/DateControl.js, src/components/Widgets/DateTimeControl.js
An earlier change broke the `format` attribute for date and datetime widgets (see #529).
Before this was handled by always treating the value as a `moment` object and having the YAML serializer respect that.
This takes a slightly different approach and always treats the value of date and datetime widgets as a formatted string. If we take this approach we should get rid of the moment specific code for formats in the YAML serializer.
The downside of this is that some future supported formats might handle actual date/datetime objects - but it seems this is the only approach I can think of where the `format` attribute would be respected across any output format apart from that...
=> Datetime format

src/components/Widgets/Markdown/MarkdownControl/VisualEditor/plugins.js
**- Summary**
Fixes #846 Backspace removes empty blocks
- `onKeyDown` takes 2 arguments, not 3.
- And `backspace` starts with an uppercase.
- Consequently others functions `SoftBreak`, `BreakToDefaultBlock` should have the issue.
=> Fixes #846 Backspace removes empty blocks

docs/widgets.md
**- Summary**
This helps people new to the platform with using the select widget and removes the need to go digging through code to work out the implementation. 
Used english dictionary
closes #764
Added basic documentation for select widget
=> Added basic documentation for select widget

src/formats/formats.js
**- Summary**
Before, we always tried to infer a file's format, even if it was
explicitly specified in the collection's config. This commit makes it so
that we always use the format from the config if it is specified, and
only if it is not set do we try to infer it from the file extension.
Fixes #763.
NOTE: Please review this fairly intensely -- I really don't want to break anything (don't think you are either).
Used CMS `/example`, as well as test case in the related issue.
Do not infer file format if collection specified.
=> Do not infer file format if collection specified.

src/formats/formats.js
**- Summary**
If a collection has no format specified, we try to infer the format from
the file extension when reading. This commit also allows us to infer the
format from the `extension` set in the config, so that we can still
create the correct format when making a new file.
Fixes #776.
(Re)based on #795.
=> Infer format from extension for new entries.

src/formats/formats.js, src/reducers/collections.js
**- Summary**
Closes #797.
If a format is specified that is unsupported, throw instead of just saving as markdown/frontmatter.
(Re)based on #795.
No regressions seen on `/example` site.
Threw if unsupported format set.
Throw on unsupported format.
=> Throw on unsupported format.

website/site/content/docs/collection-types.md, website/src/css/imports/base.css
- Summary
Closes #679
Most collection fields will be covered in the upcoming configuration doc (#685), but the difference between file, folder, and filter collections requires enough explanation to merit a separate doc. This will be linked from the config doc, and when it's complete, this doc will link back to the config doc.
- Test plan
Preview: https://docs-collection-types--netlify-cms-www.netlify.com/docs/collection-types/
- Description for the changelog
Add documentation about different types of collections
- A picture of a cute animal (not mandatory but encouraged)
No time for cuteness!
=> Add collection types doc

src/components/Editor/EditorInterface.css
=> Fix position of editor view controls

website/site/content/docs/intro.md
=> Update intro to direct to new content

website/config/variables.js, website/site/content/docs/add-to-your-site.md, website/site/content/docs/authentication-backends.md, website/site/content/docs/configuration-options.md, website/site/content/docs/start-with-a-template.md, website/src/css/imports/base.css
- Updates a few links so they point to the correct doc titles
- Changes inline page links to absolute so links aren't broken in the GitHub repo view
- Re-add the default 16px bottom-margin to paragraphs (with adjustment to offset minor effects on landing page)
=> Minor docs fixes

website/site/content/docs/collection-types.md
**- Summary**
I mistakenly thought that top-level `file` collections were a thing, and they're not.
The wording is a little funky, so I'm happy to take improvements, but on the other hand, I'd like to get the incorrect docs replaced as soon as possible. Better to merge this as correct but funky, then improve the wording later.
Check the preview! :)
=> Docs: Remove top-level file collection info (oops!)

src/actions/mediaLibrary.js, src/components/MediaLibrary/MediaLibrary.js
**- Summary**
Fixes #783 Duplicate uploading same asset name
Upload an image with the same name, it will ask you to replace the existing one.
Juste check existing files name
=> Fix #783 duplicate uploading same asset name

package.json, src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/keys.js, src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/plugins.js
**- Summary**
Fixes #855 Update Slate plugins to drop data arg
- Check SoftBreak and BreakToDefaultBlock are okay.
- Check you can use `cmd + z` and `cmd + y` to undo and redo.
- Check you can toggle marks with `cmd + ( b, i, s, u )`.
- Remove data arg due to breaking changes introduced in [0.6.0](https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md#060--october-16-2017).
- Use [is-hotkey](https://github.com/ianstormtaylor/is-hotkey).
- Fix underline typo for togglemark `cmd + u` ( but doesn't work either it throws an error ).
- Check next is defined before changeHistory to avoid error length of undefined.
=> Fixes #855 Update Slate plugins to drop data arg

src/components/Collection/Entries/EntriesCollection.js, src/components/Collection/Entries/EntriesSearch.js
Fix infinite scroll regression introduced in 1.0.
=> fix infinite scrolling for collections with integrations

src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.js
I added this in the UI update to fix markdown widget state persisting across entries (#754), but it was rushed and introduced odd regressions like #901.
Closes #901.
=> fix markdown widget re-rendering on load

src/components/MarkdownPlugins/image.js
Fixes #895 : Adding an image to an empty rich text editor doesn't trigger the Image widget.
**- Summary**
- Improve RegExp
- Do not fallback undefined alt to an empty string.
Input will be filled with `undefined` label ( the youtube widget has this behavior ).
Add an image to an empty rich text editor
- Improve RegExp
- Do not fallback undefined alt to an empty string
Input will be filled with `undefined` label ( the youtube widget has this behavior ).
=> #895 Adding an image to an empty rich text editor doesn't trigger the Image widget

src/components/EditorWidgets/List/ListControl.js, src/components/EditorWidgets/Object/Object.css, src/components/EditorWidgets/Object/ObjectControl.js
**- Add collapse/expand button to object widget**
Resolves #851
=> Collapse object widgets

website/site/content/docs/add-to-your-site.md, website/site/content/docs/start-with-a-template.md
... because going to `siteaddress.com/admin` doesn't always work.
=> Add trailing slash to /admin links in docs

src/components/EditorWidgets/List/ListControl.js
Fixes some gaps where `defaultProps` doesn't work because a `null` value was explicitly supplied.
=> fix list widget default values

src/components/Collection/Sidebar.css, src/components/UI/Toggle/Toggle.css
Hi there. In my PR I have included small fixes for the issue 907. Whilst doing this I noticed something small, not really worth an issue. The `nc-toggle-switch` button gets given the class of `undefined` when editing a post. I tracked this down to the file `src/components/UI/Toggle` getting passed `classNameSwitch` which in this case was not passed into it. My proposed solution for this is below. 
Also really love the work that everyone put into this :)
```javascript
import React from 'react'
import ReactToggled from 'react-toggled';
import c from 'classnames';
export const Toggle = ({
active,
onChange,
className,
classNameBackground,
classNameSwitch = '',
onFocus,
onBlur
}) =>
<ReactToggled on={active} onToggle={onChange}>
{({on, getElementTogglerProps}) => (
<span …
```
=>  Fixes for #907

src/valueObjects/AssetProxy.js
**- Summary**
Before we had the media library, we used uploaded image data directly when it was first uploaded, since it was likely not deployed yet. With the media library, we should be able to do this as well.
@erquhart Is this the correct fix, or do we need more in-depth changes?
=> Use cached images for new uploads

src/backends/github/API.js, src/lib/LocalForage.js
I got many errors in log and after investigating: quota for temporary storage was full due to disk full. Maybe useful test in this PR.
(https://www.html5rocks.com/en/tutorials/offline/quota-research/)
cheers
=> LocalForageTest

src/backends/github/implementation.js, src/components/MediaLibrary/MediaLibrary.js
**- Summary**
In the media library, SVG media loaded from https://raw.githubusercontent.com was unable to be displayed due to github's response content-type set to *text/plain* rather than *image/svg+xml*.
Appending a `sanitize=true` query to the url allows github to return the correct content-type.  
Example working SVG preview:  
Enable SVG preview in media library.
=> GitHub svg media library preview support

website/site/content/docs/custom-widgets.md
The sample given in the documentation for `registerEditorComponent` does not work. The component is not correctly detected in the markdown content.
The problem is with the pattern given which does not match anything. The PR changes the documentation so that the given example works correctly.
=> fix registerEditorComponent example

website/site/content/docs/custom-widgets.md
**- Summary**
The [Custom Widgets docs page](https://www.netlifycms.org/docs/custom-widgets/) has a code example missing line breaks, making it hard to read.
Fix missing line breaks in Custom Widgets docs page.
=> Fix missing line breaks in code example in Custom Widgets documentation

src/backends/github/API.js
**- Summary**
This happens when a PR must be approved first, and the user does not have force-merge permissions to override the review requirement. Before, the CMS was simply deleting the branch/PR and reporting success, whereas it should report failure and leave the branch open until an admin can merge.
Fixes https://github.com/netlify/netlify-cms/issues/1019.
Fix showing success message if PR force-merge fails.
[![mikhail-vasilyev-253977](https://user-images.githubusercontent.com/20345941/35022112-6a2125d8-faf1-11e7-87ba-e375d4cf3669.jpg)](https://unsplash.com/photos/NodtnCsLdTE)
=> Fix showing success message if PR force-merge fails.

src/components/Collection/Collection.js
Closes #997.
**- Summary**
Load any page and this appears in the console:
> Warning: Failed prop type: Invalid prop newEntryUrl of type boolean supplied to CollectionTop, expected string.
About the change, later `newEntryUrl` is evaluated on a truey/falsey base and used directly as a string, so we can supply an empty string and it will be evaluated as falsey just the same.
Load any page, warning shouldn't appear in the console.
Fix PropType warning in console.
=> Fix proptype warning

website/src/css/imports/cta.css
On the website, there is a wrong bottom margin below the CTA text on desktop. This removes it.
=> Fixes website CTA spacing on desktop

src/actions/entries.js, src/components/Editor/Editor.js, src/reducers/entryDraft.js, src/reducers/search.js
**- Summary**
Fixes #359 (regression)
- Not sure exactly when the regression happened, but the exact behavior described in #359 could be seen again for a few releases now.
- Tested manually in exactly the same way as in #360: adding, removing and updating any child of the list works, switching back and forth between pages and reloading the page has the correct metadata now.
- Tested also simple string relation fields, work as expected with the new code as well.
- Nothing to be changed in the docs, they don't really cover relation widgets much anyway.
- This definitely needs automated tests to prevent further regressions, but there's absolutely nothing covering relation fields already (that I could find), and I'm not familiar enough with the test platform or existing tests …
=> Fix relation lists (regression #359)

src/backends/backend.js, src/lib/registry.js
**- Summary**
A solution to register a custom backend API while also registering the internal API's so there is no overwriting of names.
The backends internally target `github` and the `git-gateway` without any changes to the CMS itself. This solution is a non breaking solution for the current CMS without having to change the internal backend's.
Make sure the CMS works as is using all current internal backends.
Test a custom created backend by registering the new backend `CMS.registerBackends("my-custom-backend", MyCustomBackendClass)`
Created an example [backend library here][1] (might look familiar to some of you)
Register Internal and Custom backend API's
🐶
[1]: …
=> Register Internal and Custom backend API's

.babelrc
**- Summary**
We added `babel-preset-env` before, but I was using the docs for the beta version instead of the released version, so it was actually still transpiling everything instead of just the stuff we needed.
=> Fix `babel-preset-env`.

src/backends/backend.js, src/formats/__tests__/frontmatter.spec.js, src/formats/formats.js, src/formats/frontmatter.js, src/formats/json.js, website/site/content/docs/configuration-options.md
**- Summary**
Right now we can read TOML or JSON frontmatter by inferring, but we can only write frontmatter in YAML. This change allows the frontmatter format to be explicitly set for reading and writing.
The `format` options are:
- `frontmatter` (**default**): Infer frontmatter format if possible, write to YAML.
- `json-frontmatter`: Read and write JSON frontmatter (`{` `}` delims), ignore other formats.
- `toml-frontmatter`: Read and write TOML frontmatter (`+++` delims), ignore other formats.
- `yaml-frontmatter`: Read and write YAML frontmatter (`---` delims), ignore other formats.
For now, we do not support custom delimiters, we use `---` for YAML, `+++` for TOML, and `{` `}` for JSON. If a frontmatter format is explicitly specified, and there is frontmatter inside other delimiters, …
=> Support writing frontmatter in multiple formats.

.babelrc, package.json, yarn.lock
WebPack version 1, which Gatsby is using, has the Acorn parser set to
parse ES6 and lower. The latest version of WebPack supports parsing up
to ES2017 and lower (webpack/lib/Parser.js), but Gatsby isn't using it.
This isn't something we want to do permanently, as packages should be able to do this themselves. We do have a lot of Gatsby users, though, so this is a temporary fix for now.
Closes https://github.com/netlify/netlify-cms/issues/1097.
=> Fix build for Gatsby (WebPack v1).

src/formats/__tests__/frontmatter.spec.js, src/formats/formats.js, website/site/content/docs/configuration-options.md
**- Summary**
This is a minor update on top of #1064 to allow different beginning and ending frontmatter delimiters.
Tests added. Also manually tested both with single and list.
=> Allow different beginning and ending frontmatter delimiters.

.babelrc, package.json, yarn.lock
Follow up to #1107, it seems babel-preset-env was conflicting with other babel plugins - in this case, spread operators weren't being transpiled.
=> remove babel-preset-env

src/components/EditorWidgets/List/ListControl.js
**- Summary**
If the first field in a list widget didn't return a string (or React component), the CMS would crash. This was because the CMS was trying to render the value of the first widget when a list item was collapsed, as explained in the related issue.
Fixes #1113.
Manually tested with date widget.
=> Fix list items crashing for first fields other than strings.

.babelrc, package.json, yarn.lock
Reverts netlify/netlify-cms#765
This reverts our build back to ES5 (needed for #1097).
=> Revert "Fix `babel-preset-env`."

src/backends/github/implementation.js, src/backends/test-repo/implementation.js, src/reducers/collections.js
**- Summary**
Fixes #877. See discussion there for context.
Manually tested. Is it worth mocking the API for `listFiles` to test this?
Support extensions with multiple parts (i.e. `en.md`).
Clean leading periods from extensions.
=> Support extensions with multiple parts (i.e. `en.md`)

src/components/Editor/Editor.js
**- Summary**
When changing status or publishing from the editor with unsaved changes, unsaved changes are lost.
Attempted changing status and publishing with unsaved changes. Both actions now result in a prompt to save before taking the attempted action.
Fix lost unsaved changes when updating status or publishing from editor
=> fix lost unsaved changes when updating status or publishing

package.json, webpack.dev-write.js, yarn.lock
This is necessary for local development in many scenarios, e.g. developing on the CMS and Gatsby sources simultaneously with a local test project. Been using it privately for months, tired of restoring it from stash every time I need it.
=> add dev task that writes output to disk

src/actions/editorialWorkflow.js, src/backends/backend.js
This addresses two issues:
1. `loadUnpublishedEntries` swallows errors, hiding them in both the console and the UI.
2. Unpublished entries from unknown collections crashes the editorial workflow on load. This can happen when different branches use different configurations.
=> Fix workflow silent fail

src/components/EditorWidgets/Date/DateControl.js
Sets correct and documented format for Date widget (YYYY-MM-DD).
Closes #1119.
=> exclude time from default date widget format

src/backends/backend.js, src/backends/github/implementation.js
**- Summary**
Before, if any entry in a collection failed to load, the entire collection would be empty. This PR hides only the files that actually fail, instead of the entire collection.
Partial fix for #1092 and #929.
=> Fix collection failure if entry fails.

package.json, src/actions/__tests__/config.spec.js, src/actions/config.js, src/bootstrap.js, src/components/App/App.js, src/index.js, src/init.js, src/reducers/__tests__/collections.spec.js, src/reducers/__tests__/config.spec.js, src/reducers/collections.js, src/reducers/config.js, src/reducers/integrations.js, webpack.dev.js, webpack.prod.js, website/site/content/docs/beta-features.md, yarn.lock
**- Summary**
This pull request solves at least two problems:
1. The CMS immediately runs on load, leaving no opportunity for bootstrapping.
2. The CMS config cannot be directly provided as a JS object.
These are both relevant concerns for customizing Netlify CMS for specific static site generators, where we could potentially infer an entire configuration based on SSG conventions, and have no easy way to inject the configuration.
allow manual initialization and config injection
**- Notes for reviewers**
There are PR comments explaining why changes took place for most individual files. Here are the high points:
**Config action payloads are now Immutable maps**
Config action payloads used to be objects, and conversion took place in the reducer. This sort …
=> allow manual initialization and config as code

website/site/content/docs/widgets.md
the example regex and its comment don't match.
=> correct example regex

website/site/content/docs/beta-features.md
**- Summary**
Fix beta feature document
The `init()` method requires an object with a property name `config` and the value to be the configuration
🐧
=> Fix beta feature document

src/bootstrap.js, src/index.js
**- Summary**
Here is the proposed changes to allow for single bundle today!
**- Features**
- looks for both element id `nc-root` or `no-auto` because we need to persist the element in the case `nc-root` will be a route component, that gets unmounted
-  Ability to `import CMS from 'netlify-cms'` from the bundle ( CMS.init(), CMS.reset() added )
- reset() method added to allow a reset when unmounting the cms from the dom and need to re-init
- Allow for the `import { init, reset, registry } from 'netlify-cms'` but not sure it is needed in this solution (optional)
`yarn build`
consume the assets in a project and make sure it is working :smile:
see parent description
🐧
=> Allow for single bundle init without losing automatic loading

src/backends/github/API.js, src/backends/github/implementation.js
Closes #993.
**- Summary**
When working on a private repo, new image uploads don't show the thumbnail until you reload the page, leading the user sometimes to think the upload failed because they see a broken thumbnail icon. The src url of new images don't have the token query parameter that is applied when the page loads.
This fix reloads the file list of the upload directory from the git API (as if it was first loading the media library), and fetches the url of the newly uploaded file from that list. I left the previous built-in-the-method url as a fallback, *just in case*.
**Note:** my fix seems the "simplest" in terms of what I could already find in the code, but if you think there's a better way to do it, I'm all up for it. 😄 
Tested uploading an image, to a private …
=> Fix thumbs for new uploads to private repos

src/components/Editor/EditorPreviewPane/EditorPreviewPane.js, src/lib/registry.js, website/site/content/docs/beta-features.md
**- Summary**
Raw styles can't currently be injected into the preview pane, which is a challenge for projects using modern build tooling. For example, I'd like to import styles from a specific file using inline webpack loaders and pass the result to `registerPreviewStyle`, rather than doing something hacky to get Webpack to emit files, which is next to impossible if the webpack config is shared, as in systems like Gatsby.
Adding this as a beta feature only to avoid commitment to the exact API being introduced.
Accept CSS strings in registerPreviewStyle
**- Docs**
`registerPreviewStyle` can now accept a CSS string, in addition to accepting a url. The feature is activated by passing in an object as the second argument, with `raw` set to a truthy …
=> accept CSS string in registerPreviewStyle

src/actions/editorialWorkflow.js
**- Summary**
Toast notification logic was missing for editorial workflow entry persist.
Fixes #1202.
Fix editor validation notifications for editorial workflow
=> fix validation toast notification for workflow

package.json, webpack.prod.js
**- Summary**
Closes #553. This PR changes the `npm publish` command to package our source code as well. Source maps now reference independent files rather than a single bundle.
Manually tested that sourcemaps still work.
Ship source code to NPM.
=> Ship source code to NPM

src/backends/git-gateway/API.js, src/backends/git-gateway/implementation.js
**- Summary**
Fixes #647. Also addresses the case where a user changes their GH repo from public to private after Git Gateway is set up. 
Prevent Git Gateway users with invalid tokens from logging in.
=> Prevent Git Gateway users with invalid tokens from logging in.

src/components/EditorWidgets/List/ListControl.js
**- Summary**
Closes #1198 - regression fix: PR #1087 broke relation lists preview.
This is hard, I haven't found any example in the demo that shows this. The *ListControl* component was using the `forID` property to check for metadata that has a structure like 
```
{ "collection_name": { ... } }
```
but the changes to ensure `forID` uniqueness breaks this of course as the metadata doesn't have that unique string in the object's property names.
This fix ensures that *ListControl* uses the collection name without any unique string attached when checking for metadata.
(Fix regression) previews for relation lists broken by #1087
=> Fix regression in list relation previews

src/actions/config.js
This fixes if there was an invalid route to the `config.yml` because it did not exist and it was handled without a 404.
Delete this branch when merged.
=> Allow for un-captured route of config.yml

src/backends/git-gateway/API.js, src/backends/github/API.js, src/backends/github/implementation.js
**- Summary**
New media uploads do not appear at all until the CMS is reloaded **(not the thumbnail or filename)** when using the Git Gateway backend after #994. This PR resolves #1220.
=> Fix broken new media uploads in Git Gateway.

example/config.yml, src/backends/test-repo/implementation.js
Provides simple, in-memory editorial workflow support for the test backend.
Fixes #267.
=> enable editorial workflow for test backend

src/components/Editor/EditorToolbar.js
**- Summary**
It simply remove this warning :
Add property key in EditorToolbar
=> Add property key in EditorToolbar

src/components/EditorWidgets/Date/DateControl.js
Fixes #1178 : Allow typing in date widget
**- Summary**
Allow typing in date widget by setting the date only if the format is valid
Test date widget behavior is ok
Allow typing in date widget
=> Allow typing in date widget

src/components/EditorWidgets/Markdown/MarkdownControl/RawEditor/index.js, src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/Toolbar.js, src/components/EditorWidgets/Markdown/MarkdownControl/Toolbar/ToolbarButton.js, src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.js, src/components/EditorWidgets/Markdown/MarkdownControl/index.js, website/site/content/docs/widgets/markdown.md
**- Summary**
Add markdown toolbar buttons customization, based on conf file : 
```
- ...
- {label: "Markdown", name: "markdown", widget: "markdown", buttons: ["bold", "italic", "link"]}
- ...
```
If no `buttons` field is specified we display all the buttons otherwise we display the list.
Add markdown editor toolbar customization
=> Add markdown editor toolbar customization

src/backends/github/AuthenticationPage.css
Partial revert of #1227.
Fixes GitHub icon misalignment, regression from #1227.
=> fix github auth button icon alignment

website/site/data/landing.yaml
**- Summary**
The contributor count has increased quite a bit. No linger 60+ as advertised, now over 100 contributors. This PR also rephrases this sentence a little to make it scan a little better.
This is a simple content change made purely in the data file as intended for simplified content abstraction. Locally the revised copy rendered suitably:
1. Single copy change in the landing.yaml data file
=> nudge the contributor count up

example/config.yml, src/components/EditorWidgets/Relation/RelationControl.js, website/site/content/docs/widgets/relation.md
**- Summary**
Some relation objects I have are stored by an `id` field to guarantee each object has a unique value. My `id`s are random hashes though and they are not very informative, especially looking through the autocomplete options. 
By adding the `displayFields` option, we can render information of the object that is more useful to the user. In my case I can display the title and author, which helps distinguish posts with the same title.
Manual testing works
The test suite passes using `yarn test`
The relation widget now supports custom display fields
=> Support displayFields in the Relation widget

website/site/layouts/partials/footer.html, website/src/css/imports/gitter.css, website/src/css/main.css
Closes #1323
Adds an “Open Chat” button to Netlify CMS site, excluding the home page, using [Gitter Sidecar](https://sidecar.gitter.im/).
Add Gitter Sidecar widget to docs site
=> Add Gitter Sidecar widget to docs site

website/site/content/docs/add-to-your-site.md
Added Nuxt to list of generators that use the "static" folder for static files where the Netlify CMS admin can live.
**- Summary**
Netlify CMS can be added to a Nuxt project by placing the required files in the "/static" folder.
Added Nuxt to list of generators that use the "static" folder for installing the Netlify CMS admin.
=> Updating add-to-your-site.md to include Nuxt

website/site/content/docs/examples.md
☕️  Reference for [the cupofdata.com](https://cupofdata.com) site which uses the `Netlify CMS` with [Gatsby](https://www.gatsby.org) for various sections using the `git-gateway` backend with Markdown. We were [encouraged to share our site](https://www.netlifycms.org/docs/start-with-a-template/), hence the PR!
=> Website example reference - www.cupofdata.com

src/backends/git-gateway/API.js, src/backends/github/API.js
**- Summary**
Fixes #1272.
If Git Gateway was disabled, we were still allowing the user to log in, which can cause them to lose their work when they cannot save it.
Manually tested with both scenarios: https://github.com/netlify/netlify-cms/issues/1272#issuecomment-383139642.
=> Prevent login if Git Gateway is disabled.

src/backends/github/API.js
**- Summary**
Fixes #1092. Allows files over 1MB to be fetched from GitHub's API.
=> Fix large files failing to load.

website/site/content/docs/add-to-your-site.md
Quick edits to avoid some common confusion:
- Added hints to avoid accidentally indented config file lines.
- Removed possible confusion that npm install section is the one with config details.
=> Add clarification to "Add to Your Site" doc

src/constants/fieldInference.js
**- Summary**
The list of fields to infer is kind of arbitrary. The hugo theme I'm using uses `cover` as the item cover image.
Would have been nice is this was configurable.
This doesn't require a test plan.
Adding alternate name for thumbnail image.
░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░▄▀▀▄░░░░░░░░░░░░░
░░░░░░▄▀▒▒▒▒▀▄░░░░░░░░░░░
░░░░░░░▀▌▒▒▐▀░░░░░░░░░░░░
░▄███▀░◐░░░▌░░░░░░░░░░░░░░
░░░▐▀▌░░░░░▐░░░░░░░░░░▄▀▀▀▄▄
░░▐░░▐░░░░░▐░░░░░░░░░█░▄█▀
░░▐▄▄▌░░░░░▐▄▄░░░░░░█░░▄▄▀▀▀▀▄
░░░░░░▌░░░░▄▀▒▒▀▀▀▀▄▀░▄▀░▄▄▄▀▀
░░░░▐░░░░▐▒▒▒▒▒▒▒▒▀▀▄░░▀▄▄▄░▄
░░░░▐░░░░▐▄▒▒▒▒▒▒▒▒▒▒▀▄░▄▄▀▀
░░░░░▀▄░░░░▀▄▒▒▒▒▒▒▒▒▒▒▀▄
░░░░░░░▀▄▄░░░█▄▄▄▄▄▄▄▄▄▄▄▀▄
░░░░░░░░░░▀▀▄▄▄▄▄▄▄▄▀▀░
░░░░░░░░░░░░▌▌░▌▌░░░
░░░░░░░░░░▄▄▌▌▄▌▌
=> Adding inference field

src/backends/backend.js
Closes #1164.
Previously, when a file was added with the same title as an existing one and the slug equals title, the existing file is overwritten.
**- Summary**
This checks in `src/backends/backend.js` before the `entryObj` is created in `persistEntry` if there's an existing file with the same name. Throws an Error if there is. 
First, for `editorialWorkflow` mode, it checks in `window.repoFilesUnpublished` for preexisting entry. Next, it uses `this.implementation.getEntry`, checking if there's already a published entry in danger of being overwritten.
I created a file called `test`
Saved the file successfully, and checked that it was in workflow.
Then created a new file, also called `test`, tried to save it, and--
Then instead, saved it as `Test 2`. 
Then published it. …
=> Prevent Overwriting Files with Same Slug Names

CHANGELOG.md, src/components/EditorWidgets/Date/DateControl.js, website/site/content/docs/widgets/date.md, website/site/content/docs/widgets/datetime.md
BREAKING CHANGE
As of 1.0, the documented behavior for the date and datetime widgets was
to always return a string value, but they were instead returning a date
object if the default date was not manually changed by the user. This
was addressed in #1143, but it became clear afterward that static site
generators were depending on the raw date objects that Netlify CMS was
unintentionally producing. Remaining as is or addressing the bug were
both "breaking" states, so this commit reverts to producing raw date
objects when no format is explicitly set.
It is now considered an edge case to require string dates, as most
static site generators expect to parse a raw date against formatting in
a site's templates.
Also note that this commit improves the original behavior by always
providing a date …
=> return date object from date/datetime widgets if no format set

src/actions/__tests__/config.spec.js, src/actions/config.js, src/backends/backend.js, src/constants/fieldInference.js, src/reducers/collections.js
This PR fixes #690 by verifying that folder-type collections have a valid title ("slug"-able) field at CMS load time, instead of when the user tries to save an entry. It also explains how to fix the error.
=> Check for title/slug field on config load.

src/components/EditorWidgets/Markdown/MarkdownControl/RawEditor/index.css, src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/Shortcode.css, src/components/EditorWidgets/Markdown/MarkdownControl/VisualEditor/index.css
**- Summary**
Dependency updates caused postcss to stop preprocessing css variables (due to sufficient browser support), and the following unsupported syntax stopped working:
```css
margin: -var(--value);
```
The syntax used to produce the variable preceded with a hyphen. Instead the supported way to negate a css variable is:
```css
margin: calc(-1 * var(--value));
```
Fix markdown widget styling
=> Fix negative CSS variables

src/components/Workflow/Workflow.css
Fixes styling break from recent dependencies update. Native CSS variables combined with PostCSS output optimizations converted this:
```css
.nc-workflow {
padding: var(--pageMargin);
padding-bottom: 0;
}
```
to this:
```css
.nc-workflow {
padding: var(--pageMargin) var(--pageMargin) 0;
}
```
PostCSS static analysis counted the vars as single values, but the variable equates to `84px 18px`, leading to an output of `84px 18px 84px 18px 0`, which fails in the browser.
Fixed by not declaring the bottom padding subsequent to general padding declaration, but we should consider changing or dropping related optimizations if these kinds of issues prove common.
Bug demo: https://5b084974c965920b4c7644e3--cms-demo.netlify.com/#/workflow
Fix demo: …
=> fix workflow top panel styling

website/site/content/docs/add-to-your-site.md, website/site/content/docs/authentication-backends.md, website/site/content/docs/beta-features.md, website/site/content/docs/configuration-options.md, website/site/content/docs/intro.md, website/site/content/docs/start-with-a-template.md, website/site/content/docs/widgets/index.md
**- Summary**
Updates docs to go with the addition of the GitLab backend! 🎉 
Most of the changes can be found on 
https://docs-update-gitlab--netlify-cms-www.netlify.com/docs/authentication-backends/
If someone who hasn't built the thing or written the doc could run through the instructions for Git Gateway and GitLab backends, that would be 👌 
=> Add GitLab backend to docs

src/components/EditorWidgets/List/ListControl.js
Fixes #1397.
Check the size of the item list and set the listLabel based on that.
If no label_singular is set, fall back to the normal label
**- Summary**
The list control always used the singular name as label if one is specified, even when the list contains 0 or > 1 items. It's now based on the amount of items thats provided.
Tested with the existing authors settings in the example CMS.
With 2 authors:
With 1 author:
With 0 authors:
Base the listLabel on the size of the list provided.
=> Only use label_singular when one item is rendered in the listControl

website/site/content/docs/add-to-your-site.md, website/site/content/docs/configuration-options.md, website/site/data/notifications.yml
**- Summary**
- Adds a note to docs about editorial workflow (supported with GitHub repos only).
- Adds a notification banner to the website, announcing GitLab support
Preview here:
https://website-tweaks-gitlab--netlify-cms-www.netlify.com/docs/configuration-options/#publish-mode
=> Last-minute website tweaks for GitLab release

src/backends/test-repo/implementation.js
**- Summary**
The test-repo backend was crashing if a different folder was specified in the config. Fixes #1438.
=> Fix test-repo crash on non-existent folder.

website/site/content/docs/authentication-backends.md
Warning: This is a wild guess. It makes sense for me that theese lines should be indentated, but I havn't tried it yet (I have no self-hosted Gitlab instance) so someone who knows what he is doing should look over this.
**- Summary**
The yaml example in the docs didn't look right. I think it should be indeted.
I havn't checked that this yaml is working (I am not in a possition to do so). Someone with knowledge about the config and the gitlab backend should review this before merging
I indented the yaml as good as I could. This gets a bit repetitive here.
**- A picture of a cute animal**
=> Fix indentation in config example

src/formats/__tests__/frontmatter.spec.js, src/formats/__tests__/tomlFormatter.spec.js, src/formats/toml.js
**- Summary**
Fixes #1457, int val output in TOML format, adds test
Test added and passing for int and float
Fix int val output in TOML format file
=> Fixes #1457, int val output in TOML format, adds test

src/backends/gitlab/implementation.js
**- Summary**
Fixes #1462. See discussion there for context.
I ported the exact fix from #1123  to gitlab.
Support extensions with multiple parts for gitlab (i.e. en.md)
=> Support extensions with multiple parts for gitlab (i.e. en.md)

website/site/content/docs/authentication-backends.md
**- Summary**
The example URI for creating an application in GitLab does not contain a trailing `/` but the Netlify CMS admin oauth implicit grant request to GitLab does include a trailing `/`.  This results in a failure with GitLab not matching the URI and returning an error. 
Following the example explicitly as most will do with copy-paste,  `https://example.com/app/admin` will be entered. Then the Netlify admin login will send `https://example.com/app/admin` and the URI will not match and GitLab will show an error indicating the URI is invalid.
The easy fix for the user is just to put the trailing `/` ... `https://example.com/app/admin/`.
I updated that example string in the hopes that users will not have to figure this out on their own in the future.
Doc change. Just …
=> And training forward slash to example URI for GitLab

website/site/content/docs/add-to-your-site.md, website/site/content/docs/authentication-backends.md, website/site/content/docs/intro.md, website/site/content/docs/start-with-a-template.md
**- Summary**
Adds/modifies docs content to account for Bitbucket support coming in 2.0. Some portions I've guessed based on code or conversations about possible requirements. Need review from @Benaiah, @erquhart or others who have tested the backend to ensure correctness.
I'll highlight lines that require particular attention.
Check the changed files to see changes; check the deploy preview to see that they render properly.
(implicit in the Bitbucket support changelog entry)
=> Update docs to add Bitbucket support

packages/netlify-cms-ui-default/src/Loader.js
Forgot to pass `className` to the root element in a component being wrapped with Emotion. Also condensed Loader style rules.
=> Fix loader styles

packages/netlify-cms/scripts/deprecate-old-dist.js, packages/netlify-cms/webpack.config.js, website/content/docs/add-to-your-site.md, website/content/docs/custom-widgets.md, website/content/docs/customization.md, website/content/docs/update-the-cms-version.md, website/static/admin/index.html
When loading Netlify CMS via script tag from a CDN, the file was named
`cms.js` until 2.0, when it was renamed to `netlify-cms.js` in alignment
with all packages outputting files that match the package name. To avoid
a lot of broken sites and confusion, this commit outputs both filenames
and prints a deprecation warning to the console in `cms.js` only.
=> fix(build): output aliased cms.js w/ deprecation

packages/netlify-cms-backend-git-gateway/src/implementation.js
Before 2.0 we used an internal constant to check for editorial workflow. Now we pass `useWorkflow` through the backend initialization config instead. This fix updates the Git Gateway backend to check for that option.
=> fix(git-gateway): pass options through git-gateway backend

package.json, packages/netlify-cms/package.json
Because we use `netlify-cms` for development and it builds from package sources directly, we don't need to watch all packages during development. This PR adds a `develop` task and redirects `yarn start` at repo root to use that task, which only `netlify-cms` has. Leaving the other `watch` tasks in place for future use.
=> chore: only run netlify-cms for development

packages/netlify-cms-backend-bitbucket/package.json, packages/netlify-cms-backend-git-gateway/package.json, packages/netlify-cms-backend-github/package.json, packages/netlify-cms-backend-gitlab/package.json, packages/netlify-cms-backend-test/package.json, packages/netlify-cms-editor-component-image/package.json, packages/netlify-cms-lib-auth/package.json, packages/netlify-cms-lib-util/package.json, packages/netlify-cms-ui-default/package.json, packages/netlify-cms-widget-boolean/package.json, packages/netlify-cms-widget-date/package.json, packages/netlify-cms-widget-datetime/package.json, packages/netlify-cms-widget-file/package.json, packages/netlify-cms-widget-image/package.json, packages/netlify-cms-widget-list/package.json, packages/netlify-cms-widget-markdown/package.json, packages/netlify-cms-widget-number/package.json, packages/netlify-cms-widget-object/package.json, packages/netlify-cms-widget-relation/package.json, packages/netlify-cms-widget-select/package.json, packages/netlify-cms-widget-string/package.json, packages/netlify-cms-widget-text/package.json, yarn.lock
**Problem:** `netlify-cms` imports other packages from their `src` rather than their build output. Those packages, however, import the build output of other packages. For a working development environment, all package builds must be running in watch mode. `netlify-cms` has both a `watch` and a `develop` task. We need to run the `watch` task of all other packages and the `develop` task of `netlify-cms`.
Lerna doesn't do that.
**Solution:** create a `develop` task for all packages, and for non-`netlify-cms` packages, just have it alias the `watch` task. This way `lerna run develop` at project root will run the dev server from `netlify-cms` and the `watch` task for all other packages.
=> chore: update develop task to watch all packages

packages/netlify-cms-core/src/reducers/collections.js
**- Summary**
#1123 introduced a bug, where, instead of trimming the file extension with a preceding period from the end of a filename to get a slug, it trims the file extension plus one character, regardless of whether it was actually a period or not.
This is why we use linters!
=> fix: regression from #1123

packages/netlify-cms-backend-gitlab/src/API.js
**- Summary**
This fixes the netlify-cms with GitLab as backend. Now it is possible to upload images and publish posts using the CMS.
Publishing issue (#1564):
Prior to this pull request, the `content` variable, which is passed to the `JSON.stringify()` method later, was a Promise. `JSON.stringify` transformed it to `{}` instead of the content in the markdown text editing field. Now the value is extracted out of the Promise by using the `await` operator ([source code](https://github.com/netlify/netlify-cms/blob/d08e5f5183dec997cbd2bb602b1584690ab0c324/packages/netlify-cms-backend-gitlab/src/API.js#L189-L191)).
Image uploading issue (#1565):
Prior to this pull request, it wasn't possible to upload images with the CMS. If `item`, the argument of the `uploadAndCommit` …
=> fixes #1564, #1565

jest.config.js
Travis now fails all tests with error: 
```
SecurityError: localStorage is not available for opaque origins
```
It's a Jsdom/Jest issue outlined here w/ solution: https://github.com/facebook/jest/issues/6766#issuecomment-408344243
=> chore(tests): fix jest localstorage bug

packages/netlify-cms-backend-github/src/implementation.js, packages/netlify-cms-backend-test/src/implementation.js, packages/netlify-cms-core/src/backend.js
Workflow needs to be enabled per method. `persistEntry` should only use it when persisting an unpublished entry, but must behave as if workflow were not enabled for publishing. This fixes a 2.0 regression.
=> fix(workflow): enable workflow per method

packages/netlify-cms-core/src/reducers/search.js
**- Summary**
In the `search.js` reducer, `isFetching` is set to the payloads namespace, which is a string. In all other cases it is set to a boolean, as the name implies. A truthy `if` check happens down the line, and this change simply sets it to be a boolean consistently to avoid possible issues in the future.
=> Change isFetching to consistently be boolean

packages/netlify-cms-backend-bitbucket/src/API.js, packages/netlify-cms-backend-github/src/API.js, packages/netlify-cms-backend-gitlab/src/API.js, packages/netlify-cms-backend-test/src/implementation.js
=> fix: miscellaneous backend fixes

package.json, website/content/docs/widgets/boolean.md, website/content/docs/widgets/date.md, website/content/docs/widgets/datetime.md, website/content/docs/widgets/file.md, website/content/docs/widgets/hidden.md, website/content/docs/widgets/image.md, website/content/docs/widgets/index.md, website/content/docs/widgets/list.md, website/content/docs/widgets/markdown.md, website/content/docs/widgets/number.md, website/content/docs/widgets/object.md, website/content/docs/widgets/relation.md, website/content/docs/widgets/select.md, website/content/docs/widgets/string.md, website/content/docs/widgets/text.md
Fix layout of code in examples for widgets.
- Aligns code in valid YAML format
- Indents  code block to match the line item
=> Fix widget example code layout on Site

website/content/docs/add-to-your-site.md
**Summary**
There's a rendering issue where the _ is greedily matched in `public_folder`.
**Before:**
**After:**
I don't normally like to use * for emphasis, but this was a good example of when it's useful. It seems like remark doesn't respect escaping with `\_`.
**Test plan**
- validate the test branch preview.
=> docs: fix public_folder greedy match for _ rendered

website/content/blog/netlify-cms-2-0-launches-with-bitbucket-support-and-a-new-monorepo-architecture.md, website/content/docs/add-to-your-site.md, website/content/docs/authentication-backends.md, website/content/docs/collection-types.md, website/content/docs/intro.md
**Summary**
Band-aid fix for #1600. Current state is that inline internal links on netlifycms.org are broken, but working when viewed in the repo on GitHub. This PR changes the links from absolute URLs to relative, breaking the links in repo view, but fixing them in the much more commonly used website view.
#1623 will probably fix things so that we could use absolute links again, but because relative links work better in a number of ways, I think a better long-term solution will be to stick with relative links and transform the paths at build time (see #1646).
**Test plan**
Check in preview.
=> Change inline absolute links to relative links

packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js, packages/netlify-cms-ui-default/src/ListItemTopBar.js, packages/netlify-cms-widget-list/src/ListControl.js, packages/netlify-cms-widget-object/src/ObjectControl.js, packages/netlify-cms-widget-object/src/ObjectPreview.js
Closes #1139. The original issue had two problems that I have found. The first was how the config.yml responds to `field`.
When adding in `fields` for a `list` widget as demonstrated under the label `List`, it renders correctly.
But when we use `field` instead, and indent with a dash, as we would with `fields`, 
this happens:
It doesn't render the select properly, and we get a whole console full of errors.
This error pointed to `handleChangeFor`.
```
handleChangeFor(index) {
return (fieldName, newValue, newMetadata) => {
const { value, metadata, onChange, field } = this.props;
const collectionName = field.get('name');
const newObjectValue = this.getObjectValue(index).set(fieldName, newValue);
const parsedValue = (this.valueType === valueTypes.SINGLE) ? newObjectValue.first() : …
```
=> Fixes field config usage with List widget.

packages/netlify-cms-core/src/components/Editor/EditorToolbar.js, packages/netlify-cms-ui-default/src/styles.js, packages/netlify-cms-widget-file/src/withFileControl.js
This PR addresses the edit entry page status labels look like a button. This issue was detailed here https://github.com/netlify/netlify-cms/issues/1031
I removed the background color in the success and danger text badges. I then set the default button light blue color at the button level instead of the textBadge css class level. And the status labels have been capitalized and set to bold.
Closes #1031.
=> improvement: remove button background color styling for editorial status labels

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Comment out the guidelines as some issues are being opened with the guideline text still there, making the issue text harder to parse.
=> chore: comment out issue template guidelines

website/content/docs/customization.md
**Summary**
This feature branch updates the API documentation for `CMS.registerPreviewTemplate`. The issue that gave motivation for this PR is #1625. The goal is to make the documentation more clear for registering file collection templates.
This also closes #1197.
=> docs: update register preview template parameter description

packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
**- Summary**
Fix #1406 -- see the description in the issue.
This PR was ported from #1511, created by @papandreou, see discussion there:
> @erquhart:
> We should hold off on the dynamic part in this PR and just support static default values. Fields in editor components should work exactly the same as fields that are not in an editor component, which is the basis for #1406 being considered a bug.
> @papandreou:
> I've tested it manually in my own application and found that the default values work with various widgets, including `hidden`.
=> fix: add support for default field values in editor components

packages/netlify-cms-core/src/actions/config.js
**Summary**
We weren't catching the error when config.yml fetch errored, so manual init without a config file wasn't possible in those situations. Ran into this trying to spin up Netlify CMS on Codepen, where CORS headers disallowed the CMS from attempting to access local files.
=> fix(config): stop throwing on config.yml 404, fix manual init

website/content/docs/configuration-options.md
Add  `description` option for collections which went undocumented somehow, despite it being pretty useful for client work
=> [docs] Add description option to collections docs

packages/netlify-cms-media-library-uploadcare/src/index.js
Fixes #1768 
**Summary**
The problem was caused by loose checking value for array type (plain or immutable) using `typeof value === 'object'`. In case of usage at list widget, value passed to `#getFiles` was `null` which also an object. So I did this check explicitly for the plain array and the Immutable Iterable.
**Test plan**
And now it works.
=> #1768: Fix using Uploadcare library in list widget

website/content/docs/authentication-backends.md
**Summary**
I've written a GitHub OAuth client that can be deployed as a [Firebase Cloud Function](https://firebase.google.com/docs/functions/). Just adding it to the list.
**Test plan**
No code was changed, only website markdown.
=> Add Firebase Cloud Function OAuth client to the list of external clients

packages/netlify-cms-widget-markdown/src/__tests__/__snapshots__/renderer.spec.js.snap, packages/netlify-cms-widget-markdown/src/__tests__/renderer.spec.js, packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js
**Summary**
closes #956
was getting `![null](url)` on my markdowns, when not entering any text 🐛 
made the one of the [image serializers](https://github.com/netlify/netlify-cms/blob/a262bcef530532d710540af16d83e9a9dcaaa597/packages/netlify-cms-widget-markdown/src/serializers/remarkImagesToText.js#L19) mirror [another one](https://github.com/netlify/netlify-cms/blob/a262bcef530532d710540af16d83e9a9dcaaa597/packages/netlify-cms-editor-component-image/src/index.js#L11
), from this very repository.
**Test plan**
1. manually added markdown line and snapshot.
2. `yarn jest`, it breaks (sending `null` as when empty)
3. fixed it! 💪 
before:
```diff
@@ -22,9 +22,9 @@
- <p>![](https://pbs.twimg.com/profile_images/678903331176214528/TQTdqGwD.jpg)</p>",
+ …
```
=> fix null on markdown image alt

packages/netlify-cms-widget-list/src/ListControl.js
Fixes #1684 
**Summary**
ListControl was sending listLabel to the ObjectWidgetTopBar component to use for the Add button. This label was being set to the plural form of the object if more than one were present on the list. However, the Add button would only add one object to the list at a time.
This PR will attempt to use the singular version of the label and will fallback to listLabel if singular doesn't exist.
**Test plan**
No test plan needed. Added a short-circuit evaluation.
=> Set List Widget to use singular label if available

packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/constants/configSchema.js, packages/netlify-cms-core/src/reducers/collections.js, website/content/docs/collection-types.md
**- Summary**
Sometimes `title` doesn't make sense as the identifier for a collection. For example I have a JSON collection called `clients`, which has a `name` field which I want to use for the slug. This PR adds support for an `identifier_field` setting for collections, which lets the user choose a different identifier field.
Closes #1802, #1700.
Try using the following collection:
```yaml
- label: "Blog"
name: "blog"
folder: "_posts/blog"
create: true
identifier_field: name
fields:
- {label: "Name", name: "name", widget: "string"}
- {label: "Publish Date", name: "date", widget: "datetime"}
- {label: "Featured Image", name: "thumbnail", widget: "image"}
- {label: "Body", name: "body", widget: "markdown"}
```
Allow identifier fields …
=> Add support for setting custom identifier field 

website/content/docs/widgets.md
Add a note indicating that field validation doesn't currently work on nested fields.
**Summary**
Help others figure out quickly that validation doesn't work on nested fields. I spent a few days on and off until I figured it out :)
=> Note that validation doesn't work on nested fields

website/.stylelintrc, website/gatsby-node.js, website/package.json, website/src/components/event-widget.js
Don't require prop-types for Gatsby components on website.
Do enforce no `console.log`s on website.
Remove ESLint copy on website -- just use top-level one. @verythorough Is this OK for website-only contributors?
=> dev: update website linting rules

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js, packages/netlify-cms-widget-list/src/ListControl.js
**- Summary**
This PR fixes https://github.com/netlify/netlify-cms/issues/1256 .
If a label is not supplied within the configuration then the name will be used as the label of the widget. 
1. Add this to your config.yml
`- name: "Test", widget: "markdown"`
you will see that a label is added to your widget. The cms takes the name of your widget and generates a label based off that name. 
Before this PR, you had to specify a label when creating a widget. If you did not supply a label then the widget would display without a label, like this: 
The code changes in this PR allow for the CMS to use the name of the widget as a label if no label is supplied; like this: 
If a widget does not have a label the CMS will generate one based on the …
=> If no lable is supplied, use the name.

packages/netlify-cms-backend-github/src/AuthenticationPage.js, packages/netlify-cms-backend-gitlab/src/AuthenticationPage.js
**Summary**
Use `PropTypes.func` instead of `PropTypes.function`. It removes the warning form React:
```
Failed prop type: GitLabAuthenticationPage: prop type `clearHash` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
```
=> netlify-cms-backend: fix `function` prop-type

packages/netlify-cms-core/src/actions/entries.js
**Summary**
When **not* using editorial workflow, publishing a change shows incorrect message:
Caused by this commit: https://github.com/netlify/netlify-cms/commit/c2e21ff9db954c1bdec25531ee2132bd31453b78#diff-b80adfd8b33beb6f0d8d25d454a2d6deR452
**Test plan**
Change demo to not use editorial_workflow.
Save a change and publish.
Should see the correct message
🐖
=> Fix entry saved message

dev-test/config.yml, packages/netlify-cms-widget-date/src/DateControl.js, packages/netlify-cms-widget-datetime/src/DateTimeControl.js, website/content/docs/widgets/date.md, website/content/docs/widgets/datetime.md
fixes #1648, #1736
**Summary**
If the format property in a date widget is set to YYYY-MM-DD, the field is saved correctly in the file, but in the date input in the CMS, the date is still shown as MM/DD/YYYY. 
This PR deprecates the `format` property in favor of `dateFormat` and `timeFormat` 
Currently two widgets exists, "date" and "datetime", but according to #1688 the goal is to combine these two into a single `datetime` widget.
This PR currently tries to add formatting without breaking defaults (eg. if user configs a "datetime" widget, `dateFormat` and `timeFormat` would be implicitly set to `true` and get the default formatting from the underlying `react-datetime` component.)
If desired, we could easily expand this PR to deprecate the `date` widget, and require setting `timeFormat: …
=> Date widget formatting of input values

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/index.js, packages/netlify-cms/package.json, packages/netlify-cms/src/index.js
**Summary**
`netlify-cms` package is responsible to make NetlifyCMS easy to use. It is bundled with the UMD wrapper and is used as script tag. It imports all widgets and backends...
It makes sense that `netlify-cms` should handle whole aspects about this "window bridge"... and keep `netlify-cms-core` as a clean ESM module.
It will make `netlify-cms-core` easy to use as a standalone ESM module:
```
import { init } from "netlify-cms-core"
init({})
```
Without this PR, a `window.CMS_MANUAL_INIT` should be set before the `import` is done.
=> Move window/UMD bridge in `netlify-cms` instead of `netlify-cms-core`

packages/netlify-cms-backend-git-gateway/src/implementation.js
**Summary**
For example, if the `gateway_url` is set to `https://www.my-netlify-site.com/.netlify/git/github`, it was being changed to `https://www.my-netlify-site.com/.netlify/git//github` (notice the double slash).  This commit stops adding the extra slash.
**Test plan**
Test manually.
=> fix: double slashes when gateway_url contained a backend

packages/netlify-cms-core/src/constants/configSchema.js
**Summary**
Schema for validating `identifier_field` for a collection was incorrect.
Fixes #1874.
=> fix(config): fix identifier field validation

packages/netlify-cms-core/src/components/UI/SettingsDropdown.js
**Summary**
Right now you can have focus on 2 different elements in the "profile menu button". That's because there is a tabIndex on the span and we have a nested button, so both can receive focus.
Before 
After
**Test plan**
Manually tested
**Other**
Would you be interested in moving from `react-aria-menubutton` to something like [reach/menu-button](https://ui.reach.tech/menu-button) instead? The later seems to work better and provide a bit better a11y (like not using a span to emulate a button).
=> fix(netlify-cms-core): remove double focusable elements on profile menu button

packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
**Summary**
Adds missing `border-top-right-radius` on the markdown widget toolbar. 
**Test plan**
Before
After
=> fix(netlify-cms-widget-markdown): add missing border radius on toolbar

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/netlify-cms-ui-default/src/Toggle.js, packages/netlify-cms-widget-date/src/DateControl.js, packages/netlify-cms-widget-select/src/SelectControl.js
**Summary**
Partly fixes one of the issues described (labels) in #1333.
Previously a new `forID` was generated on every render which caused some issues. Now we store a generated id on the class instance instead that never updates (unless the component re-mounts). Also had to make some adjustments in the toggle component to allow it to be controlled from a label.
There is still some work to get all the widgets to work properly, like the markdown, file etc. But I think that can be resolved in another PR.
**Test plan**
Manually tested everything
=> fix(a11y): correct label "for" references to fields

packages/netlify-cms-core/src/actions/editorialWorkflow.js, packages/netlify-cms-core/src/backend.js, packages/netlify-cms-lib-util/src/index.js
**Summary**
- allows for custom backends to use the collection and slug information to determine the file when not using only path information.
- fix editorial workflow `EditorialWorkflowError` instance check to be compatible with custom backends
- Stays backwards compatible
- ***Non Breaking*** change
**Test plan**
Tested on a custom backend.
🐥
=> Changes for registerBackend compatibility (API)

website/content/docs/custom-widgets.md
Thx for maintaining this awesome project!
**Summary**
After trying to implement custom validation (https://www.netlifycms.org/docs/custom-widgets/#advanced-field-validation), I couldn't display my error messages. Only after checking the source code I understood that the returned error object needs to have `message` field. So I added this clarification to the docs.
**Test plan**
Before:
After:
Sup!
=> docs: improve widget custom validation sample

packages/netlify-cms-core/src/reducers/collections.js
**Describe the bug**
Follow-on to #1543 and #1878. Attempting to use the identifier_field feature introduced in 2.2.0 with an identifier that is not all *lowercase* causes the backend (On Save) error: 'Collection must have a field name that is a valid entry identifier, or must have `identifier_field` set'.
**To Reproduce**
Specify an identifier_field that has uppercase characters and then attempt to create and save an entry.
**Expected behavior**
The CMS saves without throwing an error.
**Minor Refactor**
Also fix spelling of local variable in the `selectIdentifier` function.
=> fix(netlify-cms-core): fix identifier field validation

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewContent.js, yarn.lock
**Summary**
Upgrade `react-frame-component` to 4.x. No changelog available but I've skimmed through the  commits and the main change seems to be a migration to the new context API.
We are soon up-to-date with most of our dependencies 😄 
**Test plan**
Manual testing
=> chore(netlify-cms-core): upgrade react-frame-component to 4.x

packages/netlify-cms-core/src/actions/mediaLibrary.js, packages/netlify-cms-core/src/reducers/index.js, packages/netlify-cms-editor-component-image/src/index.js, packages/netlify-cms-media-library-cloudinary/README.md, packages/netlify-cms-media-library-cloudinary/package.json, packages/netlify-cms-media-library-cloudinary/src/index.js, packages/netlify-cms-media-library-cloudinary/webpack.config.js, packages/netlify-cms-media-library-uploadcare/src/index.js, packages/netlify-cms-widget-file/package.json, packages/netlify-cms-widget-file/src/withFileControl.js, packages/netlify-cms/src/media-libraries.js, website/content/docs/cloudinary.md, website/content/docs/uploadcare.md, website/content/docs/widgets/file.md, website/content/docs/widgets/image.md
Adds `netlify-cms-media-library-cloudinary` with associated docs 💥
=> feat: add cloudinary support

website/content/docs/configuration-options.md
I was just looking for where to put the option to turn off the preview, and I stumbled across this broken link.
=> docs: fix broken link to dev configuration file

packages/netlify-cms-backend-gitlab/src/implementation.js
**Summary**
If the gitlab api returns `text/plain` and the media items name ends in `.svg` we pin the mime type to `image/svg+xml`.
Closes #1945 
**Test plan**
1. Setup a project using the gitlab backend
1. Go to media library
1. Upload an svg
1. Clear indexed db and reload the page (not sure if that is necessary)
Behavior before: The svg shows as a broken image
Behavior after: The image shows a preview
=> Fixup mimetype for svgs returned from gitlab api

packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
**Summary**
Fixes broken images displaying for non-image media in media library.
I think this got lost in [83d2adc0befccc04ec39c680591894a0e995d5b1](https://github.com/netlify/netlify-cms/commit/83d2adc0befccc04ec39c680591894a0e995d5b1#diff-e7761d31229d6dc3c50cb2b99a56332a)
This also saves a bunch of API requests on initial page load as the raw content for the affected files wont be fetched.
**Test plan**
1. Open media library
1. Upload non-image file, e.g. a pdf
=> Fix broken image previews for non-image media

website/content/docs/authentication-backends.md
**Summary**
Netlify CMS supports a `test-repo` backend that can be used for trying out the CMS without pushing any changes to Git. This PR adds documentation for this feature. More info: https://github.com/netlify/netlify-cms/issues/1085#issuecomment-444908882
The demo site also includes [default content](https://github.com/netlify/netlify-cms/blob/88bf2872212779b4a23ea4e1a3e0213f70a8eaa9/dev-test/index.html#L8), but I didn't document this feature because `window.repoFiles._posts` looks like a private API.
**Test plan**
I followed these instructions on a local Netlify CMS site, made some changes, and ensured that they weren't pushed to git.
=> Document test repo backend

website/content/docs/examples.md
**Summary**
I've added an example of an [open source website](https://gatsby-netlify-cms-example.netlify.com/) that is built using Netlify CMS.
=> Add example of Netlify CMS website

packages/netlify-cms-core/src/actions/editorialWorkflow.js
**Summary**
A simple fix to prevent unnecessary entry status update.
Currently on the workflow flow page when an entry is dragged and dropped back in the inital column and on the editor page clicking on the entry current status in the `set status` dropdown triggers the `updateUnpublishedEntryStatus` action.
=> fix(netlify-cms-core): workflow status update

packages/netlify-cms-core/src/lib/__tests__/urlHelper.spec.js, packages/netlify-cms-core/src/lib/urlHelper.js
Fixes #1963.
When title of a collection (i.e. posts) starts with an escapable character (as described in the issue), and the `slug` was configured to start with the sanitized name, a replacement separator was being placed at the beginning.
```yaml
collections:
- name: "post"
...
slug: "{{slug}}"
```
```markup
'"post" title'
// should produce -> "post-title", not "-post-title"
```
I have added the same kind of replacement that is being made at the end of the slug sanitization. And to be clearer, in different RegExps.
I found this issue thanks to `npx good-first-issue netlify` and [Tierney Cyren](https://twitter.com/bitandbang/status/1066839970428653570).
**Test plan**
Added companion test.
Look at this [happy …
=> Fix extra leading replacement generated on slugs

packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
**Summary**
Workflow hide `Delete publish entry` button for config option `delete: false`.  Although `Delete unpublished changes` and `Delete unpublished entry` buttons would still show.
=> fix(netlify-cms-core): workflow hide delete publish entry button

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
**Summary**
Widgets input is required by default, but if one is made optional there is no visual indication. This PR solves this problem in the most basic way possible I think. It simply adds `[optional]` as a postfix to the label.
I picked square brackets because I think it looks better with the interface 😄 
**Test plan**
=> Display optional status in widget labels

packages/netlify-cms-widget-markdown/src/serializers/__tests__/slate.spec.js, packages/netlify-cms-widget-markdown/src/serializers/slateRemark.js
**- Summary**
See the background on #1448.
I'm not sure if this is the "correct" place to fix it up, let me know if there's a better way.
I've added the fix to my fork and am now running it in production. Will update here if I find bugs or cases it doesn't cover :)
Added some test cases, tested manually.
Fix: Invalid markdown generated when applying styling to a selection with leading or trailing whitespace (#1448)
=> Avoid producing invalid markdown when styled text has leading or trailing whitespace

website/content/docs/examples.md
**Summary**
Add a new Jekyll example showing usage with a Jekyll theme gem, this example using Alembic Jekyll theme
**Test plan**
Click the read me, repo and demo links
[A picture of a cute animal (not mandatory but encouraged)](https://media1.tenor.com/images/3882df6ea78f476404d5dbb435f1d4a6/tenor.gif?itemid=3549289)
=> Examples: Add Jekyll feat Alembic theme starter

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
**Summary**
As [commented](https://github.com/netlify/netlify-cms/pull/1928#issuecomment-454897329) on #1928 this is an attempt to break down the work needed to implement that feature on the `"userland"`, this lifts the backwards-compatible requirement for implementing it.
As there are not many tests on that feature is hard to implement it right now as it changes the underlying implementation besides adding the new feature.
I intend to provide a third-party module for achieving what is described on the PR, including the custom UI, it's also a better way to test the API before committing to it on the `core` (:
**PS**: the contents of this PR are rebased and linted changes made originally on 974fc3d
=> feat(netlify-cms-core): expose loadEntry action to Widgets

packages/netlify-cms-core/src/constants/configSchema.js
This change aims to resolve #1996 in which array values for `frontmatter_delimiter` throw an error `'frontmatter_delimiter' should be string`
**Summary**
See #1996 for details. The schema validator appears not to have been updated in PRs #1064 & #1094 to allow for arrays per the documentation.
**Test plan**
Following development steps on CONTRIBUTING.md
=> Update configSchema.js to allow arrays for frontmatter_delimiter

babel.config.js
**Summary**
I would like to modify the netlify CMS UI look and feel on a client by client basis by dropping a CSS file in my `admin/index.html` file.
React emotion computes hashed class names.
```
const brownStyles = css({ color: 'brown' }) // css-1q8eu9e
```
Adding `autoLabel: true` to the config automatically includes the label property to styles so that class names generated by css or styled include the name of the variable the result is assigned to.
```
const brownStyles = css({ color: 'brown' }) // css-1q8eu9e-brownStyles
```
With the label included in the class name I can tweak the Admin theme at my own discretion.
**Test plan**
Labeling the CSS class names shouldn't have any overhead or cause any issues to my knowledge?
=> Add autolabel to production

packages/netlify-cms-core/src/actions/config.js, website/content/docs/beta-features.md
replaces #1866
**Summary**
Checks the pre-loaded config for `load_config_file: false`
**Test plan**
Tested against multiple configurations with and without the `config.yml` existing and using a full config with `init()`.
🕊
=> Skip the `config.yml` file on init()

packages/netlify-cms-widget-select/src/SelectControl.js, packages/netlify-cms-widget-select/src/__tests__/select.spec.js
**Summary**
Fixes value being displayed in input instead of label for `multiple: true` in select widget.
This also fixes some inconsistencies I discovered when adding some more tests to the component:
- Fixes onChange being called with empty array instead of null when input contents are deleted and `multiple: false`
- Fixes onChange being called with empty string instead of null when input is cleared and `multiple: false`
- Add more tests
I am not sure how a missing value is actually represented for the select widget. I guess any falsy value will do (and also empty arrays). This is confusing to me (especially the case from above where an empty array is used for a select with `multiple: false`), so I opted for null for all of the cases where the select value is not currently set.
**Test …
=> fix(netlify-cms-widget-select) Show label instead of value when multiple is true

dev-test/config.yml, packages/netlify-cms-core/webpack.config.js, packages/netlify-cms-widget-map/CHANGELOG.md, packages/netlify-cms-widget-map/README.md, packages/netlify-cms-widget-map/package.json, packages/netlify-cms-widget-map/src/MapPreview.js, packages/netlify-cms-widget-map/src/index.js, packages/netlify-cms-widget-map/src/withMapControl.js, packages/netlify-cms-widget-map/webpack.config.js, packages/netlify-cms/package.json, packages/netlify-cms/src/widgets.js, website/content/docs/widgets/map.md, yarn.lock
**Summary**
This pull request adds a map widget to edit spatial data in Netlify CMS. See #434 for more information about possible use cases. The map widget is using the [OpenLayers](https://openlayers.org) JavaScript library and map tiles from [OpenStreetMap](https://www.openstreetmap.org). Currently the widget is limited to the most important features. Custom map widgets for special use cases can reuse the `withMapControl()` HOC.
Closes #434.
**Test plan**
The map widget has been added to the kitchen sink collection and should look similiar to the following screenshot:
=> Add map widget

dev-test/index.html, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js, packages/netlify-cms-widget-list/src/ListControl.js, packages/netlify-cms-widget-object/src/ObjectControl.js, packages/netlify-cms-widget-relation/src/RelationControl.js, website/content/docs/customization.md
**Summary**
This PR would prepend field's name for field's metadata. Currently, the kitchen sink `relationKitchenSinkPost` widget custom preview only works for the first top-level widget but does not work for the other two nested `relationKitchenSinkPost` widget. This PR fixes the issue. Plus the fix for  #1982 depending on this PR.
<!--
Demonstrate the code is solid.
Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
--
=> fix(netlify-cms-core): fields metadata

packages/netlify-cms-core/src/backend.js, website/content/docs/configuration-options.md
In `slug` and `preview_path` config templates, fields whose names conflict with a built in placeholder like `{{year}}` or `{{slug}}` cannot be used. This PR allows a field to be referenced explicitly via `fields.`, eg. `{{fields.slug}}`.
There is an extremely low potential for this to be breaking for projects that are referencing fields by name in their slug template, but that is also undocumented functionality, so not technically breaking. A break would require all of the following:
- having a field whose name begins with `fields.`
- having a separate sibling field whose name exactly matches the substring of the first field's name after `fields.`
- using this second field in your `slug` or `preview_path` string template
Example break:
```yaml
collections:
- name: posts
slug: …
```
=> feat(core): allow field name to override slug placeholders

website/src/css/imports/community.css, website/src/css/imports/docs.css, website/src/css/imports/editors.css, website/src/css/imports/header.css
**Summary**
Whilst browsing the site on mobile, I noticed a couple things off center and a pretty high line-height on h2s on the docs which looked a little off. Thought I could patch those couple things real quick. Hope it helps.
**Test plan**
I looks good in browser to me, but let me know if I can improve.
**H2 Before:**
**H2 After:**
**Spacing Before:**
**Spacing After:**
**Header Before (off center):**
**Header After:**
=> Website style fixes

website/src/components/header.js
1. Our star button makes the whole nav jump when it loads - some other projects put it first in the nav and I sort of like that idea, gives it a little more attention.
2. Search should be everywhere like every other docs site.
=> docs: put star button first, add search to home

packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/netlify-cms-ui-default/src/index.js, packages/netlify-cms-ui-default/src/styles.js, packages/netlify-cms-widget-relation/package.json, packages/netlify-cms-widget-relation/src/RelationControl.js, packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js, packages/netlify-cms-widget-select/src/SelectControl.js, yarn.lock
**Summary**
Closes #1061
Related to #1928 but this only focuses on the existing `relation` widget. The behavior should be the same as the old one. Before I continue on this I'd like some confirmation if this can "live" beside the other PR, did this pretty quickly to play around a bit. 
**Test plan**
So far just manual testing – should probably add some unit tests
=> feat(netlify-cms-widget-relation): use react-select and add support for multiple entries

website/content/docs/add-to-your-site.md
**Summary**
Adds location of static files in Gridsome static site generator (see https://gridsome.org/docs/directory-structure/#the-static-directory)
**Test plan**
Nothing to test.
=> Adds static file location for Gridsome

website/content/blog/netlify-cms-2-4-0.md
**Summary**
Seems like `Deploy Preview Links` is linking to the current blog post instead of the one specifically about the subject.
=> Fix Deploy Preview Links href in latest blog post

packages/netlify-cms-backend-git-gateway/src/implementation.js, website/content/docs/netlify-large-media.md
**Summary**
Fixes previews for images that do not match the specified Large Media patterns when using Large Media with GitHub.
=> Fix previews for GitHub images not in Large Media when using Large Media integration

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/actions/entries.js, packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/UI/ErrorBoundary.js, packages/netlify-cms-core/src/constants/defaultPhrases.js, packages/netlify-cms-core/src/formats/frontmatter.js, packages/netlify-cms-core/src/reducers/entryDraft.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, yarn.lock
- Regularly persists changes to browser storage, prompts to load local changes after unexpected exit.
- Displays raw entry (if available) on error screen w/ copy to clipboard button.
The next iteration for this functionality, though not a current priority, is to stop trying to do things when the browser is unloading, and instead create highly visible auto-saving functionality that persists to the backend, allowing the user to manage any auto-saved versions in the UI.
Closes #388 
Closes #1752
=> Recover entry after unexpected quit, show in error boundary

packages/netlify-cms-core/src/actions/__tests__/config.spec.js, packages/netlify-cms-core/src/actions/config.js
Strip leading slashes from a collections `folder` or `file` properties.
Closes #821.
=> Strip leading slashes from collection location config

packages/netlify-cms-core/src/bootstrap.js, packages/netlify-cms-core/src/components/UI/ErrorBoundary.js, packages/netlify-cms-core/src/constants/defaultPhrases.js
Fixes preview pane regression introduced in #2129, error boundary was not allowing updates through to the preview pane.
=> fix(core): allow updates through error boundary

packages/netlify-cms-backend-git-gateway/src/implementation.js
**Summary**
Images not in Large Media fail to show previews when using Git Gateway with GitHub in Netlify CMS 2.6.0. This PR fixes that bug.
=> Fix non-Large Media previews with Git Gateway+Github

packages/netlify-cms-media-library-cloudinary/src/__tests__/index.spec.js, packages/netlify-cms-media-library-cloudinary/src/index.js
**Summary**
This initializes the Cloudinary Media Library with default_transformations during the show() function invocation.
**Motivation**
default_transformation option wasn't passed when rendering the media library. As a result, transformations didn't work properly.
=> Passing default_transformation options while showing media library

packages/netlify-cms-media-library-cloudinary/src/index.js
Allow multiple assets to be returned from the Cloudinary widget when `multiple: true` is set at the field level.
=> Allow multiple asset selection per field w/ Cloudinary

packages/netlify-cms-widget-relation/src/RelationControl.js
Fixes #2114.
**Summary**
This fixes an uncaught error with relation widgets where searchFields is set to a string and not a list of values.
**Test plan**
Truth be told, I have not manually tested this code because I don't know how to. `searchFields` and `displayFields` could probably use regression tests for this bug, but I don't know how to add those. 
**Cute Animal**
[Here's a sleeping Koala.](https://unsplash.com/photos/EerxztHCjM8)
=> [WIP] Fix searchFields with single value

website/content/docs/using-netlify-cms-with-gatsby.md
**Summary**
Adding Netlify CMS to Gatsby Guide #2092
=> [Guide]: Adding Netlify CMS to Gatsby

website/content/docs/custom-widgets.md, website/content/docs/customization.md, website/content/docs/gatsby.md, website/gatsby-config.js
Menu placement as proposed on https://github.com/netlify/netlify-cms/pull/2117#issuecomment-470144816
I also went ahead and renamed the Gatsby guide to be more consistent with the Docs.
Fixes #2149
=> [Docs] Re-order navigation to accommodate guides

packages/netlify-cms-backend-git-gateway/src/implementation.js, packages/netlify-cms-core/src/actions/mediaLibrary.js
**Summary**
Prevents editorial workflow draft branches from being created with a binary version of a file that should be a Large Media pointer. Closes #2220. Also prevents images from having a broken display URL on first upload.
**Test plan**
=> Fix editorial workflow changing LM pointers to binary files

website/content/docs/add-to-your-site.md
For VuePress, assets are located in `.vuepress/public` folder
**Summary**
Just adding information for [VuePress](https://vuepress.vuejs.org/).
**Test plan**
No test... but you can find some information on this [blog post](https://www.vuejsradar.com/vuepress-netlify-cms-integration/), in the Installation part.
=> Add VuePress in generators / folder array

cypress/integration/editorial_workflow_spec.js, cypress/utils/README.md, cypress/utils/dismiss-local-backup.js, dev-test/config.yml
**Summary**
Since writing the changes to NumberControl in #2049 I thought it'd be good to have some integration tests so as shelter its custom validation from possible regressions. This introduces a few tests into the Editorial Workflow suite that test the validation of the NumberControl, along with the validation for fields nested inside objects (feature introduced in #1873 ).
Additionally, I included a little snippet that can be used on future integration tests. By default, Cypress will hit "Confirm" on any window dialogs and it will confirm the dialog put in place to restore entries that were not saved and are temporarily stored in local storage, which in some edge cases pollute the input fields making tests fail. This snippet will tell Cypress to reject this, making the fields …
=> Improve number widget tests

dev-test/config.yml, dev-test/index.html, packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js, packages/netlify-cms-core/src/constants/configSchema.js, packages/netlify-cms-core/src/lib/stringTemplate.js, packages/netlify-cms-core/src/reducers/collections.js, website/content/docs/configuration-options.md
**Summary**
This allows customising the collection list display based on multiple fields rather than the `title` or `identifier_field`. 
Adding the following to the collection definition in the config.yml controls the feature. 
```yaml
list_fields: ['version','title']
list_fields_seperator: ' - '
```
full collection
```yaml
- name: 'faq' # Used in routes, ie.: /admin/collections/:slug/edit
label: 'FAQ' # Used in the UI
folder: '_faqs'
list_fields: ['version','title']
list_fields_seperator: ' - '
create: true # Allow users to create new documents in this collection
fields: # The fields each document in this collection have
- { label: 'Question', name: 'title', widget: 'string', tagname: 'h1' }
- { label: 'Answer', name: 'body', widget: 'markdown' }
- { label: 'Version', name: 'version', …
```
=> feat(core): Allow customising the collection list based on multiple fields

packages/netlify-cms-core/src/components/App/App.js, packages/netlify-cms-core/src/components/Collection/Collection.js
**Summary**
Fixes #2155
Redirect to first collection when a collection doesn't exist.
**Test plan**
- Go to: http://localhost:8080/#/collections/non-existent-collection
- You should be redirected to: http://localhost:8080/#/collections/posts
=> Redirect to first collection when a collection doesn't exist

packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js, website/content/docs/authentication-backends.md
The implementation is a copy/paste of the gitlab implicit oauth code.
Successfully tested with chromium.
The goal is to be able use bitbucket for authentication without a auth server.
=> backend-bitbucket: add 'implicit' oauth

packages/netlify-cms-widget-markdown/src/serializers/__tests__/slate.spec.js
**Summary**
Lifted from https://github.com/netlify/netlify-cms/pull/1517#issuecomment-433533196
This shows some more cases where the slate => markdown conversion results in invalid markdown.
There's no fix is enclosed for now, but I wanted to keep the bug visible now that the other PR got merged.
**Test plan**
We should get the enclosed tests to pass :)
=> Failing tests for more invalid markdown cases

packages/netlify-cms-app/package.json, packages/netlify-cms-backend-bitbucket/package.json, packages/netlify-cms-backend-git-gateway/package.json, packages/netlify-cms-backend-github/package.json, packages/netlify-cms-backend-gitlab/package.json, packages/netlify-cms-backend-test/package.json, packages/netlify-cms-core/package.json, packages/netlify-cms-default-exports/package.json, packages/netlify-cms-editor-component-image/package.json, packages/netlify-cms-lib-auth/package.json, packages/netlify-cms-lib-util/package.json, packages/netlify-cms-media-library-cloudinary/package.json, packages/netlify-cms-media-library-uploadcare/package.json, packages/netlify-cms-ui-default/package.json, packages/netlify-cms-widget-boolean/package.json, packages/netlify-cms-widget-date/package.json, packages/netlify-cms-widget-datetime/package.json, packages/netlify-cms-widget-file/package.json, packages/netlify-cms-widget-image/package.json, packages/netlify-cms-widget-list/package.json, packages/netlify-cms-widget-map/package.json, packages/netlify-cms-widget-markdown/package.json, packages/netlify-cms-widget-number/package.json, packages/netlify-cms-widget-object/package.json, packages/netlify-cms-widget-relation/package.json, packages/netlify-cms-widget-select/package.json, packages/netlify-cms-widget-string/package.json, packages/netlify-cms-widget-text/package.json
**Summary**
Remove source maps for esm code. Not needed, because this code is not minified.
=> chore: remove esm source maps

packages/netlify-cms-widget-markdown/src/MarkdownControl/__tests__/__snapshots__/parser.spec.js.snap, packages/netlify-cms-widget-markdown/src/__tests__/__snapshots__/renderer.spec.js.snap, packages/netlify-cms-widget-markdown/src/serializers/index.js, packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js, packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js, packages/netlify-cms-widget-markdown/src/serializers/slateRemark.js
**Summary**
Allows editor component patterns to match anything, including markdown symbols and HTML.
- Removes pattern matching against sanitized paragraph node text
- Replaces with a true Remark tokenizer for actual "shortcode" node types
- New tokenizer runs before any Remark tokenizer, making the entire raw Markdown string available for pattern matching
Paves the way for MDX support 🎉🎉 
Related to #2064.
Closes #2266.
**Test plan**
Tests forthcoming.
=> feat(editor-components): match any characters with shortcodes

packages/netlify-cms-core/src/actions/editorialWorkflow.js, packages/netlify-cms-core/src/actions/entries.js, packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/reducers/editorialWorkflow.js, packages/netlify-cms-core/src/reducers/entries.js, packages/netlify-cms-core/src/reducers/index.js
**Summary**
Closes #1164, fix  extracted  from #1931
=> fix(core): slug overwrite

website/content/docs/configuration-options.md
**Summary**
Collection object accepts `files` or `folder` field not `file` as stated [here](https://www.netlifycms.org/docs/collection-types).
=> docs: fix files collection type key

packages/netlify-cms-core/src/components/Editor/EditorInterface.js
**Summary**
When working with the split pane in the editor, it's annoying to have to resize the split every time I edit an item to get the preview the size I want. This PR saves the split position to local storage and loads it when the split pane component is rerendered, persisting the split position across item views and page loads.
**Test plan**
=> Persist editor split pane position

packages/netlify-cms-ui-default/src/Dropdown.js
**Summary**
I ran into #1391 in my own environment where dropdowns drop "behind" the markdown widget. Incrementing the `z-index` from 1 to 2 resolved this issue.
**Test plan**
Verifying:
- Append `- { label: "body", name: "body", widget: "markdown" }` to Kitchen Sink example after Typed List
- Click the drop down ![image](https://user-images.githubusercontent.com/2372558/57507834-bea9f580-72b4-11e9-97f9-88ff98b8a40a.png)
- Make change to `z-index: 2`
- Reload and click the drop down 
=> fix(widget-markdown): keep markdown widget dropdowns on top

packages/netlify-cms-widget-markdown/src/serializers/__tests__/__fixtures__/commonmark.json, packages/netlify-cms-widget-markdown/src/serializers/__tests__/commonmark.spec.js
Adds a skipped test suite that asserts Commonmark compliance for all of our Markdown handlers via the [Commonmark spec](https://spec.commonmark.org/0.28/spec.json). The suite can be unskipped during local testing for developers working on improving our Commonmark support.
=> chore(widget-markdown): add failing commonmark spec

website/content/docs/add-to-your-site.md
**Summary**
This simply adds the static file directory information for Zola (documentation [here](https://www.getzola.org/documentation/getting-started/directory-structure/)) to the table found on the Add To Your Site page of the Netlify CMS docs ([here](https://www.netlifycms.org/docs/add-to-your-site/#app-file-structure)).
**Test plan**
I installed the website's dependencies and started a local server to test the modifications, using the instructions in the README.  I'm using Node.js 10.16.0 LTS and Yarn 1.16.0 locally.
```
yarn
yarn start
```
On the local version of the site, the modified table renders as expected (pictured below).
=> Add Zola to static files directory table

package.json, yarn.lock
Closes #2345
**Summary**
Fixed version to support Node 12 for monorepo
=> fix: bump babel-plugin-inline-svg to v1.0.1

packages/netlify-cms-core/src/actions/__tests__/entries.spec.js, packages/netlify-cms-core/src/actions/entries.js
**Summary**
Currently the `createEmptyDraftData`  function creates an empty array object `[{}]` and object `{}`value for `list` and `object` widgets without any default value specified in the config file which in turn forces an empty field(s) for the `list` widget  in the editor page. Also for single `list` `field` widget with config default key set, the default value generated should come like so `['default value']` but outputs something like `[{widget_name: 'default value'}]` which should be fine if it's a `list` `fields` widget. This PR fixes both issues.
=> fix(core): list widget default values

packages/netlify-cms-core/src/backend.js, packages/netlify-cms-widget-relation/src/RelationControl.js, packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js, website/content/docs/uploadcare.md, website/content/docs/widgets/relation.md
**Summary**
Fixes #2356 
You can specify nested fields for the `displayFields` and `searchFields` options for the [Relation Widget](https://www.netlifycms.org/docs/widgets/#relation). The fields are referenced as if they were JSON objects.
Ex. The nested field in the collection:
```yaml
- name: "nestedFields"
label: "Nested Fields"
...
fields:
- name: "title"
label: "Title"
widget: "string"
- name: "nestedFields"
label: "Nested Fields"
widget: "object"
fields:
- name: "field1"
label: "Field 1"
widget: "string"
- name: "field2"
label: "Field 2"
widget: "string"
...
```
can be referenced in the `displayFields` and `searchFields` options of the  [Relation Widget](https://www.netlifycms.org/docs/widgets/#relation) as so:
```
displayField: ['nestedFields.field1', ...]
searchField: …
```
=> Nested Fields for Search/Filtering in Relation Widget

packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
**Summary**
Fixes #2414.
The invisible Waypoint that loads more entries for paginated backends like GitLab was always rendered, so when the backend asynchronously updates state to show that there are more entries to load, the Waypoint was already visible, so the new entries don't load.
This PR hides removes the Waypoint component if there are no entries, and renders it if there are entries, ensuring that a half (or entirely) empty screen won't occur.
=> fix(core): load more entries until viewport is filled

website/content/docs/cloudinary.md
**Summary**
Spent an hour figuring out why I was unable to login and the request was just failing with `401` account. Didn't realize I was logged in with my personal Cloudinary account instead of the companies account.
**Test plan**
Just a document update.
The failed image looked like
After I logged in to Cloudinary with the right account.
⚠️ Sadly, the INSERT button still doesn't work, does nothing.
=> 👌 IMPROVE: Cloudinary Login Info

website/content/docs/contributor-guide.md
**Summary**
In the [Contributor Guide](https://www.netlifycms.org/docs/contributor-guide/) for the Netlify CMS docs, the link to the style guide is broken.
**Test plan**
Build the site and ensure that the link on the page works.
_[Photo by Sebastian Yepes](https://unsplash.com/photos/NnRYWprcWkE)_
=> Fix link to style guide

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/formats/__tests__/frontmatter.spec.js, packages/netlify-cms-core/src/formats/toml.js, yarn.lock
**Summary**
Closes #2144 
**Test plan**
This is a drop in replacement for the existing toml parser, but I have added a new test for dates.
Here's a cute cuttlefish (well I think it's cute):
=> Update toml library from toml-j0.4 to @iarna/toml@2.2.3

packages/netlify-cms-core/src/components/Editor/EditorInterface.js, packages/netlify-cms-core/src/components/Editor/EditorToggle.js
**Summary**
This pull request adds the `title` attribute to the Editor Toggle button, so that when a user hovers over the button icon, they can see some info about the button and what it does.
https://www.w3schools.com/tags/att_global_title.asp
**Motivation**
I usually try to figure out what an icon could mean when I first see it. On the post edit page I saw an `eye` icon, which seemed like it meant something to do with the _view_ and the other one looked like an up down arrow, so maybe something with _scroll_. Just to confirm my instinct, I tried to hover the icons to know what it did and I saw there was no info. 
Though there was no trouble for me to trying out clicking it and see what it did, but I would have appreciated that the button info could have helped me confirm my instinct in …
=> Add title attribute to Editor Toggle buttons to show info on hover

packages/netlify-cms-core/src/components/App/App.js
👋  Hey folks! This is my first PR for this project — I've used the repo for years, so I'm super excited. Let me know how I can improve this code or the PR itself. 
_See #697 for more information!_
- For a lot of users, it adds utility and clarity to access files at `/edit/:folder/:filename`, so this PR allows users to do so.
- If a user accesses `/edit/:folder/:a-filename-that-does-not-exist`, it will create a new file with that slug. 
- ex. `${baseUrl}/edit/_posts/fdjiosajfidosa` creates `posts/fdjiosajfidosa.md`.)
- If a user accesses `/edit/:a-files-based-collection/:filename`, they are redirected to the relevant collection for that file. 
- If a user accesses `/edit/:a-folder-that-does-not-exist`, they are redirected to a Not Found view.
- ~I've been informed by _some professionals_ …
=> Accessing `/edit/:folder/:filename` routes to correct editor page [Fixes #697]

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
Fixes #2098 
`translate` creates a function component hence the warning.
If the `ref` is really needed (I'm assuming not at the moment) we can:
* Update to latest version of `react-redux` and use `forwardRef`:
https://react-redux.js.org/api/connect#options-object
or
* Wait for this pr https://github.com/nayaabkhan/react-polyglot/pull/20
=> Fix: don't pass ref to react-polyglot 'translate' function component

packages/netlify-cms-backend-github/src/API.js, packages/netlify-cms-backend-github/src/GraphQLAPI.js, packages/netlify-cms-backend-github/src/fragments.js, packages/netlify-cms-backend-github/src/implementation.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCard.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryModal.js
Fixes https://github.com/netlify/netlify-cms/issues/2633
The main issue was that I constructed the `download_url` manually since it is not available from the GraphQL API. The REST API returns it with a token query parameter. The token was missing from the constructed URL, thus failing on private repositories.
The solution was to use the built-in mechanism to load media URLs by implementing `getMediaDisplayURL`.
Other fixes related to the media library:
* Adding and deleting an image was broken since `getTree` return value was missing the tree `sha`.
* Media library listed directories as well, so I filtered the result of the GraphQL query (didn't find an option to filter it in the query itself).
* Added some missing prop types to the media library as I was already debugging that code and …
=> Fix (GitHub - GraphQL): use getMediaDisplayURL to load media with authorization header

packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js
👋  Hey folks! 
_See #1983 for more information!_
- Uploading a single image should in the MediaLibraryModal should set that image to the selected image. This is a UX improvement; 99% of the time, you're uploading an image to use it immediately.
1. Run the app and navigate to it in a browser.
2. Access any post with an image field, and click **Choose an image**.
3. Upload one image.
4. That image, once uploaded, should be automatically set as the _selected_ image.
5. **Try uploading an additional image**. The first image will no longer be selected, and the newest image will be selected. 
6. **Try selecting an image other than the most recently uploaded**.
> This is Jazzy, a another greyhound I used to foster. (Some kind of lab mix, clearly 😂)
=> Uploading new media automatically sets that media to selected [Fixes #1983]

packages/netlify-cms-core/src/components/Editor/EditorInterface.js
closes #1122 
**Summary**
This PR removes the width constraint from the Editor Interface. 
---
I no longer have a large monitor, so please verify!
Thanks
=> Remove Editor Interface's width constraint

website/content/docs/nuxt.md
👋  Hey folks! 
Yet another one for #2092! 
- Borrows heavily both from the Netlify CMS "Getting Started" and previously existing guides. 
- Walks through all the way from installing Netlify CMS in the application, to rendering Netlify CMS content in Nuxt. _(A lot of the community modules for handling this are janky sometimes, so I wanted to create a guide that doesn't have additional deps for managing static content.)_
Feedback welcome and encouraged. I'll be adding commits to improve the adherence of this to the style-guide etc.
- **Should the guide be updated to use Markdown/Frontmatter, as that's the Netlify CMS default?**
In this solution, I specify that the content should be stored by Netlify CMS in JSON format — this is so it's easily-consumed by Nuxt without additional deps for …
=> [Guide] Adding Netlify CMS to Nuxt

packages/netlify-cms-widget-date/src/DateControl.js, packages/netlify-cms-widget-datetime/src/DateTimeControl.js, packages/netlify-cms-widget-datetime/src/DateTimePreview.js, packages/netlify-cms-widget-datetime/src/index.js, website/content/docs/widgets/date.md
Closes #1688 
I took the code from DateControl.js and moved it into DateTimeControl.js, removing the boolean flag which was there previously. I also added deprecation notices to the code and documentation. To reproduce the behavior of the date widget you add `timeFormat: false` to a datetime field.
=> chore: update datetime widget and deprecate date widget

packages/netlify-cms-backend-github/src/API.js
**Summary**
Previously, `editorialWorkflowGit` would update the unpublished entry branch by using `rebasePullRequest` if the entry had a pr. Since the normal editorial workflow creates PRs for all unpublished entries, that runs for all of them. When Open Authoring is active, unpublished entries that have never been submitted for review have no PR (not even a closed one), so the backend was failing to update these entries.
The one-line fix in this commit updates the corresponding branch with `patchBranch` when an unpublished entry without a PR is updated.
**Test plan**
Tested manually after reproducing the bug.
=> Update Open Authoring branches when a PR hasn't been created

packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js, packages/netlify-cms-core/src/reducers/collections.js
Closes #2481 
**Summary**
Changes the default `delete` configuration value for file collections to `false`
**Test plan**
Wrote a test to check that querying a file-based collection with no explicit value returns false
=> Prevent deletion of file collection entries by default

packages/netlify-cms-backend-github/src/API.js, packages/netlify-cms-backend-github/src/GraphQLAPI.js, packages/netlify-cms-backend-github/src/implementation.js
Follow up on this comment: https://github.com/netlify/netlify-cms/pull/2652#pullrequestreview-283938073
Moved `getMediaDisplayURL` implementation to the API class and renamed some methods so they make more sense.
=> Refactor (GitHub Backend): move getMediaDisplayURL from implementation to api

packages/netlify-cms-backend-github/src/implementation.js, packages/netlify-cms-lib-util/src/__tests__/asyncLock.spec.js, packages/netlify-cms-lib-util/src/asyncLock.js, packages/netlify-cms-lib-util/src/index.js
Fixes https://github.com/netlify/netlify-cms/issues/2634
I found two possible race conditions:
1. Publishing a branch can delete it before the update entry operation completes, thus attempting to update a non existing branch.
2. Updating entry status (e.g. moving to 'Ready') can update the metadata with old values (old head sha for the pull request). This can happen if the update status operation reads the metadata before the update entry operation completes, but updates the metadata after the update entry operation completes, thus overriding both the status (which is ok) and the head sha (which is not ok). This results in publishing the entry without the updated content.
I created an `async` version of the `semaphore`  that you can `await` on in an optimistic way.
Optimistic means it …
=> Fix (GitHub Backend): handle race condition in editorial workflow

dev-test/config.yml, packages/netlify-cms-widget-relation/src/RelationControl.js, packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js, website/content/docs/widgets/relation.md
**Summary**
Decided to take a swing at https://github.com/netlify/netlify-cms/issues/2519 which provides the ability to customize the amount of options that are presented to the user within the searchable select.
**Test plan**
1. Add `optionsLength` (with number value) to relation widget config. 
1. Should update number of results.
=> Add ability to set custom options length for relation widget

packages/netlify-cms-media-library-cloudinary/src/__tests__/index.spec.js, packages/netlify-cms-media-library-cloudinary/src/index.js
**Summary**
When selecting 2 images via Cloudinary media_library, the image strings are saved in markdown as an array. When selecting 1 image, it is saved in markdown as a string. When `multiple=true` is set in the configuration, both of these cases should return an array.
See https://github.com/netlify/netlify-cms/issues/2573 for more information.
Fixes #2573 
**Test plan**
I added unit test coverage that supports this change.
=> media-library-cloudinary: when 'multiple' is true, always return arrary (#2573)

packages/netlify-cms-widget-number/src/__tests__/number.spec.js
**Summary**
I've added the new test case to cover two if branches in this code:
https://github.com/netlify/netlify-cms/blob/3903acb431998b5a060825f2d600b4a7cb1a010a/packages/netlify-cms-widget-number/src/NumberControl.js#L34
Here the screenshot from test coverage report:
**Test plan**
Please run the test with options:
```
$ npm run test:unit --coverage --coverageReporters=html
```
After test is passed please check the report for `netlify-cms-widget-number` package.
=> Add new test to increase the test coverage in widget-number

babel.config.js, dev-test/config.yml, package.json, packages/netlify-cms-ui-default/src/Icon.js, yarn.lock
**Summary**
The `deasync` package was causing failures for Node 12, even though an update was supposed to have addressed it months back. It was in the deps tree for `babel-plugin-inline-svg`, so this PR swaps in `babel-plugin-inline-react-svg`, which is also more widely used and better maintained, and allows us to avoid an instance of `dangerouslySetInnerHTML`.
**Test plan**
They all pass.
```
_.---._    /\\
./'       "--`\//
./              o \
/./\  )______   \__ \
./  / /\ \   | \ \  \ \
/ /  \ \  | |\ \  \7
"     "    "  "        VK
```
=> fix: swap out svg plugin causing failures

website/content/docs/jekyll.md
The current YML syntax for the navigation items causes an error.
=> [Guide] Update Jekyll YML syntax

.github/workflows/nodejs.yml, website/content/pages/community.md, website/netlify.toml
We're not officially moving to Gitter, just trying it out. This PR will direct chat support seekers to Slack instead of Gitter. We're announcing a change and will switch back if we decide this is somehow worse.
Reasons for moving to Slack:
- Dedicated workspace, rather than a long list of unrelated/non-prioritized people and channels
- Mobile experience is 10,000% better - I very often am unable to respond to things because mobile Gitter is just pure pain
- Limited to 10k message history, but those 10k will be searchable in a way that's actually useful
- Lots of folks are already in multiple Slacks, so this is more meeting people where they are
- Generally better communication experience across platforms
=> docs: add community slack link

.github/workflows/nodejs.yml
Currently since the workflow triggers are `push` and `pull_request` the same GitHub Actions workflow is executed twice for the same commit. Once the commit is pushed, and once again when the pull request is opened.
This change will run the workflow on any push to master (or tags), but will ignore non master branches. For the workflow to run on non master branches a PR needs to be created.
=> ci: run workflow on push to master and tags OR pull requests

.github/workflows/nodejs.yml
Since build secrets are not passed to forked repositories the cypress tests fail on forked pull requests. This enables the tests to pass on forked pull requests AND non forked ones while keeping the recording feature of cypress.
Fixes https://github.com/netlify/netlify-cms/issues/2780
=> ci(e2e_tests): don't record cypress tests on pull requests from forked repos

packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
Currently, when opening a Collection and viewing the list of cards, hovering over one of the cards turns the card's rounded corners into square corners. 
This has always bugged me so I decided to fix it as my first contribution to an open-source project. 
**Test plan**
I don't think tests are needed, it's just a single line of additional CSS in one commit. I have verified using the development environment that the corner-unrounding is no longer present in Chrome or Safari. 
_A diagram of the UI issue being addressed_
=> Fix ListCard corners becoming un-rounded on hover

packages/netlify-cms-widget-number/src/NumberControl.js, packages/netlify-cms-widget-number/src/__tests__/number.spec.js
Fixes #2785.
Also added some tests for the min max logic.
=> fix: don't enforce min max when number value is empty

packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
**Summary**
This PR improve error message if no widget exist. fixes #2717 
If add to collection field:
```
- { label: "content", name: "content", widget: "does-not-exist" }
```
Error message before:
```
Uncaught TypeError: this.wrappedControlValid is not a function
```
Error message now:
```
Error: The wrappedControlValid is not a function (widget: does-not-exist).
```
**Test plan**
1. Add to collection this field: `- { label: "content", name: "content", widget: "does-not-exist" }`
2. Create new collection
3. Try to push Save/Publish button and observe the error in console.
=> enhancement: improve error with no existing widget

packages/netlify-cms-backend-github/src/API.js
Related to #2593.
No need to patch the branch twice
=> chore: remove duplicate bug fix for open authoring

website/content/docs/widgets/select.md
**Summary**
The docs for the select widget don't mention the widget behaviour when using object based options.
After some trial and error I think I got it figured out.
**Test plan**
Ask everyone involved at the office and see if my conclusion is correct.
Please refer to #2718
On a different/continuative note:
The widgets don't handle their own default behaviour. The control component just gets handed the current value as prop. Where in the cms is this value calculated?
=> Specified default value behaviour

website/content/docs/add-to-your-site.md
**Summary**
Reading the documentation, I noticed that the default directory for 11ty generated sites was out of date and updated it accordingly.
**Test plan**
No test, but you can verify on the official 11ty docs here:
>This will compile any content templates in the current directory or subdirectories into the output folder (defaults to _site).
-- https://www.11ty.io/docs/getting-started/#step-4-create-some-templates
¯\\\_(ツ)\_/¯
=> docs: update 11ty default site publish folder

website/content/docs/netlify-large-media.md
I ran into this issue when activating Large Media while still having not imported files.
**Summary**
When a file type (i.e. `*.jpg`) is tracked via lfs but there are still files of that type present that are not yet imported into lfs the CMS throws an error because it can't find a Large Media url for it.
Picture of the first offspring my mums tortoises produced roughly two months ago. For reference the little bugger is a bit wider than a (my) thumb.
=> Added notice about Large Media option

packages/netlify-cms-media-library-uploadcare/src/__tests__/index.spec.js, packages/netlify-cms-media-library-uploadcare/src/index.js, website/content/docs/uploadcare.md
**Summary**
I've added a several settings that control the behavior of integration with the widget.
* `autoFilename` (`boolean`) - specify whether to add a filename to the end of the url.
Example: `http://ucarecdn.com/:uuid/filename.png`
* `defaultOperations` (`string`) - specify a string added at the end of the url.
This could be useful to apply a set of CDN operations to each image,
for example resizing or compression.
=> enhancement(media-library-uploadcare): add integration settings to control url operations

packages/netlify-cms-backend-bitbucket/src/API.js, packages/netlify-cms-backend-bitbucket/src/implementation.js, packages/netlify-cms-backend-git-gateway/src/implementation.js, packages/netlify-cms-backend-gitlab/src/implementation.js, packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/lib/__tests__/backendHelper.spec.js, packages/netlify-cms-core/src/lib/backendHelper.js, website/content/docs/beta-features.md
Fixes #2809 
Example:
```yaml
backend:
commit_messages:
openAuthoring: '{{author-login}} - {{author-name}}: {{message}}'
```
Where `{{message}}` is the relevant commit message.
PR Overview:
* Extracted `commitMessageFormatter` to a separate file so I can test it
* The backend changes are to make sure the `user.login` and `user.name` are populated since they differ between backends.
* `bitbucket` backend has a bug fix - the response to the user request wasn't resolved as json. Also `hasWriteAccess` doesn't need the `user` argument so I removed it (see [here](https://github.com/netlify/netlify-cms/blob/f9d32452f9c82129b8523fa3c240535965bfda5d/packages/netlify-cms-backend-bitbucket/src/API.js#L50) and [here](https://github.com/netlify/netlify-cms/blob/f9d32452f9c82129b8523fa3c240535965bfda5d/ …
=> feat: enable specifying custom open authoring commit message

packages/netlify-cms-backend-github/src/API.js, packages/netlify-cms-backend-github/src/implementation.js
Fixes #787.
Downside - images load a bit slower on initial load.
Upside - images are not reloaded when they expire from browser cache (since it is not used anymore).
=> fix(github-backend): load media URLs via API

.github/stale.yml
`wontfix` is confusing and convey a message we won't fix the issue/pr.
This change will use an already existing label `status: stale`
=> chore: change stale bot label

yarn.lock
This commit 4335ef0aa5fb0c18be3889f6d235b41aec0305ce broke the media library modal:
Reverting until we can figure this out.
@erquhart I noticed build previews don't run for changes to `yarn.lock` file. Is this https://github.com/netlify/netlify-cms/blob/4335ef0aa5fb0c18be3889f6d235b41aec0305ce/netlify.toml#L5 the right place to change it?
=> Revert "chore(deps): lock file maintenance (#2836)"

packages/netlify-cms-core/src/components/App/App.js, packages/netlify-cms-core/src/components/App/Header.js, packages/netlify-cms-core/src/components/UI/SettingsDropdown.js
**Summary**
Fixes #2470 
>The test repo backend i indistinguishable from other backends in the UI. If a user doesn't know they're using it, the whole experience is confusing.
Added a flag, `isTestRepo` in the `Header` props. If its `true`, a Link with text `Text Backend` is shown to indicate Test Repo Mode which on click takes to [docs](https://www.netlifycms.org/docs/authentication-backends#test-repo-backend) page.
**Test plan**
=> Fix #2470: Show Test Repo is in use

website/content/docs/widgets/relation.md
Added a sentence on type specification of valueField option parameter.
**Summary**
This is related to an issue thread "Using array in valueField of relation widget causes TypeError #2445".
The purpose of this request is to give a guide to people referring to the doc so that they will not see the TypeError.
If you use array type for the valueField in the "relation" widget of collection, it shows an error screen when you access to the collection record in the admin dashboard.
To avoid this problem, String type of value needs to be set to the `valueField` option parameter.
The added sentence to the doc explicitly states so.
**Test plan**
Proofreading.
=> Type specification of valueField

packages/netlify-cms-core/src/backend.js, packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js, packages/netlify-cms-core/src/components/Workflow/WorkflowList.js, packages/netlify-cms-core/src/constants/defaultPhrases.js, packages/netlify-cms-core/src/reducers/collections.js
**Summary**
Fixes #2469 
Editorial Workflow Entries like General Settings and Authors are not differentiated in the Workflow cards(because `title` is not available). 
In this PR, Added `Slug` as fallback for `title` if not available.(Couldn't get any entry like `label`, so went forward with `slug`)
**Test plan**
** Cute Animal Pic **
=> Fix #2469 : File collection entries not differentiated in Workflow

.github/workflows/nodejs.yml
GitHub actions recently added support for caching dependencies:
https://github.com/actions/cache/blob/bc821d0c12b430b965fdc132e1a32a346ce876d4/examples.md#node---yarn
I also add the `--frozen-lockfile` flag to make sure the `yarn.lock` file is not updated during build time. See more here: https://yarnpkg.com/lang/en/docs/cli/install/
=> ci: add yarn caching

packages/netlify-cms-core/src/actions/__tests__/mediaLibrary.spec.js, packages/netlify-cms-core/src/actions/mediaLibrary.js
Support for external media libraries is broken due to this: https://github.com/netlify/netlify-cms/pull/2394/files#diff-83ad3a59b8d4a8799b655d83525af37dR85
The `insertMedia` action should accept a `string` or `string[]` as it is called from the external media libraries with such types:
https://github.com/netlify/netlify-cms/blob/1d78a2705f58cb72d81bfa66548a6060c1712963/packages/netlify-cms-media-library-cloudinary/src/index.js#L63
https://github.com/netlify/netlify-cms/blob/1d78a2705f58cb72d81bfa66548a6060c1712963/packages/netlify-cms-media-library-uploadcare/src/index.js#L104
=> fix(external-media-libraries): support for external media libraries is broken

jest.config.js, packages/netlify-cms-backend-git-gateway/src/GitHubAPI.js, packages/netlify-cms-backend-git-gateway/src/__tests__/GitHubAPI.spec.js, packages/netlify-cms-backend-github/src/API.js, packages/netlify-cms-backend-github/src/__tests__/API.spec.js
The authorization header was not sent for paginated requests when using `git-gateway` with a GitHub repo.
Introduced here: https://github.com/netlify/netlify-cms/commit/34e1f0910544d38b5142b0e45c178441faecb7a3#diff-b4ba42c688a23ed9cec5139daec2c157R115 and only partially fixed (for the GitHub backend) here: https://github.com/netlify/netlify-cms/commit/ece136c92e87500c0bda945ba4669e7a9366cda6#diff-b4ba42c688a23ed9cec5139daec2c157R120
To reproduce:
1. Deploy a site to Netlify with a `git-gateway` setup and editorial workflow.
2. Create a new POST and change to workflow tab to list the unpublished entries - you should get an error:
The `pulls` API call is sent without an authorization header:
=> fix(git-gateway): unpublished entries not loaded for git-gateway(GitHub)

packages/netlify-cms-backend-github/src/__tests__/implementation.spec.js, packages/netlify-cms-backend-github/src/implementation.js
I noticed the fix [here](https://github.com/netlify/netlify-cms/pull/2802) doesn't work for https://github.com/CSS-Tricks/serverless.
The GitHub API returns the parent name as `CSS-Tricks/serverless` while the config repo is `css-tricks/serverless` so I changed the comparison to be case-insensitive.
=> fix: make forkExists name matching case-insensitive

packages/netlify-cms-widget-relation/src/RelationControl.js
While waiting for the gatsby repo to clone 😪  I analyzed the bundle size and noticed `react-select` was imported twice.
Before:
After:
=> fix(bundle-size): don't import react-select twice

packages/netlify-cms-locales/src/index.js, packages/netlify-cms-locales/src/uk/index.js
**Summary**
- Changes: Add ukrainian (uk) locale to the list of locales
- Motivation: I'm a native ukrainian speaker and I want my editors to have a CMS in a language they can fully understand
**Test plan**
- Content:
- Editorial Workflow:  
- Media:  
=> feat(lang): add 'uk' locale

packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCardGrid.js
**Summary**
Currently, the `MediaLibraryCardGrid` is using  `innerRef` prop is which causing this console error on dev:
`innerRef is deprecated and will be removed in a future major version of Emotion, please use the ref prop instead in the usage of CardGridContainer`
Swap `innerRef` for `ref`.
=> fix: emotion use ref prop

website/content/docs/add-to-your-site.md, website/content/docs/nextjs.md
**Summary**
1. Missing Netlify Identity Widget
This is a PR for the NextJS guide in the docs: https://www.netlifycms.org/docs/nextjs. I had a tough time getting up and running—these changes would have solved the problem.
It is frustrating how your own docs mention the need to add the Netlify Identity Widget in **two places** (https://www.netlifycms.org/docs/add-to-your-site/#add-the-netlify-identity-widget), but the NextJS guide only includes it in **one place**. This results in frustrated users who can't figure why they are gettting "Email not confirmed" errors on their admin page:
Frustrated users with the same problem:
- https://github.com/netlify/netlify-identity-widget/issues/125
- https://github.com/netlify/netlify-identity-widget/issues/116
- …
=> [documentation] improve NextJS docs by adding Identity Widget to homepage

website/content/docs/configuration-options.md
**Summary**
I've added one missing option in the collection configurations list (`preview_path_date_field`) and fixed a title of `frontmatter_delimiter` section to follow the convention on the page.
**Test plan**
You can preview the updated .md file to see changes
=> Minor update for Configuration Options docs

packages/netlify-cms-widget-markdown/src/serializers/index.js
Updates the markdown widget serializer to remove \r characters from text.
Fixes issue #1437 with the patch proposed by the issue creator - @papandreou
**Summary**
Recently, carriage returns (\r) have been added to git commits for our static sites through using netlifycms. Due to these characters being added, when doing a fresh clone of a website repo there were unstaged changes in the working git tree due to our [.gitattributes file](https://github.com/Linaro/website/blob/develop/.gitattributes) setting `text=auto`. This PR will strip any \r characters from the markdown widget text. I've built a custom version of netlify-cms with this patch applied and tested by creating a duplicate PR.
Before Patch: [https://github.com/Linaro/website/pull/928/commits/89bb049f85fb64f3bbbd9a9778c25b94d5ffea …
=> Fixes carriage return issue with markdown widget #1437

website/content/docs/nextjs.md
**Summary**
This PR is giving changes to the usage of `frontmatter-markdown-loader` on the NextJS sample doc.
As an author of `frontmatter-markdown-loader`, I'd recommend using `react-component` mode to avoid using `dangerouslySetInnerHTML` which scares developers 😉 
`frontmatter-markdown-loader` now gives `react` as named import which is mountable as React component.
**Test plan**
Just updating doc. Check on your browser with running `/website`
To see the working sample, I've sent another PR to the sample repository by the original author of this doc: https://github.com/steffenz/netlify-cms-nextjs-example/pull/4
🐈
=> [documentation] Update NextJS sample: Import React component instead of inserting HTML with "dangerouslySetInnerHTML"

packages/netlify-cms-core/src/actions/editorialWorkflow.js
**Summary**
A fix for the issue described by Mateusz on slack:
> New beta feature publish/unpublish, with editorial workflow on (not sure if this is related, just letting you know) ->
When you unpublish, new branch is being created to store the file you unpublished. Good.
Then the file gets displayed under Workflow tab in CMS. Perfect.
I check in repo, and the file exists on this new branch which is cool.
Then you click to publish inside CMS to get file back again, and you randomly get error in cms, on repo branch storing unpublished file gets merged to the main branch, but it says branch has no changes, so its like empty merege, and the “store” branch gets deleted. (so you basically lose your “unpublished”  file)
-> I basically lost that way few files, but I also managed randomly to get …
=> fix: unpublish published entry

packages/netlify-cms-app/index.d.ts, packages/netlify-cms-app/package.json, packages/netlify-cms-core/index.d.ts, packages/netlify-cms-core/package.json
Hello! It's a partial fix for #2926 including TypeScript type definitions for `netlify-cms-core` and `netlify-cms-app`. 
**Summary**
I'm using Netlify CMS in TS project, so I needed types for it. I first wrote them in my project, so these types are partially tested in my project. However, there is still room for improvement since some types are defined as `any` which is not good. If I'll get more details about those types I'll open a separate PR with the fix. Also, please take a look and maybe you can tell me straight away what kind of values we can expect there, so I could change it right away before merging this PR.
Also, I've updated `package.json` files for these two packages so the types will be automatically added to the next NPM release.
**Test plan**
Well, who is testing before …
=> fix: .d.ts definitions for core and app

packages/netlify-cms-lib-auth/src/implicit-oauth.js
Fixes https://github.com/netlify/netlify-cms/issues/1824
See comment here https://github.com/netlify/netlify-cms/issues/1824#issuecomment-559064466
Dependant on https://github.com/netlify/netlify-identity-widget/pull/223 to work
=> fix: pass auth type in implicit auth URL to be used in identity widget

packages/netlify-cms-core/src/lib/stringTemplate.js
**Summary**
Tests fail when run in a UTC negative timezone, Eg., from the east coast, `2020-01-01` becomes `Tue Dec 31 2019 19:00:00 GMT-0500 (EST)` - falling back five hours and therefore referencing the previous calendar date.
**Test plan**
Existing tests that fail without this change now passes by providing the expected dates.
=> fix(core): use UTC date methods for slug formatting

website/content/docs/nextjs.md
A simple fix that allows webpack to build.
**Summary**
Webpack failed to build with previous setting use. With the following Error: options/query provided without loader (use loader + options)
**Test plan**
Changing 'use' to 'loader' solves the error, and allows the dev to build.
=> fixed webpack loader error

packages/netlify-cms-locales/src/index.js, packages/netlify-cms-locales/src/ru/index.js
**Summary**
At the moment, the admin UI does not support Russian language.
This PR implement support for the Russian language (feature request netlify#2951) in the admin UI by adding 'ru' locale file in the package netlify-cms-locales.
**Test plan**
This PR contains tested and formatted sources (yarn test & yarn format).
=> feat(lang): add 'ru' locale (netlify#2951)

packages/netlify-cms-core/src/reducers/__tests__/globalUI.js, packages/netlify-cms-core/src/reducers/globalUI.js
Small usability fix, but one that has been bugging me for a while.
When you open an unpublished entry it will load the entry, then show the progress bar for an additional 15 seconds due to the loading of the deploy preview URL (3 attempts of 5 seconds intervals).
It is not very clear that the progress bar is related to deploy preview URL loading (only visible when opening the network traffic).
I think we might want to add a specific loading indication just for the deploy preview URL in the future.
=> fix: don't show progress when loading preview URL status

packages/netlify-cms-ui-default/src/styles.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js
Allows dropdown lists within the markdown editor to stay on top of sibling markdown editors that are also nested, but keeps them inside the parent editor.
=> fix: avoid nested select widget z-index conflicts

website/content/docs/authentication-backends.md
`accept_roles` was removed a while back when the internal Cursor API was introduced, this PR removes it from the docs.
=> docs: remove outdated accept_roles reference

packages/netlify-cms-widget-object/src/ObjectControl.js
Fixes #3016 
This may break something, just can't figure out what. I did notice that, at some point, we started wrapping all object nested widgets inside of a container that was meant solely for the widget top bar, and I'm not sure if that's bad at the moment. If this breaks we'll investigate further.
=> fix(widget-object): allow nested widgets to overflow

packages/netlify-cms-app/package.json, packages/netlify-cms-app/src/extensions.js, packages/netlify-cms/package.json, packages/netlify-cms/src/extensions.js, yarn.lock
The code widget and locales are registered only in the netlify-cms package, our least used distribution. The added size they bring should be addressed in the future, perhaps through lazy loading, but the priority for now is usability.
This PR registers locales and the code widget in the netlify-cms-app distribution so just about everyone gets them out of the box.
Feedback welcome.
=> fix: move code widget and locales to netlify-cms-app

packages/netlify-cms-core/src/actions/mediaLibrary.ts
Fixes https://github.com/netlify/netlify-cms/issues/3048
=> fix: don't wait for external media library to load

website/content/docs/widgets/datetime.md
This should clarify what the format options do. The example is updated to show a plausible non-default case. The "optional" hint is not used in the other widgets' docs, so I removed it. If you want to keep it (edit my commit), the `default` parameter should have it too for consistency.
=> Update datetime widget description

packages/netlify-cms-backend-github/src/GraphQLAPI.js
Non existent folders usually happen on new projects. No reason to fail on that.
=> fix(backend-github-graphql): return empty array on non existent folder

website/content/docs/architecture.md, website/content/docs/customization.md
Kind of resolves https://github.com/netlify/netlify-cms/issues/3062.
Changing `getAsset` to return a promise was an intended breaking change as the previous version wasn't working in some cases (was dependant on having the asset deployed to the site).
=> docs: update getAsset documentation

packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js
Closes #3081, forgot to prevent default on custom paste.
=> fix(widget-markdown): stop double pasting in raw editor

packages/netlify-cms-core/src/valueObjects/EditorComponent.js, packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js
**Summary**
Replacement fix for bug outlined in #3077.
Adds multiline flag (and excludes others) for all editor component patterns - this allows the beginning and end anchors to match lines instead of the entire remaining value.
**Test plan**
Unit test added.
=> fix(core): force multiline flag for editor component patterns

packages/netlify-cms-widget-markdown/src/MarkdownControl/__tests__/__snapshots__/parser.spec.js.snap, packages/netlify-cms-widget-markdown/src/MarkdownControl/__tests__/parser.spec.js, packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkSlate.spec.js, packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js
Fixes https://github.com/netlify/netlify-cms/issues/3039
Couldn't reproduce the original issue https://github.com/netlify/netlify-cms/issues/2211
Makes sure to conform to slate schema as set here: https://github.com/ianstormtaylor/slate/blob/a0b7976cb9a2812d8d96361e9993fe8853a2cc64/packages/slate/src/plugins/core.js#L96
Not sure this is the most elegant way to solve it...
See my comment here https://github.com/netlify/netlify-cms/issues/2211#issuecomment-574141780
Also see principal number 2 here https://github.com/ianstormtaylor/slate#principles
=> fix: ensure remarkToSlate result matches slate schema

packages/netlify-cms-core/src/valueObjects/EditorComponent.js, packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js
Fixes https://github.com/netlify/netlify-cms/issues/3088
Probably fixes https://github.com/netlify/netlify-cms/issues/3086
Reverted https://github.com/netlify/netlify-cms/pull/3082 as a fix (the multiline flag had it matching when it shouldn't I think) and implemented a workaround for https://github.com/netlify/netlify-cms/pull/3077 as I'm not sure what is the correct way to handle multi lines.
Update: the second commit fixes https://github.com/netlify/netlify-cms/issues/3037 ([forked](https://github.com/erezrokah/marie-hogan-singer) the repo, [restored](https://github.com/erezrokah/marie-hogan-singer/blob/0e567eb2989b425f765b3ba843ab54079590fcb9/src/pages/posts/basic-rules-for-walking-in-the-mountains.md) the relevant file to reproduce the issue).
The error comes from here: …
=> revert: don't force multiline flag for editor component patterns

packages/netlify-cms-backend-git-gateway/src/implementation.ts, packages/netlify-cms-backend-git-gateway/src/netlify-lfs-client.ts
Fixes https://github.com/netlify/netlify-cms/issues/3093
For some reason the repo had one pointer file with empty content. We shouldn't fail just because one file.
=> fix(large-media): don't fail on malformed pointer files

packages/netlify-cms-core/src/actions/__tests__/entries.spec.js, packages/netlify-cms-core/src/actions/__tests__/media.js, packages/netlify-cms-core/src/actions/editorialWorkflow.ts, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/actions/media.ts, packages/netlify-cms-core/src/actions/mediaLibrary.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js, packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/lib/__tests__/backendHelper.spec.js, packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js, packages/netlify-cms-core/src/lib/__tests__/stringTemplate.spec.js, packages/netlify-cms-core/src/lib/backendHelper.ts, packages/netlify-cms-core/src/lib/formatters.ts, packages/netlify-cms-core/src/lib/stringTemplate.ts, packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js, packages/netlify-cms-core/src/reducers/entries.ts, packages/netlify-cms-core/src/types/redux.ts, website/content/docs/beta-features.md, website/content/docs/configuration-options.md
Fixes https://github.com/netlify/netlify-cms/issues/3054
Fixes https://github.com/netlify/netlify-cms/issues/3055
Fixes https://github.com/netlify/netlify-cms/issues/3084
Fixes https://github.com/netlify/netlify-cms/issues/3056
Moved all the different formatters to a dedicated file (renamed it from `backendHelper`) and added some tests.
Also added the ability to access nested field content (e.g. `categories[0]`)
The `filename` and `extension` are only implemented for media folders and Preview URLs templates at the moment (not sure it makes sense for `path` and `slug` as these templates are used to generate the filename).
@erquhart I have an example config [here](https://github.com/erezrokah/netlify-cms-reproductions/blob/782ac90ceab1b36e616e0c6473cc1255f53297e1/public/config.yml#L16).
If …
=> Feat: media folders templates

packages/netlify-cms-widget-file/src/withFileControl.js
=> fix(widget-image): hide image overflow in widget control

packages/netlify-cms-backend-git-gateway/src/GitHubAPI.ts, packages/netlify-cms-backend-git-gateway/src/__tests__/GitHubAPI.spec.js, packages/netlify-cms-backend-github/src/API.ts, packages/netlify-cms-lib-util/src/__tests__/backendUtil.spec.js, packages/netlify-cms-lib-util/src/backendUtil.ts
Fixes https://github.com/netlify/netlify-cms/issues/3129 which will happen on any git-gateway+GitHub setup with more than 30 pull requests.
See my comment here https://github.com/netlify/netlify-cms/issues/3129#issuecomment-577722439.
We currently follow GitHub pagination link headers as is which breaks with `git-gateway`. 
Tested with pull requests as this is the only place we follow paginations links.
Another option is to do it in the `git-gateway` project itself.
@erquhart Thoughts?
=> fix(backend-git-gateway): re-write GitHub pagination links

packages/netlify-cms-proxy-server/package.json, packages/netlify-cms-proxy-server/webpack.config.js, yarn.lock
- Removed old `joi` dependency
- Moved `netlify-cms-lib-util` to dev dependencies (it is bundled with the main index file anyway) to avoid unmet peer dependencies warnings.
- Added `bin` entry to make it work with `npx`
Related to https://github.com/netlify/netlify-cms/issues/3136
=> build(proxy_server): cleanup dependencies, add bin entry

packages/netlify-cms-locales/src/index.js, packages/netlify-cms-locales/src/it/index.js
**Summary**
I added the cms localizations for italian users (like me)
I saw that the project was not localized in italian an I wanted to help
**Test plan**
I just looked of how "en" file was defined, duplicated it's content into a new "it" folder and replaced all values in italian.
ps: I liked the cute animal thing, here is mine :D
=> feat: add italian localization

website/content/docs/nuxt.md
**Summary**
While following the tutorial I've noticed that the tutorial code had a bug in which the first two chars of a file were stripped before creating the route file. So the generated route files were named `20-01-27-slug` instead of `2020-01-27-slug`. I've corrected the mistake in the documentation
**Test plan**
Not applicable (?)
=> Docs(nuxt): Do not slice the first two chars of the file name

packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
joining the repo path with the file path is done in `entriesFromFiles`.
=> fix(proxy-server): fix entriesByFiles implementation

website/content/docs/widgets/list.md
Add the missing `collapsed` option with example to list widget docs.
Fixes #3090 
**A picture of a cute animal**
(Not my dog, just found this picture).
=> docs(list-widget): add `collapsed` option to list widget docs (#3090)

packages/netlify-cms-proxy-server/.env.example, packages/netlify-cms-proxy-server/README.md, website/content/docs/beta-features.md
Fixes https://github.com/netlify/netlify-cms/issues/3136
Adds the missing documentation related to the proxy server.
=> docs: create proxy-server docs

packages/netlify-cms-locales/src/de/index.js
**Summary**
I noticed that some german translations were missing. For a german user it might be confusing seeing the fallback language english in some places.
**Test plan**
I compared the english locale file with the german one and added the translations for all the missing entries.
=> fix(locale): add missing german translations

website/content/docs/nuxt.md
I've updated the description for this guide.  It seems you can't use mode: 'spa' if you plan on using nuxtServerInit, even though you are just doing a 'generate'.  So, you have to use 'universal'
@Atinux
=> nuxtServerInit requires mode: universal

website/src/components/sidebar-layout.js
There are some pages where page has horizontal scrolling due to content being overflowed
Example - https://www.netlifycms.org/docs/gatsby/
This PR fixes the above issue(s)
=> docs: fix overflow issue

packages/netlify-cms-core/src/formats/__tests__/yaml.spec.js, packages/netlify-cms-core/src/formats/yaml.js
**js-yaml** fails on closing separators for standalone yaml files, interpreting them as indicating a separate document. Since separators are stripped out on output anyway, and the js-yaml repo doesn't seem responsive to issues/PR's, this fix removes them if present.
=> fix(core): strip closing separators in yaml files

website/src/components/sidebar-layout.js
Noticed that our headers anchors are missing from the docs site, seems like it was introduced in https://github.com/netlify/netlify-cms/pull/3191/files
=> fix(website): missing headers anchors

packages/netlify-cms-backend-bitbucket/src/implementation.ts, packages/netlify-cms-backend-github/src/implementation.tsx, packages/netlify-cms-backend-gitlab/src/implementation.ts, packages/netlify-cms-core/src/actions/__tests__/media.js, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/actions/media.ts, packages/netlify-cms-core/src/actions/mediaLibrary.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js, packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js, packages/netlify-cms-core/src/mediaLibrary.ts, packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js, packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js, packages/netlify-cms-core/src/reducers/collections.ts, packages/netlify-cms-core/src/reducers/entries.ts, packages/netlify-cms-core/src/reducers/mediaLibrary.ts, packages/netlify-cms-core/src/types/redux.ts, packages/netlify-cms-core/src/valueObjects/AssetProxy.ts, packages/netlify-cms-editor-component-image/src/index.js, packages/netlify-cms-lib-util/src/implementation.ts, packages/netlify-cms-lib-util/src/index.ts, packages/netlify-cms-ui-default/src/Asset.js, packages/netlify-cms-widget-file/src/withFileControl.js, packages/netlify-cms-widget-image/src/ImagePreview.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/__tests__/VisualEditor.spec.js, packages/netlify-cms-widget-markdown/src/serializers/remarkRehypeShortcodes.js, yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/3201
Still requires some manual & automated tests, but will let you have a config like this:
```
publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
- name: posts
label: Posts
label_singular: 'Post'
folder: content/posts
create: true
media_folder: ''
public_folder: ''
fields:
- label: Template
name: template
widget: hidden
default: post
- label: Title
name: title
widget: string
- label: 'Cover Image'
name: 'image'
widget: 'image'
required: false
media_library:
config:
media_folder: '/{{media_folder}}/posts/images/widget/image'
public_folder: '{{public_folder}}/posts/images/widget/image'
- label: Publish Date
name: date
widget: datetime
- label: Entry Image
name: 'entryimage'
widget: 'image' …
```
=> feat: field based media/public folders

packages/netlify-cms-proxy-server/src/middlewares/localFs/index.ts
Not sure how this passed our tests (bug introduced in a [code cleanup](https://github.com/netlify/netlify-cms/pull/3217/commits/3bffffc89c1900edecbff288dea09b19960aa22f) commit I did).
Cypress reported a success GitHub status for this run: https://github.com/netlify/netlify-cms/actions/runs/36998894
But on the dashboard it failed: https://dashboard.cypress.io/projects/dzqjxb/runs/4420/specs
Also, the logs for the run are missing from the GitHub action logs
=> fix: fs proxy info action

packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js
**Summary**
Just got a `TextHttpError` in the `AuthenticationPage` -- which throws with "Objects are not valid as a React child" -- so this stringifies the error object before rendering.
**Test plan**
None
=> fix: stringify server error message in authentication page

packages/netlify-cms-core/src/components/App/App.js
Fixes broken `/edit/` redirect route.
=> fix(core): use correct name for edit route param

packages/netlify-cms-core/src/actions/search.js, packages/netlify-cms-widget-relation/src/RelationControl.js
**Summary**
currently, the `queryFailure` action creator produces a `QUERY_SUCCESSS` action, which seems wrong??
(can't find where the error case is handled though)
**Test plan**
None
=> fix: dispatch QUERY_FAILURE on query failure

packages/netlify-cms-core/src/actions/__tests__/media.js, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/actions/media.ts, packages/netlify-cms-core/src/actions/mediaLibrary.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js, packages/netlify-cms-core/src/lib/formatters.ts, packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js, packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js, packages/netlify-cms-core/src/reducers/__tests__/mediaLibrary.spec.js, packages/netlify-cms-core/src/reducers/collections.ts, packages/netlify-cms-core/src/reducers/entries.ts, packages/netlify-cms-core/src/reducers/mediaLibrary.ts, packages/netlify-cms-core/src/types/redux.ts, packages/netlify-cms-core/src/valueObjects/AssetProxy.ts, packages/netlify-cms-core/src/valueObjects/Entry.ts, packages/netlify-cms-editor-component-image/src/index.js, packages/netlify-cms-lib-util/src/implementation.ts, packages/netlify-cms-widget-file/src/FilePreview.js, packages/netlify-cms-widget-file/src/withFileControl.js, packages/netlify-cms-widget-image/src/ImagePreview.js
Fixes https://github.com/netlify/netlify-cms/issues/3235
Fixes https://github.com/netlify/netlify-cms/issues/3241
=> Fix: show specific field media files in library, cascade folder templates

packages/netlify-cms-core/src/mediaLibrary.ts, packages/netlify-cms-core/src/reducers/config.ts, packages/netlify-cms-core/src/types/redux.ts
Fixes https://github.com/netlify/netlify-cms/issues/3248
At the moment the CMS will fail silently and revert to internal media library.
=> fix: report config error when external media lib is missing

packages/netlify-cms-widget-datetime/src/DateTimeControl.js
Fixes https://github.com/netlify/netlify-cms/issues/1745
instead of checking empty value, explicitly check default from config. Checks on change for deciding entity with empty value, but also checks on render in case of new empty parent object.
**Summary**
**Test plan**
=> fix(widget-datetime): use default value when value is undefined

packages/netlify-cms-widget-markdown/src/serializers/__tests__/__fixtures__/issue_3280.md, packages/netlify-cms-widget-markdown/src/serializers/__tests__/index.spec.js, packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js
Fixes https://github.com/netlify/netlify-cms/issues/3280
The `italic` mark was added twice for the `this` text node thus preventing it from being merged here https://github.com/netlify/netlify-cms/blob/73f679480bb24ca3fbbd64b98f86a8bce99c3b25/packages/netlify-cms-widget-markdown/src/serializers/remarkSlate.js#L68
=> fix(widget-markdown): don't add duplicate marks

website/src/cms/cms.js, website/src/components/edit-link.js, website/src/components/layout.js, website/src/components/markdown.js, website/src/templates/doc-page.js
Added `rel="noopener noreferrer"` to the edit link to fix lint error when running `yarn test` from the root directory.
Also formatted the files.
We should probably enforce it during the website build, but I'll handle it in another pr
=> fix: add 'rel' attirubte to edit link

packages/netlify-cms-core/src/constants/fieldInference.js
**Summary**
'hero' is used as the cover image field in the popular theme - https://github.com/narative/gatsby-theme-novela
**Test plan**
Tested locally using content grid view in the editor.
=> Add 'hero' as inferable image field

packages/netlify-cms-core/src/actions/__tests__/mediaLibrary.spec.js, packages/netlify-cms-core/src/actions/mediaLibrary.ts, website/content/docs/configuration-options.md
Currently, users are allowed to upload images whose filename contains accents, spaces or special characters. This may cause several problems downstream (https://github.com/netlify/netlify-cms/issues/857). 
It seems that at some point, the work done in #1135 should have fixed that issue (see https://github.com/netlify/netlify-cms/issues/857#issuecomment-369054206) but I can't find any trace of that behaviour in the current codebase.
This PR adds/restores that feature by applying the policy defined in the global `slug` setting to media inserted via the default media library.
=> feat: sanitize media filenames according to global slug setting

website/content/docs/authentication-backends.md
**Summary**
Adding a link to a new Google Cloud Function with Python  External OAuth Client to the Documentation
I created a new External OAuth Client running on Google Cloud Functions with Python for use in a lightweight open-source, community-driven project and would like to add it to the list in the Netlify CMS Documentation. Another user found it useful, so figured others may as well!
**Test plan**
Updated Website markdown only. Confirmed via running local website only.
=> Docs: Added Google Cloud Function to External OAuth Clients List

renovate.json
The website was initially excluded from Renovate updates because it was way behind on major releases, this was fixed in #2068.
=> chore: enable renovate for website

packages/netlify-cms-core/src/actions/__tests__/entries.spec.js, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/Editor/__tests__/Editor.spec.js, packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js, packages/netlify-cms-core/src/reducers/collections.ts, packages/netlify-cms-core/src/types/redux.ts, website/content/docs/beta-features.md
Fixes #3322
Didn't want to leave it to the widgets to verify that the URL params values are safe to use, so added html escaping.
=> feat: populate new entry from URL params

packages/netlify-cms-proxy-server/src/index.ts, packages/netlify-cms-proxy-server/src/middlewares.ts, packages/netlify-cms-proxy-server/src/middlewares/common/index.ts, packages/netlify-cms-proxy-server/webpack.config.js
Fixes #3348
Usage in Gatsby:
```
const { registerLocalFs } = require('netlify-cms-proxy-server/dist/middlewares');
exports.onCreateDevServer = async ({ app }) => {
await registerLocalFs(app);
};
```
We should actually handle this in our SSGs plugins, but this is a first step towards that.
=> feat(proxy-server): export proxy middlewares

dev-test/config.yml, packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/ToolbarButton.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, website/content/docs/widgets/markdown.md
**Summary**
Resolves #1788.
- Allows specific editor components to be enabled per markdown widget via `editorComponents` field property, with an empty list removing the dropdown and button completely. Important when you want markdown content to have no block level entities.
- Allows minimal height markdown widget via `minimal` field property. When authoring a small amount of markdown, often with inline content only, the 300px minimal height is overkill. This becames a bigger problem with a list of markdown widgets.
=> Configure included editor components per field, add optional minimal height

website/content/docs/beta-features.md
Related to https://github.com/netlify/netlify-cms/issues/2307
=> docs: rephrase previews support for variable types

packages/netlify-cms-core/src/lib/__tests__/registry.spec.js, packages/netlify-cms-core/src/lib/registry.js
Fixes https://github.com/netlify/netlify-cms/issues/3283
Handles most of the expected behaviour in that issue.
We could also validate widget names during configuration load, but that might request some thought as widgets can be registered dynamically after the config was loaded (odd case to support).
Furthermore, we could extend that validation to any required dynamically registered resource (e.g. backends, locales, media library).
=> fix: show better error for missing widgets

packages/netlify-cms-core/src/actions/__tests__/media.spec.js, packages/netlify-cms-core/src/actions/media.ts, packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
Fixes https://github.com/netlify/netlify-cms/issues/3330
`getAsset` was re-triggered again an again on error in the grid view.
=> fix: cache assets using resolved path on error

packages/netlify-cms-backend-git-gateway/src/implementation.ts, packages/netlify-cms-backend-github/src/__tests__/implementation.spec.js, packages/netlify-cms-backend-github/src/implementation.tsx, packages/netlify-cms-lib-util/src/Cursor.ts
Fixes: https://github.com/netlify/netlify-cms/issues/50
Related: https://github.com/netlify/netlify-cms/issues/68
Paginate the results returning from GitHub tree API.
P.S. tested with https://github.com/erezrokah/netlify-cms-reproductions/tree/netlify_cms/pagination
=> Feat: add GitHub folder collections pagination

packages/netlify-cms-core/index.d.ts
`registerWidget` can be called with a single argument `CmsWidgetParam`
=> Fix signature for CMS.registerWidget

packages/netlify-cms-app/package.json, packages/netlify-cms/package.json
**Summary**
We need to manually force minor/major bumps on the primary packages when a release will feel like a minor or major release to users - there's isn't a great way to determine programatically when this is the case. The simplest way is to add an arbitrary code change to these packages in commits that should trigger a bump for them. For example, a `feat:` prefixed commit will produce a minor bump for all packages that are changed in that commit.
This PR facilitates this temporarily by adding an `incrementToForceBump` key in the `package.json` files of the `netlify-cms` and `netlify-cms-app` packages, each set to `0` initially. The number can be incremented to provide a somewhat self documenting way of including these packages in Lerna's semantic versioning calculations.
=> chore: add hack to manually bump main packages

packages/netlify-cms-backend-github/src/API.ts
Empty commits could have been created before https://github.com/netlify/netlify-cms/pull/3306 was merged and published.
This fixes rebasing of entries created with empty commits.
=> fix(backend-github): don't create new commits on empty diff when rebasing

packages/netlify-cms-locales/src/ca/index.js, packages/netlify-cms-locales/src/cat/index.js, packages/netlify-cms-locales/src/index.js
**Motivation and summary**
I dived into your amazing CMS lately and I found out that it currently doesn't offer Catalan, my native language. 
This PR fixes the issue by adding a Catalan translation for the netlify-cms-locales package. 
I know that it's a minor contribution but I'd love to contribute to this amazing project and make it reach even more people.
I hope to keep adding features as soon as my schedule allows me.
**Test plan**
As mentioned in my  previous PR #3409, I won't add any coverage tests. However, I made sure that the current tests work appropriately, as shown in the following screenshot:
> **A picture of a cute animal (not mandatory but encouraged)**
Cute pic requirement complied with.
=> feat(catalan-translation): catalan translation added

packages/netlify-cms-core/src/actions/__tests__/editorialWorkflow.spec.js, packages/netlify-cms-core/src/actions/editorialWorkflow.ts, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/Editor/__tests__/Editor.spec.js, packages/netlify-cms-core/src/reducers/entryDraft.js
Related to https://github.com/netlify/netlify-cms/pull/3411.
When an unpublished entry save failed the editor reverted to the previous state losing all unsaved changes.
Tried to ditch `redux-optimistic` completely since it was used during persisting editorial workflow entries and reverted redux state on failure, but that didn't work since the editor was calling `createDraftFromEntry` on almost every re-render which would reset the editor content and lose unsaved data.
Only other solution I found was to store persist errors in redux and check it here:
https://github.com/netlify/netlify-cms/blob/8b0248bdc3f55dca451121d089b3274c8e72c09d/packages/netlify-cms-core/src/components/Editor/Editor.js#L203
e.g having:
```js
entry && !entry.get('isFetching') && !entry.get('error') && …
```
=> fix: call createDraftFromEntry after entry is loaded instead in Editor

website/content/docs/collection-types.md
Adds `create: true` to the example provided for **Filtered folder collections** given that you can create a folder collection without it.
=> Update Docs: Quick Start “collection-types”

website/netlify.toml, website/src/components/widgets.js, website/src/templates/doc-page.js
Fixes two issues with the widgets docs:
1. Linking to a specific widget (e.g. https://www.netlifycms.org/docs/widgets/#datetime) doesn't scroll to the widget.
2. Clicking multiple widgets (e.g. Boolean, String, then Date) and clicking the back button in the browser only changes the browser hash, but doesn't actually navigates back to the widget.
=> docs: scroll to widget on load, fix widget navigation history

packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
Hi folks, I'm so glad to see many updates to this project in the last few months. Thanks for the hardwork!
**Summary**
In the latest version, the method `loadEntry` that was passed down to widgets no longer work (I've been relying on this API for a few custom widgets in production). I digged around the repo to see what changed & send this PR just to facilitate communication.
This is how it worked before:
```js
async componentDidMount() {
const { loadEntry } = this.props
const results = await loadEntry(collectionName, slug)
// results.payload.data. etc etc</p>
}
```
I found 3 issues:
- In EditorControl, it seems that `loadEntry` wasn't properly dispatched here, resulting in failed call
https://github.com/netlify/netlify-cms/blob/ab7ba435baf07862e7adbfaf0f6cd9950af7ad52/packages/netlify-cms- …
=> fix(core): dispatch loadEntry, pass entities to widget

packages/netlify-cms-app/src/index.js
Fixes https://github.com/netlify/netlify-cms/issues/2578
Still undocumented as this is more of a workaround.
Allows changing the date widget locale without the overhead of bundling all moment locales with the CMS.
Usage with `netlify-cms`:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Netlify CMS Development Test</title>
</head>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
<script>
const data = moment.localeData('ja');
let locale = {};
Object.keys(data).forEach(key => {
const value = data[key];
if (key.startsWith('_')) {
key = key.substring(1);
}
locale[key] = value;
});
CMS.moment.locale('ja', locale);
</script> …
```
=> feat: expose CMS moment

packages/netlify-cms-core/src/__tests__/backend.spec.js, packages/netlify-cms-core/src/actions/__tests__/editorialWorkflow.spec.js, packages/netlify-cms-core/src/actions/__tests__/entries.spec.js, packages/netlify-cms-core/src/actions/editorialWorkflow.ts, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/actions/mediaLibrary.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/formats/formats.js, packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js, packages/netlify-cms-core/src/reducers/entries.ts
Fixes the following scenario:
1. Create an entry in editorial workflow and save it.
2. Manually add an image that is not mapped to any media folder (either collection/file/field media folder) to the CMS PR branch.
3. Update the editorial workflow entry and save it.
See that the previously added image is replaced with an empty svg file.
Underlying issue:
When persisting an entry `getMediaAssets` was used to retrieve entry assets. `getMediaAssets` calls `getAsset` which tries to get the asset from the redux store or initiates a load asset action.
When persisting an entry all of those entries assets should already be loaded into the store, but since the specific image is not mapped to any media folder, an empty asset is returned.
The solution was to dump `getAsset` and create the asset …
=> fix: don't use getAsset for draft entries

website/content/docs/beta-features.md
**Summary**
Make clear that path is an additional argument and file is placed under `<folder>/<path>`.
**Test plan**
Just minor docu change.
=> Minor: clarify absolut path with additional path argument

.github/workflows/nodejs.yml, .github/workflows/publish.yml, CONTRIBUTING.md, scripts/webpack.js
Fixes https://github.com/netlify/netlify-cms/issues/3444
Also, added build jobs for Mac OS and Windows and removed building on Node 10 (updated the contributing guide).
I think we can use Node LTS as a convention.
@erquhart Do you see any reason to build on non LTS versions?
=> build: fix windows build, build on multiple os using node 12 only

packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/netlify-cms-widget-file/src/withFileControl.js
Fixes https://github.com/netlify/netlify-cms/issues/3436
When using collection/field level media folders the value that is validated includes the media folder.
Couldn't think of a better way to do it at the moment.
This moves us towards widgets controlling their own validation logic (I think this might be good as well as widgets controlling their defaults).
@erquhart thoughts?
=> fix: allow widgets to control value to be validated

website/content/docs/external-oauth-clients.md
**Summary**
Adding in [bericp1/netlify-cms-oauth-provider-node](https://github.com/bericp1/netlify-cms-oauth-provider-node) to the "External OAuth Clients" documentation.
Built out primarily to support serverless platforms, specifically Zeit now but also supports generic handlers for any Node HTTP server or Node serverless environment.
**Test plan**
No tests need. Only documentation updates.
**Note**
I tried to edit these docs from the admin panel via the "Edit this page" link but for some reason the Backends section of the documentation wasn't showing up 🤷‍♂
=> Add `netlify-cms-oauth-provider-node` external OAuth client

packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js, packages/netlify-cms-core/src/components/App/Header.js, packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js, packages/netlify-cms-core/src/components/Collection/Sidebar.js, packages/netlify-cms-core/src/components/Editor/EditorInterface.js, packages/netlify-cms-core/src/components/Editor/EditorToolbar.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryActions.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrarySearch.js, packages/netlify-cms-core/src/components/UI/Modal.js, packages/netlify-cms-core/src/components/UI/Toast.js, packages/netlify-cms-ui-default/src/Dropdown.js, packages/netlify-cms-ui-default/src/Loader.js, packages/netlify-cms-ui-default/src/index.js, packages/netlify-cms-ui-default/src/styles.js, packages/netlify-cms-widget-code/src/SettingsButton.js, packages/netlify-cms-widget-code/src/SettingsPane.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/components/VoidBlock.js, packages/netlify-cms-widget-markdown/src/styles.js, website/src/components/chat-button.js
**Summary**
> Our z-index rules are mostly set with raw values, and we're starting to see collisions between them - especially extensions like widgets. This issue requires all z-index rules across the repo to be driven by a set of variables to ensure against unexpected visibility issues for non-static positioned elements.
This PR is intended to fix the above-mentioned issue.
**Test plan**
There are some test failures currently, so I'm marking this PR as Draft, so as to get some feedback as to what might be going wrong here. 
Closes #2989 
---
@erquhart Sorry, this took a while! So, I created an object `zIndex` in `ui-default/src/styles.js`, as we had discussed in Slack earlier, and defined values according to what is currently being used across netlify-cms. However, I came across a few …
=> refactor(ui): use variables for z-index values

packages/netlify-cms-backend-github/src/API.ts
Related to https://github.com/netlify/netlify-cms/issues/3506
Added logs to get more information for the error in the issue.
Also, when using open authoring and a single branch failed to load it broke the workflow view.
Added a fix for that and increased the timeout for cross repositories diff.
=> fix(open-authoring): prevent workflow view from breaking on entry error

packages/netlify-cms-backend-github/src/API.ts
Fixes https://github.com/netlify/netlify-cms/issues/3506
Underlying issue - open authoring branches were only deleted if they were merged using "squash and merge" and not deleted when using "create merge commit".
The fix was to call `getBranchPullRequest` directly instead of using `retrieveMetadata` since it uses the diff API which returned an empty diff for merge commits.
=> fix(open-authoring): properly delete open authoring branches

packages/netlify-cms-core/src/actions/__tests__/config.spec.js, packages/netlify-cms-core/src/actions/config.js
Since `currentBackend` memoize the backend using it when applying config defaults will memoize the backend with a config without defaults applied
=> fix: use resolveBackend instead of currentBackend

packages/netlify-cms-core/src/lib/__tests__/registry.spec.js, packages/netlify-cms-core/src/lib/registry.js
Fixes: https://github.com/netlify/netlify-cms/issues/3535 and https://github.com/netlify/netlify-cms/issues/3540
To reproduce - create a config with a list widget containing a hidden widget.
Reverts https://github.com/netlify/netlify-cms/pull/3377.
Re-checked and couldn't reproduce the original issue https://github.com/netlify/netlify-cms/issues/3283
Now the CMS loads the "unknown widget properly":
=> fix: missing widgets

packages/netlify-cms-core/src/actions/config.js
Prints error location on parse failure
=> fix: pass prettyErrors to yaml when parsing config

packages/netlify-cms-ui-default/src/Dropdown.js
fixes #3503 
**Summary**
Seems that z-index:299 is high enough to bring dropdown items in front of other widgets. 
Probably the easiest way to achieve expected behaviour would be change z-index in DropdownList
=> fix: DropdownList z-index increased

packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js, packages/netlify-cms-core/src/components/Workflow/WorkflowList.js, packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js, packages/netlify-cms-core/src/reducers/collections.ts
**Summary**
Fix #3573 
This also fixes the currently broken label for file type collections mentioned in #3573.
**Test plan**
Added unit tests for the new helper.
As can be seen below the title for a file type entry works correctly now and the folder collection uses the summary field.
=> fix: unify the title used in entry cards and workflow cards (#3573)

packages/netlify-cms-core/index.d.ts
**Summary**
The error: JSX.Element' is not assignable to parameter of type 'ComponentType<{}>' was coming up due to missing generic
**Test plan**
`yarn test` passed 66 of 68 total tests and skipped 2 as configured with a few warnings unrelated to this commit.
=> fix: removed error regarding warnings due to missing generic type closes #3572

packages/netlify-cms-core/index.d.ts
**Summary**
EditorComponentData doesn't accept string
But in [docs](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) it accept that.
=> fix EditorComponentData

packages/netlify-cms-core/src/components/App/App.js
Fixes https://github.com/netlify/netlify-cms/issues/3587
Replaces https://github.com/netlify/netlify-cms/pull/3595
Due to https://github.com/netlify/netlify-identity-widget/issues/86, in order to test locally change your local env url to `http://localhost:8080/#/error=access_denied&error_description=Signups+not+allowed+for+this+instance` to simulate an unsuccessful external login.
=> fix: redirect to default path after login success if url has previous error

dev-test/config.yml, packages/netlify-cms-widget-object/src/ObjectControl.js, website/content/docs/widgets/object.md
**Summary**
This adds the possibility for objects to be collapsed by default.
It was not possible to collapse an object by default before which sometimes added a lot of clutter for long object fields. This allows the user to better control the initial UI state.
The collapsed state defaults to false so this does not change the default behavior.
**Test plan**
The option has been added to the `object` in the kitchen sink dev test collection to verify that it's working.
=> feat(widget-object): add collapsed option to collapse object by default

packages/netlify-cms-locales/src/es/index.js
**Summary**
My native language is spanish, I started trying Netlify cms, found that I could change the default language to spanish using netlify-cms-locales but that some translations were missing so I decided to add it.
**Test plan**
Test output
```
npm run test
> @ test /home/cajotafer/Projects/netlify-cms
> run-s clean lint type-check test:unit
> @ clean /home/cajotafer/Projects/netlify-cms
> rimraf "packages/*/dist" dev-test/dist
> @ lint /home/cajotafer/Projects/netlify-cms
> run-p -c --aggregate-output "lint:*"
> @ lint:css /home/cajotafer/Projects/netlify-cms
> stylelint --ignore-path .gitignore "{packages/**/*.{css,js,jsx,ts,tsx},website/**/*.css}"
Build Package: netlify-cms
> @ lint:format /home/cajotafer/Projects/netlify-cms
> prettier …
```
=> fix(locale): add missing translation strings for 'es' locale

website/content/docs/widgets/datetime.md
**Summary**
The Date widget is [being deprecated](https://github.com/netlify/netlify-cms/issues/1688) in favor of the DateTime widget. Currently, the DateTime widget docs suggest using the Date widget for saving the date only. This PR removes that reference so that we don't encourage folks to use the deprecated Date widget.
**Test plan**
None. This is a docs-only change.
=> Remove reference to Date widget from DateTime widget docs

packages/netlify-cms-core/index.d.ts
**Summary**
Though the fix in https://github.com/netlify/netlify-cms/pull/3597 might made the warnings go away, it was not correct.
Also did not cover all other cases with `ComponentType`.
**Test plan**
N/A
=> fix: instead of the inferred {}, allow any kind of props

packages/netlify-cms-backend-git-gateway/src/implementation.ts
Context https://community.netlify.com/t/large-media-storage/12915/16?u=erez
The move from `netlify.com` to `netlify.app` trips the CMS's auto LFS detection.
=> fix(large-media): match netlify.app as lfs host

packages/netlify-cms-core/src/reducers/entries.ts
Fixes https://github.com/netlify/netlify-cms/issues/3647
The cleanup was done as an optimization to return to a lazy loaded list when the sort direction for a collection is `none`.
This is not required since we check for it here: https://github.com/netlify/netlify-cms/blob/f8603c5d920c5105fa6d267ac2eb9e1cbd119f7d/packages/netlify-cms-core/src/actions/entries.ts#L468
`selectEntriesSortFields` filters out `none` sort directions.
=> fix(sort): don't clear sort data on entries request

packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkEscapeMarkdownEntities.spec.js, packages/netlify-cms-widget-markdown/src/serializers/remarkEscapeMarkdownEntities.js
**Summary**
Prevent markdown footnotes (`[^1]: blah`) and footnote references (`[^1]`) from being incorrectly escaped when switching between Markdown and Rich Text modes. Netlify CMS doesn't do anything with either of these entities, so they should not be transformed in any way. At present, switching mode to Rich Text, and making any kind of edit, for example to add an image using the widget, then switching back, results in all footnotes or references being escaped (`/[^1]`) which means whatever parses the markdown no-longer treats them as markdown entities. Switching mode without editing does not exhibit this behaviour.
Fixes #2386 
**Test plan**
I've amended existing tests and added tests to be slightly more granular (testing explicitly for both footnotes and both footnote references). …
=> fix: prevent escaping of footnotes and references

packages/netlify-cms-core/src/components/Collection/Sidebar.js
**Summary**
Icon for sidebar nav items shrinks if label wraps. 
Closes #3652
**Test plan**
I tested the fix in-browser using dev-tools but I don't see anything in the contributing docs about how to run a demo version of the CMS locally to verify the fix. If you can let me know how that goes I will do that.
=> fix: sidebar icon shrinking when label wraps

packages/netlify-cms-core/index.d.ts
**Summary**
Related to #2926 for TS support, the current types do not permit the common options for backend configuration from the [docs](https://netlifycms.org/docs/backends-overview). I'm using a non-master branch and using typescript for configuration.
**Test plan**
Verified I can add repo/branch for my project without TS compiler errors. If there are more specific tests for these type definitions I'll gladly add them.
=> fix: support common backend configuration options from docs in ts types

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js
**Summary**
Pass down `entry`, `collection` and `config` properties to the control widget. 
This allows control widgets to inspect and act on whole entry data and collection or configuration values. 
A specific use case for this feature is the creation of a slug widget which updates according to some other fields.
**Test plan**
I don't think a test plan is needed since it's relative straight forward.
=> feat: add entry, collection and config prop to control widget

packages/netlify-cms-backend-git-gateway/src/AuthenticationPage.js, packages/netlify-cms-backend-git-gateway/src/implementation.ts
Fixes https://github.com/netlify/netlify-cms/issues/2260
Also related https://community.netlify.com/t/manual-initialisation-with-identitywidget-enabled/12194/6
Reproduces only in Gatsby prod build in the following repo: https://github.com/erezrokah/netlify-cms-2260-overlay-intial-load. The effect in that repo is that the login dialog opens immediately when opening the CMS and not only after clicking the login button.
When deployed the effect is a bit different of a overlay like the original bug:
https://amazing-swirles-f2a7bc.netlify.app/admin/
This underlying issue is a race condition where the CMS is trying to access the Identity widget before it was initialized.
The Identity widget can be imported from CDN as so:
```js
<script type="text/javascript" …
```
=> fix(git-gateway): wait for identity widget to initialize

dev-test/config.yml, packages/netlify-cms-widget-list/package.json, packages/netlify-cms-widget-list/src/ListControl.js, packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js, website/content/docs/beta-features.md, website/content/docs/widgets/list.md
Hi folks! This PR is a WIP, in collaboration with @djMax 
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/3713
In the list widget's control, when an item is collapsed, only its type name is displayed. This makes it difficult for editors to understand the content of a list at a glance. This issue is more pronounced when editing a large list with many items of the same type.
This PR explores adding a `summary` field to each list's type, allow each item to display a summary based on its content, in the same fashion as a folder collection.
```diff
- label: 'Typed List'
name: 'typed_list'
widget: 'list'
types:
- label: 'Type 1 Object'
name: 'type_1_object'
+       summary: 'Type 1 | {{string}}'
widget: 'object'
fields:
- { label: 'String', name: 'string', widget: 'string' }
- { …
```
=> feat(netlify-cms-widget-list): allow 'summary' field

packages/netlify-cms-widget-datetime/src/DateTimeControl.js, website/content/docs/widgets/datetime.md
I have a field that I would like to contain just a date (with no specific time). When I configure the `datetime` widget with sensible options for a date-only field, dates are stored properly in the saved markdown, but when I load those dates in the UI, I see the date before.
This is happening because the `DateTime` component from the [`react-datetime` library](https://github.com/YouCanBookMe/react-datetime) uses local timezones by default. It loads the date as the start of day UTC and then converts to the local timezone, which is going to be the previous day in any timezone with a negative UTC offset, including all of the Americas.
This change adds a `pickerUtc` option to the `datetime` widget so that users can specify when they would like the `datetime` picker to display times in UTC …
=> feat: add pickerUtc option to datetime widget

packages/netlify-cms-core/src/actions/__tests__/entries.spec.js, packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/types/redux.ts
Fixes https://github.com/netlify/netlify-cms/issues/3534
Replaces https://github.com/netlify/netlify-cms/pull/3675
=> fix: allow setting an empty array as default for complex lists

dev-test/config.yml, packages/netlify-cms-widget-list/src/ListControl.js, packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js, packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap, website/content/docs/widgets/list.md
**Summary**
This adds the option to completely hide list content when the list widget itself is collapsed. 
If the option `minimize_collapsed` is set to `true` all list items are hidden rather then only collapsed when the list collapse toggle is used. 
This is a direct response to https://github.com/netlify/netlify-cms/pull/3606#issuecomment-613952382. 
Instead of completely changing the behavior of the `collapsed` option as suggested in https://github.com/netlify/netlify-cms/pull/3606#issuecomment-613977784 I added the `minimize_collapsed` option such that the change is not breaking and a list with just `collapsed: true` will still expand it's items. 
I feel like there are valid use cases for having a list expand it's items when the collapsed state is toggled., e.g. object with single …
=> feat(widget-list): add hiding list content with minimize_collapsed option

cypress/integration/search_suggestion_spec.js, packages/netlify-cms-core/src/actions/__tests__/search.spec.js, packages/netlify-cms-core/src/actions/collections.js, packages/netlify-cms-core/src/actions/search.ts, packages/netlify-cms-core/src/components/App/App.js, packages/netlify-cms-core/src/components/Collection/Collection.js, packages/netlify-cms-core/src/components/Collection/CollectionSearch.js, packages/netlify-cms-core/src/components/Collection/Entries/EntriesSearch.js, packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js, packages/netlify-cms-core/src/components/Collection/Sidebar.js, packages/netlify-cms-core/src/reducers/index.ts, packages/netlify-cms-core/src/reducers/search.js, packages/netlify-cms-core/src/types/redux.ts, packages/netlify-cms-locales/src/de/index.js, packages/netlify-cms-locales/src/en/index.js
Closes #3756
**Summary**
This is a direct follow up of my feature request in #3756. 
It turned out it was quite easy to implement.
This PR adds a "suggestion" box (for lack of a better term) that suggests all collections that can be searched. The collections are listed under "Search in" together with an "All Collections" item. The selection in the suggestion box can be navigated with the arrow up and down keys. The currently selected option in the suggestion box is used when the search is submitted or an option is clicked by the user. It's basically how GitHubs search bar works.
The box opens up when the search field is focused for the first time and starts with the current collection selected by default. This changes the default search behavior since now we only search in the current …
=> feat: improve search to target single collections

.github/workflows/labeler.yml
See https://github.com/netlify/netlify-cms/runs/690718297?check_suite_focus=true#step:4:1
The PR labeler fails on forked PRs (makes sense due to permissions issues)
=> chore: disable labeler on forked PRs

packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js, packages/netlify-cms-core/src/lib/formatters.ts, website/content/docs/beta-features.md
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/3793
author-name and author-login are already passed to the template, so we might as well expose them to the commit messages even if openAuthoring is false.
**Test plan**
Existing tests pass.
=> feat: allow author login/name to work in commit message templates #3793

packages/netlify-cms-locales/src/nl/index.js
I updated the dutch locale.
**Test plan**
I used the english locale for comparison and made all necessary additions (and a removal). I ran `yarn:format` and tested the CMS locally.
=> fix(locale): update translation strings for 'nl' locale

packages/netlify-cms-backend-test/src/implementation.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/lib/__tests__/registry.spec.js, packages/netlify-cms-core/src/lib/registry.js, packages/netlify-cms-core/src/types/immutable.ts, packages/netlify-cms-lib-util/src/implementation.ts, website/content/docs/beta-features.md
In continuance to resolving #1348.   Add `prePush`  hook to the list of hooks, which should allow modifying entry data.
Fixes #1348
=> feat: add pre save/ post save hooks

packages/netlify-cms-core/index.d.ts
**Summary**
I've run into some Typescript errors while using the Manual Initialization in a separate `.js` files, for example missing property definitions on the `CmsCollection` type. I've added the ones I used and the ones I have found described in the docs.
**Test plan**
Ran `yarn type-check` and `yarn test` without any errors.
=> fix: add missing type definitions

packages/netlify-cms-core/index.d.ts
**Summary**
A project with `netlify-cms-core@2.28.0` as a dependency fails to compile due to the `List` import being missing.
This PR adds the missing dependency.
**Test plan**
Should have been caught by `type-check`, but seems to have been missed because of the `"skipLibCheck": true` option. However, enabling this brings about some other errors.
=> fix: missing List import to netlify-cms-core index.d.ts

packages/netlify-cms-backend-bitbucket/src/AuthenticationPage.js, packages/netlify-cms-backend-bitbucket/src/implementation.ts, packages/netlify-cms-backend-git-gateway/src/implementation.ts, packages/netlify-cms-backend-github/src/API.ts, packages/netlify-cms-backend-github/src/implementation.tsx, packages/netlify-cms-backend-gitlab/src/implementation.ts, packages/netlify-cms-backend-proxy/src/implementation.ts, packages/netlify-cms-backend-test/src/implementation.ts, packages/netlify-cms-core/src/actions/auth.js, packages/netlify-cms-core/src/actions/status.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/components/App/Header.js, packages/netlify-cms-core/src/reducers/globalUI.js, packages/netlify-cms-core/src/reducers/index.ts, packages/netlify-cms-core/src/reducers/status.ts, packages/netlify-cms-core/src/types/redux.ts, packages/netlify-cms-lib-util/src/AccessTokenError.ts, packages/netlify-cms-lib-util/src/implementation.ts, packages/netlify-cms-lib-util/src/index.ts, packages/netlify-cms-locales/src/en/index.js
Fixes https://github.com/netlify/netlify-cms/issues/3779 (shows a relevant message as we can't refresh a Bitbucket implicit token: https://developer.atlassian.com/cloud/bitbucket/oauth-2/#refresh-tokens)
Fixes https://github.com/netlify/netlify-cms/issues/941
Related https://github.com/netlify/gotrue-js/pull/83
Token expiry can happen in the following cases:
- **Web Application Flow** - Revoking OAuth app from the relevant GitHub/GitLab/Bitbucket interface. Relevant config is:
```yaml
backend:
name: github/gitlab/bitbucket
```
- **GoTrue/Netlify Identity** - token expires every hour, but auto refreshed by identity widget/gotrue-js. That can fails when the refresh token is no longer valid. That can happen when a user logs in via a different browser window and then goes back to the original …
=> Fix: handle token expiry

packages/netlify-cms-backend-bitbucket/src/API.ts, packages/netlify-cms-backend-github/src/API.ts, packages/netlify-cms-backend-github/src/GraphQLAPI.ts, packages/netlify-cms-backend-gitlab/src/API.ts, packages/netlify-cms-lib-util/src/API.ts, packages/netlify-cms-lib-util/src/index.ts
Related to:
https://github.com/netlify/netlify-cms/issues/1693
https://github.com/netlify/netlify-cms/issues/2827
Handles errors originating from branch conflicts (existing `cms` branches).
=> Fix: handle branch names conflicts

packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js
**Summary**
The `CardsGrid` component currently relies on builtin browser CSS for top and bottom margins on `<ul>`. This can be a problem when the page includes a global css reset, so better be explicit. see:
**Test plan**
none
=> fix: don't rely on browser builtin css for CardsGrid margins

packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
**Summary**
on Firefox, the "Headings" dropdown in the richtext editor toolbar does not display with correct width (it's fine on chrome).
see e.g. https://cms-demo.netlify.com/#/collections/posts/entries/2020-6-16-post-number-20
firefox:
chrome:
=> fix: fix headings dropdown width

packages/netlify-cms-backend-bitbucket/src/implementation.ts, packages/netlify-cms-backend-git-gateway/src/implementation.ts, packages/netlify-cms-backend-github/src/implementation.tsx, packages/netlify-cms-backend-gitlab/src/implementation.ts, packages/netlify-cms-backend-proxy/src/implementation.ts, packages/netlify-cms-backend-test/src/implementation.ts, packages/netlify-cms-core/src/actions/status.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/reducers/status.ts, packages/netlify-cms-lib-util/src/implementation.ts, packages/netlify-cms-lib-util/src/unsentRequest.js, packages/netlify-cms-locales/src/en/index.js
**Summary**
Closes https://github.com/netlify/netlify-cms/issues/3334
Note: i18n needed for new key `ui.toast.onBackendDown`
**Test plan**
Tested on development environment:
Ran `yarn lint`
=> feat: add backend status down indicator

.github/workflows/labeler.yml
This reverts commit cd79ea70243bd175489d7fb92ed50d3b620e969a (https://github.com/netlify/netlify-cms/pull/3902)
Secrets are not passed to builds from forks, so we can't use this approach.
We need to use a Netlify Function
=> Revert "chore: fix PR labeler for forked PRs"

packages/netlify-cms-core/src/__tests__/backend.spec.js, packages/netlify-cms-core/src/backend.ts
Make sure calls to `persistLocalDraftBackup` and `deleteLocalDraftBackup` are executed in-order 
Fixes an issue with the backup pop showing up in the following scenario:
1. Open https://cms-demo.netlify.com/#/collections/posts/new
2. Quickly exit the editor.
3. Click on `New post`
4. See that the backup pop up is shown.
=> fix(backup): synchronize calls to localForage

packages/netlify-cms-ui-default/src/AppBar/AppBar.jsx, packages/netlify-cms-ui-default/src/SearchBar/SearchBar.jsx, packages/netlify-cms-ui-default/src/SearchBar/index.js, packages/netlify-cms-ui-default/src/SearchBar/story.jsx
**Summary**
Commit 1:
Removes the `LogoTile` from the `AppBar`
Commit 2:
Adds a `SearchBar` component with an optional `renderEnd` parameter.
The design was inherited from existing `CollectionSearch` component and extended.
**Test plan**
Snapshot of the newly added component with `renderEnd` enabled
**Note**
Some changes on the `AppBar` component are pending and will be done soon.
=> header ui update closes #3263

packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Fixes https://github.com/netlify/netlify-cms/issues/3951
Using `history. goBack` was introduced in #3716 in order to preserve the URL state (and collection filter state) when exiting the editor.
The current `history.length` doesn't work when the CMS is opened from another page using a link with `target="_blank"`.
Also see https://stackoverflow.com/questions/3588315/how-to-check-if-the-user-can-go-back-in-browser-history-or-not#answer-36645802
=> fix(editor): proper length check for history when going back in editor

packages/netlify-cms-core/src/constants/__tests__/configSchema.spec.js, packages/netlify-cms-core/src/constants/configSchema.js
Fixes https://github.com/netlify/netlify-cms/issues/3967
While not officially documented it makes sense to allow setting a regular expression via JavaScript.
=> fix(config-schema): allow field pattern to be a regex

packages/netlify-cms-core/src/__tests__/backend.spec.js, packages/netlify-cms-core/src/actions/search.ts, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-lib-widgets/package.json, packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js, packages/netlify-cms-lib-widgets/src/stringTemplate.ts, packages/netlify-cms-widget-relation/package.json, packages/netlify-cms-widget-relation/src/RelationControl.js, packages/netlify-cms-widget-relation/src/__tests__/relation.spec.js
Fixes https://github.com/netlify/netlify-cms/issues/3810
Fixes https://github.com/netlify/netlify-cms/issues/3908
1. Fixes the search for file collections by using `expandPath` inside `backend.ts` (moved to a shared lib).
2. Virtualises the select dropdown.
3. Passes options length as a limit to `backend.ts` to avoid saving all results in the redux store.
=> Fix: relation widget performance

cypress/plugins/proxy.js, packages/netlify-cms-proxy-server/.env.example, packages/netlify-cms-proxy-server/package.json, packages/netlify-cms-proxy-server/src/index.ts, packages/netlify-cms-proxy-server/src/logger.ts, packages/netlify-cms-proxy-server/src/middlewares.ts, packages/netlify-cms-proxy-server/src/middlewares/common/index.ts, packages/netlify-cms-proxy-server/src/middlewares/localFs/index.ts, packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts, yarn.lock
Fixes https://github.com/netlify/netlify-cms/issues/3979
@erquhart this should allow setting log level both when running as a cli using `npx` and when registering the middlewares programatically. 
Most of the changes are just passing the `logger` instance down to where it is used.
=> feat(proxy-server): allow setting proxy log level

website/content/docs/add-to-your-site.md, website/content/docs/backends-overview.md, website/content/docs/beta-features.md, website/content/docs/bitbucket-backend.md, website/content/docs/collection-types.md, website/content/docs/configuration-options.md, website/content/docs/custom-widgets.md, website/content/docs/deploy-preview-links.md, website/content/docs/examples.md, website/content/docs/external-oauth-clients.md, website/content/docs/git-gateway-backend.md, website/content/docs/github-backend.md, website/content/docs/gitlab-backend.md, website/content/docs/intro.md, website/content/docs/open-authoring.md, website/content/docs/releases.md, website/content/docs/start-with-a-template.md, website/content/docs/test-backend.md, website/content/docs/update-the-cms-version.md, website/content/docs/widgets.md, website/site.yml, website/static/_redirects
Starting in on https://github.com/netlify/netlify-cms/issues/3764
> A proposal for reorganizing the navigation on the NetlifyCMS docs site. The goal is to make it easier for users to find the guidance they need.
=> feat: reorganizing the NetlifyCMS Docs navigation

packages/netlify-cms-proxy-server/src/middlewares/common/index.ts
Current default is too verbose.
This is configurable via `LOG_LEVEL` env variable.
=> fix(proxy-server): change request logging level to debug

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/netlify-cms-widget-list/src/ListControl.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js, packages/netlify-cms-widget-object/src/ObjectControl.js, yarn.lock
A recent update to `react-redux` added some prop types warnings.
See https://github.com/reduxjs/react-redux/releases/tag/v7.0.1
Specifically the comment:
> Note: connect now uses React.memo() internally, which returns a special object rather than a function. Any code that assumed React components are only functions is wrong, and has been wrong since the release of React 16.6. If you were using PropTypes to check for valid component types, you should change from PropTypes.func to PropTypes.elementType instead.
I updated the relevant locations for a correct prop types check and also updated `react-router-dom` since it had the same prop type check which was resolved only in v5 (or a v4 beta https://github.com/ReactTraining/react-router/issues/6471).
react router v5 is actually a minor …
=> fix(prop-types): check for react components via PropTypes.elementType

cypress/plugins/index.js
Removed flags are now added by cypress by default.
`--disable-dev-shm-usage` adds better compatibility for running inside a docker container.
=> test(e2e): update chrome flags

.github/workflows/publish.yml
We should pass a `GITHUB_TOKEN` to the 2fa publish action
=> chore: fix publish action

packages/netlify-cms-backend-gitlab/src/API.ts
Fixes https://github.com/netlify/netlify-cms/issues/4059
=> fix(backend-gitlab): use move commit action only if paths are different

.github/workflows/publish.yml
1. Use major version notation for referencing the action.
2. Switch to `CHANNEL_ID` env
=> ci(publish): switch to v1 of 2fa publish action

website/content/docs/nuxt.md
**Summary**
Nuxt 2.14 deprecates the `nuxt build && nuxt export` in favor of `nuxt generate` as you can read [here](https://nuxtjs.org/blog/nuxt-static-improvements#using-in-your-projects).
**Additional thoughts**:
In the docs, you are talking about the npm script, that probably does not match with the nuxt script. Should this be explained in order to avoid issues with persons that do not use to deal with npm scripts?
=> docs: replace outdated command

packages/netlify-cms-core/src/actions/entries.ts, packages/netlify-cms-core/src/components/Collection/Collection.js, packages/netlify-cms-core/src/components/Collection/__tests__/__snapshots__/Collection.spec.js.snap, packages/netlify-cms-core/src/reducers/entries.ts, packages/netlify-cms-core/src/types/redux.ts
**Summary**
fixes #3876 
Currently view style preference is not persisting in local storage.
This fixes save, maintain, and retrieve view style in local storage under `netlify-cms.entries.viewStyle` key
**Test plan**
The following image shows the saved view style in local storage
=> fix: persistent view style

packages/netlify-cms-locales/src/pt/index.js
Signed-off-by: Daniel Soares <daniel.soares@me.com>
**Summary**
I am updating the translation to Portuguese.
**Test plan**
`yarn test`
A coati at Iguassu Falls (Brazil)
=> fix(locale): add missing translation strings for pt locale

packages/netlify-cms-backend-proxy/src/implementation.ts
**Summary**
When using `local_backend: true` and `npx netlify-cms-proxy-server`, SVG images are broken in the media browser and entrycard interfaces. Most of the other backends have SVG detection and add a filetype to the `File` blob. This brings that fix to the proxy backend. 
There may be a bigger refactor here that would reduce duplication of code across backends, but I'm not the one to take that on.
The broken images were driving me nuts.
Before:
After:
**Test plan**
This is a two line code change that adds an option to the `new File`. I did not add a unit test, but I did build the change and confirm the fix works.
=> Fix SVGs when using local_backend

packages/netlify-cms-lib-util/src/API.ts
**Summary**
Fixes #4183. If a bitbucket auth token expires when using implicit auth, when the user tries to log in again they need to wait for repeated failing attempts to refresh the token. This PR check for the error message in the requestWithBackoff and throws an error instead of continuing to make new requests.
**Test plan**
All existing tests pass. Need help to properly test this locally, is there a way to mock in a bitbucket backend and try out the login page?
=> fix(api): bitbucket implicit auth login delay

packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js, packages/netlify-cms-widget-markdown/src/schema.js, website/content/docs/widgets/markdown.md
**Summary**
This PR adds the new option "onlyRawMode" to the markdown widget.
If it is set to true, the widget only allows editing real markdown with the raw editor. The visual editor cannot be used.
This is achieved by removing the toggle button and always showing the raw editor.
This feature should prevent users from pasting formatted text from editors that may lead to broken markdown.
**Test plan**
To be defined.
=> feat(widget-markdown): add option mode (#4112)

packages/netlify-cms-locales/src/index.js, packages/netlify-cms-locales/src/ko/index.js
**Summary**
This PR Adds Korean Locale to Netlify CMS
**Test plan**
In `config.yml`
- Use `test-repo` backend to test in localhost environment.
- Set `locale:` to `ko`
> Cat image source: https://pixabay.com/photos/cat-sweet-kitty-animals-feline-323262/
=> feat(locale): add 'ko' locale 🇰🇷

dev-test/config.yml, packages/netlify-cms-core/src/backend.ts, packages/netlify-cms-core/src/lib/__tests__/formatters.spec.js, packages/netlify-cms-core/src/lib/formatters.ts, packages/netlify-cms-lib-widgets/src/stringTemplate.ts, website/content/docs/beta-features.md, website/content/docs/configuration-options.md
Related to: #445
**Summary**
This PR allows the generated `meta.path` to be accessible in `summary` and `preview_path` when using nested collections.
eg:
```yaml
collections:
- name: 'pages'
create: true
label: 'Pages'
label_singular: 'Page'
folder: 'src/content/pages'
preview_path: '{{dirname}}'
media_folder: '/{{media_folder}}/pages/{{dirname}}'
summary: '{{title}} - {{dirname}}'
nested: { depth: 100 }
meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
fields:
- label: 'Title'
name: 'title'
widget: 'string'
- label: 'Image'
name: 'image'
widget: 'image'
- label: 'Body'
name: 'body'
widget: 'markdown'
```
**Docs Preview** 
https://deploy-preview-4279--netlify-cms-www.netlify.app/docs/configuration-options/#preview_path …
=> feat(core) feat(lib-widget) Add {{dirname}} to summary and preview_path

website/content/docs/jekyll.md
Fixes an issue in the docs where `title` is used as a name for the `Layout` field and the `Title` field.
=> Update Docs: Fix duplicate field name

packages/netlify-cms-core/src/components/Editor/EditorInterface.js, packages/netlify-cms-core/src/reducers/collections.ts
**Summary**
currently, the editor preview pane can only be configured on the collection level. for file-based collections it is not possible to set editor preview for individual files. this pr adds that.
closes #3581
=> fix: allow setting per-file editor preview

packages/netlify-cms-widget-object/src/ObjectControl.js, website/content/docs/widgets/object.md
**Summary**
fixes #4291 
- display summary in ObjectWidgetTopBar when object is collapsed
when an object is collapsed, display a summary like when the object is collapsed in a list widget
**Test plan**
tested manually
```yaml
fields:
- label: "an object"
name: "anobject"
widget: "object"
summary: '{{fields.heading}}-{{fields.content}}'
fields:
- {label: Heading, name: heading, widget: string, required: false}
- {label: Content, name: content, widget: markdown }
```
collapsed:
=> "summary" for object widget #4291

packages/netlify-cms/package.json
See https://github.com/webpack/webpack-dev-server/issues/2759
`yarn start` stopped working due to https://github.com/netlify/netlify-cms/pull/4451
=> chore: use webpack serve instead of webpack-dev-server

packages/netlify-cms-widget-list/src/ListControl.js
**Summary**
Fixes #3807 ("Removing all values from the list with empty array as default value results in array of one empty string")
As per issue #3807 , the Widget List would save an array with an empty string when attempting to delete all elements from the widget.
The source of the problem is that splitting an empty string in Javascript returns an array with an empty string - this is as the language is designed, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split
**Test plan**
I ran `yarn test` and `yarn format`.
=> Fixes #3807 by ensuring we don't attempt to split an empty string.

packages/netlify-cms-widget-list/src/ListControl.js, website/content/docs/widgets/list.md
Currently, when a user adds a new item to a list, that item is added to the bottom. If the user would prefer to have the new item added to the top of the list, they would need to click the "add" button, scroll to the bottom of the list, edit the new entry, and drag it all the way to the top of the list. For long lists, this can be tedious.
This change adds a new `add_to_top` option to the list widget. For a list that the user intends to maintain in a newest-first order, adding this option would prevent them from going through the tedious scrolling and dragging task for each new item.
closes https://github.com/netlify/netlify-cms/issues/3270
I tested the new option locally by updating the two list widgets in the Kitchen Sink collection in `dev-test/config.yml`.
=> feat: add add_to_top option to list widget

packages/netlify-cms-widget-select/src/SelectControl.js
Related to https://github.com/netlify/netlify-cms/issues/4489
The runtime validation is no longer required as we do schema validations for widgets
=> chore(widget-select): remove runtime validation for options

dev-test/config.yml, packages/netlify-cms-widget-select/src/schema.js
**Summary**
Fixes #4577 
Allows numbers to be used as the value type in select widgets
Added an example in the dev-test environment
**Test plan**
`yarn start`
Open the kitchen sink collection and open the first entry
Scroll down to the select widgets (end of chapter 1)
Obligatory cute koala:
=> fix(widget-select): allow number value type

packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/Workflow/WorkflowList.js
closes #4541 
**Summary**
Assume you are on the workflow page and want to edit the post. After you finish your edit process, you click the "backlink" button, you would like to go to the workflow page. But you directed to the home page.
This behavior is wrong. 
What did I do? 
I added a referrer param for the workflow page. 
If you were on the workflow page and wanted to edit the post, I added the param at the end of the URL. 
If you want to go back, I check the URL whether has a param. 
If the `ref` param exists, then I return the user to the workflow page.
**Test plan**
I have done manual tests
=> feat: added the referrer param for the workflow page

packages/netlify-cms-widget-string/src/StringControl.js
Closes #3578
Closes #4539
The approach taken here seems suboptimal since it's generally not necessary when writing React components to manually update cursor location. Please let me know if anyone has a better solution.
I did do some debugging to try to identify the root issue, but did not find the root cause.
The summary of what I found is this: It seems that nested widgets undergo additional rendering because they trigger a state update for their parent component as well as themself. For example, when editing the alt text of an image using the built-in image block element the updating markdown string causes the parent markdown widget to update. 
**Summary**
This PR fixes the cursor problem described in detail in the linked issues. To summarize: Nested inputs within any collection would …
=> fix(widget-string): fix cursor jumping to end of line

website/content/docs/customization.md
**Summary**
The document highlighting in the following URLs was broken, so I fixed it.
https://www.netlifycms.org/docs/customization/
- Before
- After
**Test plan**
Please Check changing md file.
=> Fix the code highlights in docs/customization

packages/netlify-cms-core/index.d.ts
**Summary**
This PR adds i18n support (plus the `squash_merges` backend beta feature) to the `netlify-cms-core` typings.
**Test plan**
Amendments to existing interfaces are all optional fields, so this should not be a breaking change for any users/consumers.
=> fix(typings): add i18n support to typings

packages/netlify-cms-core/index.d.ts
**Summary**
Hi! The TS typing for the [`local_backend`](https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository) scheme's field seems missing. The PR is intended to fill the gap.
The added types are based on the [docs](https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository) and the [schema](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/constants/configSchema.js#L137).
**Test plan**
I tested it locally in my project, works well. 👌 
=> fix: added a TS type definition for local_backend schema field

packages/netlify-cms-locales/src/da/index.js, packages/netlify-cms-locales/src/index.js
**Summary**
This adds Danish translation to the ``netlify-cms-locales`` package to allow localization
**Test plan**
I tested by adding locale to ``config.yml`` and running locally
```config.yml
locale: da
```
This is my first contribution here so please don't hesitate to point out necessary changes.
Thank you
=> feat(locales): add danish translation

website/content/docs/beta-features.md
**Summary**
This PR is a follow up to #4632. 
The existing documentation at https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository is confusing because it mixes instructions for _default_ configuration with instructions for _optional_ custom configuration. Also the custom configuration instructions are missing a critical step for defining the custom port number in a `.env` file
This change separates the custom configuration instructions into a separate section and adds a step that explains how to define the custom port number.
=> Update DOCS: Working with a Local Git Repository (take 2)

packages/netlify-cms-core/index.d.ts
**Summary**
This PR introduces makes the `widget` field for the `CmsField` type a discriminant. Not only does this allow for much better type inference when declaring fields, it also makes the typings for individual widgets much easier and less error-prone to maintain, since they're split out rather than pooled together under one mega-interface where all properties are optional.
**Test plan**
I've tested this with my own practical code and verified that it works correctly. It correctly supports fields that don't declare a widget type.
One thing to note is that it _doesn't_ support widgets registered with `CMS.registerWidget` -- but the current typings don't really support them either. (The current typings will tolerate any string value for the `widget` field, but not any configuration …
=> fix(typings): discriminated types for widgets

packages/netlify-cms-backend-git-gateway/src/GitHubAPI.ts, packages/netlify-cms-backend-git-gateway/src/implementation.ts, packages/netlify-cms-backend-git-gateway/src/netlify-lfs-client.ts, packages/netlify-cms-backend-github/src/API.ts
Replaces https://github.com/netlify/netlify-cms/pull/4613
We can't skip files (as suggested in that PR) as the CMS synchronizes client state with server state on save.
Filtering files means those file will be removed on save - the reason it's not happening is due to another bug with large media where pointer files are not marked as binary here:
https://github.com/netlify/netlify-cms/blob/dd080347b09606d651bb154a9a4870d704f0d48e/packages/netlify-cms-backend-github/src/API.ts#L171
So the solution is to both fix marking LFS files as binary and retrieving metadata for the original non transformed files.
This PR also fixes another issue where setting `use_large_media_transforms_in_media_library: false` did not work.
=> fix(large-media): mark pointer files as binary

CONTRIBUTING.md
I would like to update the contributing document to add a new section for debugging.
**Summary**
When I contribute to the Netlify CMS project, I usually need to debug the code to understand it better. Netlify CMS project provides a test server for local development, but if you need to connect to a real Github backend and test your features you need to do some configuration.
=> Adding a new Debugging section

packages/netlify-cms-lib-util/src/getBlobSHA.ts, packages/netlify-cms-lib-util/src/types/js-sha256.d.ts
Import named export because no default export exists
**Summary**
I was trying to create a custom backend and my typescript compiler complained about a wrong import. There is no default export in js-sha256, only named exports.
=> Fixed sha256 import

packages/netlify-cms-core/src/backend.ts
**Summary**
Fixes #4665 to allow collections with i18n enabled to use filtered entries.
**Test plan**
Ran yarn test and all tests pass.
I don't have a cute animal unfortunately :(
=> fix(i18n filtering): enable filtering when i18n is enabled

packages/netlify-cms-core/src/actions/status.ts, packages/netlify-cms-core/src/components/App/App.js, packages/netlify-cms-core/src/components/App/Header.js, packages/netlify-cms-core/src/components/Editor/Editor.js, packages/netlify-cms-core/src/components/Editor/EditorInterface.js, packages/netlify-cms-core/src/components/Editor/EditorToolbar.js, packages/netlify-cms-core/src/reducers/__tests__/auth.spec.ts, packages/netlify-cms-core/src/reducers/auth.ts, packages/netlify-cms-core/src/reducers/status.ts
**Summary**
First step on closing #3853
**Test plan**
Run existing tests
=> Remove immutable from status and auth

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/actions/__tests__/media.spec.ts, packages/netlify-cms-core/src/actions/media.ts, packages/netlify-cms-core/src/reducers/__tests__/medias.spec.ts, packages/netlify-cms-core/src/reducers/medias.ts, packages/netlify-cms-core/src/types/redux.ts, yarn.lock
**Summary**
Continue with #3853
**Test plan**
Run existing tests
=> refactor: remove immutable from medias state slice

website/static/_redirects
=> chore: update slack invite link

packages/netlify-cms-backend-gitlab/src/API.ts
**Summary**
Fixes #4786
Merge request rebasing creates a GitLab CI pipeline and the subsequent commit creates another. This fix skips the first pipeline creation. Relevant API documentation is located here: https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request
<sup>[GIMP's official mascot Wilber](https://commons.wikimedia.org/wiki/File:The_GIMP_icon_-_gnome.svg) by Tuomas Kuosmanen licensed under [GNU GPLv2+](http://www.gnu.org/licenses/gpl.html)</sup>
=> Skip creating a CI pipeline when rebasing the merge request

packages/netlify-cms-locales/src/de/index.js
Closes #4778
**Summary**
The translation of newButton is supposed to be Neue(r/s), because there are 3 possible cases:
Neue Blume
Neuer Artikel
Neues Tier
**Test plan**
Nothing to test here. The .js file syntax is still correct.
=> Fixed translation issue of newButton (#4778)

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/redux/index.ts, yarn.lock
**Summary**
Use redux-devtools-extension package (extracted from https://github.com/netlify/netlify-cms/pull/4776). Benefits: less code, happier TypeScript.
**Test plan**
Make sure that redux devtools extension works
=> refactor: use redux-devtools-extension package

packages/netlify-cms-locales/src/en/index.js, packages/netlify-cms-widget-file/src/withFileControl.js
**Summary**
Closes #1293, and enble Netlify CMS users to use images from other sources.
**Test plan**
Testing this could be done just like testing with media library, although this one requires the image URL to be reliable. I'm not very sure where to put those tests, so please let me know where should I put it if you think these requires some testing.
Here's my cat!
=> feat(widget-file): allow adding file from url

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/actions/__tests__/config.spec.js, packages/netlify-cms-core/src/actions/config.js, packages/netlify-cms-core/src/bootstrap.js, packages/netlify-cms-core/src/components/App/App.js, packages/netlify-cms-core/src/reducers/config.ts
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/4817
In this refactoring config loading has been moved from App.js to bootstrap.js, which makes App component "dumber". And also redundant mergeConfig and configDidLoad actions has been removed. This also should make https://github.com/netlify/netlify-cms/pull/4776 merging easier.
**Test plan**
=> refactor: different config loading strategy

packages/netlify-cms-core/src/constants/configSchema.js
This option was [removed in ajv v7](https://github.com/ajv-validator/ajv/releases/tag/v7.0.0)
=> fix: remove redundant ajv option

packages/netlify-cms-core/src/actions/config.js, packages/netlify-cms-core/src/reducers/collections.ts, packages/netlify-cms-core/src/reducers/integrations.ts, packages/netlify-cms-core/src/types/redux.ts
Fixes an issue with the `listEntries` integration where it would infer commit author and date a default sort fields.
There is no guarantee that information is available when using an external integration.
=> fix(list-entries-integration): don't show commit date & author as default sort

.github/workflows/docslint.yml
`v1.3.0` uses the latest docker tag from https://hub.docker.com/r/jdkato/vale/tags?page=1&ordering=last_updated
This PR pins it to https://github.com/errata-ai/vale-action/commit/0dec3032fa59c4097deece7cf6ee3261b27bb3f1
=> chore: fix vale linting

website/content/docs/widgets/select.md
As is, the code to create a `select` widget with options as objects will **not** compile. It throws the following error:
```
YAMLSemanticError: Separator , missing in flow map at line 49, column 15:
- { label: "Chicago", value: "ORD" }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I've changed the code to match the [kitchen sink config example](https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml#L151).
=> Update Docs: Widgets “select”

packages/netlify-cms-core/src/reducers/mediaLibrary.ts
Add missing `displayURLs` when using private assets
=> fix: add missing displayURLs to state

__mocks__/styleMock.js, jest.config.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibrary.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryButtons.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryModal.js, packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryTop.js, packages/netlify-cms-core/src/components/MediaLibrary/__tests__/MediaLibraryButtons.spec.js, packages/netlify-cms-locales/src/en/index.js
This PR adds a `copy to clipboard` button for the media library modal and also allows previews of `avif` files
=> feat(media-library): add copy to clipboard, allow avif

.github/workflows/nodejs.yml, cypress/run.js, package.json
This PR changes Cypress tests to run in parallel also on forked PRs (when the Cypress record secret is not available).
=> chore: improve cypress runs on forks

packages/netlify-cms-core/src/actions/__tests__/config.spec.js, packages/netlify-cms-core/src/actions/config.js
**Summary**
Another atomic PR to make https://github.com/netlify/netlify-cms/pull/4776 easier to merge
**Test plan**
=> refactor: mutate config in normalizeConfig and handleLocalBackend fns

packages/netlify-cms-core/src/components/Editor/EditorInterface.js, packages/netlify-cms-locales/src/en/index.js, packages/netlify-cms-locales/src/fr/index.js
**Summary**
The buttons at the top-right edge of the editor had hard-coded titles, so it wasn't possible to translate them.
I've added new translation strings, filled them for `en` and `fr`, and used them instead of the hard-coded values.
Concerned buttons are those three:
**Test plan**
I ran `yarn test:all` successfully, and checked with `yarn start`, in both `en` and `fr`, that buttons hover values were OK.
If I need to add some tests for this, please tell me!
=> feat(locale): Make editor interface buttons translatable

packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js
closes #4894
**Summary**
The custom editor components name is hiding by ul width
I have added dropdownWidth="max-content", so that solve the problem. 
**Test plan**
=> custom editorComponents name is cut by <ul> width #4894

.github/workflows/nodejs.yml
Save Cypress results as GitHub artifacts to make it easier to debug PRs running from forks
=> test: save cypress results as artifacts

packages/netlify-cms-backend-bitbucket/src/API.ts, packages/netlify-cms-proxy-server/src/middlewares/localGit/index.ts
Fixes our Cypress tests (we use prerecorded data so string changes in the URL break the tests).
Also remove the very verbose log of `simpleGit`
=> test: fix cypress tests

packages/netlify-cms-core/index.d.ts
**Summary**
Fixes #4984 wherein fixing TypeScript type errors introduced in #4950 would result in a config-loading runtime error. These changes fix those unexpected type errors and bring the public facing config types (`packages/netlify-cms-core/index.d.ts`) more in line with user expectations.
**Test plan**
No new code or tests have been added. All existing tests pass after these changes to `packages/netlify-cms-core/index.d.ts`.
I believe that is expected and _okay_ because afaik `index.d.ts` is kind of a facade (i.e. not generated from the actual implementation). At the very least, this PR gets rid of a few type errors for TypeScript users and doesn’t knock anything over.
A future, worthwhile test may be to type-check a kitchen-sink config object—like one that would be used in a manual …
=> Fixes user-facing config types in netlify-cms-core

packages/netlify-cms-core/index.d.ts
Just a quick fix, unless I've missed something `globalStyles` shouldn't be required in the following case:
```ts
CMS.registerWidget({
name: 'custom-select',
controlComponent: SelectWidget,
})
```
=> fix(core): typedef: globalStyles should not be required in CmsWidgetParam

website/package.json, website/yarn.lock
Forces the same version for `mini-css-extract-plugin` to be used by the CMS plugin and Gatsby
=> chore: fix website build

packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js
**Summary**
(This is tangentially related to #1341.)
When viewing a collection in grid view, if the entries don’t have images (or perhaps a custom summary), the cards are currently usually larger than the summary text. This results in poor UX, because only the upper part of the card actually contains the link element. Clicking in the lower part of the card won’t open the entry.
This PR adds `height: 100%` to the `GridCardLink` component, ensuring the link element always fills the full card height:
In addition, I have added `outline-offset: -2px` to ensure that outline styling on keyboard focus remains visible. The `GridCard` has `overflow: hidden` and so the default focus outline for the link would otherwise fall entirely outside the card. (Previously it was only visible on the bottom of …
=> fix(core): ensure GridCardLink fills entire card

website/content/docs/beta-features.md
**Summary**
I had quite a confusing time debugging i18n with a file collection until I finally found #4844. I had been missing the fact that each file in a file collection also needs its own `i18n` key.
This PR updates the i18n docs to mention this.
[Aside: this is partly confusing because a file collection with i18n enabled shows the side-by-side translation interface for all files, but it is broken for files that don’t themselves have `i18n: true` (as detailed in #4844). I guess to support per-file config like this better, files that don’t have i18n enabled should not show the i18n UI at all.]
**Test plan**
I read through my docs changes several times and tried to make them consistent with the rest of the examples.
Docs ox.
=> docs: clarify i18n configuration for file collections

packages/netlify-cms-locales/src/ja/index.js
**Summary**
update Japanese locale file.
**Test plan**
=> feat: update locale (ja)

packages/netlify-cms-core/src/reducers/editorialWorkflow.ts
**Summary**
fix https://github.com/netlify/netlify-cms/issues/4072
the entry should remain on the screen so that the user can publish again.
**Test plan**
yarn test
https://user-images.githubusercontent.com/35182743/110475698-91ceff80-8124-11eb-9772-2f875044241b.mov
https://user-images.githubusercontent.com/35182743/110475712-95fb1d00-8124-11eb-9135-463910a98847.mov
=> fix: entry disappears from workflow screen on failing to merge pull request

website/content/docs/custom-widgets.md
I was following the custom widgets docs, but hit a road bump. I just did exactly what the guide said, but still got a webpack error about the list of loaders. I looked at the webpack docs, found `use` and it seemed to work.
=> Fix webpack config in “custom-widgets”

packages/netlify-cms-core/src/lib/__tests__/i18n.spec.js, packages/netlify-cms-core/src/lib/i18n.ts
**Summary**
Fixes #5049 where files with "md" (or other extensions) within the name is mistaken for file extension.
**Test Plan**
Described in the mentioned issue.
My first time contributing. I think a test could be added as well, but not sure how. Thanks!
=> fix: i18n regex logic

.github/workflows/docslint.yml, .github/workflows/nodejs.yml
We tags releases when we publish and we also push to `master` at the same time.
We don't need to waste CI machines on tags:
=> chore: don't run tests on tags

.github/workflows/nodejs.yml
Previously we were saving only artifacts of successful runs.
=> chore: always save tests artifacts

packages/netlify-cms-widget-code/src/CodeControl.js
**Summary**
The code widget resizes to a maximum of *300px* whenever you focus into it, no matter how much code there is.
This PR partially fixes #4897 , however I think the other problem is related to code mirror.
**Test plan**
The only addition is an `!important` tag:
```css
/* ... */
.CodeMirror {
height: auto !important;
}
/* ... */
```
<details>
<summary>
Before
</summary>
https://user-images.githubusercontent.com/9270494/111359028-afa3e380-8693-11eb-9130-3606a5297665.mp4
</details>
<details>
<summary>
After
</summary>
https://user-images.githubusercontent.com/9270494/111359258-f5f94280-8693-11eb-9e51-d48852395d81.mp4
</details>
=> #4897: fix code widget resize on focus bug

.github/workflows/nodejs.yml
Caching on Windows is super slow and adds more than 7m to the build:
See https://github.com/actions/cache/issues/529 and https://github.com/actions/cache/issues/442
On MacOS it's not that great either:
Ubuntu seems good:
but since we wait for all builds to finish I think it's better to remove caching.
=> chore: remove GitHub cache action

cypress.json
Another attempt to stabilize tests.
Retries allows us to later examine flaky tests in the Cypress dashboard. See https://docs.cypress.io/guides/guides/test-retries
=> test(e2e): add retries

packages/netlify-cms-core/index.d.ts
**Summary**
Should resolve #5143
**Test plan**
Call registerWidget() in TypeScript, check if control and preview params are typed.
=> fix: #5143 added types for registerWidget()

yarn.lock
`yarn install` results in changes to `yarn.lock` (probably this is a result of one of the dependency PRs)
=> chore: update yarn file

packages/netlify-cms-ui-default/src/Dropdown.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/Link.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/renderers.js
**Summary**
**Links:** Editing a link has a really bad UX. Clicking the link button first removes an existing link and then you have to select the desired text again to actually add another link.
This PR introduces logic to auto-complete the link prompt if the selected text is already a link, editing the link will change it like normal, and it will also prevent removing a link if the prompt is canceled or the input remains the same.
**Headings:** When selecting a heading, there was no way of knowing which type was selected other than the size of the text.
The attached image and video will show both functionalities.
**Test plan**
https://user-images.githubusercontent.com/9270494/110871066-5a07b980-82d6-11eb-9f65-6bcf6482de5a.mp4
=> Improve UX in Markdown editor - link editing and selected heading underline

babel.config.js, packages/netlify-cms-app/package.json, packages/netlify-cms/package.json
**Summary**
Solve #5086 
**Test plan**
Run `npm run build:es` on any package and check that `dist/esm` output is `esm` (export) instead of `commonjs`(module.exports)
=> Generate esm correctly

packages/netlify-cms/package.json
Small fix to https://github.com/netlify/netlify-cms/pull/5087
We don't generate `esm` for `netlify-cms` so the `module` field is redundant
=> fix(netlify-cms-package): remove module field

packages/netlify-cms-backend-github/src/implementation.tsx, packages/netlify-cms-lib-util/src/implementation.ts
**Summary**
This PR adds a new `always_fork` option to be used with open authoring. When a user has write/admin access to the repo the current behavior is to avoid the fork flow. When `always_fork` is set to true, forking will always be used even when the user has write/admin access. Resolves #5203 
**Test plan**
Still working on testing this.
=> Add alwaysFork option for open authoring

website/content/docs/external-oauth-clients.md
Follow up on https://github.com/netlify/netlify-cms/pull/5237
=> fix(docs-external-auth-client): use correct casing for GitHub, GitLab and TypeScript

packages/netlify-cms-backend-azure/README.md, packages/netlify-cms-backend-bitbucket/README.md, packages/netlify-cms-backend-git-gateway/README.md, packages/netlify-cms-backend-github/README.md, packages/netlify-cms-backend-gitlab/README.md, packages/netlify-cms-backend-proxy/README.md, packages/netlify-cms-backend-test/README.md, packages/netlify-cms-lib-auth/README.md, packages/netlify-cms-lib-util/README.md
**Summary**
Added short readme. It's better than nothing. Now these packages are of no value in and of themselves, so I think the "quick look at the code" format is appropriate.
**Test plan**
I dont know)
**A picture of a cute animal**
=> docs: add netlify-cms-backend-* readme for developers

packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
Closes #3887 
**Summary**
This PR aims to hide the `unpublish` button in the UI when a collection has a `delete: false` flag, Since netlify prevents the `unpublish` action in the backend when `!delete` then it's a good idea to hide the button from the UI in the first place.
Before: 
After:
**Test plan**
I couldn't find a way to test this.
=> fix: Remove `Unpublish` UI button if  collection has a `delete: false`. (#3887)

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/lib/urlHelper.ts, packages/netlify-cms-core/src/reducers/__tests__/entries.spec.js, packages/netlify-cms-core/src/reducers/entries.ts, website/content/docs/configuration-options.md, yarn.lock
**Summary**
I am trying to use absolute urls in the `public_folder` config for my CMS use case. Essentailly this is because the CMS sits as a standalone CDN for other applications and I wished to make the media uploads accessible from the CDN with absolute urls present all files editable in the CMS.
There is a rather old issue where someone requests this functionality #1668
However clearly in between this issue being created and now this no longer works. What happens when you have an absolute path in the `public_folder` is the second slash at the start of the url is stripped.
``` yaml
public_folder: https://netify.com/images
```
Currently produces: `https:/netlify.com/images/image.png` (note the missing second slash after `https`)
With this PR produces: …
=> Fixing an issue with public_folder not working with absolute urls

website/content/docs/jekyll.md
**Summary**
This pull request adds a section about enabling authentication for a Jekyll setup. The instruction contains two major steps:
- Enable Netlify Identity and Git Gateway on the backend.
- Add script to load the Netlify Identity widget at the `/admin` route.
A critical step of integrating Netlify CMS into an existing Jekyll site is authentication. The current doc tells users to visit the related Netlify documentation for instruction. However, it took me a while to wrap my head around Netlify Identity. 
Therefore, I like to help future readers get set up as quickly as possible by including the detailed step-by-step instruction for adding authentication functionality to their sites.
=> feat: add instruction for authenticating Netlify CMS users

website/content/docs/widgets/image.md
Fixed a "typo" in the image widget doc, and also some re-wording and style (removed a dot to be consistent with other list elements, added code style around a folder name).
=> fix(docs): image widget

packages/netlify-cms-ui-default/src/styles.js
**Summary**
Button elements don't inherit the font-stack, they use the browser's default, which in the case of Firefox/Windows at least is terrible.
Before: ![image](https://user-images.githubusercontent.com/3504434/117198186-99d3b480-ade0-11eb-9948-aa15c4e5c80e.png)
After: ![image](https://user-images.githubusercontent.com/3504434/117198115-81fc3080-ade0-11eb-85a1-014f17506756.png)
Very minor, I just noticed while looking at another issue.
**Test plan**
Didn't run any tests, purely cosmetic.
=> fixes: buttons using browser font-family, not the font-stack

packages/netlify-cms-ui-default/package.json, yarn.lock
Looks like https://github.com/netlify/netlify-cms/pull/5378 is causing our tests to be flaky.
Reverting so I can investigate
=> Revert "fix(deps): update dependency react-aria-menubutton to v7

packages/netlify-cms-core/index.d.ts
**Summary**
`CMS.registerEventListener` takes an `options` arg which is currently marked as required, but should be optional
**Test plan**
none
=> chore: mark registerEventListener options as optional

packages/netlify-cms-locales/src/nb_no/index.js
**Summary**
The translation of the Norwegian `editorToolbar.deleteEntry` was using the wrong inflection, making it sound like it was already deleting the entry.
This PR changes the translation from "deleting" to "delete".
**Test plan**
=> fix spelling of the norwegian deleteEntry translation

packages/netlify-cms-core/index.d.ts
**Summary**
Preview templates receive the `iframe`'s `window` and `document` - those were missing from the `PreviewTemplateComponentProps` type
**Test plan**
none
=> chore: add document and window to PreviewTemplateComponentProps type

packages/netlify-cms-widget-markdown/src/MarkdownControl/Toolbar.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CommandsAndQueries.js
fixes #5338 
**Summary**
This PR attempts to fix the problem with Netlify Markdown widget wherein the toolbar buttons for quote, bulleted list and numbered list are not highlighted when clicking on the corresponding block in the editor. 
All files mentioned are located inside packages/netlify-cms-widget-markdown/src/MarkdownControl.
When referencing Slate's documentation, please visit the 0.47 version. Netlify CMS app uses Slate 0.47, and Slate was rewritten from the ground up after this version. Most of the functionalities mentioned below don't apply to versions after 0.47.
Here is a tree diagram starting from the `<VisualEditor>` component.
The Quote toolbar button is just a presentation component. It has several props, one of which is  isActive whose boolean value determines the color …
=> Fix some block style buttons not highlighted when clicking on the equivalent blocks in the editor

website/content/docs/site-generator-overview.md
**Summary**
This pull request contains a new Markdown file called Overview that is meant to be added to the Platform Guides in the docs. It is a high-level view of what it means to integrate Netlify CMS with common static site generators without being biased to any framework.
Integrating Netlify CMS into a website built with SSG contains many moving pieces. The process also requires a bit of a mental leap, especially for someone from monolithic CMS. There are already plenty of detailed guides for all the popular SSGs, but none really explains the process from a high level or the rationale behind each step.
With this article, I hope that readers will have a better grasp on the benefits of integrating Netlify CMS with their static sites, why they should do what they are instructed to do …
=> feat(docs): add overview for integrating Netlify CSS with site generators

packages/netlify-cms-core/index.d.ts
**Summary**
adds `always_fork` option (see https://github.com/netlify/netlify-cms/pull/5204/files) to `CmsBackend` type.
**Test plan**
none
=> chore: add missing always_fork option to CmsBackend type

dev-test/config.yml, packages/netlify-cms-widget-file/src/withFileControl.js, website/content/docs/widgets/file.md, website/content/docs/widgets/image.md
**Summary**
Fixes: Image widget "Insert From URL" should be optional as requested here: [#5558](https://github.com/netlify/netlify-cms/issues/5532)
**Test plan**
By puting the option choose_url as true:
We see this in the cover image section when creating a new post:
By putting false:
We see that the option of _Insert From URL_ does not appear:
=> feat: image widget insert from url should be optional

dev-test/config.yml, packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, website/content/docs/widgets.md, yarn.lock
**Summary**
This adds the option to include HTML in the hint message on a field. Closes #5559 
The issue creator requested support for Markdown, which could be added in future but would require parsing the markdown from the config and would be a larger change. This is a simpler addition that addresses the same issue.
**Test plan**
I didn't see any existing tests for these components, but would be more than happy to add if I just missed them! This passes the existing tests.
=> feat: pass markdown for hint message on field

packages/netlify-cms-widget-list/src/ListControl.js
**Summary**
This PR improves the validation of the simple list (no fields) value.
Before the following will crash the editor:
```
default: '[1]` # This is a string not an array
```
I believe this is related to some of the following issues:
https://github.com/netlify/netlify-cms/issues?q=join+is+not+a+function
**Test plan**
Existing tests
**Checklist**
🐱
=> fix(list-control): better value validation

cypress/integration/markdown_widget_list_spec.js, cypress/integration/markdown_widget_quote_spec.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/BreakToDefaultBlock.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js
fixes #3474 
A different approach to the above issue without changing the underlying schema.
1. After running the app, go to http://localhost:8080.
2. Click on any of the pre-created blog post.
3. Toggle the text editor to rich text.
4. Place cursor at the end of the last line in the text editor and press Enter or Return key to create a new empty paragraph block.
5. Type anything in the new block.
1. With the cursor in any block you want, click the Bulleted List button to turn a block into a bulleted list.
2. Move cursor to the end of the bulleted list item block and hit Enter.
3. *Expect*: A new list item underneath, marked by a bullet icon.
4. Inspect the element in the Developer Tools. *Expect*: Under the block that receives the Enter key is a new `<li> element containing a `<p>` …
=> Fix: Hitting Enter key in a list item doesn't create a new list item [NO CHANGING SCHEMA]

jest.config.js, packages/netlify-cms-core/index.d.ts, packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js, packages/netlify-cms-core/src/lib/registry.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/CopyPasteVisual.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/visual.js, packages/netlify-cms-widget-markdown/src/MarkdownPreview.js, packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkPlugins.spec.js, packages/netlify-cms-widget-markdown/src/serializers/index.js, website/content/docs/beta-features.md
**Summary**
This PR allows registering remark plugins (and presets) to customize how markdown is serialized/deserialized in the richtext editor.
Two usecases which have come up are (i) avoid saving autolinks for mdx-compatibility, and (ii) enforce formatting options.
fixes:  #5516
related: #4601
did not mark #4601 as fixed, because this only affects how the richtext editor serializes to markdown. to enforce formatting for the markdown editor, the plaintext content would probably have to be run through a remark pipeline [here](https://github.com/netlify/netlify-cms/blob/3bd36776d6c02a0669df9a5b11f105efee2d2ca3/packages/netlify-cms-widget-markdown/src/MarkdownControl/RawEditor.js#L100) but that means text would change while typing, which is odd (i also ran into issues where the textarea …
=> Allow registering remark plugins

packages/netlify-cms-backend-git-gateway/src/__tests__/__snapshots__/AuthenticationPage.spec.js.snap, packages/netlify-cms-core/src/components/Editor/EditorToolbar.js, packages/netlify-cms-core/src/components/Editor/__tests__/EditorToolbar.spec.js, packages/netlify-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap, packages/netlify-cms-ui-default/src/styles.js
**Summary**
Closes #5553.
**Test plan**
Added a few tests
**Figure: When no changes have been made or saved**
**Figure: When changes have been saved** 
**Checklist**
=> Disable 'Save' button when there are no changes

packages/netlify-cms-locales/src/en/index.js, packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js, packages/netlify-cms-widget-list/src/ListControl.js, packages/netlify-cms-widget-list/src/__tests__/ListControl.spec.js, packages/netlify-cms-widget-list/src/__tests__/__snapshots__/ListControl.spec.js.snap, packages/netlify-cms-widget-object/src/ObjectControl.js
**Summary**
While using the CMS in another language, I noticed that in the list widget some labels were not translatable.
This was also reported in [this issue](https://github.com/netlify/netlify-cms/issues/5471) by another user.
This PR fixes #5471 by updating the component responsible for displaying the `Add` button and exposes two new translations keys to respectively handle the basic and the variable types code paths.
**Test plan**
Here is a code extract where I'm willingly adding very verbose translations:
Here is the expected result in the Kitchen Sink demo:
**Checklist**
**A picture of my cute cat**
=> fix(widget-list): add missing translations in widget list top bar

website/src/components/markdown.js, website/src/components/sidebar-layout.js
Fixes #5659
**Summary**
When the table width is too wide, the scrollbar is not in the right place (at the bottom of the content page)
**Test plan**
Before:
After:
**Checklist**
- [x  Code is formatted via running `yarn format`.
=> fix: overflow table on the docs page

cypress/integration/markdown_widget_list_spec.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js
fixes #5654 
**Summary**
When selecting multiple paragraph blocks and click List button, the current behaviour is to turn them into one list block which contains **one** list item, no matter how many paragraph blocks are selected.
This PR changes that behavior to make Netlify CMS editor more in line with the convention in most rich text editors. Each paragraph block in the selection will be wrapped with a respective list item. Then all the list items will be wrapped with one unifying list block.
HTML before clicking List button:
```
<p>Item 1</p>
<p>Item 2</p>
<p>Item 3</p>
```
HTML after clicking List button:
```
<ul>
<li>
<p>Item 1</p>
</li>
<li>
<p>Item 2</p>
</li>
<li>
<p>Item 3</p>
</li>
</ul>
```
**Test plan**
TODO:
**Checklist**
=> fix(markdown-widget): apply list item style on each block in a selection

packages/netlify-cms-core/src/components/Workflow/WorkflowCard.js
**Summary**
Currently, the "Publish" button in the Workflow tab has a "pointer" cursor, even when it is disabled, which can be confusing to users. This PR changes the cursor to `not-allowed` when the publish button is disabled.
**Test plan**
**Checklist**
=> style: indicate that disabled publish button is not clickable

packages/netlify-cms-ui-default/src/ObjectWidgetTopBar.js, packages/netlify-cms-ui-default/src/styles.js, packages/netlify-cms-widget-datetime/src/DateTimeControl.js
**Summary**
Closes #5706
Changed the styling of the 'Now' button on the DateTime widget to match the styling of the 'Add xxx' button on the List widget.
**Test plan**
Tested locally
Figure: 'Now' button changed to be consistent with 'Add xxx' buttons
**Checklist**
=> Make 'Now' button on DateTime widget consistent with 'Add' button on List widget

packages/netlify-cms-core/src/valueObjects/EditorComponent.js, packages/netlify-cms-widget-markdown/src/MarkdownControl/index.js, packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkShortcodes.spec.js, packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js, website/content/docs/custom-widgets.md
Fixes #5258
Reopen of #5259
Updates `remarkShortcodes` to handle custom editor components occurring in
any order in a given markdown field.
Previously, `remarkShortcodes` (the remark tokenizer plugin in the markdown widget) was relying on [`Map.find`](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js#L15-L23) to attempt to match the registered editor components' patterns against the remaining uneaten markdown. Because Map.find returns after the first instance that returns true, some valid shortcode matches can be "skipped" by the plugin, and parsed as plain text instead.
This made it almost impossible to use multiple shortcodes in a single markdown field. At least one of them regularly gets "skipped" by the …
=> fix(markdown-widget): support arbitrary component order

website/content/docs/beta-features.md, website/content/docs/netlify-large-media.md
**Summary**
made corrections to the typos i have found in the documentations.
**Checklist**
=> fix(docs): fix typos in docs

.github/workflows/nodejs.yml
Our CI fails due to https://github.com/nodejs/node/issues/40030
=> chore(ci): pin Node.js version

packages/netlify-cms-core/package.json, packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, website/content/docs/widgets.md, yarn.lock
**Summary**
This adds the option to include strikethrough HTML in the hint message on a field. Closes #5717
The issue creator requested support for strikethrough Markdown
**Test plan**
Please guide me to the testing details if any for this modification. Thanks in advance.
**Checklist**
=> feat: pass strikethrough markdown for hint message on field

.github/workflows/nodejs.yml
Reverts https://github.com/netlify/netlify-cms/pull/5796 now that Node.js 16.9.1 was released
=> chore: use latest Node.js

packages/netlify-cms-widget-relation/src/RelationControl.js
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/5093
Probably fixes https://github.com/netlify/netlify-cms/issues/4891 too
This should fix a race condition in the relation widget, where slower to load entries override faster to load ones when switching between entries.
**Test plan**
Existing tests
**Checklist**
🐱
=> fix(widget-relation): don't invoke onChange if component is not mounted

packages/netlify-cms-core/src/reducers/__tests__/collections.spec.js, packages/netlify-cms-core/src/reducers/collections.ts
Fixes #5773 
**Summary**
When using the `nested depth` collections feature, netlify displays the entry title in the sidebar which can be quite long. Overriding via `identifier_field` requires that the `identifier_field` is present (and non-empty?) for all entries which is not desirable.
This change simply checks whether the overriding field content is non-empty and otherwise falls back to using the `title` content.
**Test plan**
The impact should be visible from the screentshots in #5773. To achieve that:
- Change `dev-test/config.yml` and `dev-test/index.html` as attached
[config.yml.txt](https://github.com/netlify/netlify-cms/files/7090449/config.yml.txt)
[index.html.txt](https://github.com/netlify/netlify-cms/files/7090456/index.html.txt)
Netlify should then display the short title …
=> Fallback to title when overriding with empty or non-existant field

CONTRIBUTING.md
**Summary**
I hope to make the Debugging section of the Contributing guide clearer to newbie contributors. Here is what I add:
- Add more concrete instruction for configuring backend
- Explain what users should look for when changing `dev-test/index.html`
- Add more info to use local storage to set Netlify site's URL
**Test plan**
**Checklist**
=> Update Contributing guide: Add more details to Debugging section

packages/netlify-cms-locales/src/ca/index.js
I started the Catalan contribution of Netlify CMS (https://github.com/netlify/netlify-cms/pull/3412) and I'm glad and impressed that some fellow countrymen joined and improved my initial translation, even with the new strings added by you in the new features. 
I've been following the trace of the translations and I've noticed a few (extremely minor) mistakes in the translation strings so the aim of this PR is to fix them and encourage people to keep collaborating with you guys.
The cute animal picture, which because of my debauchery has evolved into a GIF.
=> fix(translations): correct catalan locale

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js, packages/netlify-cms-locales/src/de/index.js, packages/netlify-cms-locales/src/en/index.js
allow copying data from other locales (#5850), so that translators have an easier job
use multiple locales, when editing it is now possible to copy values from one locale to another
**Checklist**
=> feat(locales): allow copying data from other locales (#5850)

.github/workflows/nodejs.yml
**Summary**
Follow up from https://github.com/netlify/netlify-cms/pull/5924
=> ci(workflow): add yarn' cache from setup-node action to 'e2e-with-cypress' job

website/content/docs/widgets.md
**Summary**
- Changing the indent level seems to have worked here
- The single line issue was because of the ```white-space: nowrap```
- Changing it to ```white-space: normal``` results in
The first one looks cleaner imo
**Checklist**
=> fix: Unformatted text in the widgets docs page

packages/netlify-cms-core/index.d.ts
**Summary**
This adds the missing `auth_type` field to the `CmsBackend` type.
**Test plan**
none
**Checklist**
=> Add missing `auth_type` to `CmsBackend` type

website/content/docs/add-to-your-site.md
**Summary**
The Nuxt 2 `static` directory became the `public` directory on Nuxt 3, as described
on the [official docs](https://v3.nuxtjs.org/docs/directory-structure/public). 
This PR updates the `add-to-your-site` docs so both Nuxt 2 and 3 are covered
on the App File Structure table
**Test plan**
Lint:
```
❯ cd website
❯ yarn lint
yarn run v1.22.10
$ markdownlint 'content/docs/**/*.md'
✨  Done in 0.43s.
```
Run (with `yarn start`) and check UI on browser:
**Checklist**
=> docs: add Nuxt 3 static files location

packages/netlify-cms-proxy-server/webpack.config.js, packages/netlify-cms-widget-map/package.json, packages/netlify-cms-widget-map/src/withMapControl.js, yarn.lock
**Summary**
We are using netlify-cms for a client who has a strict csp policy that would forbid adding:
```
"'unsafe-inline'",
"'unsafe-eval'",
```
to the csp.
After looking into the problem, it would appear that [rbush](https://github.com/mourner/rbush) which is here in the dependency tree:
```
netlify-cms
└─┬ netlify-cms-widget-map@1.5.0 -> ./packages/netlify-cms-widget-map
└─┬ ol@5.3.3
└── rbush@2.0.2
```
Is using `new Function("blah"` calls which will get blocked by csp unless the `unsafe-` directives are added.
Upgrading `ol` to `6.9.0` upgrades `rbush` to `3.0.1` where the `new Function` calls have been replaced:
```
netlify-cms
└─┬ netlify-cms-widget-map@1.5.0 -> ./packages/netlify-cms-widget-map
└─┬ ol@6.9.0
└── rbush@3.0.1
**Checklist**
=> fix(csp): update ol and fix webpack global emit (#2138)

.github/workflows/nodejs.yml
We've been having `yarn install` timeouts in our CI, see https://github.com/netlify/netlify-cms/runs/4505200149?check_suite_focus=true#step:5:7
Increasing the timeout should fix this.
=> chore: increase yarn network timeout

packages/netlify-cms-backend-git-gateway/src/__tests__/__snapshots__/AuthenticationPage.spec.js.snap, packages/netlify-cms-ui-default/src/styles.js
**Summary**
This PR is a fix for
https://github.com/netlify/netlify-cms/issues/1333#issuecomment-998115794
because it changes the background color used by `button` to `grayDark`
so that it is accessible.
**Test plan**
Tested the `grayDark` color [here ](https://dequeuniversity.com/rules/axe/4.3/color-contrast?application=axeAPI)and it passes.
**Checklist**
=> refactor(netlify-cms-ui-default): use grayDark for button

packages/netlify-cms-backend-git-gateway/src/GitLabAPI.ts, packages/netlify-cms-backend-gitlab/package.json, packages/netlify-cms-backend-gitlab/src/API.ts, packages/netlify-cms-backend-gitlab/src/implementation.ts, packages/netlify-cms-backend-gitlab/src/queries.ts, packages/netlify-cms-lib-util/src/implementation.ts, website/content/docs/beta-features.md
**Summary**
Fixes https://github.com/netlify/netlify-cms/issues/5920, part of https://github.com/netlify/netlify-cms/issues/6034
**Test plan**
TBD
**Checklist**
🐼
=> feat(backend-gitlab): initial GraphQL support

packages/netlify-cms-core/index.d.ts
**Summary**
this adds the missing `app_id` field (documented e.g. [here](https://www.netlifycms.org/docs/gitlab-backend/#client-side-pkce-authorization)) to the `CmsBackend` type
**Checklist**
=> chore: add missing `app_id` field to `CmsBackend` type

packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
**Summary**
Removes a debug log
**Test plan**
Existing tests
**Checklist**
🐒
=> fix: remove redundant log from EditorControlPane

packages/netlify-cms-lib-widgets/src/__tests__/stringTemplate.spec.js, packages/netlify-cms-lib-widgets/src/stringTemplate.ts, website/content/docs/beta-features.md
**Summary**
When using the new types feature of the list widget, there is no good solution to show a summary for markdown fields. I added a new `truncate` filter for the summary tag.
I can be used as followed:
{{body | truncate(20)}} -> Will truncate the body field after 20 characters and adds the default ... at the end.
{{body | truncate(20, '***')}} -> Will truncate the body field after 20 characters and adds *** at the end.
**Checklist**
=> feat: add truncate filter to summary tag

packages/netlify-cms-core/src/lib/__tests__/i18n.spec.js, packages/netlify-cms-core/src/lib/i18n.ts
fixes that getFilePaths returns same path twice when i18n structure is SINGLE_FILE
**Checklist**
=> fix(i18n): fix that unable to delete page with SINGLE_FILE i18n structure

cypress/plugins/bitbucket.js, cypress/plugins/github.js, cypress/plugins/gitlab.js, cypress/plugins/proxy.js, packages/netlify-cms-core/src/formats/frontmatter.ts, packages/netlify-cms-core/src/lib/textHelper.js, packages/netlify-cms-widget-file/src/withFileControl.js, packages/netlify-cms-widget-markdown/src/serializers/slateRemark.js
**Summary**
This is a second step after #6333 which removes all uses of `substring()` and replaces it with `slice()`
**Test plan**
**Checklist**
=> chore: remove all .substring() usage

.github/workflows/nodejs.yml
**Summary**
Using `paths-ignore` doesn't add status checks required by our branch protection, see https://github.com/netlify/netlify-cms/pull/6388.
This PR fixes that
**Test plan**
Existing tests
**Checklist**
🐟
=> chore(ci): add passing status checks when ignoring website changes

.github/workflows/nodejs.yml
Follow up to https://github.com/netlify/netlify-cms/pull/6390
The checkout step is needed for `push` events
=> chore: add checkout step

website/content/docs/add-to-your-site.md
**Summary**
Adds code in docs (/docs/add-to-your-site/) that issue #6616 asked for. However, I cannot find within the codebase where I could add this line: `<meta name="robots" content="noindex" />`so by default the /admin is not picked up by Search engines. 
This is my first PR to netlify-cms, so a bit of guidance would be greatly appreciated on where to place that line of code mentioned above. 
**Test plan**
Add that line of code so the actual /admin that is deployed - so that page is not picked up by Search engines. 
**Checklist**
=> Update Docs: Meta tag 'noindex' added

website/content/blog/github-discussions.md
Fixed a typo and adjusted the casing of GitHub
=> fix: typo and GitHub casing

website/content/blog/introducing-decap.md
**Summary**
Add a link to netlify blog post on the introductory Decap CMS blog post, to show that this rebranding has been made with  support from Netlify (otherwise it might feel like a fork coming out of the blue).
=> Add a link to netlify blog post

website/content/docs/intro.md
**Summary**
Update the intro doc, to show that Decap CMS was previously known as Netlify CMS.
Otherwise it is quite disturbing to read `has never been locked to the Netlify platform (despite the name)`, since the new name has nothing to do with Netlify :)
=> document that Netlify CMS became Decap CMS

website/content/docs/beta-features.md
**Summary**
Currently on the [Beta Features](https://www.netlifycms.org/docs/beta-features/) page the "added in ..." version numbers are displaying as mailto: links, presumably because they contain an @ symbol. I assume this is undesirable? 
I clicked on one expecting to be taken to a change log associated with that version, but instead my email client opened.  Surrounding them in backticks makes them display as code instead. Alternatively we can turn them into actual links pointing to a change log, but I looked and couldn't seem to find a log (nor a matching release branch) on the website or on github. 
There is also another potential solution (adding an empty link) as explained in this [StackOverflow](https://stackoverflow.com/questions/59697538/making-it-so-email-addresses-arent-turned- …
=> fix the display of "added in ..." versions

website/content/docs/nextjs.md
**Summary**
Noticed that the js snippets in this markdown file use _mostly_ no-semicolons, but there are a couple of strays.
**Test plan**
Wishing really hard
**Checklist**
- [👀] Tests are passing via running `yarn test`.
- [👀] The status checks are successful (continuous integration). Those can be seen below.
=> chore: consistent semicolons in js snippets

.github/PULL_REQUEST_TEMPLATE.md
**Summary**
My opinion: there's no need for these three checkboxes: 
The CI checks can run `yarn format` and `yarn test`, and the status checks speak for themselves. CI creates a ✅ , there's no need to ask a human to do it too. (plus, the status checks usually _can't_ be successful when the PR is first created, since it's the PR that triggers them in the first place, so the question doesn't really make sense.
**Test plan**
N/A
**Checklist**
=> chore: rm pr template checkboxes covered by CI

website/content/docs/add-to-your-site.md
**Summary**
Add the astro 'public' folder to the add-to-your-site documentation.
**Test plan**
N/A
**Checklist**
=> docs: add astro to add-to-your-site generators

packages/netlify-cms-core/src/components/MediaLibrary/MediaLibraryCard.js
**Summary**
Currently when you open Media Library, all media insides are shown causing a lot of network requests even if you don't need them.
Using native image attribute `lazy` will optimize images outside the viewport and reducing unused network requests.
**Test plan**
There is not UI changes, just browser default behaviour and performance increased.
**Checklist**
=> feat(netlify-cms-core): add lazy property to images in Media Library

packages/netlify-cms-core/index.d.ts, packages/netlify-cms-core/src/types/redux.ts
**Summary**
When implementing the option to add a `choose_url` flag to the image widget  https://github.com/netlify/netlify-cms/pull/5572 the TS interface declaration for `CmsFieldFileOrImage` has not been adapted accordingly which keeps the user to set this option when declaring a field with Typescript
**Test plan**
na/
**Checklist**
=> feat: add choose url option to file or image ts interface

website/content/docs/beta-features.md, website/content/docs/custom-widgets.md
Closes #2855
There were 2 references of the old package in the docs, this PR updates that.
=> docs: use 'netlify-cms-app' everywhere

website/content/docs/configuration-options.md
Closes #5062
Adds `hint` to Fields section in Configuration options.
=> docs: add hint to config options - fields

packages/netlify-cms-core/src/components/Editor/EditorToolbar.js, packages/netlify-cms-ui-default/src/styles.js
Closes #6355 
**Summary**
Fixes issue where publish drop down items were overflowing and not visible by:
1) Increasing the dropdown menu width to 200px (Looks cramped and breaks into 3 lines at current width of 150px, but happy to undo this part if people disagree)
2) Adjusting publish dropdown menu min-width property so that text wraps properly.
**Test plan**
This issue occurred in French, English, and German (Although issue only complained about French, this fixes all 3). Since these are the only locals explicitly declared in the code (That I can find) those are all I tested, however this fix should work regardless of the length (see lorem ipsum screenshot examples)
Broken - English
Fixed - English
Fixed - French
Fixed - German
Fixed - Long Lorem Ipsum text to demo that longer text …
=> fix(#6355): publish button dropdown items overflow menu

packages/decap-cms/README.md
Update package readme for the NPM page
=> feat: update package readme

.github/workflows/nodejs.yml
Change runs to:
- `build` on ubuntu, macos & window, each with Node 16 and 18
- `cypress` with Node 16 and 17
=> chore(node-ci): update machine count & node version

packages/decap-cms-core/src/components/Editor/EditorControlPane/EditorControlPane.js
i18n feature "Fill from another locale" produced an error if a field was undefined. This was problematic if field was an object, then an error would appear on save.
=> fix: fill from locale error if undefined

packages/decap-cms-widget-file/src/withFileControl.js
Fix for issue https://github.com/decaporg/decap-cms/issues/6918
Since recent changes to image gallery & sorting, file widget value defaulted to an empty array, which caused incorrect structure when single field was used within list. This reverts to how it was before 3.0.
=> fix: change file-control default value to string

packages/decap-cms-core/src/backend.ts, packages/decap-cms-core/src/lib/i18n.ts
Fix issue #6913  that was caused by https://github.com/decaporg/decap-cms/pull/6898
**Summary**
The issue appeared when we added some filtering to prevent hitting Github gateway rate limits on large projects. When filtering by locale path in order to load only default locale for lists, we failed to consider all three possible i18n structures when building the regex.
This fix will create an appropriate path for folder structure and leave the path as is for single file structure.
**Test plan**
**Checklist**
=> fix: consider i18n structure when building path regex

packages/decap-cms-core/src/backend.ts
**Summary**
#6898 introduced filtering by path for Github, but it also introduced a couple of bugs for i18n. #6937 resolved it for multi-folder project structures and it was already working for multi-file structures. However single file structures were not being filtered right, resulting in no results appearing for collections using that structure.
**Test plan**
**Checklist**
=> fix: handle single file i18n when filtering

dev-test/config.yml, packages/decap-cms-widget-colorstring/package.json, packages/decap-cms-widget-colorstring/src/ColorControl.js, yarn.lock
**Summary**
Replacing validatecolor with tinycolor2. This fixes #7007 because of a snyk vulnerability for the validatecolor package.
**Test plan**
Screenshot of the application started up: 
Screenshot of the color picker:
**Checklist**
=> fix(#7007) Replace validate color with tiny color 2

packages/decap-cms-ui-default/src/styles.js
**Summary**
this adds "system-ui" to the default font stack.
**Motivation**
on my firefox on linux the current font stack falls back on "sans-serif" which looks awful.
**Test plan**
**Checklist**
=> style: add system-ui to default font stack

website/content/docs/custom-widgets.md
https://deploy-preview-7032--decap-www.netlify.app/docs/custom-widgets/
1. **Fix the code example**
The code example for the `registerEditorComponent` is incorrect as the line `name: 'details',` should be `name: 'detail',`. I think this mistake has come about because we're naming the field name the same as the HTML element `<details>`.
I'm proposing to rename it to `contents` to avoid this mistake in the future.
2. **Markup headings correctly**
We're currently marking up what look like headings with a `**` bold to make it look like a heading. I'm proposing we use actual headings here.
3. **Remove 'results' section**
It seems to be from some previous code example where it referred to a Youtube widget. This doesn't seem to be relevant anymore.
4. **Remove unnecessary links**
Looks like …
=> Update Docs: Improve custom widgets documentation

website/content/docs/beta-features.md, website/content/docs/customization.md
Relating to #7040 this seems most logical place for this.
=>  Update Docs migrate Beta Features - Raw CSS

website/content/docs/beta-features.md, website/content/docs/custom-formatters.md
=>  Update Docs: migrate Beta Features - Custom Formatters

website/content/docs/beta-features.md, website/content/docs/registering-events.md
=> Update Docs: migrate Beta Features - Registering CMS Events

website/content/docs/beta-features.md, website/content/docs/dynamic-default-values.md
=> Update Docs: migrate Beta Features - Dynamic Default Values

website/content/docs/beta-features.md, website/content/docs/widgets/file.md, website/content/docs/widgets/image.md
=> Update Docs: migrate Beta Features - Image Size Limit

website/content/docs/beta-features.md, website/content/docs/custom-mounting.md
Given how minimal this is, it feels wrong it is on own page, but it seems semantically to make most sense. 
I am not sure in what creative cases this is useful or what code to do it looks like- maybe  because I am not a React developer? 🤔
@martinjagodic perhaps adding some example snippets and slightly more text or links to examples?
Relating to #7040
=> Update Docs: migrate Beta Features - Custom Mount Element

packages/decap-cms-core/index.d.ts, packages/decap-cms-core/src/constants/configSchema.js
**Summary**
Allow empty string setting for publishing mode. Issue https://github.com//decaporg/decap-cms/issues/7102
**Test plan**
Before:
After:
**Checklist**
=> publish mode allow empty string

packages/decap-cms-core/src/components/Editor/EditorControlPane/EditorControl.js, packages/decap-cms-core/src/components/Editor/EditorControlPane/Widget.js, packages/decap-cms-widget-code/src/CodeControl.js, packages/decap-cms-widget-object/src/ObjectControl.js
**Summary**
fixes #6812 
code widgets now shows content if it's inside list.
**Test plan**
config.yml
```
local_backend: true
backend:
name: proxy
proxy_url: http://localhost:8082/api/v1
branch: main
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads
collections:
- name: docs
label: Docs
label_singular: "Doc"
folder: "docs"
path: "{{title}}/{{id}}"
slug: "{{id}}"
create: true
nested: { depth: 100 } # accepts an optional summary template
allow_nesting: true
meta: { path: { widget: string, label: "Path", index_file: "index" } }
fields:
- { label: "title", name: "title", widget: "string" }
- {
name: "code test",
label: "Example Code",
widget: "code", …
```
=> show code widget content if initially hidden

.npmrc
**Summary**
By setting lockfileVersion to 3 it instructs npm to use the third version of the lockfile format.
This helps prevent the lockfileversion from changing (reverting to an older version).
Info: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion
**Test plan**
n/a
**Checklist**
=> Specify Lock file version in `.npmrc` config

dev-test/config.yml, packages/decap-cms-widget-relation/src/RelationControl.js, packages/decap-cms-widget-relation/src/__tests__/relation.spec.js, packages/decap-cms-widget-relation/src/schema.js
**Summary**
This PR adds a `filters` field for the Relation widget which allows adding filters by which the available options are filtered on. This was requested in issue #2405 (and also by myself :)). 
How it works is that you can add "filters" which are a pair of `field` and the allowed `values`, where the widget will only show options (collection items) that satisfy all the "filters". An collection item satisfies a filter if the value of `field` is one of the values in `values`.
**Example**
```
collections:
- name: posts
label: Posts
folder: _posts
create: true
fields:
- label: Title
name: title
widget: string
- label: Draft
name: draft
widget: boolean
default: true
- label: Body
name: body
widget: markdown
- name: restaurants
label: Restaurants
folder: _restaurants
create: true …
```
=> feat: filtering for relation widget (#2405)

packages/decap-cms-widget-relation/src/RelationControl.js
**Summary**
This should patch up a bug that was introduced here: https://github.com/decaporg/decap-cms/pull/7161
There is an edge case that we use for our client where relation widget is collapsed within an list and if the widget wasn't displayed right away it would populate the value as if it was a single value field and after saving the format would be corrupted. 
**Test plan**
Add the following field to the list of authors in config.yml
```
- { name: 'posts', widget: relation, collection: posts, multiple: true, search_fields: [ "title" ], display_fields: [ "title" ], value_field: "{{slug}}", filters: [ {field: "draft", values: [false]} ] }
```
In settings > authors add a single related post, publish (so far so good), close and open authors again. The value would be blank before this …
=> fix: handle single values in multi select relation widget

dev-test/backends/azure/config.yml, dev-test/backends/bitbucket/config.yml, dev-test/backends/git-gateway/config.yml, dev-test/backends/gitea/config.yml, dev-test/backends/github/config.yml, dev-test/backends/gitlab/config.yml, dev-test/backends/proxy/config.yml, packages/decap-cms-widget-datetime/src/DateTimeControl.js
**Summary**
https://github.com/decaporg/decap-cms/pull/7091 unintentionally changed how the date format is saved to frontmatter by default
this PR should patch this
to avoid re-recording fixtures, I set the format in the config.yml for e2e tests
**Test plan**
**Checklist**
=> fix(datetime-widget): revert default date format to include timezone

packages/decap-cms-widget-datetime/src/DateTimeControl.js
A fix for a bug that was introduced in https://github.com/decaporg/decap-cms/pull/7091
Should solve issue https://github.com/decaporg/decap-cms/issues/7166 
`format` prop was used only if the auto parser returned an invalid date, so dates like 1.4.2024 were parsed as 4.1.2024 as both options are valid dates
**Summary**
**Test plan**
**Checklist**
=> fix: fix formatInputValue ignoring format

packages/decap-cms-widget-relation/src/RelationControl.js, packages/decap-cms-widget-relation/src/__tests__/relation.spec.js, packages/decap-cms-widget-relation/src/schema.js
**Summary**
This PR for the relation widget adds functionality for nested fields in the filters and also allows integer types for the values in the filters. 
- Nested fields: it is now possible to have a filter like this: `filters: [ { field: 'deeply.nested.field', values: ['Some text'] } ]`
- Integer type: values can now also be integers (before only booleans and strings were allowed): `filters: [ { field: 'num', values: [1, 12, 20] } ]`
**Test plan**
I added a unit test for the nested fields and for the integer type.
**Checklist**
=> feat: nested fields and integer values for filter relation widget

packages/decap-cms-widget-datetime/src/DateTimeControl.js
**Summary**
This is a quick patch for a problem where the date is not displayed in the CMS after being saved. It happens when format and input format are not set in the CMS. This should patch up the problem for now, but we should think about a thorough review of how the widget should work
**Test plan**
**Checklist**
=> fix: datetime parsing display value when format not provided

packages/decap-cms-app/README.md
update react and react-dom version from 16 to 18
related issue:
https://github.com/decaporg/gatsby-plugin-decap-cms/issues/4
**Summary**
The readme was outdated. The correct react versions are 18
Manually initializing decap threw: `i.createRoot is not a function`
**Test plan**
**Checklist**
=> chore: update readme

packages/decap-cms-backend-proxy/src/AuthenticationPage.js, packages/decap-cms-ui-default/src/AuthenticationPage.js, packages/decap-cms-ui-default/src/index.js
**Summary**
fixes #5752 
Bug occurred because the  `decap-cms-backend-proxy` package uses a different authentication page. Yet, this page didn't reuse `renderPageLogo` function that is defined in `decap-cms-ui-default`, which allows the display of a custom logo.
**Test plan**
1. Run `npm run decap-server`
2. Add `logo_url: YOUR_LOGO_URL` to `config.yml`
**Checklist**
=> fix: display custom logo when using a proxy server

packages/decap-cms-core/src/components/App/Header.js
**Summary**
Fixes #7208 by changing style of AppHeaderButton to use :focus-visible instead of :focus.
This was noticed when closing the media library the "Media" header link would remain blue until anything else was interacted with.
**Test plan**
Passed all tests after running npm run test. Everything still functions identically when navigating the site with a keyboard as well as a mouse.
**Checklist**
- [ x] I have read the [contribution guidelines](https://github.com/decaporg/decap-cms/blob/main/CONTRIBUTING.md).
=> fix: change AppHeaderButton style fixing #7208

packages/decap-cms-core/src/components/Editor/EditorToolbar.js, packages/decap-cms-core/src/components/Editor/__tests__/__snapshots__/EditorToolbar.spec.js.snap
Changed ToolbarContainer's position element to be absolute - #7197
Fixes #7197 
**Summary**
I was following the docs and wanted to mount decap inside of a div on my page, this worked good on the landing page of decap but did not work once I was on an editing page. The editor toolbar had a fixed position to the top so it would come out of my div and cover the custom header that I had made.
**Test plan**
I ran the tests using npm, at first they failed since the editor toolbar did not match the snapshot but since changing the component was what was intended, I updated the snapshot and the tests passed. (there was a warning that was also present before my change)
Screenshots before my change (I have decap mounted inside of a div that only covers 90% width of the page and has a header and …
=> fix: change EditorToolbar position style

packages/decap-cms-backend-git-gateway/src/implementation.ts
=> Pass avatar_url un git-gateway backend

packages/decap-cms-lib-util/src/API.ts
The authorization type "Bearer" is more widely recognized than "token". E.g. Gitlab requires that you use "Bearer".
Github mentions that it accepts both "token" and "Bearer": https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication
Gitlab seems to require the use of "Bearer", which was apparently the cause of #7172: https://github.com/decaporg/decap-cms/issues/7172#issuecomment-2184138768 (thanks to @b-xb for digging into this)
See also: https://github.com/decaporg/decap-cms/pull/5844#discussion_r1658974332
Fixes #7172.
**Summary**
Gitlab login is broken in current versions: #7172
**Test plan**
**Checklist**
=> Fix login with Gitlab (change API `Authorization` header "token" → "Bearer")

packages/decap-cms-core/src/components/Editor/EditorControlPane/EditorControl.js
Improves position of the field error so that it doesn't hide behind label.
I also aligned text to the left.
This is the updated look:
Closes #1654
=> fix: improve field error position

packages/decap-cms-widget-datetime/src/DateTimeControl.js
Closes #7271
The value was set in the UI, but handleChange never triggerred, so it never rewrote `"{{now}}"` with the current date. This PR moves the check into the mount hook and triggers `handleChange`, so that correct value is saved.
=> fix: trigger change if default is {{now}}

package.json
**Summary**
closes #7201
**Test plan**
running `npm run test:all` runs linting, Jest, and Cypress tests
**Checklist**
=> missing npm script test:all

packages/decap-cms-lib-widgets/src/stringTemplate.ts
**Summary**
allow empty spaces in Summary String Transformations
closes #7221 
**Test plan**
`summary: "{{ title | upper }} / {{ title | lower }} / {{ title | truncate(1) }} / {{ nonexistant | default('Hello') }} / {{ mytruth | ternary('Yep','Nope') }} / {{ date | date('YYYY') }}"`
BEFORE: 
`/ / / / / `
AFTER:
`TITLE / title / t... / Hello / Yep / 2024`
**Checklist**
=> fix: summary string transformations format (#7221)

packages/decap-cms-widget-markdown/src/MarkdownControl/VisualEditor.js, packages/decap-cms-widget-markdown/src/MarkdownControl/plugins/html/withHtml.js, packages/decap-cms-widget-markdown/src/MarkdownControl/renderers.js, packages/decap-cms-widget-markdown/src/serializers/slateRemark.js
closes #7233 
**Summary**
When pasting html into markdown, keep styles instead of plain text.
Code copied from official example https://github.com/ianstormtaylor/slate/blob/main/site/examples/ts/paste-html.tsx
**Test plan**
**Checklist**
=> fix(markdown): copying html into markdown

packages/decap-cms-widget-object/src/ObjectControl.js
**Summary**
When building nested controls for fields in an object widget, ensure the object's ID is passed through as a 'parent' so that errors in nested fields can be linked to the parent.
This ensures that a validation error on a field within an object will "bubble up" and show an error on a collapsed object's control in the editor, helping users to identify where there are validation errors.
**Test plan**
1. Open the demo site
2. Create a new Kitchen Sink collection entry
3. Enter something for the title, click Save
4. Scroll down to check the "Object" editor control and check if it's highlighted red
Before:
After:
**Checklist**
=> fix(object-widget): highlight nested validation errors

packages/decap-cms-widget-object/src/ObjectControl.js
**Summary**
This a quick patch for https://github.com/decaporg/decap-cms/issues/7383 that happened after the validation rework in https://github.com/decaporg/decap-cms/pull/7374
I have tested against most of the cases that I could think of and it seems to be ok.
**Test plan**
This is the config that I tested with, changing required on/off and trying multiple nested depths
```
{name: pageHero, label: Page hero, widget: object, collapsed: true, summary: '{{fields.title}}', fields: [
{name: title, widget: string, i18n: true, required: false, hint: 'if empty, page title will be used'},
{name: description, widget: string, i18n: true, required: false, hint: 'if empty, page description will be used'},
{name: button, widget: object, i18n: true, fields: [
{name: text, widget: string, i18n: true, …
```
=> fix(ObjectControl): hotfix nested object validation

.github/workflows/nodejs.yml
**Summary**
**Test plan**
**Checklist**
=> chore: update to upload-artifact@v4

packages/decap-cms-core/src/backend.ts
**Summary**
Addressing https://github.com/decaporg/decap-cms/issues/7389
When using nested collection combined with i18n, we encountered a bug, where instead of saving content, we would get empty commits. This did not happen when using local backend via proxy. 
After inspecting exactly what happens in the backend implementation I figured out that the problem actually happens in `backend.ts` when it sets the `newPath` property as if the file was being renamed every time the customPath is set. This way the updateTree function in the API.ts goes into another mode, loops the i18n files and eventually updates the tree with existing blob IDS instead of the newly uploaded ones. 
Added a condition where newPath is passed on only if it differs from the currentPath - so only in case the file is …
=> Fix: nested + i18n customPath issue

packages/decap-cms-core/src/components/Editor/EditorToolbar.js
This will fix #7479 
Test: open the UI with a german environment and add a new entry. The old version will have the entries in the dropdown menu for publishing cropped. This change fixes this.
=> fix: dropdown menu with adjusts to content

functions/publish.js, scripts/cache.js
**Summary**
This change ensures that when ALLOWED_USERS is split, each user ID is trimmed of whitespace and compared in a case-insensitive manner.
Previously, extra spaces or mismatched casing in the environment variable could prevent valid users from being recognized.
Improved the cache restore log message in the build configuration.
Replaced echo noop with a more descriptive message:
echo "No operation needed — cache intact".
This makes CI/CD logs clearer, helping developers quickly understand that the cache step was executed successfully but no rebuild was needed.
**Test plan**
Set ALLOWED_USERS=" U12345 ,u67890 " in .env.
Trigger a request with user_id="U12345" and user_id="u67890" — both should match successfully.
Trigger a request with an unauthorized user_id and confirm it is …
=> chore : Fix allowed users check by trimming spaces, ignoring case and improve cache restore message for clarity

packages/decap-cms-editor-component-image/src/index.js
**Summary**
This PR updates the `pattern` prop of the Image editor component and fixes the issue #7575.
The problem was that the previous regex pattern expected the image Markdown to occupy the entire string, using ^ at the start and $ at the end. As a result, images embedded in Markdown blocks with preceding or trailing text, blank lines, or paragraphs were not detected, breaking the editor preview for these images.
The proposed solution removes the $ anchor at the end and uses a global regex that matches images anywhere in the Markdown block. This ensures that images like:
```md
Lorem ipsum text
More text
```
are correctly recognized by the Image editor component and rendered in both the rich text editor and preview pane.
**Test plan**
- Verified that Markdown containing images between …
=> Fixed image editor component pattern

packages/decap-cms-ui-default/src/styles.js
**Summary**
Currently long items in select controls (e.g. in a relation widget) will wrap and overlap subsequent items, since all items are positioned absolutely with a fixed height, and overflow is not hidden. The issue appears to be agnostic of browser; I have reproduced the issue in Firefox, Chrome, and Safari.
**Test plan**
I've tested my change in the three browsers I mentioned above. At least for modern versions of these browsers, the changes work as expected.
**Checklist**
Here's are my boys Moss and Roy sharing a chair that's too small for them
=> Prevent select dropdown item text wrapping
